# Only understand the syntax tree and the pseudocode.

- Understand the code  especially the output itself possible  patterns( 1 hrs )
- Come up with 3 experiments to improve it using the subsample approach itself and 2 experiments to run and find what interventions could be done to figure out the issue (1 hr)
- Implement figure things out ( 3 hrs )
Goal - Atleast get a 30% improvement on current AUROC of 0.61

In [176]:
import os, re

def explore(path, max_show=3, max_depth=4):
    def walk(p, depth=0):
        if depth > max_depth:
            return
        try:
            entries = sorted(os.listdir(p))
        except (PermissionError, NotADirectoryError):
            return
        entries = [e for e in entries if not e.startswith('.')]
        dirs  = [e for e in entries if os.path.isdir(os.path.join(p, e))]
        files = [e for e in entries if not os.path.isdir(os.path.join(p, e))]
        ind = '  ' * depth

        # group dirs by their name-pattern (digits -> #)
        groups = {}
        for d in dirs:
            groups.setdefault(re.sub(r'\d+', '#', d), []).append(d)

        for pattern, members in groups.items():
            for d in members[:max_show]:
                print(f"{ind}{d}/")
                walk(os.path.join(p, d), depth + 1)
            if len(members) > max_show:
                print(f"{ind}... {len(members) - max_show} more matching '{pattern}'")

        for f in files[:max_show]:
            print(f"{ind}{f}")
        if len(files) > max_show:
            print(f"{ind}... {len(files) - max_show} more files")

    print(f"{os.path.basename(path.rstrip('/'))}/")
    walk(path, 1)

explore("CheXpert-v1.0-small/CheXpert-v1.0-small")

CheXpert-v1.0-small/
  train/
    patient00001/
      study1/
        view1_frontal.jpg
    patient00002/
      study1/
        view1_frontal.jpg
        view2_lateral.jpg
      study2/
        view1_frontal.jpg
    patient00003/
      study1/
        view1_frontal.jpg
    ... 64537 more matching 'patient#'
  valid/
    patient64541/
      study1/
        view1_frontal.jpg
    patient64542/
      study1/
        view1_frontal.jpg
        view2_lateral.jpg
    patient64543/
      study1/
        view1_frontal.jpg
    ... 197 more matching 'patient#'
  train.csv
  valid.csv

In [177]:
import pandas as pd
df = pd.read_csv("CheXpert-v1.0-small/CheXpert-v1.0-small/train.csv")
print(df.shape)
df.head()

(223414, 19)

,Path,Sex,Age,Frontal/Lateral,AP/PA,No Finding,Enlarged Cardiomediastinum,Cardiomegaly,Lung Opacity,Lung Lesion,Edema,Consolidation,Pneumonia,Atelectasis,Pneumothorax,Pleural Effusion,Pleural Other,Fracture,Support Devices
0,CheXpert-v1.0-small/train/patient00001/study1/...,Female,68,Frontal,AP,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,1.0
1,CheXpert-v1.0-small/train/patient00002/study2/...,Female,87,Frontal,AP,NaN,NaN,-1.0,1.0,NaN,-1.0,-1.0,NaN,-1.0,NaN,-1.0,NaN,1.0,NaN
2,CheXpert-v1.0-small/train/patient00002/study1/...,Female,83,Frontal,AP,NaN,NaN,NaN,1.0,NaN,NaN,-1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN
3,CheXpert-v1.0-small/train/patient00002/study1/...,Female,83,Lateral,NaN,NaN,NaN,NaN,1.0,NaN,NaN,-1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN
4,CheXpert-v1.0-small/train/patient00003/study1/...,Male,41,Frontal,AP,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN

In [178]:
df['AP/PA'].value_counts(dropna=False)

AP/PA
AP     161590
NaN     32387
PA      29420
LL         16
RL          1
Name: count, dtype: int64

In [179]:
df.columns

Index(['Path', 'Sex', 'Age', 'Frontal/Lateral', 'AP/PA', 'No Finding',
       'Enlarged Cardiomediastinum', 'Cardiomegaly', 'Lung Opacity',
       'Lung Lesion', 'Edema', 'Consolidation', 'Pneumonia', 'Atelectasis',
       'Pneumothorax', 'Pleural Effusion', 'Pleural Other', 'Fracture',
       'Support Devices'],
      dtype='str')

In [180]:
df1 = df[~(df[df.columns[5:]]==-1).any(axis='columns')]

In [181]:
df.shape

(223414, 19)

In [182]:
df1.shape

(138358, 19)

In [183]:
label_cols = df1.columns[5:]

In [184]:
df1[label_cols] = df1[label_cols].fillna(0)

In [185]:
df1[label_cols].isnull().sum().sum()

np.int64(0)

In [186]:
df[label_cols].isnull().sum().sum()

np.int64(2277974)

In [187]:
label_cols

Index(['No Finding', 'Enlarged Cardiomediastinum', 'Cardiomegaly',
       'Lung Opacity', 'Lung Lesion', 'Edema', 'Consolidation', 'Pneumonia',
       'Atelectasis', 'Pneumothorax', 'Pleural Effusion', 'Pleural Other',
       'Fracture', 'Support Devices'],
      dtype='str')

In [188]:
df1 = df1[df1["Frontal/Lateral"] == 'Frontal']

In [189]:
df1.shape

(118286, 19)

- Removed uncertain labels (-1)
- Filled missing labels (NaN → 0)
- Kept frontal views only

118k clean, frontal chest X-rays with 14 binary labels. That's your training data.

In [190]:
import torch
from open_clip import create_model_from_pretrained, get_tokenizer

print(torch.__version__)
print("MPS available:", torch.backends.mps.is_available())

2.13.0
MPS available: True

In [191]:
import torch
from open_clip import create_model_from_pretrained, get_tokenizer

model, preprocess = create_model_from_pretrained(
    'hf-hub:microsoft/BiomedCLIP-PubMedBERT_256-vit_base_patch16_224'
)
tokenizer = get_tokenizer(
    'hf-hub:microsoft/BiomedCLIP-PubMedBERT_256-vit_base_patch16_224'
)
model = model.eval()
print("loaded")

loaded

In [194]:
from PIL import Image
import torch

concepts = [
    "blunted costophrenic angle",
    "enlarged cardiac silhouette",
    "normal chest radiograph",
    "a chest x-ray showing blunted costophrenic angle",
    "My nose is itching"
]

img = Image.open("CheXpert-v1.0-small/CheXpert-v1.0-small/train/patient00001/study1/view1_frontal.jpg").convert("RGB")
img_t = preprocess(img).unsqueeze(0)
txt_t = tokenizer(concepts, context_length=256)

with torch.no_grad():
    img_emb, txt_emb, _ = model(img_t, txt_t)
    scores = (img_emb @ txt_emb.T).squeeze()

for c, s in zip(concepts, scores):
    print(f"{c}: {s:.4f}")

blunted costophrenic angle: 0.3825
enlarged cardiac silhouette: 0.3612
normal chest radiograph: 0.3752
a chest x-ray showing blunted costophrenic angle: 0.4367
My nose is itching: 0.1430

In [195]:
import os

print("HF_HUB_DISABLE_XET:", os.environ.get("HF_HUB_DISABLE_XET"))
print("TRANSFORMERS_OFFLINE:", os.environ.get("TRANSFORMERS_OFFLINE"))
print("HF_HUB_OFFLINE:", os.environ.get("HF_HUB_OFFLINE"))

HF_HUB_DISABLE_XET: None
TRANSFORMERS_OFFLINE: None
HF_HUB_OFFLINE: None

In [196]:

# ============================================================
# Cell 1 — imports + config
# ============================================================
import json
import torch
import open_clip
 
MAX_LEN = 50
SIM_TO_LABEL_THRESH = 0.9
SIM_TO_CONCEPT_THRESH = 0.9
 # SIM_TO_LABEL_THRESH keeps the bottleneck from trivially encoding the label itself
 # (e.g. a concept literally named "cardiomegaly" would make Cardiomegaly prediction circular)
 # SIM_TO_CONCEPT_THRESH removes near-duplicate concepts so the linear probe isn't
 # given multiple near-identical columns competing for the same signal
 
CLASS_LABELS = [
    "No Finding", "Enlarged Cardiomediastinum", "Cardiomegaly", "Lung Opacity",
    "Lung Lesion", "Edema", "Consolidation", "Pneumonia", "Atelectasis",
    "Pneumothorax", "Pleural Effusion", "Pleural Other", "Fracture", "Support Devices",
]

In [198]:
# ============================================================
# Cell 2 — load raw concepts, flatten, dedup exact strings
# ============================================================
raw = json.load(open("../data/raw_concepts.json"))
 
seen = set()
candidates = []
for pathology, concepts in raw.items():
    for c in concepts:
        if c.strip().lower() not in seen:
            seen.add(c.strip().lower())
            candidates.append(c)
 
print(f"Flattened + exact-deduped: {len(candidates)} candidates")

Flattened + exact-deduped: 107 candidates

In [199]:
 
# ============================================================
# Cell 3 — length filter
# ============================================================
candidates = [c for c in candidates if len(c) <= MAX_LEN]
print(f"After length filter: {len(candidates)}")

After length filter: 107

In [200]:
# ============================================================
# Cell 4 — load BiomedCLIP (reuse your already-verified model/tokenizer
# if they're still in memory from your smoke test — no need to reload)
# ============================================================
model, _, preprocess = open_clip.create_model_and_transforms(
    "hf-hub:microsoft/BiomedCLIP-PubMedBERT_256-vit_base_patch16_224"
)
tokenizer = open_clip.get_tokenizer(
    "hf-hub:microsoft/BiomedCLIP-PubMedBERT_256-vit_base_patch16_224"
)
model.eval()

CustomTextCLIP(
  (visual): TimmModel(
    (trunk): VisionTransformer(
      (patch_embed): PatchEmbed(
        (proj): Conv2d(3, 768, kernel_size=(16, 16), stride=(16, 16))
        (norm): Identity()
      )
      (pos_drop): Dropout(p=0.0, inplace=False)
      (patch_drop): Identity()
      (norm_pre): Identity()
      (blocks): Sequential(
        (0): Block(
          (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True, bias=True)
          (attn): Attention(
            (qkv): Linear(in_features=768, out_features=2304, bias=True)
            (q_norm): Identity()
            (k_norm): Identity()
            (attn_drop): Dropout(p=0.0, inplace=False)
            (norm): Identity()
            (proj): Linear(in_features=768, out_features=768, bias=True)
            (proj_drop): Dropout(p=0.0, inplace=False)
          )
          (ls1): Identity()
          (drop_path1): Identity()
          (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True, bias=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=768, out_features=3072, bias=True)
            (act): GELU(approximate='none')
            (drop1): Dropout(p=0.0, inplace=False)
            (norm): Identity()
            (fc2): Linear(in_features=3072, out_features=768, bias=True)
            (drop2): Dropout(p=0.0, inplace=False)
          )
          (ls2): Identity()
          (drop_path2): Identity()
        )
        (1): Block(
          (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True, bias=True)
          (attn): Attention(
            (qkv): Linear(in_features=768, out_features=2304, bias=True)
            (q_norm): Identity()
            (k_norm): Identity()
            (attn_drop): Dropout(p=0.0, inplace=False)
            (norm): Identity()
            (proj): Linear(in_features=768, out_features=768, bias=True)
            (proj_drop): Dropout(p=0.0, inplace=False)
          )
          (ls1): Identity()
          (drop_path1): Identity()
          (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True, bias=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=768, out_features=3072, bias=True)
            (act): GELU(approximate='none')
            (drop1): Dropout(p=0.0, inplace=False)
            (norm): Identity()
            (fc2): Linear(in_features=3072, out_features=768, bias=True)
            (drop2): Dropout(p=0.0, inplace=False)
          )
          (ls2): Identity()
          (drop_path2): Identity()
        )
        (2): Block(
          (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True, bias=True)
          (attn): Attention(
            (qkv): Linear(in_features=768, out_features=2304, bias=True)
            (q_norm): Identity()
            (k_norm): Identity()
            (attn_drop): Dropout(p=0.0, inplace=False)
            (norm): Identity()
            (proj): Linear(in_features=768, out_features=768, bias=True)
            (proj_drop): Dropout(p=0.0, inplace=False)
          )
          (ls1): Identity()
          (drop_path1): Identity()
          (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True, bias=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=768, out_features=3072, bias=True)
            (act): GELU(approximate='none')
            (drop1): Dropout(p=0.0, inplace=False)
            (norm): Identity()
            (fc2): Linear(in_features=3072, out_features=768, bias=True)
            (drop2): Dropout(p=0.0, inplace=False)
          )
          (ls2): Identity()
          (drop_path2): Identity()
        )
        (3): Block(
          (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True, bias=True)
          (attn): Attention(
            (qkv): Linear(in_features=768, out_features=2304, bias=True)
            (q_norm): Identity()
            (k_norm): Identity()
            (attn_drop): Dropout(p=0.0, inplace=False)
            (norm): Identity()
            (proj): Linear(in_features=768, out_features=768, bias=True)
            (proj_drop): Dropout(p=0.0, inplace=False)
          )
          (ls1): Identity()
          (drop_path1): Identity()
          (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True, bias=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=768, out_features=3072, bias=True)
            (act): GELU(approximate='none')
            (drop1): Dropout(p=0.0, inplace=False)
            (norm): Identity()
            (fc2): Linear(in_features=3072, out_features=768, bias=True)
            (drop2): Dropout(p=0.0, inplace=False)
          )
          (ls2): Identity()
          (drop_path2): Identity()
        )
        (4): Block(
          (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True, bias=True)
          (attn): Attention(
            (qkv): Linear(in_features=768, out_features=2304, bias=True)
            (q_norm): Identity()
            (k_norm): Identity()
            (attn_drop): Dropout(p=0.0, inplace=False)
            (norm): Identity()
            (proj): Linear(in_features=768, out_features=768, bias=True)
            (proj_drop): Dropout(p=0.0, inplace=False)
          )
          (ls1): Identity()
          (drop_path1): Identity()
          (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True, bias=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=768, out_features=3072, bias=True)
            (act): GELU(approximate='none')
            (drop1): Dropout(p=0.0, inplace=False)
            (norm): Identity()
            (fc2): Linear(in_features=3072, out_features=768, bias=True)
            (drop2): Dropout(p=0.0, inplace=False)
          )
          (ls2): Identity()
          (drop_path2): Identity()
        )
        (5): Block(
          (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True, bias=True)
          (attn): Attention(
            (qkv): Linear(in_features=768, out_features=2304, bias=True)
            (q_norm): Identity()
            (k_norm): Identity()
            (attn_drop): Dropout(p=0.0, inplace=False)
            (norm): Identity()
            (proj): Linear(in_features=768, out_features=768, bias=True)
            (proj_drop): Dropout(p=0.0, inplace=False)
          )
          (ls1): Identity()
          (drop_path1): Identity()
          (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True, bias=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=768, out_features=3072, bias=True)
            (act): GELU(approximate='none')
            (drop1): Dropout(p=0.0, inplace=False)
            (norm): Identity()
            (fc2): Linear(in_features=3072, out_features=768, bias=True)
            (drop2): Dropout(p=0.0, inplace=False)
          )
          (ls2): Identity()
          (drop_path2): Identity()
        )
        (6): Block(
          (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True, bias=True)
          (attn): Attention(
            (qkv): Linear(in_features=768, out_features=2304, bias=True)
            (q_norm): Identity()
            (k_norm): Identity()
            (attn_drop): Dropout(p=0.0, inplace=False)
            (norm): Identity()
            (proj): Linear(in_features=768, out_features=768, bias=True)
            (proj_drop): Dropout(p=0.0, inplace=False)
          )
          (ls1): Identity()
          (drop_path1): Identity()
          (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True, bias=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=768, out_features=3072, bias=True)
            (act): GELU(approximate='none')
            (drop1): Dropout(p=0.0, inplace=False)
            (norm): Identity()
            (fc2): Linear(in_features=3072, out_features=768, bias=True)
            (drop2): Dropout(p=0.0, inplace=False)
          )
          (ls2): Identity()
          (drop_path2): Identity()
        )
        (7): Block(
          (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True, bias=True)
          (attn): Attention(
            (qkv): Linear(in_features=768, out_features=2304, bias=True)
            (q_norm): Identity()
            (k_norm): Identity()
            (attn_drop): Dropout(p=0.0, inplace=False)
            (norm): Identity()
            (proj): Linear(in_features=768, out_features=768, bias=True)
            (proj_drop): Dropout(p=0.0, inplace=False)
          )
          (ls1): Identity()
          (drop_path1): Identity()
          (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True, bias=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=768, out_features=3072, bias=True)
            (act): GELU(approximate='none')
            (drop1): Dropout(p=0.0, inplace=False)
            (norm): Identity()
            (fc2): Linear(in_features=3072, out_features=768, bias=True)
            (drop2): Dropout(p=0.0, inplace=False)
          )
          (ls2): Identity()
          (drop_path2): Identity()
        )
        (8): Block(
          (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True, bias=True)
          (attn): Attention(
            (qkv): Linear(in_features=768, out_features=2304, bias=True)
            (q_norm): Identity()
            (k_norm): Identity()
            (attn_drop): Dropout(p=0.0, inplace=False)
            (norm): Identity()
            (proj): Linear(in_features=768, out_features=768, bias=True)
            (proj_drop): Dropout(p=0.0, inplace=False)
          )
          (ls1): Identity()
          (drop_path1): Identity()
          (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True, bias=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=768, out_features=3072, bias=True)
            (act): GELU(approximate='none')
            (drop1): Dropout(p=0.0, inplace=False)
            (norm): Identity()
            (fc2): Linear(in_features=3072, out_features=768, bias=True)
            (drop2): Dropout(p=0.0, inplace=False)
          )
          (ls2): Identity()
          (drop_path2): Identity()
        )
        (9): Block(
          (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True, bias=True)
          (attn): Attention(
            (qkv): Linear(in_features=768, out_features=2304, bias=True)
            (q_norm): Identity()
            (k_norm): Identity()
            (attn_drop): Dropout(p=0.0, inplace=False)
            (norm): Identity()
            (proj): Linear(in_features=768, out_features=768, bias=True)
            (proj_drop): Dropout(p=0.0, inplace=False)
          )
          (ls1): Identity()
          (drop_path1): Identity()
          (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True, bias=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=768, out_features=3072, bias=True)
            (act): GELU(approximate='none')
            (drop1): Dropout(p=0.0, inplace=False)
            (norm): Identity()
            (fc2): Linear(in_features=3072, out_features=768, bias=True)
            (drop2): Dropout(p=0.0, inplace=False)
          )
          (ls2): Identity()
          (drop_path2): Identity()
        )
        (10): Block(
          (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True, bias=True)
          (attn): Attention(
            (qkv): Linear(in_features=768, out_features=2304, bias=True)
            (q_norm): Identity()
            (k_norm): Identity()
            (attn_drop): Dropout(p=0.0, inplace=False)
            (norm): Identity()
            (proj): Linear(in_features=768, out_features=768, bias=True)
            (proj_drop): Dropout(p=0.0, inplace=False)
          )
          (ls1): Identity()
          (drop_path1): Identity()
          (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True, bias=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=768, out_features=3072, bias=True)
            (act): GELU(approximate='none')
            (drop1): Dropout(p=0.0, inplace=False)
            (norm): Identity()
            (fc2): Linear(in_features=3072, out_features=768, bias=True)
            (drop2): Dropout(p=0.0, inplace=False)
          )
          (ls2): Identity()
          (drop_path2): Identity()
        )
        (11): Block(
          (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True, bias=True)
          (attn): Attention(
            (qkv): Linear(in_features=768, out_features=2304, bias=True)
            (q_norm): Identity()
            (k_norm): Identity()
            (attn_drop): Dropout(p=0.0, inplace=False)
            (norm): Identity()
            (proj): Linear(in_features=768, out_features=768, bias=True)
            (proj_drop): Dropout(p=0.0, inplace=False)
          )
          (ls1): Identity()
          (drop_path1): Identity()
          (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True, bias=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=768, out_features=3072, bias=True)
            (act): GELU(approximate='none')
            (drop1): Dropout(p=0.0, inplace=False)
            (norm): Identity()
            (fc2): Linear(in_features=3072, out_features=768, bias=True)
            (drop2): Dropout(p=0.0, inplace=False)
          )
          (ls2): Identity()
          (drop_path2): Identity()
        )
      )
      (norm): LayerNorm((768,), eps=1e-06, elementwise_affine=True, bias=True)
      (fc_norm): Identity()
      (head_drop): Dropout(p=0.0, inplace=False)
      (head): Identity()
    )
    (head): Sequential(
      (drop): Dropout(p=0.0, inplace=False)
      (proj): Linear(in_features=768, out_features=512, bias=False)
    )
  )
  (text): HFTextEncoder(
    (transformer): BertModel(
      (embeddings): BertEmbeddings(
        (word_embeddings): Embedding(30522, 768, padding_idx=0)
        (position_embeddings): Embedding(512, 768)
        (token_type_embeddings): Embedding(2, 768)
        (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
        (dropout): Dropout(p=0.1, inplace=False)
      )
      (encoder): BertEncoder(
        (layer): ModuleList(
          (0-11): 12 x BertLayer(
            (attention): BertAttention(
              (self): BertSelfAttention(
                (query): Linear(in_features=768, out_features=768, bias=True)
                (key): Linear(in_features=768, out_features=768, bias=True)
                (value): Linear(in_features=768, out_features=768, bias=True)
                (dropout): Dropout(p=0.1, inplace=False)
              )
              (output): BertSelfOutput(
                (dense): Linear(in_features=768, out_features=768, bias=True)
                (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
                (dropout): Dropout(p=0.1, inplace=False)
              )
            )
            (intermediate): BertIntermediate(
              (dense): Linear(in_features=768, out_features=3072, bias=True)
              (intermediate_act_fn): GELUActivation()
            )
            (output): BertOutput(
              (dense): Linear(in_features=3072, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
        )
      )
    )
    (pooler): ClsLastHiddenStatePooler()
    (proj): Sequential(
      (0): Linear(in_features=768, out_features=640, bias=False)
      (1): GELU(approximate='none')
      (2): Linear(in_features=640, out_features=512, bias=False)
    )
  )
)

In [201]:
# ============================================================
# Cell 5 — encode labels and candidates (one function, used twice)
# ============================================================
def encode(strings):
    toks = tokenizer(strings, context_length=256)
    with torch.no_grad():
        emb = model.encode_text(toks)
    return emb / emb.norm(dim=-1, keepdim=True)
 
label_emb = encode(CLASS_LABELS)
concept_emb = encode(candidates)

In [202]:
# ============================================================
# Cell 6 — filter: drop concepts too similar to any class label
# ============================================================
# Dropping concepts too similar to a label name prevents the CBM from trivially
# "cheating" by encoding the label as a concept, rather than a genuine radiological finding
max_sim_to_label = (concept_emb @ label_emb.T).max(dim=1).values
keep = max_sim_to_label <= SIM_TO_LABEL_THRESH
 
candidates = [c for c, k in zip(candidates, keep.tolist()) if k]
concept_emb = concept_emb[keep]
print(f"After label-similarity filter: {len(candidates)}")

After label-similarity filter: 105

In [204]:
# ============================================================
# Cell 7 — filter: drop near-duplicate concepts (greedy, keep first)
# ============================================================
# Greedy dedup, not exhaustive clustering: keeps the first-seen concept in near-duplicate
# groups, which is simple and deterministic but sensitive to input ordering — fine here
# since candidates come from a fixed seed list, not a randomly-ordered source
sim = concept_emb @ concept_emb.T
dropped = set()
final = []
 
for i in range(len(candidates)):
    if i in dropped:
        continue
    final.append(candidates[i])
    for j in range(i + 1, len(candidates)):
        if j not in dropped and sim[i, j] > SIM_TO_CONCEPT_THRESH:
            dropped.add(j)
 
print(f"After concept-concept similarity filter: {len(final)}")

After concept-concept similarity filter: 95

In [205]:
# ============================================================
# Cell 8 — save
# ============================================================
json.dump(final, open("concepts_stage1.json", "w"), indent=2)
print("Saved concepts_stage1.json")
final  # display in notebook to eyeball the survivors

Saved concepts_stage1.json

['clear lung fields',
 'normal cardiac silhouette',
 'sharp costophrenic angles',
 'normal mediastinal contour',
 'no focal opacity',
 'normal bony thorax',
 'symmetric lung inflation',
 'unremarkable chest radiograph',
 'widened mediastinal silhouette',
 'enlarged cardiac contour',
 'widened superior mediastinum',
 'mediastinal mass effect',
 'abnormal aortic contour',
 'tracheal deviation',
 'widened vascular pedicle',
 'loss of mediastinal margins',
 'increased cardiothoracic ratio',
 'globular heart shape',
 'left ventricular enlargement',
 'prominent cardiac apex',
 'cardiac border exceeds half thorax width',
 'biventricular enlargement',
 'boot shaped heart',
 'hazy lung opacity',
 'increased lung density',
 'airspace opacification',
 'patchy parenchymal opacity',
 'obscured vascular markings',
 'ill defined opacity',
 'diffuse ground glass opacity',
 'focal consolidative opacity',
 'solitary pulmonary nodule',
 'well circumscribed mass',
 'cavitary lung lesion',
 'spiculated nodule margins',
 'calcified granuloma',
 'irregular lung mass',
 'mass with irregular border',
 'perihilar haziness',
 'interstitial lung markings',
 'kerley b lines',
 'peribronchial cuffing',
 'bat wing opacity pattern',
 'vascular redistribution',
 'diffuse bilateral haziness',
 'fluid in fissures',
 'air bronchograms',
 'lobar consolidation',
 'homogeneous parenchymal opacity',
 'segmental consolidation',
 'lobar infiltrate',
 'patchy infiltrate',
 'peribronchial infiltrate',
 'unilateral lung infiltrate',
 'volume loss in lung',
 'elevated hemidiaphragm',
 'shifted fissure',
 'linear atelectatic bands',
 'crowded bronchovascular markings',
 'mediastinal shift toward opacity',
 'platelike atelectasis',
 'collapsed lung segment',
 'visceral pleural line',
 'absent lung markings peripherally',
 'deep sulcus sign',
 'lucent area without vessels',
 'mediastinal shift away from lucency',
 'tension pneumothorax with shift',
 'small apical lucency',
 'meniscus sign',
 'layering fluid on lateral view',
 'fluid tracking into fissure',
 'subpulmonic effusion',
 'mediastinal shift from large effusion',
 'pleural thickening',
 'pleural plaque',
 'calcified pleura',
 'loculated pleural fluid',
 'pleural scarring',
 'fibrothorax',
 'rib cortical discontinuity',
 'displaced bone fragment',
 'callus formation',
 'step off in bone cortex',
 'clavicle fracture line',
 'vertebral compression deformity',
 'acute rib fracture',
 'endotracheal tube',
 'central venous catheter',
 'chest tube',
 'nasogastric tube',
 'pacemaker leads',
 'sternotomy wires',
 'picc line',
 'tracheostomy tube']

In [206]:
# ============================================================
# Cell 1 — imports + config
# ============================================================
import pandas as pd
import numpy as np
 
np.random.seed(42)
 
# Flip this to False later to skip subsampling entirely and run on all 118k rows.
# Everything downstream (Cell 4 onward) works unchanged either way.
USE_SUBSAMPLE = False
TARGET_ROWS = 10_000
 
LABEL_COLS = [
    "No Finding", "Enlarged Cardiomediastinum", "Cardiomegaly", "Lung Opacity",
    "Lung Lesion", "Edema", "Consolidation", "Pneumonia", "Atelectasis",
    "Pneumothorax", "Pleural Effusion", "Pleural Other", "Fracture", "Support Devices",
]

In [207]:
df1.shape

(118286, 19)

In [208]:
df1.head(4)

,Path,Sex,Age,Frontal/Lateral,AP/PA,No Finding,Enlarged Cardiomediastinum,Cardiomegaly,Lung Opacity,Lung Lesion,Edema,Consolidation,Pneumonia,Atelectasis,Pneumothorax,Pleural Effusion,Pleural Other,Fracture,Support Devices
0,CheXpert-v1.0-small/train/patient00001/study1/...,Female,68,Frontal,AP,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,CheXpert-v1.0-small/train/patient00003/study1/...,Male,41,Frontal,AP,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,CheXpert-v1.0-small/train/patient00004/study1/...,Female,20,Frontal,PA,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,CheXpert-v1.0-small/train/patient00005/study1/...,Male,33,Frontal,PA,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [209]:
# ============================================================
# Cell 2 — use df1 (already filtered: no -1s, NaN→0, frontal only)
# If df1 is not in memory, replace this line with:
#   df = pd.read_csv("your_filtered_file.csv")
# ============================================================
df = df1.copy()
df["patient_id"] = df["Path"].str.extract(r"(patient\d+)")
 
n_patients = df["patient_id"].nunique()
print(f"Rows: {len(df)}, unique patients: {n_patients}")

Rows: 118286, unique patients: 49404

In [210]:
# ============================================================
# Cell 3 — SUBSAMPLING (only runs if USE_SUBSAMPLE is True)
# Skip/ignore this cell's effect entirely when USE_SUBSAMPLE = False —
# `sub_df` just becomes the full `df` below.
# ============================================================
if USE_SUBSAMPLE:
    patient_labels = df.groupby("patient_id")[LABEL_COLS].max()
    label_prevalence = patient_labels[LABEL_COLS].sum().sort_values()
 
    def rarest_label(row):
        positives = [l for l in LABEL_COLS if row[l] == 1]
        if not positives:
            return "none"
        return min(positives, key=lambda l: label_prevalence[l])
 
    patient_labels["strat_key"] = patient_labels.apply(rarest_label, axis=1)
 
    rows_per_patient = len(df) / n_patients
    target_patients = int(TARGET_ROWS / rows_per_patient)
 
    sampled_patients = (
        patient_labels
        .groupby("strat_key", group_keys=False)
        .apply(lambda g: g.sample(
            n=max(1, round(len(g) * target_patients / n_patients)),
            random_state=42
        ))
        .index
    )
    sampled_patients = pd.Index(sampled_patients).unique()
 
    sub_df = df[df["patient_id"].isin(sampled_patients)].copy()
    print(f"Subsampled: {len(sampled_patients)} patients, {len(sub_df)} rows")
else:
    sub_df = df
    print(f"Using full dataset: {n_patients} patients, {len(sub_df)} rows")

Using full dataset: 49404 patients, 118286 rows

In [211]:
# ============================================================
# Cell 4 — split PATIENTS 80/10/10, then assign rows by patient
# (identical whether sub_df is the subsample or the full dataframe)
# ============================================================
patients = sub_df["patient_id"].unique().astype(str)  # force plain numpy array
np.random.shuffle(patients)
n = len(patients)
n_train = int(0.8 * n)
n_val = int(0.1 * n)
 
train_patients = set(patients[:n_train])
val_patients = set(patients[n_train:n_train + n_val])
test_patients = set(patients[n_train + n_val:])
 
train_df = sub_df[sub_df["patient_id"].isin(train_patients)]
val_df = sub_df[sub_df["patient_id"].isin(val_patients)]
test_df = sub_df[sub_df["patient_id"].isin(test_patients)]
 
print(f"Patients -> train {len(train_patients)}, val {len(val_patients)}, test {len(test_patients)}")
print(f"Rows     -> train {len(train_df)}, val {len(val_df)}, test {len(test_df)}")
 
assert not (train_patients & val_patients)
assert not (train_patients & test_patients)
assert not (val_patients & test_patients)
print("No patient overlap across splits — confirmed.")

/var/folders/1f/h4qhh2cx0c1fc6x1f1v148540000gn/T/ipykernel_58117/75565785.py:6: UserWarning: you are shuffling a 'ArrowStringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(patients)

Patients -> train 39523, val 4940, test 4941
Rows     -> train 94563, val 11925, test 11798
No patient overlap across splits — confirmed.

In [212]:
# ============================================================
# Cell 5 — save (filename suffix follows the toggle automatically)
# ============================================================
suffix = "_sub" if USE_SUBSAMPLE else "_full"
 
train_df.to_csv(f"train{suffix}.csv", index=False)
val_df.to_csv(f"val{suffix}.csv", index=False)
test_df.to_csv(f"test{suffix}.csv", index=False)
print(f"Saved train{suffix}.csv, val{suffix}.csv, test{suffix}.csv")
 
for name, split in [("train", train_df), ("val", val_df), ("test", test_df)]:
    print(f"\n{name} positive label counts:")
    print(split[LABEL_COLS].sum().sort_values())

Saved train_full.csv, val_full.csv, test_full.csv

train positive label counts:
Pleural Other                  1117.0
Pneumonia                      2388.0
Lung Lesion                    3465.0
Fracture                       4021.0
Enlarged Cardiomediastinum     4790.0
Consolidation                  6217.0
Pneumothorax                  10884.0
Cardiomegaly                  12399.0
No Finding                    13553.0
Atelectasis                   16969.0
Edema                         27468.0
Lung Opacity                  38598.0
Pleural Effusion              40005.0
Support Devices               54648.0
dtype: float64

val positive label counts:
Pleural Other                  163.0
Pneumonia                      312.0
Fracture                       450.0
Lung Lesion                    463.0
Enlarged Cardiomediastinum     617.0
Consolidation                  777.0
Cardiomegaly                  1501.0
Pneumothorax                  1553.0
No Finding                    1680.0
Atelectasis                   2149.0
Edema                         3237.0
Lung Opacity                  4865.0
Pleural Effusion              5036.0
Support Devices               6895.0
dtype: float64

test positive label counts:
Pleural Other                  147.0
Pneumonia                      274.0
Lung Lesion                    469.0
Fracture                       518.0
Enlarged Cardiomediastinum     639.0
Consolidation                  752.0
Pneumothorax                  1265.0
Cardiomegaly                  1542.0
No Finding                    1662.0
Atelectasis                   2199.0
Edema                         3400.0
Lung Opacity                  4921.0
Pleural Effusion              5084.0
Support Devices               6857.0
dtype: float64

# Step 3

In [213]:
# ============================================================
# Cell 1 — load concepts (order is fixed from here on, never reshuffle)
# ============================================================
import json
import torch
 
concepts = json.load(open("concepts_stage1.json"))
print(f"Loaded {len(concepts)} concepts")
print(f"First 3: {concepts[:3]}")
print(f"Last 3:  {concepts[-3:]}")

Loaded 95 concepts
First 3: ['clear lung fields', 'normal cardiac silhouette', 'sharp costophrenic angles']
Last 3:  ['sternotomy wires', 'picc line', 'tracheostomy tube']

In [214]:
# ============================================================
# Cell 2 — encode through BiomedCLIP text tower
# (model + tokenizer assumed live in kernel from earlier steps)
# ============================================================
txt_tokens = tokenizer(concepts, context_length=256)
 
with torch.no_grad():
    text_emb = model.encode_text(txt_tokens)
    text_emb = text_emb / text_emb.norm(dim=-1, keepdim=True)  # L2 normalize
 
print(f"text_emb shape: {text_emb.shape}")   # expect [95, 512]
print(f"Sample norms (should all be ~1.0): {text_emb.norm(dim=-1)[:5]}")

text_emb shape: torch.Size([95, 512])
Sample norms (should all be ~1.0): tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000])

In [215]:
# ============================================================
# Cell 3 — save to disk (computed once, never recomputed)
# ============================================================
torch.save(text_emb, "text_emb.pt")
print("Saved text_emb.pt")

Saved text_emb.pt

In [216]:
# ============================================================
# Cell 4 — sanity check: reload and verify
# ============================================================
loaded = torch.load("text_emb.pt")
assert loaded.shape == text_emb.shape
assert torch.allclose(loaded, text_emb)
print(f"Reload check passed — shape {loaded.shape}, values match ✓")

Reload check passed — shape torch.Size([95, 512]), values match ✓

### Step 4 - Get the tensor for the imaegs that is the timage embeddigns [image_count, 512]

In [217]:

# ============================================================
# Cell 1 — imports + config
# ============================================================
import numpy as np
import pandas as pd
import torch
from PIL import Image
from pathlib import Path
from tqdm import tqdm
 
DEVICE = "mps"       # Apple Silicon — change to "cuda" or "cpu" if needed
BATCH_SIZE = 32
CHECKPOINT_EVERY = 1000
IMG_ROOT = Path("CheXpert-v1.0-small")   # folder containing train/patient.../...jpg
 
# model + preprocess assumed live in kernel from earlier steps
# CRITICAL: move the model itself to MPS — inputs alone being on MPS
# isn't enough, the weights must be on the same device or PyTorch errors.
model = model.to(DEVICE)

In [219]:
# ============================================================
# Cell 2 — encoding function (shared across all three splits)
# ============================================================
def encode_split(df, split_name):
    """
    Encodes all images in df (in CSV row order) through BiomedCLIP image tower.
    Saves checkpoints every CHECKPOINT_EVERY images to avoid losing progress.
    Returns full embedding array of shape [len(df), 512].
    """
    out_path = Path(f"img_emb_{split_name}.npy")
    ckpt_path = Path(f"img_emb_{split_name}_ckpt.npy")
 
    paths = df["Path"].tolist()
    n = len(paths)
 
    # resume from checkpoint if one exists
    if ckpt_path.exists():
        done = np.load(ckpt_path)
        start_idx = len(done)
        print(f"[{split_name}] Resuming from checkpoint at image {start_idx}/{n}")
    else:
        done = np.zeros((0, 512), dtype=np.float32)
        start_idx = 0
        print(f"[{split_name}] Starting fresh — {n} images to encode")
 
    all_embs = list(done) if len(done) > 0 else []
 
    model.eval()
    batch_imgs = []
    batch_indices = []
 
    def flush_batch():
        if not batch_imgs:
            return
        tensor = torch.stack(batch_imgs).to(DEVICE)
        with torch.no_grad():
            emb = model.encode_image(tensor)
            emb = emb / emb.norm(dim=-1, keepdim=True)  # L2 normalize
        all_embs.extend(emb.cpu().numpy())
        batch_imgs.clear()
        batch_indices.clear()
 
    for i in tqdm(range(start_idx, n), desc=split_name):
        img_path = IMG_ROOT / paths[i]
        img = Image.open(img_path).convert("RGB")
        batch_imgs.append(preprocess(img))
        batch_indices.append(i)
 
        # flush when batch is full
        if len(batch_imgs) == BATCH_SIZE:
            flush_batch()
 
        # checkpoint
        if (i + 1) % CHECKPOINT_EVERY == 0:
            np.save(ckpt_path, np.array(all_embs, dtype=np.float32))
            print(f"[{split_name}] Checkpoint saved at {i + 1}/{n}")
 
    # flush any remaining images in the last partial batch
    flush_batch()
 
    # save final output, remove checkpoint
    final = np.array(all_embs, dtype=np.float32)
    np.save(out_path, final)
    if ckpt_path.exists():
        ckpt_path.unlink()
 
    print(f"[{split_name}] Done — saved {out_path}, shape {final.shape}")
    return final

In [221]:
# ============================================================
# Cell 3 — encode all three splits
# (order: train first, then val, then test — each is independent)
# ============================================================
train_df = pd.read_csv("train_full.csv")
val_df   = pd.read_csv("val_full.csv")
test_df  = pd.read_csv("test_full.csv")
 
img_emb_train = encode_split(train_df, "train")
img_emb_val   = encode_split(val_df,   "val")
img_emb_test  = encode_split(test_df,  "test")

[train] Starting fresh — 94563 images to encode

train:   0%|                                         | 0/94563 [00:00<?, ?it/s]

train:   0%|                                | 32/94563 [00:00<18:20, 85.91it/s]

train:   0%|                                | 64/94563 [00:00<16:29, 95.49it/s]

train:   0%|                                | 96/94563 [00:00<15:53, 99.07it/s]

train:   0%|                              | 128/94563 [00:01<15:34, 101.03it/s]

train:   0%|                              | 160/94563 [00:01<15:24, 102.10it/s]

train:   0%|                              | 192/94563 [00:01<15:17, 102.81it/s]

train:   0%|                              | 224/94563 [00:02<15:15, 103.04it/s]

train:   0%|                              | 256/94563 [00:02<15:11, 103.49it/s]

train:   0%|                              | 288/94563 [00:02<15:10, 103.50it/s]

train:   0%|                              | 320/94563 [00:03<15:09, 103.64it/s]

train:   0%|                              | 352/94563 [00:03<15:14, 103.01it/s]

train:   0%|                              | 384/94563 [00:03<15:12, 103.18it/s]

train:   0%|▏                             | 416/94563 [00:04<15:10, 103.39it/s]

train:   0%|▏                             | 448/94563 [00:04<15:09, 103.47it/s]

train:   1%|▏                             | 480/94563 [00:04<15:07, 103.64it/s]

train:   1%|▏                             | 512/94563 [00:05<15:06, 103.76it/s]

train:   1%|▏                             | 544/94563 [00:05<15:05, 103.79it/s]

train:   1%|▏                             | 576/94563 [00:05<15:07, 103.61it/s]

train:   1%|▏                             | 608/94563 [00:05<15:06, 103.67it/s]

train:   1%|▏                             | 640/94563 [00:06<15:28, 101.18it/s]

train:   1%|▏                             | 672/94563 [00:06<15:19, 102.11it/s]

train:   1%|▏                             | 704/94563 [00:06<15:11, 102.99it/s]

train:   1%|▏                             | 736/94563 [00:07<15:07, 103.41it/s]

train:   1%|▏                             | 768/94563 [00:07<15:03, 103.76it/s]

train:   1%|▎                             | 800/94563 [00:07<15:04, 103.70it/s]

train:   1%|▎                             | 832/94563 [00:08<15:02, 103.82it/s]

train:   1%|▎                             | 864/94563 [00:08<15:02, 103.85it/s]

train:   1%|▎                             | 896/94563 [00:08<14:59, 104.11it/s]

train:   1%|▎                             | 928/94563 [00:09<14:57, 104.31it/s]

train:   1%|▎                             | 960/94563 [00:09<14:55, 104.49it/s]

train:   1%|▎                             | 992/94563 [00:09<14:56, 104.33it/s]

[train] Checkpoint saved at 1000/94563

train:   1%|▎                            | 1024/94563 [00:09<14:57, 104.19it/s]

train:   1%|▎                            | 1056/94563 [00:10<14:56, 104.30it/s]

train:   1%|▎                            | 1088/94563 [00:10<14:56, 104.30it/s]

train:   1%|▎                            | 1120/94563 [00:10<14:56, 104.19it/s]

train:   1%|▎                            | 1152/94563 [00:11<14:55, 104.29it/s]

train:   1%|▎                            | 1184/94563 [00:11<14:54, 104.34it/s]

train:   1%|▎                            | 1216/94563 [00:11<14:55, 104.26it/s]

train:   1%|▍                            | 1248/94563 [00:12<14:55, 104.16it/s]

train:   1%|▍                            | 1280/94563 [00:12<14:56, 104.05it/s]

train:   1%|▍                            | 1312/94563 [00:12<14:56, 104.03it/s]

train:   1%|▍                            | 1344/94563 [00:13<14:54, 104.21it/s]

train:   1%|▍                            | 1376/94563 [00:13<14:53, 104.25it/s]

train:   1%|▍                            | 1408/94563 [00:13<14:53, 104.26it/s]

train:   2%|▍                            | 1440/94563 [00:13<14:55, 103.97it/s]

train:   2%|▍                            | 1472/94563 [00:14<14:55, 103.97it/s]

train:   2%|▍                            | 1504/94563 [00:14<14:54, 104.08it/s]

train:   2%|▍                            | 1536/94563 [00:14<14:56, 103.80it/s]

train:   2%|▍                            | 1568/94563 [00:15<14:57, 103.63it/s]

train:   2%|▍                            | 1600/94563 [00:15<14:56, 103.72it/s]

train:   2%|▌                            | 1632/94563 [00:15<14:55, 103.82it/s]

train:   2%|▌                            | 1664/94563 [00:16<14:54, 103.86it/s]

train:   2%|▌                            | 1696/94563 [00:16<14:53, 103.93it/s]

train:   2%|▌                            | 1728/94563 [00:16<14:53, 103.86it/s]

train:   2%|▌                            | 1760/94563 [00:17<15:22, 100.63it/s]

train:   2%|▌                            | 1792/94563 [00:17<15:16, 101.20it/s]

train:   2%|▌                            | 1824/94563 [00:17<15:13, 101.49it/s]

train:   2%|▌                            | 1856/94563 [00:17<15:10, 101.82it/s]

train:   2%|▌                            | 1888/94563 [00:18<15:05, 102.30it/s]

train:   2%|▌                            | 1920/94563 [00:18<15:01, 102.76it/s]

train:   2%|▌                            | 1952/94563 [00:18<14:56, 103.25it/s]

train:   2%|▌                            | 1984/94563 [00:19<14:56, 103.25it/s]

[train] Checkpoint saved at 2000/94563

train:   2%|▌                            | 2016/94563 [00:19<14:55, 103.36it/s]

train:   2%|▋                            | 2048/94563 [00:19<14:54, 103.42it/s]

train:   2%|▋                            | 2080/94563 [00:20<14:53, 103.49it/s]

train:   2%|▋                            | 2112/94563 [00:20<14:51, 103.68it/s]

train:   2%|▋                            | 2144/94563 [00:20<14:49, 103.96it/s]

train:   2%|▋                            | 2176/94563 [00:21<14:47, 104.05it/s]

train:   2%|▋                            | 2208/94563 [00:21<14:46, 104.18it/s]

train:   2%|▋                            | 2240/94563 [00:21<14:44, 104.37it/s]

train:   2%|▋                            | 2272/94563 [00:21<14:44, 104.30it/s]

train:   2%|▋                            | 2304/94563 [00:22<14:47, 103.99it/s]

train:   2%|▋                            | 2336/94563 [00:22<14:47, 103.92it/s]

train:   3%|▋                            | 2368/94563 [00:22<14:47, 103.93it/s]

train:   3%|▋                            | 2400/94563 [00:23<14:46, 103.97it/s]

train:   3%|▋                            | 2432/94563 [00:23<14:45, 103.99it/s]

train:   3%|▊                            | 2464/94563 [00:23<14:50, 103.42it/s]

train:   3%|▊                            | 2496/94563 [00:24<14:51, 103.22it/s]

train:   3%|▊                            | 2528/94563 [00:24<14:50, 103.37it/s]

train:   3%|▊                            | 2560/94563 [00:24<14:48, 103.52it/s]

train:   3%|▊                            | 2592/94563 [00:25<14:47, 103.68it/s]

train:   3%|▊                            | 2624/94563 [00:25<14:45, 103.83it/s]

train:   3%|▊                            | 2656/94563 [00:25<14:46, 103.72it/s]

train:   3%|▊                            | 2688/94563 [00:26<14:46, 103.69it/s]

train:   3%|▊                            | 2720/94563 [00:26<14:44, 103.80it/s]

train:   3%|▊                            | 2752/94563 [00:26<14:44, 103.85it/s]

train:   3%|▊                            | 2784/94563 [00:26<14:44, 103.78it/s]

train:   3%|▊                            | 2816/94563 [00:27<14:43, 103.81it/s]

train:   3%|▊                            | 2848/94563 [00:27<14:42, 103.88it/s]

train:   3%|▉                            | 2880/94563 [00:27<14:42, 103.86it/s]

train:   3%|▉                            | 2912/94563 [00:28<14:42, 103.83it/s]

train:   3%|▉                            | 2944/94563 [00:28<14:42, 103.80it/s]

train:   3%|▉                            | 2976/94563 [00:28<14:41, 103.90it/s]

[train] Checkpoint saved at 3000/94563

train:   3%|▉                            | 3008/94563 [00:29<15:03, 101.29it/s]

train:   3%|▉                            | 3040/94563 [00:29<14:57, 101.94it/s]

train:   3%|▉                            | 3072/94563 [00:29<14:53, 102.45it/s]

train:   3%|▉                            | 3104/94563 [00:30<14:48, 102.91it/s]

train:   3%|▉                            | 3136/94563 [00:30<14:48, 102.91it/s]

train:   3%|▉                            | 3168/94563 [00:30<14:47, 102.96it/s]

train:   3%|▉                            | 3200/94563 [00:30<14:48, 102.78it/s]

train:   3%|▉                            | 3232/94563 [00:31<14:48, 102.77it/s]

train:   3%|█                            | 3264/94563 [00:31<14:49, 102.65it/s]

train:   3%|█                            | 3296/94563 [00:31<14:48, 102.78it/s]

train:   4%|█                            | 3328/94563 [00:32<14:46, 102.90it/s]

train:   4%|█                            | 3360/94563 [00:32<14:44, 103.12it/s]

train:   4%|█                            | 3392/94563 [00:32<14:43, 103.14it/s]

train:   4%|█                            | 3424/94563 [00:33<14:43, 103.11it/s]

train:   4%|█                            | 3456/94563 [00:33<14:42, 103.20it/s]

train:   4%|█                            | 3488/94563 [00:33<14:41, 103.27it/s]

train:   4%|█                            | 3520/94563 [00:34<14:41, 103.31it/s]

train:   4%|█                            | 3552/94563 [00:34<14:38, 103.64it/s]

train:   4%|█                            | 3584/94563 [00:34<14:37, 103.70it/s]

train:   4%|█                            | 3616/94563 [00:34<14:36, 103.72it/s]

train:   4%|█                            | 3648/94563 [00:35<14:38, 103.46it/s]

train:   4%|█▏                           | 3680/94563 [00:35<14:38, 103.39it/s]

train:   4%|█▏                           | 3712/94563 [00:35<14:38, 103.43it/s]

train:   4%|█▏                           | 3744/94563 [00:36<14:39, 103.27it/s]

train:   4%|█▏                           | 3776/94563 [00:36<14:38, 103.31it/s]

train:   4%|█▏                           | 3808/94563 [00:36<14:39, 103.24it/s]

train:   4%|█▏                           | 3840/94563 [00:37<14:41, 102.92it/s]

train:   4%|█▏                           | 3872/94563 [00:37<14:41, 102.90it/s]

train:   4%|█▏                           | 3904/94563 [00:37<14:41, 102.87it/s]

train:   4%|█▏                           | 3936/94563 [00:38<14:40, 102.91it/s]

train:   4%|█▏                           | 3968/94563 [00:38<14:39, 103.03it/s]

train:   4%|█▏                           | 4000/94563 [00:38<14:40, 102.91it/s]

[train] Checkpoint saved at 4000/94563

train:   4%|█▏                           | 4032/94563 [00:39<14:38, 103.04it/s]

train:   4%|█▏                           | 4064/94563 [00:39<14:36, 103.26it/s]

train:   4%|█▎                           | 4096/94563 [00:39<14:37, 103.15it/s]

train:   4%|█▎                           | 4128/94563 [00:39<14:36, 103.15it/s]

train:   4%|█▎                           | 4160/94563 [00:40<14:37, 103.02it/s]

train:   4%|█▎                           | 4192/94563 [00:40<14:38, 102.84it/s]

train:   4%|█▎                           | 4224/94563 [00:40<14:38, 102.78it/s]

train:   5%|█▎                           | 4256/94563 [00:41<14:38, 102.85it/s]

train:   5%|█▎                           | 4288/94563 [00:41<14:36, 103.05it/s]

train:   5%|█▎                           | 4320/94563 [00:41<14:35, 103.11it/s]

train:   5%|█▎                           | 4352/94563 [00:42<14:34, 103.12it/s]

train:   5%|█▎                           | 4384/94563 [00:42<14:33, 103.25it/s]

train:   5%|█▎                           | 4416/94563 [00:42<14:33, 103.21it/s]

train:   5%|█▎                           | 4448/94563 [00:43<14:33, 103.19it/s]

train:   5%|█▎                           | 4480/94563 [00:43<14:31, 103.40it/s]

train:   5%|█▍                           | 4512/94563 [00:43<14:31, 103.35it/s]

train:   5%|█▍                           | 4544/94563 [00:43<14:30, 103.41it/s]

train:   5%|█▍                           | 4576/94563 [00:44<14:30, 103.39it/s]

train:   5%|█▍                           | 4608/94563 [00:44<14:31, 103.23it/s]

train:   5%|█▍                           | 4640/94563 [00:44<14:30, 103.29it/s]

train:   5%|█▍                           | 4672/94563 [00:45<14:29, 103.38it/s]

train:   5%|█▍                           | 4704/94563 [00:45<14:28, 103.41it/s]

train:   5%|█▍                           | 4736/94563 [00:45<14:29, 103.35it/s]

train:   5%|█▍                           | 4768/94563 [00:46<14:30, 103.20it/s]

train:   5%|█▍                           | 4800/94563 [00:46<14:31, 103.02it/s]

train:   5%|█▍                           | 4832/94563 [00:46<14:30, 103.06it/s]

train:   5%|█▍                           | 4864/94563 [00:47<14:29, 103.22it/s]

train:   5%|█▌                           | 4896/94563 [00:47<14:28, 103.21it/s]

train:   5%|█▌                           | 4928/94563 [00:47<14:28, 103.20it/s]

train:   5%|█▌                           | 4960/94563 [00:48<14:28, 103.15it/s]

train:   5%|█▌                           | 4992/94563 [00:48<14:27, 103.25it/s]

[train] Checkpoint saved at 5000/94563

train:   5%|█▌                           | 5024/94563 [00:48<14:29, 103.00it/s]

train:   5%|█▌                           | 5056/94563 [00:48<14:28, 103.12it/s]

train:   5%|█▌                           | 5088/94563 [00:49<14:27, 103.17it/s]

train:   5%|█▌                           | 5120/94563 [00:49<14:25, 103.30it/s]

train:   5%|█▌                           | 5152/94563 [00:49<14:28, 102.95it/s]

train:   5%|█▌                           | 5184/94563 [00:50<14:27, 103.02it/s]

train:   6%|█▌                           | 5216/94563 [00:50<14:25, 103.19it/s]

train:   6%|█▌                           | 5248/94563 [00:50<14:25, 103.18it/s]

train:   6%|█▌                           | 5280/94563 [00:51<14:33, 102.26it/s]

train:   6%|█▋                           | 5312/94563 [00:51<14:28, 102.72it/s]

train:   6%|█▋                           | 5344/94563 [00:51<14:26, 103.02it/s]

train:   6%|█▋                           | 5376/94563 [00:52<14:24, 103.16it/s]

train:   6%|█▋                           | 5408/94563 [00:52<14:47, 100.47it/s]

train:   6%|█▋                           | 5440/94563 [00:52<14:39, 101.30it/s]

train:   6%|█▋                           | 5472/94563 [00:53<14:33, 102.02it/s]

train:   6%|█▋                           | 5504/94563 [00:53<14:29, 102.47it/s]

train:   6%|█▋                           | 5536/94563 [00:53<14:24, 102.96it/s]

train:   6%|█▋                           | 5568/94563 [00:53<14:23, 103.09it/s]

train:   6%|█▋                           | 5600/94563 [00:54<14:22, 103.10it/s]

train:   6%|█▋                           | 5632/94563 [00:54<14:23, 103.02it/s]

train:   6%|█▋                           | 5664/94563 [00:54<14:20, 103.29it/s]

train:   6%|█▋                           | 5696/94563 [00:55<14:19, 103.42it/s]

train:   6%|█▊                           | 5728/94563 [00:55<14:17, 103.54it/s]

train:   6%|█▊                           | 5760/94563 [00:55<14:19, 103.29it/s]

train:   6%|█▊                           | 5792/94563 [00:56<14:19, 103.34it/s]

train:   6%|█▊                           | 5824/94563 [00:56<14:18, 103.32it/s]

train:   6%|█▊                           | 5856/94563 [00:56<14:17, 103.44it/s]

train:   6%|█▊                           | 5888/94563 [00:57<14:17, 103.40it/s]

train:   6%|█▊                           | 5920/94563 [00:57<14:15, 103.65it/s]

train:   6%|█▊                           | 5952/94563 [00:57<14:16, 103.46it/s]

train:   6%|█▊                           | 5984/94563 [00:57<14:16, 103.47it/s]

[train] Checkpoint saved at 6000/94563

train:   6%|█▊                           | 6016/94563 [00:58<14:19, 103.07it/s]

train:   6%|█▊                           | 6048/94563 [00:58<14:18, 103.16it/s]

train:   6%|█▊                           | 6080/94563 [00:58<14:15, 103.45it/s]

train:   6%|█▊                           | 6112/94563 [00:59<14:14, 103.50it/s]

train:   6%|█▉                           | 6144/94563 [00:59<14:14, 103.52it/s]

train:   7%|█▉                           | 6176/94563 [00:59<14:12, 103.67it/s]

train:   7%|█▉                           | 6208/94563 [01:00<14:11, 103.79it/s]

train:   7%|█▉                           | 6240/94563 [01:00<14:09, 103.92it/s]

train:   7%|█▉                           | 6272/94563 [01:00<14:09, 103.93it/s]

train:   7%|█▉                           | 6304/94563 [01:01<14:11, 103.68it/s]

train:   7%|█▉                           | 6336/94563 [01:01<14:11, 103.60it/s]

train:   7%|█▉                           | 6368/94563 [01:01<14:11, 103.55it/s]

train:   7%|█▉                           | 6400/94563 [01:01<14:12, 103.45it/s]

train:   7%|█▉                           | 6432/94563 [01:02<14:12, 103.40it/s]

train:   7%|█▉                           | 6464/94563 [01:02<14:12, 103.33it/s]

train:   7%|█▉                           | 6496/94563 [01:02<14:12, 103.33it/s]

train:   7%|██                           | 6528/94563 [01:03<14:10, 103.46it/s]

train:   7%|██                           | 6560/94563 [01:03<14:10, 103.51it/s]

train:   7%|██                           | 6592/94563 [01:03<14:09, 103.61it/s]

train:   7%|██                           | 6624/94563 [01:04<14:08, 103.70it/s]

train:   7%|██                           | 6656/94563 [01:04<14:06, 103.83it/s]

train:   7%|██                           | 6688/94563 [01:04<14:08, 103.56it/s]

train:   7%|██                           | 6720/94563 [01:05<14:09, 103.45it/s]

train:   7%|██                           | 6752/94563 [01:05<14:12, 102.98it/s]

train:   7%|██                           | 6784/94563 [01:05<14:14, 102.78it/s]

train:   7%|██                           | 6816/94563 [01:06<14:14, 102.67it/s]

train:   7%|██                           | 6848/94563 [01:06<14:12, 102.85it/s]

train:   7%|██                           | 6880/94563 [01:06<14:10, 103.13it/s]

train:   7%|██                           | 6912/94563 [01:06<14:10, 103.06it/s]

train:   7%|██▏                          | 6944/94563 [01:07<14:08, 103.21it/s]

train:   7%|██▏                          | 6976/94563 [01:07<14:07, 103.29it/s]

[train] Checkpoint saved at 7000/94563

train:   7%|██▏                          | 7008/94563 [01:07<14:11, 102.77it/s]

train:   7%|██▏                          | 7040/94563 [01:08<14:09, 103.03it/s]

train:   7%|██▏                          | 7072/94563 [01:08<14:08, 103.17it/s]

train:   8%|██▏                          | 7104/94563 [01:08<14:06, 103.29it/s]

train:   8%|██▏                          | 7136/94563 [01:09<14:04, 103.50it/s]

train:   8%|██▏                          | 7168/94563 [01:09<14:03, 103.57it/s]

train:   8%|██▏                          | 7200/94563 [01:09<14:03, 103.57it/s]

train:   8%|██▏                          | 7232/94563 [01:10<14:04, 103.41it/s]

train:   8%|██▏                          | 7264/94563 [01:10<14:05, 103.22it/s]

train:   8%|██▏                          | 7296/94563 [01:10<14:06, 103.10it/s]

train:   8%|██▏                          | 7328/94563 [01:10<14:08, 102.85it/s]

train:   8%|██▎                          | 7360/94563 [01:11<14:10, 102.50it/s]

train:   8%|██▎                          | 7392/94563 [01:11<14:11, 102.39it/s]

train:   8%|██▎                          | 7424/94563 [01:11<14:11, 102.33it/s]

train:   8%|██▎                          | 7456/94563 [01:12<14:13, 102.09it/s]

train:   8%|██▎                          | 7488/94563 [01:12<14:14, 101.89it/s]

train:   8%|██▎                          | 7520/94563 [01:12<14:17, 101.51it/s]

train:   8%|██▎                          | 7552/94563 [01:13<14:19, 101.20it/s]

train:   8%|██▎                          | 7584/94563 [01:13<14:19, 101.20it/s]

train:   8%|██▎                          | 7616/94563 [01:13<14:18, 101.23it/s]

train:   8%|██▎                          | 7648/94563 [01:14<14:19, 101.13it/s]

train:   8%|██▎                          | 7680/94563 [01:14<14:19, 101.12it/s]

train:   8%|██▎                          | 7712/94563 [01:14<14:20, 100.95it/s]

train:   8%|██▎                          | 7744/94563 [01:15<14:20, 100.94it/s]

train:   8%|██▍                          | 7776/94563 [01:15<14:21, 100.74it/s]

train:   8%|██▍                          | 7808/94563 [01:15<14:24, 100.41it/s]

train:   8%|██▍                          | 7840/94563 [01:16<14:22, 100.57it/s]

train:   8%|██▍                          | 7872/94563 [01:16<14:21, 100.65it/s]

train:   8%|██▍                          | 7904/94563 [01:16<14:21, 100.63it/s]

train:   8%|██▍                          | 7936/94563 [01:16<14:18, 100.88it/s]

train:   8%|██▍                          | 7968/94563 [01:17<14:18, 100.90it/s]

train:   8%|██▍                          | 8000/94563 [01:17<14:21, 100.49it/s]

[train] Checkpoint saved at 8000/94563

train:   8%|██▍                          | 8032/94563 [01:17<14:20, 100.55it/s]

train:   9%|██▍                          | 8064/94563 [01:18<14:17, 100.86it/s]

train:   9%|██▍                          | 8096/94563 [01:18<14:19, 100.56it/s]

train:   9%|██▍                          | 8128/94563 [01:18<14:19, 100.62it/s]

train:   9%|██▌                          | 8160/94563 [01:19<14:18, 100.69it/s]

train:   9%|██▌                          | 8192/94563 [01:19<14:16, 100.86it/s]

train:   9%|██▌                          | 8224/94563 [01:19<14:16, 100.78it/s]

train:   9%|██▌                          | 8256/94563 [01:20<14:16, 100.81it/s]

train:   9%|██▌                          | 8288/94563 [01:20<14:16, 100.70it/s]

train:   9%|██▌                          | 8320/94563 [01:20<14:16, 100.74it/s]

train:   9%|██▌                          | 8352/94563 [01:21<14:18, 100.44it/s]

train:   9%|██▌                          | 8384/94563 [01:21<14:17, 100.46it/s]

train:   9%|██▌                          | 8416/94563 [01:21<14:15, 100.65it/s]

train:   9%|██▌                          | 8448/94563 [01:22<14:14, 100.75it/s]

train:   9%|██▌                          | 8480/94563 [01:22<14:13, 100.80it/s]

train:   9%|██▌                          | 8512/94563 [01:22<14:14, 100.71it/s]

train:   9%|██▌                          | 8544/94563 [01:23<14:13, 100.78it/s]

train:   9%|██▋                          | 8576/94563 [01:23<14:14, 100.62it/s]

train:   9%|██▋                          | 8608/94563 [01:23<14:14, 100.61it/s]

train:   9%|██▋                          | 8640/94563 [01:23<14:13, 100.72it/s]

train:   9%|██▋                          | 8672/94563 [01:24<14:13, 100.65it/s]

train:   9%|██▋                          | 8704/94563 [01:24<14:14, 100.52it/s]

train:   9%|██▋                          | 8736/94563 [01:24<14:15, 100.35it/s]

train:   9%|██▋                          | 8768/94563 [01:25<14:14, 100.38it/s]

train:   9%|██▋                          | 8800/94563 [01:25<14:16, 100.17it/s]

train:   9%|██▋                          | 8832/94563 [01:25<14:15, 100.27it/s]

train:   9%|██▋                          | 8864/94563 [01:26<14:13, 100.45it/s]

train:   9%|██▋                          | 8896/94563 [01:26<14:11, 100.61it/s]

train:   9%|██▋                          | 8928/94563 [01:26<14:10, 100.68it/s]

train:   9%|██▋                          | 8960/94563 [01:27<14:11, 100.55it/s]

train:  10%|██▊                          | 8992/94563 [01:27<14:12, 100.42it/s]

[train] Checkpoint saved at 9000/94563

train:  10%|██▊                           | 9024/94563 [01:27<14:17, 99.74it/s]

train:  10%|██▊                           | 9056/94563 [01:28<14:16, 99.87it/s]

train:  10%|██▊                          | 9088/94563 [01:28<14:12, 100.23it/s]

train:  10%|██▊                          | 9120/94563 [01:28<14:11, 100.40it/s]

train:  10%|██▊                          | 9152/94563 [01:29<14:10, 100.40it/s]

train:  10%|██▊                          | 9184/94563 [01:29<14:11, 100.22it/s]

train:  10%|██▊                          | 9216/94563 [01:29<14:11, 100.23it/s]

train:  10%|██▊                          | 9248/94563 [01:30<14:09, 100.39it/s]

train:  10%|██▊                          | 9280/94563 [01:30<14:10, 100.28it/s]

train:  10%|██▊                          | 9312/94563 [01:30<14:09, 100.34it/s]

train:  10%|██▊                          | 9344/94563 [01:31<14:08, 100.40it/s]

train:  10%|██▉                          | 9376/94563 [01:31<14:08, 100.37it/s]

train:  10%|██▉                          | 9408/94563 [01:31<14:08, 100.38it/s]

train:  10%|██▉                          | 9440/94563 [01:31<14:09, 100.20it/s]

train:  10%|██▉                          | 9472/94563 [01:32<14:08, 100.32it/s]

train:  10%|██▉                          | 9504/94563 [01:32<14:08, 100.27it/s]

train:  10%|██▉                          | 9536/94563 [01:32<14:08, 100.26it/s]

train:  10%|███                           | 9568/94563 [01:33<14:10, 99.88it/s]

train:  10%|███                           | 9600/94563 [01:33<14:13, 99.57it/s]

train:  10%|███                           | 9632/94563 [01:33<14:13, 99.47it/s]

train:  10%|███                           | 9664/94563 [01:34<14:14, 99.38it/s]

train:  10%|███                           | 9696/94563 [01:34<14:13, 99.42it/s]

train:  10%|███                           | 9728/94563 [01:34<14:13, 99.40it/s]

train:  10%|███                           | 9760/94563 [01:35<14:13, 99.39it/s]

train:  10%|███                           | 9792/94563 [01:35<14:16, 98.93it/s]

train:  10%|███                           | 9824/94563 [01:35<14:19, 98.53it/s]

train:  10%|███▏                          | 9856/94563 [01:36<14:20, 98.46it/s]

train:  10%|███▏                          | 9888/94563 [01:36<14:19, 98.57it/s]

train:  10%|███▏                          | 9920/94563 [01:36<14:26, 97.64it/s]

train:  11%|███▏                          | 9952/94563 [01:37<14:41, 95.96it/s]

train:  11%|███▏                          | 9984/94563 [01:37<14:51, 94.92it/s]

[train] Checkpoint saved at 10000/94563

train:  11%|███                          | 10016/94563 [01:37<15:04, 93.47it/s]

train:  11%|███                          | 10048/94563 [01:38<15:06, 93.19it/s]

train:  11%|███                          | 10080/94563 [01:38<14:52, 94.70it/s]

train:  11%|███                          | 10112/94563 [01:38<14:41, 95.80it/s]

train:  11%|███                          | 10144/94563 [01:39<14:28, 97.25it/s]

train:  11%|███                          | 10176/94563 [01:39<14:25, 97.49it/s]

train:  11%|███▏                         | 10208/94563 [01:39<14:21, 97.89it/s]

train:  11%|███▏                         | 10240/94563 [01:40<14:20, 97.96it/s]

train:  11%|███▏                         | 10272/94563 [01:40<14:30, 96.83it/s]

train:  11%|███▏                         | 10304/94563 [01:40<14:27, 97.13it/s]

train:  11%|███▏                         | 10336/94563 [01:41<14:21, 97.71it/s]

train:  11%|███▏                         | 10368/94563 [01:41<14:18, 98.02it/s]

train:  11%|███▏                         | 10400/94563 [01:41<14:13, 98.57it/s]

train:  11%|███▏                         | 10432/94563 [01:42<14:11, 98.82it/s]

train:  11%|███▏                         | 10464/94563 [01:42<14:13, 98.57it/s]

train:  11%|███▏                         | 10496/94563 [01:42<14:52, 94.20it/s]

train:  11%|███▏                         | 10528/94563 [01:43<14:38, 95.70it/s]

train:  11%|███▏                         | 10560/94563 [01:43<14:27, 96.79it/s]

train:  11%|███▏                         | 10592/94563 [01:43<14:21, 97.51it/s]

train:  11%|███▎                         | 10624/94563 [01:44<14:14, 98.19it/s]

train:  11%|███▎                         | 10656/94563 [01:44<14:11, 98.50it/s]

train:  11%|███▎                         | 10688/94563 [01:44<14:08, 98.89it/s]

train:  11%|███▎                         | 10720/94563 [01:45<14:05, 99.18it/s]

train:  11%|███▎                         | 10752/94563 [01:45<14:03, 99.38it/s]

train:  11%|███▎                         | 10784/94563 [01:45<14:02, 99.47it/s]

train:  11%|███▎                         | 10816/94563 [01:46<14:01, 99.57it/s]

train:  11%|███▎                         | 10848/94563 [01:46<13:58, 99.79it/s]

train:  12%|███▎                         | 10880/94563 [01:46<13:59, 99.71it/s]

train:  12%|███▎                         | 10912/94563 [01:46<13:59, 99.65it/s]

train:  12%|███▎                         | 10944/94563 [01:47<13:57, 99.82it/s]

train:  12%|███▏                        | 10976/94563 [01:47<13:55, 100.00it/s]

[train] Checkpoint saved at 11000/94563

train:  12%|███▍                         | 11008/94563 [01:47<14:02, 99.14it/s]

train:  12%|███▍                         | 11040/94563 [01:48<13:59, 99.49it/s]

train:  12%|███▍                         | 11072/94563 [01:48<13:57, 99.63it/s]

train:  12%|███▍                         | 11104/94563 [01:48<13:58, 99.57it/s]

train:  12%|███▍                         | 11136/94563 [01:49<13:57, 99.61it/s]

train:  12%|███▍                         | 11168/94563 [01:49<13:55, 99.78it/s]

train:  12%|███▍                         | 11200/94563 [01:49<13:55, 99.78it/s]

train:  12%|███▍                         | 11232/94563 [01:50<13:56, 99.63it/s]

train:  12%|███▍                         | 11264/94563 [01:50<13:56, 99.62it/s]

train:  12%|███▍                         | 11296/94563 [01:50<13:56, 99.53it/s]

train:  12%|███▍                         | 11328/94563 [01:51<13:55, 99.68it/s]

train:  12%|███▍                         | 11360/94563 [01:51<13:54, 99.68it/s]

train:  12%|███▍                         | 11392/94563 [01:51<13:54, 99.66it/s]

train:  12%|███▌                         | 11424/94563 [01:52<13:54, 99.63it/s]

train:  12%|███▌                         | 11456/94563 [01:52<13:52, 99.87it/s]

train:  12%|███▌                         | 11488/94563 [01:52<13:52, 99.80it/s]

train:  12%|███▌                         | 11520/94563 [01:53<13:51, 99.91it/s]

train:  12%|███▌                         | 11552/94563 [01:53<13:50, 99.90it/s]

train:  12%|███▌                         | 11584/94563 [01:53<13:50, 99.91it/s]

train:  12%|███▌                         | 11616/94563 [01:54<13:50, 99.88it/s]

train:  12%|███▌                         | 11648/94563 [01:54<13:49, 99.92it/s]

train:  12%|███▌                         | 11680/94563 [01:54<13:49, 99.91it/s]

train:  12%|███▍                        | 11712/94563 [01:55<13:48, 100.00it/s]

train:  12%|███▍                        | 11744/94563 [01:55<13:47, 100.05it/s]

train:  12%|███▍                        | 11776/94563 [01:55<13:46, 100.11it/s]

train:  12%|███▍                        | 11808/94563 [01:55<13:46, 100.08it/s]

train:  13%|███▌                        | 11840/94563 [01:56<13:45, 100.26it/s]

train:  13%|███▌                        | 11872/94563 [01:56<13:43, 100.37it/s]

train:  13%|███▌                        | 11904/94563 [01:56<13:44, 100.19it/s]

train:  13%|███▌                        | 11936/94563 [01:57<13:44, 100.24it/s]

train:  13%|███▌                        | 11968/94563 [01:57<13:44, 100.16it/s]

train:  13%|███▋                         | 12000/94563 [01:57<13:49, 99.53it/s]

[train] Checkpoint saved at 12000/94563

train:  13%|███▋                         | 12032/94563 [01:58<13:48, 99.57it/s]

train:  13%|███▋                         | 12064/94563 [01:58<13:47, 99.68it/s]

train:  13%|███▋                         | 12096/94563 [01:58<13:46, 99.79it/s]

train:  13%|███▋                         | 12128/94563 [01:59<13:44, 99.93it/s]

train:  13%|███▋                         | 12160/94563 [01:59<13:44, 99.91it/s]

train:  13%|███▌                        | 12192/94563 [01:59<13:43, 100.00it/s]

train:  13%|███▌                        | 12224/94563 [02:00<13:42, 100.07it/s]

train:  13%|███▋                        | 12256/94563 [02:00<13:41, 100.19it/s]

train:  13%|███▋                        | 12288/94563 [02:00<13:40, 100.32it/s]

train:  13%|███▋                        | 12320/94563 [02:01<13:40, 100.30it/s]

train:  13%|███▋                        | 12352/94563 [02:01<13:38, 100.45it/s]

train:  13%|███▋                        | 12384/94563 [02:01<13:39, 100.25it/s]

train:  13%|███▋                        | 12416/94563 [02:02<13:39, 100.21it/s]

train:  13%|███▋                        | 12448/94563 [02:02<13:40, 100.11it/s]

train:  13%|███▋                        | 12480/94563 [02:02<13:38, 100.29it/s]

train:  13%|███▋                        | 12512/94563 [02:02<13:38, 100.30it/s]

train:  13%|███▋                        | 12544/94563 [02:03<13:37, 100.31it/s]

train:  13%|███▋                        | 12576/94563 [02:03<13:36, 100.36it/s]

train:  13%|███▋                        | 12608/94563 [02:03<13:37, 100.21it/s]

train:  13%|███▋                        | 12640/94563 [02:04<13:37, 100.15it/s]

train:  13%|███▊                        | 12672/94563 [02:04<13:37, 100.20it/s]

train:  13%|███▊                        | 12704/94563 [02:04<13:38, 100.01it/s]

train:  13%|███▊                        | 12736/94563 [02:05<13:37, 100.06it/s]

train:  14%|███▊                        | 12768/94563 [02:05<13:37, 100.01it/s]

train:  14%|███▊                        | 12800/94563 [02:05<13:35, 100.24it/s]

train:  14%|███▊                        | 12832/94563 [02:06<13:35, 100.28it/s]

train:  14%|███▊                        | 12864/94563 [02:06<13:34, 100.25it/s]

train:  14%|███▊                        | 12896/94563 [02:06<13:34, 100.26it/s]

train:  14%|███▊                        | 12928/94563 [02:07<13:34, 100.21it/s]

train:  14%|███▊                        | 12960/94563 [02:07<13:33, 100.25it/s]

train:  14%|███▊                        | 12992/94563 [02:07<13:33, 100.24it/s]

[train] Checkpoint saved at 13000/94563

train:  14%|███▉                         | 13024/94563 [02:08<13:40, 99.43it/s]

train:  14%|████                         | 13056/94563 [02:08<13:36, 99.83it/s]

train:  14%|████                         | 13088/94563 [02:08<13:35, 99.87it/s]

train:  14%|███▉                        | 13120/94563 [02:09<13:33, 100.08it/s]

train:  14%|███▉                        | 13152/94563 [02:09<13:32, 100.24it/s]

train:  14%|███▉                        | 13184/94563 [02:09<13:31, 100.29it/s]

train:  14%|███▉                        | 13216/94563 [02:10<13:31, 100.30it/s]

train:  14%|███▉                        | 13248/94563 [02:10<13:29, 100.42it/s]

train:  14%|███▉                        | 13280/94563 [02:10<13:28, 100.49it/s]

train:  14%|███▉                        | 13312/94563 [02:10<13:28, 100.47it/s]

train:  14%|███▉                        | 13344/94563 [02:11<13:28, 100.43it/s]

train:  14%|███▉                        | 13376/94563 [02:11<13:27, 100.50it/s]

train:  14%|███▉                        | 13408/94563 [02:11<13:27, 100.53it/s]

train:  14%|███▉                        | 13440/94563 [02:12<13:26, 100.65it/s]

train:  14%|███▉                        | 13472/94563 [02:12<13:25, 100.63it/s]

train:  14%|███▉                        | 13504/94563 [02:12<13:25, 100.67it/s]

train:  14%|████                        | 13536/94563 [02:13<13:24, 100.74it/s]

train:  14%|████                        | 13568/94563 [02:13<13:25, 100.54it/s]

train:  14%|████                        | 13600/94563 [02:13<13:25, 100.45it/s]

train:  14%|████                        | 13632/94563 [02:14<13:25, 100.47it/s]

train:  14%|████                        | 13664/94563 [02:14<13:24, 100.50it/s]

train:  14%|████                        | 13696/94563 [02:14<13:23, 100.62it/s]

train:  15%|████                        | 13728/94563 [02:15<13:23, 100.56it/s]

train:  15%|████                        | 13760/94563 [02:15<13:24, 100.44it/s]

train:  15%|████                        | 13792/94563 [02:15<13:24, 100.37it/s]

train:  15%|████▏                        | 13824/94563 [02:16<13:28, 99.90it/s]

train:  15%|████▏                        | 13856/94563 [02:16<13:31, 99.43it/s]

train:  15%|████▎                        | 13888/94563 [02:16<13:35, 98.94it/s]

train:  15%|████▎                        | 13920/94563 [02:17<13:37, 98.67it/s]

train:  15%|████▎                        | 13952/94563 [02:17<13:38, 98.45it/s]

train:  15%|████▎                        | 13984/94563 [02:17<13:43, 97.91it/s]

[train] Checkpoint saved at 14000/94563

train:  15%|████▎                        | 14016/94563 [02:18<13:53, 96.69it/s]

train:  15%|████▎                        | 14048/94563 [02:18<13:51, 96.84it/s]

train:  15%|████▎                        | 14080/94563 [02:18<13:46, 97.36it/s]

train:  15%|████▎                        | 14112/94563 [02:19<13:45, 97.42it/s]

train:  15%|████▎                        | 14144/94563 [02:19<13:44, 97.52it/s]

train:  15%|████▎                        | 14176/94563 [02:19<13:45, 97.38it/s]

train:  15%|████▎                        | 14208/94563 [02:20<13:40, 97.91it/s]

train:  15%|████▎                        | 14240/94563 [02:20<13:37, 98.24it/s]

train:  15%|████▍                        | 14272/94563 [02:20<13:34, 98.60it/s]

train:  15%|████▍                        | 14304/94563 [02:20<13:30, 99.05it/s]

train:  15%|████▍                        | 14336/94563 [02:21<13:27, 99.40it/s]

train:  15%|████▍                        | 14368/94563 [02:21<13:26, 99.47it/s]

train:  15%|████▍                        | 14400/94563 [02:21<13:24, 99.66it/s]

train:  15%|████▎                       | 14432/94563 [02:22<13:20, 100.05it/s]

train:  15%|████▎                       | 14464/94563 [02:22<13:20, 100.05it/s]

train:  15%|████▎                       | 14496/94563 [02:22<13:18, 100.27it/s]

train:  15%|████▎                       | 14528/94563 [02:23<13:16, 100.47it/s]

train:  15%|████▎                       | 14560/94563 [02:23<13:14, 100.65it/s]

train:  15%|████▎                       | 14592/94563 [02:23<13:14, 100.60it/s]

train:  15%|████▎                       | 14624/94563 [02:24<13:16, 100.42it/s]

train:  15%|████▎                       | 14656/94563 [02:24<13:14, 100.59it/s]

train:  16%|████▎                       | 14688/94563 [02:24<13:14, 100.54it/s]

train:  16%|████▎                       | 14720/94563 [02:25<13:15, 100.37it/s]

train:  16%|████▎                       | 14752/94563 [02:25<13:16, 100.19it/s]

train:  16%|████▍                       | 14784/94563 [02:25<13:15, 100.27it/s]

train:  16%|████▍                       | 14816/94563 [02:26<13:15, 100.28it/s]

train:  16%|████▌                        | 14848/94563 [02:26<13:17, 99.90it/s]

train:  16%|████▌                        | 14880/94563 [02:26<13:20, 99.50it/s]

train:  16%|████▌                        | 14912/94563 [02:27<13:23, 99.12it/s]

train:  16%|████▌                        | 14944/94563 [02:27<13:31, 98.14it/s]

train:  16%|████▌                        | 14976/94563 [02:27<13:30, 98.23it/s]

[train] Checkpoint saved at 15000/94563

train:  16%|████▌                        | 15008/94563 [02:28<13:35, 97.50it/s]

train:  16%|████▌                        | 15040/94563 [02:28<13:30, 98.10it/s]

train:  16%|████▌                        | 15072/94563 [02:28<13:26, 98.53it/s]

train:  16%|████▋                        | 15104/94563 [02:29<13:22, 99.02it/s]

train:  16%|████▋                        | 15136/94563 [02:29<13:19, 99.34it/s]

train:  16%|████▋                        | 15168/94563 [02:29<13:17, 99.55it/s]

train:  16%|████▋                        | 15200/94563 [02:29<13:16, 99.66it/s]

train:  16%|████▋                        | 15232/94563 [02:30<13:14, 99.83it/s]

train:  16%|████▌                       | 15264/94563 [02:30<13:12, 100.05it/s]

train:  16%|████▌                       | 15296/94563 [02:30<13:10, 100.33it/s]

train:  16%|████▌                       | 15328/94563 [02:31<13:08, 100.45it/s]

train:  16%|████▌                       | 15360/94563 [02:31<13:07, 100.62it/s]

train:  16%|████▌                       | 15392/94563 [02:31<13:05, 100.75it/s]

train:  16%|████▌                       | 15424/94563 [02:32<13:04, 100.91it/s]

train:  16%|████▌                       | 15456/94563 [02:32<13:03, 100.92it/s]

train:  16%|████▌                       | 15488/94563 [02:32<13:02, 101.02it/s]

train:  16%|████▌                       | 15520/94563 [02:33<13:02, 100.97it/s]

train:  16%|████▌                       | 15552/94563 [02:33<13:01, 101.04it/s]

train:  16%|████▌                       | 15584/94563 [02:33<13:02, 100.88it/s]

train:  17%|████▌                       | 15616/94563 [02:34<13:02, 100.83it/s]

train:  17%|████▋                       | 15648/94563 [02:34<13:03, 100.66it/s]

train:  17%|████▋                       | 15680/94563 [02:34<13:03, 100.66it/s]

train:  17%|████▋                       | 15712/94563 [02:35<13:04, 100.55it/s]

train:  17%|████▋                       | 15744/94563 [02:35<13:04, 100.48it/s]

train:  17%|████▊                        | 15776/94563 [02:35<13:10, 99.72it/s]

train:  17%|████▊                        | 15808/94563 [02:36<13:11, 99.52it/s]

train:  17%|████▊                        | 15840/94563 [02:36<13:13, 99.22it/s]

train:  17%|████▊                        | 15872/94563 [02:36<13:16, 98.82it/s]

train:  17%|████▉                        | 15904/94563 [02:36<13:15, 98.88it/s]

train:  17%|████▉                        | 15936/94563 [02:37<13:12, 99.23it/s]

train:  17%|████▉                        | 15968/94563 [02:37<13:09, 99.53it/s]

train:  17%|████▉                        | 16000/94563 [02:37<13:16, 98.59it/s]

[train] Checkpoint saved at 16000/94563

train:  17%|████▉                        | 16032/94563 [02:38<13:12, 99.13it/s]

train:  17%|████▉                        | 16064/94563 [02:38<13:08, 99.53it/s]

train:  17%|████▉                        | 16096/94563 [02:38<13:06, 99.71it/s]

train:  17%|████▉                        | 16128/94563 [02:39<13:05, 99.91it/s]

train:  17%|████▉                        | 16160/94563 [02:39<13:04, 99.88it/s]

train:  17%|████▉                        | 16192/94563 [02:39<13:03, 99.99it/s]

train:  17%|████▊                       | 16224/94563 [02:40<13:00, 100.31it/s]

train:  17%|████▊                       | 16256/94563 [02:40<12:58, 100.55it/s]

train:  17%|████▊                       | 16288/94563 [02:40<12:57, 100.62it/s]

train:  17%|████▊                       | 16320/94563 [02:41<12:56, 100.81it/s]

train:  17%|████▊                       | 16352/94563 [02:41<12:55, 100.83it/s]

train:  17%|████▊                       | 16384/94563 [02:41<12:55, 100.85it/s]

train:  17%|████▊                       | 16416/94563 [02:42<12:53, 101.04it/s]

train:  17%|████▊                       | 16448/94563 [02:42<12:54, 100.90it/s]

train:  17%|█████                        | 16480/94563 [02:42<13:11, 98.60it/s]

train:  17%|█████                        | 16512/94563 [02:43<13:08, 99.03it/s]

train:  17%|█████                        | 16544/94563 [02:43<13:05, 99.32it/s]

train:  18%|█████                        | 16576/94563 [02:43<13:04, 99.40it/s]

train:  18%|█████                        | 16608/94563 [02:44<13:03, 99.55it/s]

train:  18%|█████                        | 16640/94563 [02:44<13:02, 99.57it/s]

train:  18%|█████                        | 16672/94563 [02:44<13:01, 99.72it/s]

train:  18%|█████                        | 16704/94563 [02:44<13:00, 99.79it/s]

train:  18%|█████▏                       | 16736/94563 [02:45<13:00, 99.75it/s]

train:  18%|█████▏                       | 16768/94563 [02:45<13:00, 99.73it/s]

train:  18%|█████▏                       | 16800/94563 [02:45<12:58, 99.93it/s]

train:  18%|█████▏                       | 16832/94563 [02:46<12:57, 99.92it/s]

train:  18%|█████▏                       | 16864/94563 [02:46<12:57, 99.94it/s]

train:  18%|█████▏                       | 16896/94563 [02:46<12:58, 99.74it/s]

train:  18%|█████▏                       | 16928/94563 [02:47<13:00, 99.52it/s]

train:  18%|█████▏                       | 16960/94563 [02:47<13:01, 99.31it/s]

train:  18%|█████▏                       | 16992/94563 [02:47<13:05, 98.78it/s]

[train] Checkpoint saved at 17000/94563

train:  18%|█████▏                       | 17024/94563 [02:48<13:13, 97.68it/s]

train:  18%|█████▏                       | 17056/94563 [02:48<13:11, 97.95it/s]

train:  18%|█████▏                       | 17088/94563 [02:48<13:11, 97.93it/s]

train:  18%|█████▎                       | 17120/94563 [02:49<13:10, 98.00it/s]

train:  18%|█████▎                       | 17152/94563 [02:49<13:04, 98.64it/s]

train:  18%|█████▎                       | 17184/94563 [02:49<12:59, 99.25it/s]

train:  18%|█████▎                       | 17216/94563 [02:50<12:54, 99.81it/s]

train:  18%|█████                       | 17248/94563 [02:50<12:49, 100.43it/s]

train:  18%|█████                       | 17280/94563 [02:50<12:47, 100.68it/s]

train:  18%|█████▏                      | 17312/94563 [02:51<12:44, 101.05it/s]

train:  18%|█████▏                      | 17344/94563 [02:51<12:42, 101.22it/s]

train:  18%|█████▏                      | 17376/94563 [02:51<12:42, 101.25it/s]

train:  18%|█████▏                      | 17408/94563 [02:52<12:41, 101.38it/s]

train:  18%|█████▏                      | 17440/94563 [02:52<12:40, 101.46it/s]

train:  18%|█████▏                      | 17472/94563 [02:52<12:43, 100.95it/s]

train:  19%|█████▏                      | 17504/94563 [02:53<12:45, 100.62it/s]

train:  19%|█████▏                      | 17536/94563 [02:53<12:45, 100.62it/s]

train:  19%|█████▏                      | 17568/94563 [02:53<12:46, 100.44it/s]

train:  19%|█████▏                      | 17600/94563 [02:53<12:45, 100.52it/s]

train:  19%|█████▏                      | 17632/94563 [02:54<12:47, 100.26it/s]

train:  19%|█████▏                      | 17664/94563 [02:54<12:47, 100.22it/s]

train:  19%|█████▏                      | 17696/94563 [02:54<12:47, 100.18it/s]

train:  19%|█████▏                      | 17728/94563 [02:55<12:47, 100.08it/s]

train:  19%|█████▎                      | 17760/94563 [02:55<12:47, 100.06it/s]

train:  19%|█████▎                      | 17792/94563 [02:55<12:47, 100.08it/s]

train:  19%|█████▎                      | 17824/94563 [02:56<12:47, 100.05it/s]

train:  19%|█████▍                       | 17856/94563 [02:56<12:47, 99.90it/s]

train:  19%|█████▍                       | 17888/94563 [02:56<12:47, 99.92it/s]

train:  19%|█████▎                      | 17920/94563 [02:57<12:45, 100.10it/s]

train:  19%|█████▎                      | 17952/94563 [02:57<12:46, 100.00it/s]

train:  19%|█████▌                       | 17984/94563 [02:57<12:46, 99.86it/s]

[train] Checkpoint saved at 18000/94563

train:  19%|█████▌                       | 18016/94563 [02:58<12:55, 98.72it/s]

train:  19%|█████▌                       | 18048/94563 [02:58<12:52, 99.04it/s]

train:  19%|█████▌                       | 18080/94563 [02:58<12:51, 99.10it/s]

train:  19%|█████▌                       | 18112/94563 [02:59<12:50, 99.28it/s]

train:  19%|█████▌                       | 18144/94563 [02:59<12:48, 99.47it/s]

train:  19%|█████▌                       | 18176/94563 [02:59<12:47, 99.55it/s]

train:  19%|█████▌                       | 18208/94563 [03:00<12:47, 99.54it/s]

train:  19%|█████▌                       | 18240/94563 [03:00<12:48, 99.36it/s]

train:  19%|█████▌                       | 18272/94563 [03:00<12:49, 99.17it/s]

train:  19%|█████▌                       | 18304/94563 [03:01<12:48, 99.23it/s]

train:  19%|█████▌                       | 18336/94563 [03:01<12:48, 99.24it/s]

train:  19%|█████▋                       | 18368/94563 [03:01<12:44, 99.62it/s]

train:  19%|█████▍                      | 18400/94563 [03:01<12:40, 100.13it/s]

train:  19%|█████▍                      | 18432/94563 [03:02<12:38, 100.32it/s]

train:  20%|█████▍                      | 18464/94563 [03:02<12:36, 100.61it/s]

train:  20%|█████▍                      | 18496/94563 [03:02<12:34, 100.86it/s]

train:  20%|█████▍                      | 18528/94563 [03:03<12:32, 101.10it/s]

train:  20%|█████▍                      | 18560/94563 [03:03<12:30, 101.33it/s]

train:  20%|█████▌                      | 18592/94563 [03:03<12:29, 101.39it/s]

train:  20%|█████▌                      | 18624/94563 [03:04<12:28, 101.50it/s]

train:  20%|█████▌                      | 18656/94563 [03:04<12:27, 101.48it/s]

train:  20%|█████▌                      | 18688/94563 [03:04<12:30, 101.15it/s]

train:  20%|█████▌                      | 18720/94563 [03:05<12:29, 101.18it/s]

train:  20%|█████▌                      | 18752/94563 [03:05<12:30, 101.02it/s]

train:  20%|█████▌                      | 18784/94563 [03:05<12:31, 100.77it/s]

train:  20%|█████▌                      | 18816/94563 [03:06<12:31, 100.78it/s]

train:  20%|█████▌                      | 18848/94563 [03:06<12:32, 100.68it/s]

train:  20%|█████▌                      | 18880/94563 [03:06<12:34, 100.33it/s]

train:  20%|█████▌                      | 18912/94563 [03:07<12:34, 100.22it/s]

train:  20%|█████▌                      | 18944/94563 [03:07<12:36, 100.00it/s]

train:  20%|█████▌                      | 18976/94563 [03:07<12:35, 100.05it/s]

[train] Checkpoint saved at 19000/94563

train:  20%|█████▊                       | 19008/94563 [03:08<12:45, 98.74it/s]

train:  20%|█████▊                       | 19040/94563 [03:08<12:41, 99.19it/s]

train:  20%|█████▊                       | 19072/94563 [03:08<12:41, 99.15it/s]

train:  20%|█████▊                       | 19104/94563 [03:09<12:39, 99.35it/s]

train:  20%|█████▊                       | 19136/94563 [03:09<12:37, 99.57it/s]

train:  20%|█████▉                       | 19168/94563 [03:09<12:37, 99.59it/s]

train:  20%|█████▉                       | 19200/94563 [03:09<12:35, 99.81it/s]

train:  20%|█████▋                      | 19232/94563 [03:10<12:32, 100.07it/s]

train:  20%|█████▋                      | 19264/94563 [03:10<12:31, 100.17it/s]

train:  20%|█████▋                      | 19296/94563 [03:10<12:31, 100.12it/s]

train:  20%|█████▋                      | 19328/94563 [03:11<12:30, 100.19it/s]

train:  20%|█████▋                      | 19360/94563 [03:11<12:30, 100.21it/s]

train:  21%|█████▋                      | 19392/94563 [03:11<12:29, 100.28it/s]

train:  21%|█████▊                      | 19424/94563 [03:12<12:27, 100.55it/s]

train:  21%|█████▊                      | 19456/94563 [03:12<12:26, 100.66it/s]

train:  21%|█████▉                       | 19488/94563 [03:12<12:41, 98.61it/s]

train:  21%|█████▉                       | 19520/94563 [03:13<12:38, 98.90it/s]

train:  21%|█████▉                       | 19552/94563 [03:13<12:36, 99.14it/s]

train:  21%|██████                       | 19584/94563 [03:13<12:34, 99.33it/s]

train:  21%|██████                       | 19616/94563 [03:14<12:32, 99.62it/s]

train:  21%|██████                       | 19648/94563 [03:14<12:30, 99.77it/s]

train:  21%|██████                       | 19680/94563 [03:14<12:30, 99.81it/s]

train:  21%|██████                       | 19712/94563 [03:15<12:29, 99.87it/s]

train:  21%|██████                       | 19744/94563 [03:15<12:28, 99.91it/s]

train:  21%|█████▊                      | 19776/94563 [03:15<12:27, 100.11it/s]

train:  21%|█████▊                      | 19808/94563 [03:16<12:25, 100.23it/s]

train:  21%|█████▊                      | 19840/94563 [03:16<12:24, 100.37it/s]

train:  21%|█████▉                      | 19872/94563 [03:16<12:24, 100.37it/s]

train:  21%|█████▉                      | 19904/94563 [03:17<12:23, 100.43it/s]

train:  21%|█████▉                      | 19936/94563 [03:17<12:22, 100.47it/s]

train:  21%|█████▉                      | 19968/94563 [03:17<12:23, 100.28it/s]

train:  21%|██████▏                      | 20000/94563 [03:17<12:31, 99.28it/s]

[train] Checkpoint saved at 20000/94563

train:  21%|██████▏                      | 20032/94563 [03:18<12:27, 99.74it/s]

train:  21%|██████▏                      | 20064/94563 [03:18<12:25, 99.94it/s]

train:  21%|█████▉                      | 20096/94563 [03:18<12:23, 100.21it/s]

train:  21%|█████▉                      | 20128/94563 [03:19<12:21, 100.35it/s]

train:  21%|█████▉                      | 20160/94563 [03:19<12:20, 100.49it/s]

train:  21%|█████▉                      | 20192/94563 [03:19<12:19, 100.54it/s]

train:  21%|█████▉                      | 20224/94563 [03:20<12:18, 100.71it/s]

train:  21%|█████▉                      | 20256/94563 [03:20<12:16, 100.86it/s]

train:  21%|██████                      | 20288/94563 [03:20<12:15, 101.01it/s]

train:  21%|██████                      | 20320/94563 [03:21<12:15, 100.94it/s]

train:  22%|██████                      | 20352/94563 [03:21<12:15, 100.92it/s]

train:  22%|██████                      | 20384/94563 [03:21<12:14, 101.04it/s]

train:  22%|██████                      | 20416/94563 [03:22<12:13, 101.12it/s]

train:  22%|██████                      | 20448/94563 [03:22<12:13, 100.98it/s]

train:  22%|██████                      | 20480/94563 [03:22<12:13, 100.95it/s]

train:  22%|██████                      | 20512/94563 [03:23<12:13, 100.98it/s]

train:  22%|██████                      | 20544/94563 [03:23<12:13, 100.91it/s]

train:  22%|██████                      | 20576/94563 [03:23<12:12, 100.95it/s]

train:  22%|██████                      | 20608/94563 [03:23<12:13, 100.86it/s]

train:  22%|██████                      | 20640/94563 [03:24<12:12, 100.96it/s]

train:  22%|██████                      | 20672/94563 [03:24<12:11, 101.01it/s]

train:  22%|██████▏                     | 20704/94563 [03:24<12:11, 100.94it/s]

train:  22%|██████▏                     | 20736/94563 [03:25<12:10, 101.01it/s]

train:  22%|██████▏                     | 20768/94563 [03:25<12:10, 100.98it/s]

train:  22%|██████▏                     | 20800/94563 [03:25<12:10, 100.94it/s]

train:  22%|██████▏                     | 20832/94563 [03:26<12:10, 100.92it/s]

train:  22%|██████▏                     | 20864/94563 [03:26<12:12, 100.63it/s]

train:  22%|██████▏                     | 20896/94563 [03:26<12:12, 100.52it/s]

train:  22%|██████▏                     | 20928/94563 [03:27<12:13, 100.41it/s]

train:  22%|██████▏                     | 20960/94563 [03:27<12:12, 100.45it/s]

train:  22%|██████▏                     | 20992/94563 [03:27<12:11, 100.57it/s]

[train] Checkpoint saved at 21000/94563

train:  22%|██████▍                      | 21024/94563 [03:28<12:18, 99.54it/s]

train:  22%|██████▍                      | 21056/94563 [03:28<12:16, 99.83it/s]

train:  22%|██████▏                     | 21088/94563 [03:28<12:13, 100.10it/s]

train:  22%|██████▎                     | 21120/94563 [03:29<12:12, 100.20it/s]

train:  22%|██████▎                     | 21152/94563 [03:29<12:12, 100.16it/s]

train:  22%|██████▎                     | 21184/94563 [03:29<12:11, 100.26it/s]

train:  22%|██████▎                     | 21216/94563 [03:30<12:11, 100.27it/s]

train:  22%|██████▎                     | 21248/94563 [03:30<12:10, 100.32it/s]

train:  23%|██████▎                     | 21280/94563 [03:30<12:10, 100.36it/s]

train:  23%|██████▎                     | 21312/94563 [03:31<12:11, 100.15it/s]

train:  23%|██████▎                     | 21344/94563 [03:31<12:10, 100.25it/s]

train:  23%|██████▎                     | 21376/94563 [03:31<12:08, 100.47it/s]

train:  23%|██████▎                     | 21408/94563 [03:31<12:07, 100.53it/s]

train:  23%|██████▎                     | 21440/94563 [03:32<12:06, 100.70it/s]

train:  23%|██████▎                     | 21472/94563 [03:32<12:04, 100.87it/s]

train:  23%|██████▎                     | 21504/94563 [03:32<12:03, 100.99it/s]

train:  23%|██████▍                     | 21536/94563 [03:33<12:04, 100.84it/s]

train:  23%|██████▍                     | 21568/94563 [03:33<12:03, 100.83it/s]

train:  23%|██████▍                     | 21600/94563 [03:33<12:02, 101.01it/s]

train:  23%|██████▍                     | 21632/94563 [03:34<12:00, 101.27it/s]

train:  23%|██████▍                     | 21664/94563 [03:34<12:01, 100.97it/s]

train:  23%|██████▍                     | 21696/94563 [03:34<12:00, 101.19it/s]

train:  23%|██████▍                     | 21728/94563 [03:35<12:00, 101.09it/s]

train:  23%|██████▍                     | 21760/94563 [03:35<12:02, 100.74it/s]

train:  23%|██████▍                     | 21792/94563 [03:35<12:02, 100.73it/s]

train:  23%|██████▍                     | 21824/94563 [03:36<12:06, 100.08it/s]

train:  23%|██████▍                     | 21856/94563 [03:36<12:06, 100.15it/s]

train:  23%|██████▋                      | 21888/94563 [03:36<12:07, 99.90it/s]

train:  23%|██████▋                      | 21920/94563 [03:37<12:09, 99.61it/s]

train:  23%|██████▋                      | 21952/94563 [03:37<12:08, 99.65it/s]

train:  23%|██████▋                      | 21984/94563 [03:37<12:08, 99.67it/s]

[train] Checkpoint saved at 22000/94563

train:  23%|██████▊                      | 22016/94563 [03:38<12:15, 98.67it/s]

train:  23%|██████▊                      | 22048/94563 [03:38<12:11, 99.17it/s]

train:  23%|██████▊                      | 22080/94563 [03:38<12:07, 99.69it/s]

train:  23%|██████▌                     | 22112/94563 [03:38<12:03, 100.17it/s]

train:  23%|██████▌                     | 22144/94563 [03:39<12:00, 100.53it/s]

train:  23%|██████▌                     | 22176/94563 [03:39<11:58, 100.70it/s]

train:  23%|██████▌                     | 22208/94563 [03:39<11:58, 100.74it/s]

train:  24%|██████▌                     | 22240/94563 [03:40<11:56, 100.95it/s]

train:  24%|██████▌                     | 22272/94563 [03:40<11:56, 100.83it/s]

train:  24%|██████▌                     | 22304/94563 [03:40<11:54, 101.08it/s]

train:  24%|██████▌                     | 22336/94563 [03:41<11:54, 101.15it/s]

train:  24%|██████▌                     | 22368/94563 [03:41<11:54, 101.09it/s]

train:  24%|██████▋                     | 22400/94563 [03:41<11:54, 101.00it/s]

train:  24%|██████▋                     | 22432/94563 [03:42<11:54, 100.93it/s]

train:  24%|██████▋                     | 22464/94563 [03:42<11:53, 100.98it/s]

train:  24%|██████▋                     | 22496/94563 [03:42<11:53, 100.97it/s]

train:  24%|██████▋                     | 22528/94563 [03:43<11:52, 101.10it/s]

train:  24%|██████▋                     | 22560/94563 [03:43<11:52, 101.07it/s]

train:  24%|██████▋                     | 22592/94563 [03:43<11:53, 100.92it/s]

train:  24%|██████▋                     | 22624/94563 [03:44<11:53, 100.89it/s]

train:  24%|██████▋                     | 22656/94563 [03:44<11:51, 101.03it/s]

train:  24%|██████▋                     | 22688/94563 [03:44<11:51, 101.08it/s]

train:  24%|██████▋                     | 22720/94563 [03:44<11:49, 101.19it/s]

train:  24%|██████▋                     | 22752/94563 [03:45<11:50, 101.04it/s]

train:  24%|██████▋                     | 22784/94563 [03:45<11:50, 101.05it/s]

train:  24%|██████▊                     | 22816/94563 [03:45<11:51, 100.87it/s]

train:  24%|██████▊                     | 22848/94563 [03:46<11:49, 101.01it/s]

train:  24%|██████▊                     | 22880/94563 [03:46<11:50, 100.87it/s]

train:  24%|██████▊                     | 22912/94563 [03:46<11:50, 100.78it/s]

train:  24%|██████▊                     | 22944/94563 [03:47<11:51, 100.68it/s]

train:  24%|██████▊                     | 22976/94563 [03:47<11:51, 100.56it/s]

[train] Checkpoint saved at 23000/94563

train:  24%|███████                      | 23008/94563 [03:47<12:03, 98.88it/s]

train:  24%|███████                      | 23040/94563 [03:48<12:00, 99.27it/s]

train:  24%|███████                      | 23072/94563 [03:48<11:56, 99.76it/s]

train:  24%|██████▊                     | 23104/94563 [03:48<11:54, 100.05it/s]

train:  24%|██████▊                     | 23136/94563 [03:49<11:52, 100.19it/s]

train:  25%|██████▊                     | 23168/94563 [03:49<11:51, 100.39it/s]

train:  25%|██████▊                     | 23200/94563 [03:49<11:49, 100.60it/s]

train:  25%|██████▉                     | 23232/94563 [03:50<11:47, 100.76it/s]

train:  25%|██████▉                     | 23264/94563 [03:50<11:47, 100.83it/s]

train:  25%|██████▉                     | 23296/94563 [03:50<11:47, 100.74it/s]

train:  25%|██████▉                     | 23328/94563 [03:51<11:48, 100.59it/s]

train:  25%|██████▉                     | 23360/94563 [03:51<11:48, 100.54it/s]

train:  25%|██████▉                     | 23392/94563 [03:51<11:50, 100.14it/s]

train:  25%|██████▉                     | 23424/94563 [03:52<11:51, 100.05it/s]

train:  25%|██████▉                     | 23456/94563 [03:52<11:49, 100.19it/s]

train:  25%|██████▉                     | 23488/94563 [03:52<11:48, 100.31it/s]

train:  25%|██████▉                     | 23520/94563 [03:52<11:45, 100.65it/s]

train:  25%|██████▉                     | 23552/94563 [03:53<11:45, 100.64it/s]

train:  25%|██████▉                     | 23584/94563 [03:53<11:45, 100.59it/s]

train:  25%|██████▉                     | 23616/94563 [03:53<11:46, 100.47it/s]

train:  25%|███████                     | 23648/94563 [03:54<11:47, 100.29it/s]

train:  25%|███████                     | 23680/94563 [03:54<11:45, 100.43it/s]

train:  25%|███████                     | 23712/94563 [03:54<11:44, 100.58it/s]

train:  25%|███████                     | 23744/94563 [03:55<11:43, 100.70it/s]

train:  25%|███████                     | 23776/94563 [03:55<11:43, 100.65it/s]

train:  25%|███████                     | 23808/94563 [03:55<11:40, 101.03it/s]

train:  25%|███████                     | 23840/94563 [03:56<11:38, 101.26it/s]

train:  25%|███████                     | 23872/94563 [03:56<11:36, 101.55it/s]

train:  25%|███████                     | 23904/94563 [03:56<11:37, 101.35it/s]

train:  25%|███████                     | 23936/94563 [03:57<11:37, 101.19it/s]

train:  25%|███████                     | 23968/94563 [03:57<11:36, 101.30it/s]

train:  25%|███████▎                     | 24000/94563 [03:57<11:47, 99.75it/s]

[train] Checkpoint saved at 24000/94563

train:  25%|███████▎                     | 24032/94563 [03:58<11:46, 99.89it/s]

train:  25%|███████▏                    | 24064/94563 [03:58<11:42, 100.42it/s]

train:  25%|███████▏                    | 24096/94563 [03:58<11:39, 100.74it/s]

train:  26%|███████▏                    | 24128/94563 [03:58<11:37, 100.98it/s]

train:  26%|███████▏                    | 24160/94563 [03:59<11:35, 101.19it/s]

train:  26%|███████▏                    | 24192/94563 [03:59<11:33, 101.44it/s]

train:  26%|███████▏                    | 24224/94563 [03:59<11:32, 101.53it/s]

train:  26%|███████▏                    | 24256/94563 [04:00<11:30, 101.76it/s]

train:  26%|███████▏                    | 24288/94563 [04:00<11:29, 101.87it/s]

train:  26%|███████▏                    | 24320/94563 [04:00<11:29, 101.81it/s]

train:  26%|███████▏                    | 24352/94563 [04:01<11:28, 101.91it/s]

train:  26%|███████▏                    | 24384/94563 [04:01<11:28, 101.89it/s]

train:  26%|███████▏                    | 24416/94563 [04:01<11:28, 101.88it/s]

train:  26%|███████▏                    | 24448/94563 [04:02<11:27, 101.92it/s]

train:  26%|███████▏                    | 24480/94563 [04:02<11:28, 101.86it/s]

train:  26%|███████▎                    | 24512/94563 [04:02<11:28, 101.72it/s]

train:  26%|███████▎                    | 24544/94563 [04:03<11:28, 101.70it/s]

train:  26%|███████▎                    | 24576/94563 [04:03<11:28, 101.63it/s]

train:  26%|███████▎                    | 24608/94563 [04:03<11:27, 101.75it/s]

train:  26%|███████▎                    | 24640/94563 [04:04<11:26, 101.81it/s]

train:  26%|███████▎                    | 24672/94563 [04:04<11:26, 101.76it/s]

train:  26%|███████▎                    | 24704/94563 [04:04<11:25, 101.88it/s]

train:  26%|███████▎                    | 24736/94563 [04:04<11:27, 101.60it/s]

train:  26%|███████▎                    | 24768/94563 [04:05<11:26, 101.64it/s]

train:  26%|███████▎                    | 24800/94563 [04:05<11:26, 101.67it/s]

train:  26%|███████▎                    | 24832/94563 [04:05<11:26, 101.54it/s]

train:  26%|███████▎                    | 24864/94563 [04:06<11:27, 101.44it/s]

train:  26%|███████▎                    | 24896/94563 [04:06<11:27, 101.26it/s]

train:  26%|███████▍                    | 24928/94563 [04:06<11:28, 101.14it/s]

train:  26%|███████▍                    | 24960/94563 [04:07<11:27, 101.22it/s]

train:  26%|███████▍                    | 24992/94563 [04:07<11:27, 101.16it/s]

[train] Checkpoint saved at 25000/94563

train:  26%|███████▋                     | 25024/94563 [04:07<11:48, 98.12it/s]

train:  26%|███████▋                     | 25056/94563 [04:08<11:39, 99.31it/s]

train:  27%|███████▍                    | 25088/94563 [04:08<11:34, 100.06it/s]

train:  27%|███████▍                    | 25120/94563 [04:08<11:31, 100.42it/s]

train:  27%|███████▍                    | 25152/94563 [04:09<11:30, 100.47it/s]

train:  27%|███████▍                    | 25184/94563 [04:09<11:28, 100.75it/s]

train:  27%|███████▍                    | 25216/94563 [04:09<11:28, 100.66it/s]

train:  27%|███████▍                    | 25248/94563 [04:10<11:26, 100.92it/s]

train:  27%|███████▍                    | 25280/94563 [04:10<11:26, 100.91it/s]

train:  27%|███████▍                    | 25312/94563 [04:10<11:24, 101.11it/s]

train:  27%|███████▌                    | 25344/94563 [04:11<11:22, 101.40it/s]

train:  27%|███████▌                    | 25376/94563 [04:11<11:22, 101.33it/s]

train:  27%|███████▌                    | 25408/94563 [04:11<11:22, 101.36it/s]

train:  27%|███████▌                    | 25440/94563 [04:11<11:20, 101.53it/s]

train:  27%|███████▌                    | 25472/94563 [04:12<11:20, 101.59it/s]

train:  27%|███████▌                    | 25504/94563 [04:12<11:18, 101.82it/s]

train:  27%|███████▌                    | 25536/94563 [04:12<11:17, 101.91it/s]

train:  27%|███████▌                    | 25568/94563 [04:13<11:16, 101.97it/s]

train:  27%|███████▌                    | 25600/94563 [04:13<11:15, 102.04it/s]

train:  27%|███████▌                    | 25632/94563 [04:13<11:16, 101.83it/s]

train:  27%|███████▌                    | 25664/94563 [04:14<11:17, 101.65it/s]

train:  27%|███████▌                    | 25696/94563 [04:14<11:18, 101.55it/s]

train:  27%|███████▌                    | 25728/94563 [04:14<11:17, 101.67it/s]

train:  27%|███████▋                    | 25760/94563 [04:15<11:16, 101.76it/s]

train:  27%|███████▋                    | 25792/94563 [04:15<11:14, 101.90it/s]

train:  27%|███████▋                    | 25824/94563 [04:15<11:14, 101.86it/s]

train:  27%|███████▋                    | 25856/94563 [04:16<11:13, 102.09it/s]

train:  27%|███████▋                    | 25888/94563 [04:16<11:12, 102.05it/s]

train:  27%|███████▋                    | 25920/94563 [04:16<11:10, 102.33it/s]

train:  27%|███████▋                    | 25952/94563 [04:16<11:13, 101.84it/s]

train:  27%|███████▋                    | 25984/94563 [04:17<11:14, 101.69it/s]

[train] Checkpoint saved at 26000/94563

train:  28%|███████▉                     | 26016/94563 [04:17<11:25, 99.97it/s]

train:  28%|███████▋                    | 26048/94563 [04:17<11:21, 100.55it/s]

train:  28%|███████▋                    | 26080/94563 [04:18<11:18, 100.99it/s]

train:  28%|███████▋                    | 26112/94563 [04:18<11:17, 101.02it/s]

train:  28%|███████▋                    | 26144/94563 [04:18<11:17, 100.93it/s]

train:  28%|███████▊                    | 26176/94563 [04:19<11:16, 101.08it/s]

train:  28%|███████▊                    | 26208/94563 [04:19<11:16, 100.99it/s]

train:  28%|███████▊                    | 26240/94563 [04:19<11:17, 100.92it/s]

train:  28%|███████▊                    | 26272/94563 [04:20<11:17, 100.78it/s]

train:  28%|███████▊                    | 26304/94563 [04:20<11:17, 100.77it/s]

train:  28%|███████▊                    | 26336/94563 [04:20<11:16, 100.87it/s]

train:  28%|███████▊                    | 26368/94563 [04:21<11:16, 100.83it/s]

train:  28%|███████▊                    | 26400/94563 [04:21<11:15, 100.88it/s]

train:  28%|███████▊                    | 26432/94563 [04:21<11:14, 101.00it/s]

train:  28%|███████▊                    | 26464/94563 [04:22<11:12, 101.28it/s]

train:  28%|███████▊                    | 26496/94563 [04:22<11:15, 100.84it/s]

train:  28%|███████▊                    | 26528/94563 [04:22<11:13, 101.07it/s]

train:  28%|███████▊                    | 26560/94563 [04:22<11:10, 101.42it/s]

train:  28%|███████▊                    | 26592/94563 [04:23<11:07, 101.77it/s]

train:  28%|███████▉                    | 26624/94563 [04:23<11:05, 102.04it/s]

train:  28%|███████▉                    | 26656/94563 [04:23<11:05, 102.05it/s]

train:  28%|███████▉                    | 26688/94563 [04:24<11:04, 102.22it/s]

train:  28%|███████▉                    | 26720/94563 [04:24<11:03, 102.32it/s]

train:  28%|███████▉                    | 26752/94563 [04:24<11:03, 102.17it/s]

train:  28%|███████▉                    | 26784/94563 [04:25<11:02, 102.27it/s]

train:  28%|███████▉                    | 26816/94563 [04:25<11:02, 102.32it/s]

train:  28%|███████▉                    | 26848/94563 [04:25<11:01, 102.36it/s]

train:  28%|███████▉                    | 26880/94563 [04:26<11:01, 102.39it/s]

train:  28%|███████▉                    | 26912/94563 [04:26<11:00, 102.42it/s]

train:  28%|███████▉                    | 26944/94563 [04:26<11:00, 102.33it/s]

train:  29%|███████▉                    | 26976/94563 [04:27<11:01, 102.15it/s]

[train] Checkpoint saved at 27000/94563

train:  29%|███████▉                    | 27008/94563 [04:27<11:11, 100.58it/s]

train:  29%|████████                    | 27040/94563 [04:27<11:07, 101.12it/s]

train:  29%|████████                    | 27072/94563 [04:28<11:05, 101.39it/s]

train:  29%|████████                    | 27104/94563 [04:28<11:04, 101.56it/s]

train:  29%|████████                    | 27136/94563 [04:28<11:04, 101.50it/s]

train:  29%|████████                    | 27168/94563 [04:28<11:02, 101.73it/s]

train:  29%|████████                    | 27200/94563 [04:29<11:01, 101.78it/s]

train:  29%|████████                    | 27232/94563 [04:29<11:02, 101.69it/s]

train:  29%|████████                    | 27264/94563 [04:29<11:01, 101.80it/s]

train:  29%|████████                    | 27296/94563 [04:30<11:00, 101.78it/s]

train:  29%|████████                    | 27328/94563 [04:30<11:00, 101.76it/s]

train:  29%|████████                    | 27360/94563 [04:30<10:59, 101.85it/s]

train:  29%|████████                    | 27392/94563 [04:31<11:04, 101.12it/s]

train:  29%|████████                    | 27424/94563 [04:31<11:02, 101.35it/s]

train:  29%|████████▏                   | 27456/94563 [04:31<11:01, 101.49it/s]

train:  29%|████████▏                   | 27488/94563 [04:32<11:01, 101.34it/s]

train:  29%|████████▏                   | 27520/94563 [04:32<11:02, 101.16it/s]

train:  29%|████████▏                   | 27552/94563 [04:32<11:02, 101.09it/s]

train:  29%|████████▏                   | 27584/94563 [04:33<11:03, 101.01it/s]

train:  29%|████████▏                   | 27616/94563 [04:33<11:03, 100.89it/s]

train:  29%|████████▏                   | 27648/94563 [04:33<11:02, 100.93it/s]

train:  29%|████████▏                   | 27680/94563 [04:34<11:01, 101.14it/s]

train:  29%|████████▏                   | 27712/94563 [04:34<10:59, 101.35it/s]

train:  29%|████████▏                   | 27744/94563 [04:34<10:58, 101.44it/s]

train:  29%|████████▏                   | 27776/94563 [04:34<10:57, 101.62it/s]

train:  29%|████████▏                   | 27808/94563 [04:35<10:56, 101.71it/s]

train:  29%|████████▏                   | 27840/94563 [04:35<10:54, 101.98it/s]

train:  29%|████████▎                   | 27872/94563 [04:35<10:54, 101.94it/s]

train:  30%|████████▎                   | 27904/94563 [04:36<10:52, 102.12it/s]

train:  30%|████████▎                   | 27936/94563 [04:36<10:52, 102.13it/s]

train:  30%|████████▎                   | 27968/94563 [04:36<10:51, 102.16it/s]

train:  30%|████████▌                    | 28000/94563 [04:37<11:18, 98.12it/s]

[train] Checkpoint saved at 28000/94563

train:  30%|████████▌                    | 28032/94563 [04:37<11:16, 98.29it/s]

train:  30%|████████▌                    | 28064/94563 [04:37<11:06, 99.73it/s]

train:  30%|████████▎                   | 28096/94563 [04:38<11:00, 100.65it/s]

train:  30%|████████▎                   | 28128/94563 [04:38<10:55, 101.37it/s]

train:  30%|████████▎                   | 28160/94563 [04:38<10:53, 101.68it/s]

train:  30%|████████▎                   | 28192/94563 [04:39<10:50, 102.10it/s]

train:  30%|████████▎                   | 28224/94563 [04:39<10:49, 102.18it/s]

train:  30%|████████▎                   | 28256/94563 [04:39<10:47, 102.39it/s]

train:  30%|████████▍                   | 28288/94563 [04:40<10:46, 102.57it/s]

train:  30%|████████▍                   | 28320/94563 [04:40<10:44, 102.73it/s]

train:  30%|████████▍                   | 28352/94563 [04:40<10:45, 102.63it/s]

train:  30%|████████▍                   | 28384/94563 [04:40<10:44, 102.68it/s]

train:  30%|████████▍                   | 28416/94563 [04:41<10:45, 102.52it/s]

train:  30%|████████▍                   | 28448/94563 [04:41<10:45, 102.46it/s]

train:  30%|████████▍                   | 28480/94563 [04:41<10:46, 102.18it/s]

train:  30%|████████▍                   | 28512/94563 [04:42<10:46, 102.09it/s]

train:  30%|████████▍                   | 28544/94563 [04:42<10:46, 102.18it/s]

train:  30%|████████▍                   | 28576/94563 [04:42<10:46, 102.00it/s]

train:  30%|████████▍                   | 28608/94563 [04:43<10:47, 101.90it/s]

train:  30%|████████▍                   | 28640/94563 [04:43<10:45, 102.10it/s]

train:  30%|████████▍                   | 28672/94563 [04:43<10:45, 102.04it/s]

train:  30%|████████▍                   | 28704/94563 [04:44<10:45, 101.95it/s]

train:  30%|████████▌                   | 28736/94563 [04:44<10:44, 102.07it/s]

train:  30%|████████▌                   | 28768/94563 [04:44<10:44, 102.13it/s]

train:  30%|████████▌                   | 28800/94563 [04:45<10:42, 102.33it/s]

train:  30%|████████▌                   | 28832/94563 [04:45<10:43, 102.13it/s]

train:  31%|████████▌                   | 28864/94563 [04:45<10:43, 102.14it/s]

train:  31%|████████▌                   | 28896/94563 [04:45<10:42, 102.22it/s]

train:  31%|████████▌                   | 28928/94563 [04:46<10:40, 102.42it/s]

train:  31%|████████▌                   | 28960/94563 [04:46<10:40, 102.38it/s]

train:  31%|████████▌                   | 28992/94563 [04:46<10:40, 102.32it/s]

[train] Checkpoint saved at 29000/94563

train:  31%|████████▌                   | 29024/94563 [04:47<10:50, 100.68it/s]

train:  31%|████████▌                   | 29056/94563 [04:47<10:47, 101.23it/s]

train:  31%|████████▉                    | 29088/94563 [04:47<10:56, 99.72it/s]

train:  31%|████████▌                   | 29120/94563 [04:48<10:52, 100.34it/s]

train:  31%|████████▋                   | 29152/94563 [04:48<10:50, 100.53it/s]

train:  31%|████████▋                   | 29184/94563 [04:48<10:48, 100.87it/s]

train:  31%|████████▋                   | 29216/94563 [04:49<10:44, 101.40it/s]

train:  31%|████████▋                   | 29248/94563 [04:49<10:44, 101.36it/s]

train:  31%|████████▋                   | 29280/94563 [04:49<10:41, 101.73it/s]

train:  31%|████████▋                   | 29312/94563 [04:50<10:42, 101.63it/s]

train:  31%|████████▋                   | 29344/94563 [04:50<10:42, 101.57it/s]

train:  31%|████████▋                   | 29376/94563 [04:50<10:42, 101.51it/s]

train:  31%|████████▋                   | 29408/94563 [04:51<10:42, 101.46it/s]

train:  31%|████████▋                   | 29440/94563 [04:51<10:43, 101.27it/s]

train:  31%|████████▋                   | 29472/94563 [04:51<10:44, 101.01it/s]

train:  31%|████████▋                   | 29504/94563 [04:51<10:44, 101.01it/s]

train:  31%|████████▋                   | 29536/94563 [04:52<10:44, 100.83it/s]

train:  31%|████████▊                   | 29568/94563 [04:52<10:44, 100.84it/s]

train:  31%|████████▊                   | 29600/94563 [04:52<10:44, 100.86it/s]

train:  31%|████████▊                   | 29632/94563 [04:53<10:43, 100.97it/s]

train:  31%|████████▊                   | 29664/94563 [04:53<10:41, 101.13it/s]

train:  31%|████████▊                   | 29696/94563 [04:53<10:44, 100.57it/s]

train:  31%|████████▊                   | 29728/94563 [04:54<10:41, 101.09it/s]

train:  31%|████████▊                   | 29760/94563 [04:54<10:39, 101.36it/s]

train:  32%|████████▊                   | 29792/94563 [04:54<10:38, 101.51it/s]

train:  32%|████████▊                   | 29824/94563 [04:55<10:35, 101.84it/s]

train:  32%|████████▊                   | 29856/94563 [04:55<10:34, 102.04it/s]

train:  32%|████████▊                   | 29888/94563 [04:55<10:32, 102.32it/s]

train:  32%|████████▊                   | 29920/94563 [04:56<10:30, 102.52it/s]

train:  32%|████████▊                   | 29952/94563 [04:56<10:30, 102.54it/s]

train:  32%|████████▉                   | 29984/94563 [04:56<10:28, 102.68it/s]

[train] Checkpoint saved at 30000/94563

train:  32%|████████▉                   | 30016/94563 [04:57<10:38, 101.04it/s]

train:  32%|████████▉                   | 30048/94563 [04:57<10:34, 101.73it/s]

train:  32%|████████▉                   | 30080/94563 [04:57<10:31, 102.04it/s]

train:  32%|████████▉                   | 30112/94563 [04:57<10:29, 102.32it/s]

train:  32%|████████▉                   | 30144/94563 [04:58<10:27, 102.61it/s]

train:  32%|████████▉                   | 30176/94563 [04:58<10:26, 102.77it/s]

train:  32%|████████▉                   | 30208/94563 [04:58<10:25, 102.81it/s]

train:  32%|████████▉                   | 30240/94563 [04:59<10:25, 102.85it/s]

train:  32%|████████▉                   | 30272/94563 [04:59<10:26, 102.63it/s]

train:  32%|████████▉                   | 30304/94563 [04:59<10:25, 102.72it/s]

train:  32%|████████▉                   | 30336/94563 [05:00<10:25, 102.62it/s]

train:  32%|████████▉                   | 30368/94563 [05:00<10:24, 102.75it/s]

train:  32%|█████████                   | 30400/94563 [05:00<10:24, 102.72it/s]

train:  32%|█████████                   | 30432/94563 [05:01<10:24, 102.67it/s]

train:  32%|█████████                   | 30464/94563 [05:01<10:25, 102.41it/s]

train:  32%|█████████                   | 30496/94563 [05:01<10:26, 102.24it/s]

train:  32%|█████████                   | 30528/94563 [05:01<10:26, 102.26it/s]

train:  32%|█████████                   | 30560/94563 [05:02<10:25, 102.30it/s]

train:  32%|█████████                   | 30592/94563 [05:02<10:26, 102.04it/s]

train:  32%|█████████                   | 30624/94563 [05:02<10:26, 102.04it/s]

train:  32%|█████████                   | 30656/94563 [05:03<10:27, 101.92it/s]

train:  32%|█████████                   | 30688/94563 [05:03<10:26, 101.99it/s]

train:  32%|█████████                   | 30720/94563 [05:03<10:26, 101.97it/s]

train:  33%|█████████                   | 30752/94563 [05:04<10:27, 101.75it/s]

train:  33%|█████████                   | 30784/94563 [05:04<10:25, 101.93it/s]

train:  33%|█████████                   | 30816/94563 [05:04<10:24, 102.08it/s]

train:  33%|█████████▏                  | 30848/94563 [05:05<10:25, 101.87it/s]

train:  33%|█████████▏                  | 30880/94563 [05:05<10:25, 101.78it/s]

train:  33%|█████████▏                  | 30912/94563 [05:05<10:25, 101.77it/s]

train:  33%|█████████▏                  | 30944/94563 [05:06<10:25, 101.77it/s]

train:  33%|█████████▏                  | 30976/94563 [05:06<10:24, 101.86it/s]

[train] Checkpoint saved at 31000/94563

train:  33%|█████████▏                  | 31008/94563 [05:06<10:35, 100.00it/s]

train:  33%|█████████▏                  | 31040/94563 [05:07<10:33, 100.31it/s]

train:  33%|█████████▏                  | 31072/94563 [05:07<10:31, 100.53it/s]

train:  33%|█████████▏                  | 31104/94563 [05:07<10:32, 100.41it/s]

train:  33%|█████████▏                  | 31136/94563 [05:08<10:34, 100.04it/s]

train:  33%|█████████▌                   | 31168/94563 [05:08<10:35, 99.73it/s]

train:  33%|█████████▌                   | 31200/94563 [05:08<10:35, 99.71it/s]

train:  33%|█████████▌                   | 31232/94563 [05:08<10:35, 99.67it/s]

train:  33%|█████████▌                   | 31264/94563 [05:09<10:34, 99.69it/s]

train:  33%|█████████▌                   | 31296/94563 [05:09<10:34, 99.70it/s]

train:  33%|█████████▌                   | 31328/94563 [05:09<10:33, 99.77it/s]

train:  33%|█████████▌                   | 31360/94563 [05:10<10:32, 99.91it/s]

train:  33%|█████████▎                  | 31392/94563 [05:10<10:29, 100.28it/s]

train:  33%|█████████▎                  | 31424/94563 [05:10<10:26, 100.73it/s]

train:  33%|█████████▎                  | 31456/94563 [05:11<10:25, 100.97it/s]

train:  33%|█████████▎                  | 31488/94563 [05:11<10:22, 101.37it/s]

train:  33%|█████████▎                  | 31520/94563 [05:11<10:19, 101.74it/s]

train:  33%|█████████▎                  | 31552/94563 [05:12<10:17, 101.97it/s]

train:  33%|█████████▎                  | 31584/94563 [05:12<10:16, 102.11it/s]

train:  33%|█████████▎                  | 31616/94563 [05:12<10:15, 102.25it/s]

train:  33%|█████████▎                  | 31648/94563 [05:13<10:14, 102.35it/s]

train:  34%|█████████▍                  | 31680/94563 [05:13<10:13, 102.52it/s]

train:  34%|█████████▍                  | 31712/94563 [05:13<10:12, 102.62it/s]

train:  34%|█████████▍                  | 31744/94563 [05:14<10:10, 102.93it/s]

train:  34%|█████████▍                  | 31776/94563 [05:14<10:08, 103.18it/s]

train:  34%|█████████▍                  | 31808/94563 [05:14<10:08, 103.15it/s]

train:  34%|█████████▍                  | 31840/94563 [05:14<10:08, 103.11it/s]

train:  34%|█████████▍                  | 31872/94563 [05:15<10:08, 103.09it/s]

train:  34%|█████████▍                  | 31904/94563 [05:15<10:08, 103.05it/s]

train:  34%|█████████▍                  | 31936/94563 [05:15<10:08, 102.89it/s]

train:  34%|█████████▍                  | 31968/94563 [05:16<10:08, 102.83it/s]

train:  34%|█████████▍                  | 32000/94563 [05:16<10:18, 101.13it/s]

[train] Checkpoint saved at 32000/94563

train:  34%|█████████▍                  | 32032/94563 [05:16<10:16, 101.38it/s]

train:  34%|█████████▍                  | 32064/94563 [05:17<10:13, 101.89it/s]

train:  34%|█████████▌                  | 32096/94563 [05:17<10:11, 102.14it/s]

train:  34%|█████████▌                  | 32128/94563 [05:17<10:12, 101.94it/s]

train:  34%|█████████▌                  | 32160/94563 [05:18<10:12, 101.96it/s]

train:  34%|█████████▌                  | 32192/94563 [05:18<10:10, 102.09it/s]

train:  34%|█████████▌                  | 32224/94563 [05:18<10:08, 102.36it/s]

train:  34%|█████████▌                  | 32256/94563 [05:19<10:09, 102.15it/s]

train:  34%|█████████▌                  | 32288/94563 [05:19<10:08, 102.34it/s]

train:  34%|█████████▌                  | 32320/94563 [05:19<10:08, 102.35it/s]

train:  34%|█████████▌                  | 32352/94563 [05:19<10:09, 102.07it/s]

train:  34%|█████████▌                  | 32384/94563 [05:20<10:09, 102.01it/s]

train:  34%|█████████▌                  | 32416/94563 [05:20<10:09, 102.02it/s]

train:  34%|█████████▌                  | 32448/94563 [05:20<10:09, 101.90it/s]

train:  34%|█████████▌                  | 32480/94563 [05:21<10:10, 101.70it/s]

train:  34%|█████████▋                  | 32512/94563 [05:21<10:11, 101.50it/s]

train:  34%|█████████▋                  | 32544/94563 [05:21<10:10, 101.54it/s]

train:  34%|█████████▋                  | 32576/94563 [05:22<10:10, 101.48it/s]

train:  34%|█████████▋                  | 32608/94563 [05:22<10:10, 101.49it/s]

train:  35%|█████████▋                  | 32640/94563 [05:22<10:10, 101.45it/s]

train:  35%|█████████▋                  | 32672/94563 [05:23<10:10, 101.41it/s]

train:  35%|█████████▋                  | 32704/94563 [05:23<10:09, 101.50it/s]

train:  35%|█████████▋                  | 32736/94563 [05:23<10:09, 101.38it/s]

train:  35%|█████████▋                  | 32768/94563 [05:24<10:08, 101.51it/s]

train:  35%|█████████▋                  | 32800/94563 [05:24<10:09, 101.40it/s]

train:  35%|█████████▋                  | 32832/94563 [05:24<10:09, 101.25it/s]

train:  35%|█████████▋                  | 32864/94563 [05:24<10:09, 101.24it/s]

train:  35%|█████████▋                  | 32896/94563 [05:25<10:07, 101.53it/s]

train:  35%|█████████▋                  | 32928/94563 [05:25<10:06, 101.69it/s]

train:  35%|█████████▊                  | 32960/94563 [05:25<10:05, 101.80it/s]

train:  35%|█████████▊                  | 32992/94563 [05:26<10:04, 101.84it/s]

[train] Checkpoint saved at 33000/94563

train:  35%|█████████▊                  | 33024/94563 [05:26<10:14, 100.18it/s]

train:  35%|█████████▊                  | 33056/94563 [05:26<10:08, 101.00it/s]

train:  35%|█████████▊                  | 33088/94563 [05:27<10:06, 101.37it/s]

train:  35%|█████████▊                  | 33120/94563 [05:27<10:03, 101.80it/s]

train:  35%|█████████▊                  | 33152/94563 [05:27<10:01, 102.07it/s]

train:  35%|█████████▊                  | 33184/94563 [05:28<10:01, 102.01it/s]

train:  35%|█████████▊                  | 33216/94563 [05:28<10:02, 101.90it/s]

train:  35%|█████████▊                  | 33248/94563 [05:28<10:01, 101.99it/s]

train:  35%|█████████▊                  | 33280/94563 [05:29<09:59, 102.24it/s]

train:  35%|█████████▊                  | 33312/94563 [05:29<09:58, 102.43it/s]

train:  35%|█████████▊                  | 33344/94563 [05:29<09:57, 102.44it/s]

train:  35%|█████████▉                  | 33376/94563 [05:30<09:57, 102.38it/s]

train:  35%|█████████▉                  | 33408/94563 [05:30<09:57, 102.28it/s]

train:  35%|█████████▉                  | 33440/94563 [05:30<09:58, 102.06it/s]

train:  35%|█████████▉                  | 33472/94563 [05:30<09:58, 102.06it/s]

train:  35%|█████████▉                  | 33504/94563 [05:31<09:59, 101.88it/s]

train:  35%|█████████▉                  | 33536/94563 [05:31<09:59, 101.83it/s]

train:  35%|█████████▉                  | 33568/94563 [05:31<09:58, 101.89it/s]

train:  36%|█████████▉                  | 33600/94563 [05:32<09:57, 101.96it/s]

train:  36%|█████████▉                  | 33632/94563 [05:32<09:58, 101.86it/s]

train:  36%|█████████▉                  | 33664/94563 [05:32<09:57, 101.89it/s]

train:  36%|█████████▉                  | 33696/94563 [05:33<09:56, 102.04it/s]

train:  36%|█████████▉                  | 33728/94563 [05:33<09:57, 101.81it/s]

train:  36%|█████████▉                  | 33760/94563 [05:33<09:56, 101.98it/s]

train:  36%|██████████                  | 33792/94563 [05:34<09:54, 102.18it/s]

train:  36%|██████████                  | 33824/94563 [05:34<09:52, 102.50it/s]

train:  36%|██████████                  | 33856/94563 [05:34<09:53, 102.24it/s]

train:  36%|██████████                  | 33888/94563 [05:35<09:52, 102.37it/s]

train:  36%|██████████                  | 33920/94563 [05:35<09:53, 102.11it/s]

train:  36%|██████████                  | 33952/94563 [05:35<09:54, 101.97it/s]

train:  36%|██████████                  | 33984/94563 [05:35<09:51, 102.42it/s]

[train] Checkpoint saved at 34000/94563

train:  36%|██████████                  | 34016/94563 [05:36<10:03, 100.32it/s]

train:  36%|██████████                  | 34048/94563 [05:36<10:01, 100.67it/s]

train:  36%|██████████                  | 34080/94563 [05:36<09:57, 101.25it/s]

train:  36%|██████████                  | 34112/94563 [05:37<09:55, 101.52it/s]

train:  36%|██████████                  | 34144/94563 [05:37<09:54, 101.60it/s]

train:  36%|██████████                  | 34176/94563 [05:37<09:54, 101.52it/s]

train:  36%|██████████▏                 | 34208/94563 [05:38<09:55, 101.37it/s]

train:  36%|██████████▏                 | 34240/94563 [05:38<09:55, 101.25it/s]

train:  36%|██████████▏                 | 34272/94563 [05:38<09:54, 101.45it/s]

train:  36%|██████████▏                 | 34304/94563 [05:39<09:53, 101.49it/s]

train:  36%|██████████▏                 | 34336/94563 [05:39<09:52, 101.63it/s]

train:  36%|██████████▏                 | 34368/94563 [05:39<09:51, 101.81it/s]

train:  36%|██████████▏                 | 34400/94563 [05:40<09:51, 101.79it/s]

train:  36%|██████████▏                 | 34432/94563 [05:40<09:50, 101.83it/s]

train:  36%|██████████▏                 | 34464/94563 [05:40<09:51, 101.52it/s]

train:  36%|██████████▏                 | 34496/94563 [05:41<09:52, 101.43it/s]

train:  37%|██████████▏                 | 34528/94563 [05:41<09:54, 100.95it/s]

train:  37%|██████████▏                 | 34560/94563 [05:41<09:52, 101.28it/s]

train:  37%|██████████▏                 | 34592/94563 [05:41<09:50, 101.61it/s]

train:  37%|██████████▎                 | 34624/94563 [05:42<09:50, 101.51it/s]

train:  37%|██████████▎                 | 34656/94563 [05:42<09:50, 101.39it/s]

train:  37%|██████████▎                 | 34688/94563 [05:42<09:54, 100.73it/s]

train:  37%|██████████▎                 | 34720/94563 [05:43<09:54, 100.69it/s]

train:  37%|██████████▎                 | 34752/94563 [05:43<09:52, 100.88it/s]

train:  37%|██████████▎                 | 34784/94563 [05:43<09:52, 100.81it/s]

train:  37%|██████████▎                 | 34816/94563 [05:44<09:52, 100.81it/s]

train:  37%|██████████▎                 | 34848/94563 [05:44<09:51, 100.99it/s]

train:  37%|██████████▎                 | 34880/94563 [05:44<09:51, 100.87it/s]

train:  37%|██████████▎                 | 34912/94563 [05:45<09:50, 101.10it/s]

train:  37%|██████████▎                 | 34944/94563 [05:45<09:49, 101.09it/s]

train:  37%|██████████▎                 | 34976/94563 [05:45<09:49, 101.06it/s]

[train] Checkpoint saved at 35000/94563

train:  37%|██████████▋                  | 35008/94563 [05:46<10:03, 98.67it/s]

train:  37%|██████████▋                  | 35040/94563 [05:46<09:57, 99.65it/s]

train:  37%|██████████▊                  | 35072/94563 [05:46<09:55, 99.97it/s]

train:  37%|██████████▊                  | 35104/94563 [05:47<09:59, 99.23it/s]

train:  37%|██████████▊                  | 35136/94563 [05:47<10:00, 98.99it/s]

train:  37%|██████████▊                  | 35168/94563 [05:47<09:59, 99.11it/s]

train:  37%|██████████▊                  | 35200/94563 [05:48<09:57, 99.42it/s]

train:  37%|██████████▊                  | 35232/94563 [05:48<09:57, 99.32it/s]

train:  37%|██████████▊                  | 35264/94563 [05:48<09:57, 99.20it/s]

train:  37%|██████████▊                  | 35296/94563 [05:49<09:57, 99.18it/s]

train:  37%|██████████▊                  | 35328/94563 [05:49<09:53, 99.73it/s]

train:  37%|██████████▊                  | 35360/94563 [05:49<09:53, 99.77it/s]

train:  37%|██████████▍                 | 35392/94563 [05:49<09:49, 100.31it/s]

train:  37%|██████████▍                 | 35424/94563 [05:50<09:47, 100.64it/s]

train:  37%|██████████▍                 | 35456/94563 [05:50<09:45, 100.90it/s]

train:  38%|██████████▌                 | 35488/94563 [05:50<09:43, 101.24it/s]

train:  38%|██████████▌                 | 35520/94563 [05:51<09:41, 101.55it/s]

train:  38%|██████████▌                 | 35552/94563 [05:51<09:40, 101.71it/s]

train:  38%|██████████▌                 | 35584/94563 [05:51<09:41, 101.47it/s]

train:  38%|██████████▌                 | 35616/94563 [05:52<09:39, 101.71it/s]

train:  38%|██████████▌                 | 35648/94563 [05:52<09:38, 101.78it/s]

train:  38%|██████████▌                 | 35680/94563 [05:52<09:40, 101.46it/s]

train:  38%|██████████▌                 | 35712/94563 [05:53<09:40, 101.41it/s]

train:  38%|██████████▌                 | 35744/94563 [05:53<09:44, 100.61it/s]

train:  38%|██████████▌                 | 35776/94563 [05:53<09:42, 100.94it/s]

train:  38%|██████████▌                 | 35808/94563 [05:54<09:40, 101.21it/s]

train:  38%|██████████▌                 | 35840/94563 [05:54<09:40, 101.18it/s]

train:  38%|██████████▌                 | 35872/94563 [05:54<09:38, 101.43it/s]

train:  38%|██████████▋                 | 35904/94563 [05:55<09:36, 101.76it/s]

train:  38%|██████████▋                 | 35936/94563 [05:55<09:35, 101.94it/s]

train:  38%|██████████▋                 | 35968/94563 [05:55<09:34, 101.91it/s]

train:  38%|██████████▋                 | 36000/94563 [05:55<09:45, 100.06it/s]

[train] Checkpoint saved at 36000/94563

train:  38%|██████████▋                 | 36032/94563 [05:56<09:40, 100.81it/s]

train:  38%|██████████▋                 | 36064/94563 [05:56<09:37, 101.34it/s]

train:  38%|██████████▋                 | 36096/94563 [05:56<09:33, 101.90it/s]

train:  38%|██████████▋                 | 36128/94563 [05:57<09:32, 102.11it/s]

train:  38%|██████████▋                 | 36160/94563 [05:57<09:31, 102.26it/s]

train:  38%|██████████▋                 | 36192/94563 [05:57<09:29, 102.42it/s]

train:  38%|██████████▋                 | 36224/94563 [05:58<09:28, 102.65it/s]

train:  38%|██████████▋                 | 36256/94563 [05:58<09:29, 102.47it/s]

train:  38%|██████████▋                 | 36288/94563 [05:58<09:28, 102.53it/s]

train:  38%|██████████▊                 | 36320/94563 [05:59<09:27, 102.68it/s]

train:  38%|██████████▊                 | 36352/94563 [05:59<09:26, 102.74it/s]

train:  38%|██████████▊                 | 36384/94563 [05:59<09:25, 102.87it/s]

train:  39%|██████████▊                 | 36416/94563 [06:00<09:24, 102.93it/s]

train:  39%|██████████▊                 | 36448/94563 [06:00<09:24, 102.87it/s]

train:  39%|██████████▊                 | 36480/94563 [06:00<09:24, 102.81it/s]

train:  39%|██████████▊                 | 36512/94563 [06:00<09:24, 102.79it/s]

train:  39%|██████████▊                 | 36544/94563 [06:01<09:24, 102.76it/s]

train:  39%|██████████▊                 | 36576/94563 [06:01<09:25, 102.53it/s]

train:  39%|██████████▊                 | 36608/94563 [06:01<09:25, 102.48it/s]

train:  39%|██████████▊                 | 36640/94563 [06:02<09:26, 102.25it/s]

train:  39%|██████████▊                 | 36672/94563 [06:02<09:26, 102.13it/s]

train:  39%|██████████▊                 | 36704/94563 [06:02<09:27, 102.00it/s]

train:  39%|██████████▉                 | 36736/94563 [06:03<09:26, 102.04it/s]

train:  39%|██████████▉                 | 36768/94563 [06:03<09:27, 101.92it/s]

train:  39%|██████████▉                 | 36800/94563 [06:03<09:26, 101.98it/s]

train:  39%|██████████▉                 | 36832/94563 [06:04<09:26, 101.91it/s]

train:  39%|██████████▉                 | 36864/94563 [06:04<09:25, 102.00it/s]

train:  39%|██████████▉                 | 36896/94563 [06:04<09:25, 102.06it/s]

train:  39%|██████████▉                 | 36928/94563 [06:05<09:25, 101.93it/s]

train:  39%|██████████▉                 | 36960/94563 [06:05<09:24, 101.96it/s]

train:  39%|██████████▉                 | 36992/94563 [06:05<09:24, 101.97it/s]

[train] Checkpoint saved at 37000/94563

train:  39%|███████████▎                 | 37024/94563 [06:05<09:36, 99.85it/s]

train:  39%|██████████▉                 | 37056/94563 [06:06<09:32, 100.45it/s]

train:  39%|██████████▉                 | 37088/94563 [06:06<09:30, 100.79it/s]

train:  39%|██████████▉                 | 37120/94563 [06:06<09:28, 101.01it/s]

train:  39%|███████████                 | 37152/94563 [06:07<09:27, 101.22it/s]

train:  39%|███████████                 | 37184/94563 [06:07<09:26, 101.31it/s]

train:  39%|███████████                 | 37216/94563 [06:07<09:25, 101.49it/s]

train:  39%|███████████                 | 37248/94563 [06:08<09:24, 101.53it/s]

train:  39%|███████████                 | 37280/94563 [06:08<09:24, 101.52it/s]

train:  39%|███████████                 | 37312/94563 [06:08<09:23, 101.51it/s]

train:  39%|███████████                 | 37344/94563 [06:09<09:23, 101.54it/s]

train:  40%|███████████                 | 37376/94563 [06:09<09:24, 101.28it/s]

train:  40%|███████████                 | 37408/94563 [06:09<09:24, 101.27it/s]

train:  40%|███████████                 | 37440/94563 [06:10<09:24, 101.23it/s]

train:  40%|███████████                 | 37472/94563 [06:10<09:23, 101.38it/s]

train:  40%|███████████                 | 37504/94563 [06:10<09:22, 101.50it/s]

train:  40%|███████████                 | 37536/94563 [06:11<09:25, 100.85it/s]

train:  40%|███████████                 | 37568/94563 [06:11<09:23, 101.13it/s]

train:  40%|███████████▏                | 37600/94563 [06:11<09:21, 101.38it/s]

train:  40%|███████████▏                | 37632/94563 [06:11<09:21, 101.46it/s]

train:  40%|███████████▏                | 37664/94563 [06:12<09:19, 101.66it/s]

train:  40%|███████████▏                | 37696/94563 [06:12<09:18, 101.87it/s]

train:  40%|███████████▏                | 37728/94563 [06:12<09:17, 101.95it/s]

train:  40%|███████████▏                | 37760/94563 [06:13<09:16, 102.13it/s]

train:  40%|███████████▏                | 37792/94563 [06:13<09:16, 102.00it/s]

train:  40%|███████████▏                | 37824/94563 [06:13<09:15, 102.18it/s]

train:  40%|███████████▏                | 37856/94563 [06:14<09:15, 102.11it/s]

train:  40%|███████████▏                | 37888/94563 [06:14<09:14, 102.24it/s]

train:  40%|███████████▏                | 37920/94563 [06:14<09:13, 102.34it/s]

train:  40%|███████████▏                | 37952/94563 [06:15<09:12, 102.37it/s]

train:  40%|███████████▏                | 37984/94563 [06:15<09:13, 102.14it/s]

[train] Checkpoint saved at 38000/94563

train:  40%|███████████▋                 | 38016/94563 [06:15<09:26, 99.88it/s]

train:  40%|███████████▎                | 38048/94563 [06:16<09:21, 100.72it/s]

train:  40%|███████████▎                | 38080/94563 [06:16<09:17, 101.35it/s]

train:  40%|███████████▎                | 38112/94563 [06:16<09:14, 101.73it/s]

train:  40%|███████████▎                | 38144/94563 [06:17<09:13, 101.93it/s]

train:  40%|███████████▎                | 38176/94563 [06:17<09:12, 102.12it/s]

train:  40%|███████████▎                | 38208/94563 [06:17<09:12, 102.09it/s]

train:  40%|███████████▎                | 38240/94563 [06:17<09:19, 100.61it/s]

train:  40%|███████████▎                | 38272/94563 [06:18<09:16, 101.17it/s]

train:  41%|███████████▎                | 38304/94563 [06:18<09:14, 101.45it/s]

train:  41%|███████████▎                | 38336/94563 [06:18<09:12, 101.72it/s]

train:  41%|███████████▎                | 38368/94563 [06:19<09:10, 102.04it/s]

train:  41%|███████████▎                | 38400/94563 [06:19<09:09, 102.18it/s]

train:  41%|███████████▍                | 38432/94563 [06:19<09:09, 102.12it/s]

train:  41%|███████████▍                | 38464/94563 [06:20<09:09, 102.03it/s]

train:  41%|███████████▍                | 38496/94563 [06:20<09:10, 101.92it/s]

train:  41%|███████████▍                | 38528/94563 [06:20<09:11, 101.68it/s]

train:  41%|███████████▍                | 38560/94563 [06:21<09:12, 101.41it/s]

train:  41%|███████████▍                | 38592/94563 [06:21<09:12, 101.23it/s]

train:  41%|███████████▍                | 38624/94563 [06:21<09:12, 101.23it/s]

train:  41%|███████████▍                | 38656/94563 [06:22<09:12, 101.19it/s]

train:  41%|███████████▍                | 38688/94563 [06:22<09:12, 101.17it/s]

train:  41%|███████████▍                | 38720/94563 [06:22<09:12, 101.15it/s]

train:  41%|███████████▍                | 38752/94563 [06:23<09:11, 101.19it/s]

train:  41%|███████████▍                | 38784/94563 [06:23<09:11, 101.22it/s]

train:  41%|███████████▍                | 38816/94563 [06:23<09:09, 101.36it/s]

train:  41%|███████████▌                | 38848/94563 [06:23<09:08, 101.54it/s]

train:  41%|███████████▌                | 38880/94563 [06:24<09:07, 101.76it/s]

train:  41%|███████████▌                | 38912/94563 [06:24<09:06, 101.87it/s]

train:  41%|███████████▌                | 38944/94563 [06:24<09:05, 101.99it/s]

train:  41%|███████████▌                | 38976/94563 [06:25<09:04, 102.10it/s]

[train] Checkpoint saved at 39000/94563

train:  41%|███████████▌                | 39008/94563 [06:25<09:13, 100.31it/s]

train:  41%|███████████▌                | 39040/94563 [06:25<09:09, 101.06it/s]

train:  41%|███████████▌                | 39072/94563 [06:26<09:06, 101.51it/s]

train:  41%|███████████▌                | 39104/94563 [06:26<09:04, 101.87it/s]

train:  41%|███████████▌                | 39136/94563 [06:26<09:02, 102.08it/s]

train:  41%|███████████▌                | 39168/94563 [06:27<09:01, 102.23it/s]

train:  41%|███████████▌                | 39200/94563 [06:27<09:00, 102.43it/s]

train:  41%|███████████▌                | 39232/94563 [06:27<08:59, 102.51it/s]

train:  42%|███████████▋                | 39264/94563 [06:28<08:59, 102.57it/s]

train:  42%|███████████▋                | 39296/94563 [06:28<08:59, 102.39it/s]

train:  42%|███████████▋                | 39328/94563 [06:28<08:59, 102.33it/s]

train:  42%|███████████▋                | 39360/94563 [06:28<08:59, 102.42it/s]

train:  42%|███████████▋                | 39392/94563 [06:29<08:58, 102.41it/s]

train:  42%|███████████▋                | 39424/94563 [06:29<08:58, 102.39it/s]

train:  42%|███████████▋                | 39456/94563 [06:29<08:58, 102.33it/s]

train:  42%|███████████▋                | 39488/94563 [06:30<08:58, 102.21it/s]

train:  42%|███████████▋                | 39520/94563 [06:30<08:57, 102.38it/s]

train:  42%|███████████▋                | 39552/94563 [06:30<08:58, 102.14it/s]

train:  42%|███████████▋                | 39584/94563 [06:31<08:58, 102.08it/s]

train:  42%|███████████▋                | 39616/94563 [06:31<08:58, 101.96it/s]

train:  42%|███████████▋                | 39648/94563 [06:31<08:58, 101.91it/s]

train:  42%|███████████▋                | 39680/94563 [06:32<08:58, 101.89it/s]

train:  42%|███████████▊                | 39712/94563 [06:32<08:58, 101.91it/s]

train:  42%|███████████▊                | 39744/94563 [06:32<08:58, 101.81it/s]

train:  42%|███████████▊                | 39776/94563 [06:33<08:58, 101.78it/s]

train:  42%|███████████▊                | 39808/94563 [06:33<08:56, 101.99it/s]

train:  42%|███████████▊                | 39840/94563 [06:33<08:57, 101.87it/s]

train:  42%|███████████▊                | 39872/94563 [06:33<08:57, 101.74it/s]

train:  42%|███████████▊                | 39904/94563 [06:34<08:58, 101.60it/s]

train:  42%|███████████▊                | 39936/94563 [06:34<08:57, 101.72it/s]

train:  42%|███████████▊                | 39968/94563 [06:34<08:56, 101.78it/s]

train:  42%|████████████▎                | 40000/94563 [06:35<09:05, 99.93it/s]

[train] Checkpoint saved at 40000/94563

train:  42%|███████████▊                | 40032/94563 [06:35<09:02, 100.50it/s]

train:  42%|███████████▊                | 40064/94563 [06:35<08:59, 101.03it/s]

train:  42%|███████████▊                | 40096/94563 [06:36<08:57, 101.27it/s]

train:  42%|███████████▉                | 40128/94563 [06:36<08:56, 101.45it/s]

train:  42%|███████████▉                | 40160/94563 [06:36<08:55, 101.61it/s]

train:  43%|███████████▉                | 40192/94563 [06:37<08:54, 101.78it/s]

train:  43%|███████████▉                | 40224/94563 [06:37<08:53, 101.78it/s]

train:  43%|███████████▉                | 40256/94563 [06:37<08:53, 101.86it/s]

train:  43%|███████████▉                | 40288/94563 [06:38<08:52, 101.96it/s]

train:  43%|███████████▉                | 40320/94563 [06:38<08:53, 101.69it/s]

train:  43%|███████████▉                | 40352/94563 [06:38<08:52, 101.89it/s]

train:  43%|███████████▉                | 40384/94563 [06:39<08:52, 101.82it/s]

train:  43%|███████████▉                | 40416/94563 [06:39<08:51, 101.86it/s]

train:  43%|███████████▉                | 40448/94563 [06:39<08:51, 101.82it/s]

train:  43%|███████████▉                | 40480/94563 [06:39<08:51, 101.85it/s]

train:  43%|███████████▉                | 40512/94563 [06:40<08:50, 101.91it/s]

train:  43%|████████████                | 40544/94563 [06:40<08:51, 101.71it/s]

train:  43%|████████████                | 40576/94563 [06:40<08:51, 101.64it/s]

train:  43%|████████████                | 40608/94563 [06:41<08:50, 101.72it/s]

train:  43%|████████████                | 40640/94563 [06:41<08:49, 101.77it/s]

train:  43%|████████████                | 40672/94563 [06:41<08:48, 101.89it/s]

train:  43%|████████████                | 40704/94563 [06:42<08:48, 101.95it/s]

train:  43%|████████████                | 40736/94563 [06:42<08:47, 102.02it/s]

train:  43%|████████████                | 40768/94563 [06:42<08:46, 102.26it/s]

train:  43%|████████████                | 40800/94563 [06:43<08:44, 102.45it/s]

train:  43%|████████████                | 40832/94563 [06:43<08:44, 102.40it/s]

train:  43%|████████████                | 40864/94563 [06:43<08:45, 102.24it/s]

train:  43%|████████████                | 40896/94563 [06:44<08:46, 102.01it/s]

train:  43%|████████████                | 40928/94563 [06:44<08:46, 101.93it/s]

train:  43%|████████████▏               | 40960/94563 [06:44<08:45, 102.00it/s]

train:  43%|████████████▏               | 40992/94563 [06:44<08:46, 101.82it/s]

[train] Checkpoint saved at 41000/94563

train:  43%|████████████▌                | 41024/94563 [06:45<08:57, 99.54it/s]

train:  43%|████████████▏               | 41056/94563 [06:45<08:52, 100.40it/s]

train:  43%|████████████▏               | 41088/94563 [06:45<08:50, 100.90it/s]

train:  43%|████████████▏               | 41120/94563 [06:46<08:47, 101.23it/s]

train:  44%|████████████▏               | 41152/94563 [06:46<08:45, 101.61it/s]

train:  44%|████████████▏               | 41184/94563 [06:46<08:44, 101.85it/s]

train:  44%|████████████▏               | 41216/94563 [06:47<08:43, 101.85it/s]

train:  44%|████████████▏               | 41248/94563 [06:47<08:42, 102.04it/s]

train:  44%|████████████▏               | 41280/94563 [06:47<08:41, 102.10it/s]

train:  44%|████████████▏               | 41312/94563 [06:48<08:41, 102.15it/s]

train:  44%|████████████▏               | 41344/94563 [06:48<08:42, 101.89it/s]

train:  44%|████████████▎               | 41376/94563 [06:48<08:42, 101.76it/s]

train:  44%|████████████▎               | 41408/94563 [06:49<08:43, 101.57it/s]

train:  44%|████████████▎               | 41440/94563 [06:49<08:43, 101.41it/s]

train:  44%|████████████▎               | 41472/94563 [06:49<08:42, 101.55it/s]

train:  44%|████████████▎               | 41504/94563 [06:50<08:42, 101.62it/s]

train:  44%|████████████▎               | 41536/94563 [06:50<08:41, 101.64it/s]

train:  44%|████████████▎               | 41568/94563 [06:50<08:42, 101.45it/s]

train:  44%|████████████▎               | 41600/94563 [06:50<08:42, 101.33it/s]

train:  44%|████████████▎               | 41632/94563 [06:51<08:42, 101.21it/s]

train:  44%|████████████▎               | 41664/94563 [06:51<08:42, 101.17it/s]

train:  44%|████████████▎               | 41696/94563 [06:51<08:42, 101.24it/s]

train:  44%|████████████▎               | 41728/94563 [06:52<08:42, 101.19it/s]

train:  44%|████████████▎               | 41760/94563 [06:52<08:41, 101.25it/s]

train:  44%|████████████▎               | 41792/94563 [06:52<08:44, 100.52it/s]

train:  44%|████████████▍               | 41824/94563 [06:53<08:42, 100.85it/s]

train:  44%|████████████▍               | 41856/94563 [06:53<08:41, 101.03it/s]

train:  44%|████████████▍               | 41888/94563 [06:53<08:38, 101.51it/s]

train:  44%|████████████▍               | 41920/94563 [06:54<08:37, 101.77it/s]

train:  44%|████████████▍               | 41952/94563 [06:54<08:36, 101.95it/s]

train:  44%|████████████▍               | 41984/94563 [06:54<08:35, 102.08it/s]

[train] Checkpoint saved at 42000/94563

train:  44%|████████████▉                | 42016/94563 [06:55<08:46, 99.74it/s]

train:  44%|████████████▍               | 42048/94563 [06:55<08:41, 100.64it/s]

train:  44%|████████████▍               | 42080/94563 [06:55<08:38, 101.28it/s]

train:  45%|████████████▍               | 42112/94563 [06:56<08:35, 101.85it/s]

train:  45%|████████████▍               | 42144/94563 [06:56<08:32, 102.19it/s]

train:  45%|████████████▍               | 42176/94563 [06:56<08:33, 101.97it/s]

train:  45%|████████████▍               | 42208/94563 [06:56<08:32, 102.06it/s]

train:  45%|████████████▌               | 42240/94563 [06:57<08:31, 102.24it/s]

train:  45%|████████████▌               | 42272/94563 [06:57<08:31, 102.32it/s]

train:  45%|████████████▌               | 42304/94563 [06:57<08:31, 102.17it/s]

train:  45%|████████████▌               | 42336/94563 [06:58<08:30, 102.35it/s]

train:  45%|████████████▌               | 42368/94563 [06:58<08:29, 102.35it/s]

train:  45%|████████████▌               | 42400/94563 [06:58<08:30, 102.17it/s]

train:  45%|████████████▌               | 42432/94563 [06:59<08:30, 102.20it/s]

train:  45%|████████████▌               | 42464/94563 [06:59<08:30, 102.11it/s]

train:  45%|████████████▌               | 42496/94563 [06:59<08:30, 101.98it/s]

train:  45%|████████████▌               | 42528/94563 [07:00<08:30, 102.01it/s]

train:  45%|████████████▌               | 42560/94563 [07:00<08:29, 102.09it/s]

train:  45%|████████████▌               | 42592/94563 [07:00<08:29, 102.04it/s]

train:  45%|████████████▌               | 42624/94563 [07:01<08:29, 101.93it/s]

train:  45%|████████████▋               | 42656/94563 [07:01<08:29, 101.85it/s]

train:  45%|████████████▋               | 42688/94563 [07:01<08:29, 101.83it/s]

train:  45%|████████████▋               | 42720/94563 [07:02<08:29, 101.67it/s]

train:  45%|████████████▋               | 42752/94563 [07:02<08:29, 101.77it/s]

train:  45%|████████████▋               | 42784/94563 [07:02<08:28, 101.84it/s]

train:  45%|████████████▋               | 42816/94563 [07:02<08:28, 101.83it/s]

train:  45%|████████████▋               | 42848/94563 [07:03<08:27, 101.87it/s]

train:  45%|████████████▋               | 42880/94563 [07:03<08:27, 101.84it/s]

train:  45%|████████████▋               | 42912/94563 [07:03<08:27, 101.71it/s]

train:  45%|████████████▋               | 42944/94563 [07:04<08:27, 101.77it/s]

train:  45%|████████████▋               | 42976/94563 [07:04<08:26, 101.92it/s]

[train] Checkpoint saved at 43000/94563

train:  45%|█████████████▏               | 43008/94563 [07:04<08:36, 99.86it/s]

train:  46%|████████████▋               | 43040/94563 [07:05<08:31, 100.73it/s]

train:  46%|████████████▊               | 43072/94563 [07:05<08:28, 101.18it/s]

train:  46%|████████████▊               | 43104/94563 [07:05<08:27, 101.32it/s]

train:  46%|████████████▊               | 43136/94563 [07:06<08:26, 101.47it/s]

train:  46%|████████████▊               | 43168/94563 [07:06<08:26, 101.47it/s]

train:  46%|████████████▊               | 43200/94563 [07:06<08:25, 101.59it/s]

train:  46%|████████████▊               | 43232/94563 [07:07<08:24, 101.70it/s]

train:  46%|████████████▊               | 43264/94563 [07:07<08:24, 101.66it/s]

train:  46%|████████████▊               | 43296/94563 [07:07<08:23, 101.77it/s]

train:  46%|████████████▊               | 43328/94563 [07:07<08:23, 101.70it/s]

train:  46%|████████████▊               | 43360/94563 [07:08<08:23, 101.76it/s]

train:  46%|████████████▊               | 43392/94563 [07:08<08:22, 101.76it/s]

train:  46%|████████████▊               | 43424/94563 [07:08<08:23, 101.56it/s]

train:  46%|████████████▊               | 43456/94563 [07:09<08:22, 101.66it/s]

train:  46%|████████████▉               | 43488/94563 [07:09<08:22, 101.71it/s]

train:  46%|████████████▉               | 43520/94563 [07:09<08:21, 101.73it/s]

train:  46%|████████████▉               | 43552/94563 [07:10<08:21, 101.81it/s]

train:  46%|████████████▉               | 43584/94563 [07:10<08:20, 101.81it/s]

train:  46%|████████████▉               | 43616/94563 [07:10<08:20, 101.79it/s]

train:  46%|████████████▉               | 43648/94563 [07:11<08:20, 101.74it/s]

train:  46%|████████████▉               | 43680/94563 [07:11<08:20, 101.67it/s]

train:  46%|████████████▉               | 43712/94563 [07:11<08:19, 101.83it/s]

train:  46%|████████████▉               | 43744/94563 [07:12<08:19, 101.72it/s]

train:  46%|████████████▉               | 43776/94563 [07:12<08:19, 101.68it/s]

train:  46%|████████████▉               | 43808/94563 [07:12<08:19, 101.66it/s]

train:  46%|████████████▉               | 43840/94563 [07:13<08:19, 101.60it/s]

train:  46%|████████████▉               | 43872/94563 [07:13<08:18, 101.75it/s]

train:  46%|████████████▉               | 43904/94563 [07:13<08:17, 101.78it/s]

train:  46%|█████████████               | 43936/94563 [07:13<08:17, 101.66it/s]

train:  46%|█████████████               | 43968/94563 [07:14<08:17, 101.67it/s]

train:  47%|█████████████▍               | 44000/94563 [07:14<08:28, 99.47it/s]

[train] Checkpoint saved at 44000/94563

train:  47%|█████████████               | 44032/94563 [07:14<08:25, 100.04it/s]

train:  47%|█████████████               | 44064/94563 [07:15<08:20, 100.82it/s]

train:  47%|█████████████               | 44096/94563 [07:15<08:18, 101.17it/s]

train:  47%|█████████████               | 44128/94563 [07:15<08:17, 101.39it/s]

train:  47%|█████████████               | 44160/94563 [07:16<08:16, 101.49it/s]

train:  47%|█████████████               | 44192/94563 [07:16<08:15, 101.63it/s]

train:  47%|█████████████               | 44224/94563 [07:16<08:15, 101.55it/s]

train:  47%|█████████████               | 44256/94563 [07:17<08:15, 101.54it/s]

train:  47%|█████████████               | 44288/94563 [07:17<08:14, 101.68it/s]

train:  47%|█████████████               | 44320/94563 [07:17<08:13, 101.85it/s]

train:  47%|█████████████▏              | 44352/94563 [07:18<08:13, 101.84it/s]

train:  47%|█████████████▏              | 44384/94563 [07:18<08:13, 101.72it/s]

train:  47%|█████████████▏              | 44416/94563 [07:18<08:12, 101.73it/s]

train:  47%|█████████████▏              | 44448/94563 [07:19<08:12, 101.77it/s]

train:  47%|█████████████▏              | 44480/94563 [07:19<08:13, 101.55it/s]

train:  47%|█████████████▏              | 44512/94563 [07:19<08:13, 101.49it/s]

train:  47%|█████████████▏              | 44544/94563 [07:19<08:12, 101.58it/s]

train:  47%|█████████████▏              | 44576/94563 [07:20<08:12, 101.52it/s]

train:  47%|█████████████▏              | 44608/94563 [07:20<08:11, 101.61it/s]

train:  47%|█████████████▏              | 44640/94563 [07:20<08:10, 101.73it/s]

train:  47%|█████████████▏              | 44672/94563 [07:21<08:10, 101.73it/s]

train:  47%|█████████████▏              | 44704/94563 [07:21<08:10, 101.67it/s]

train:  47%|█████████████▏              | 44736/94563 [07:21<08:10, 101.69it/s]

train:  47%|█████████████▎              | 44768/94563 [07:22<08:09, 101.70it/s]

train:  47%|█████████████▎              | 44800/94563 [07:22<08:09, 101.62it/s]

train:  47%|█████████████▎              | 44832/94563 [07:22<08:08, 101.84it/s]

train:  47%|█████████████▎              | 44864/94563 [07:23<08:07, 101.86it/s]

train:  47%|█████████████▎              | 44896/94563 [07:23<08:07, 101.93it/s]

train:  48%|█████████████▎              | 44928/94563 [07:23<08:08, 101.67it/s]

train:  48%|█████████████▎              | 44960/94563 [07:24<08:07, 101.85it/s]

train:  48%|█████████████▎              | 44992/94563 [07:24<08:07, 101.71it/s]

[train] Checkpoint saved at 45000/94563

train:  48%|█████████████▊               | 45024/94563 [07:24<08:21, 98.88it/s]

train:  48%|█████████████▊               | 45056/94563 [07:25<08:15, 99.85it/s]

train:  48%|█████████████▎              | 45088/94563 [07:25<08:11, 100.65it/s]

train:  48%|█████████████▎              | 45120/94563 [07:25<08:09, 101.06it/s]

train:  48%|█████████████▎              | 45152/94563 [07:25<08:08, 101.23it/s]

train:  48%|█████████████▍              | 45184/94563 [07:26<08:06, 101.41it/s]

train:  48%|█████████████▍              | 45216/94563 [07:26<08:05, 101.59it/s]

train:  48%|█████████████▍              | 45248/94563 [07:26<08:05, 101.68it/s]

train:  48%|█████████████▍              | 45280/94563 [07:27<08:04, 101.62it/s]

train:  48%|█████████████▍              | 45312/94563 [07:27<08:04, 101.75it/s]

train:  48%|█████████████▍              | 45344/94563 [07:27<08:03, 101.75it/s]

train:  48%|█████████████▍              | 45376/94563 [07:28<08:04, 101.58it/s]

train:  48%|█████████████▍              | 45408/94563 [07:28<08:03, 101.62it/s]

train:  48%|█████████████▍              | 45440/94563 [07:28<08:03, 101.67it/s]

train:  48%|█████████████▍              | 45472/94563 [07:29<08:02, 101.83it/s]

train:  48%|█████████████▍              | 45504/94563 [07:29<08:02, 101.72it/s]

train:  48%|█████████████▍              | 45536/94563 [07:29<08:01, 101.79it/s]

train:  48%|█████████████▍              | 45568/94563 [07:30<08:00, 101.87it/s]

train:  48%|█████████████▌              | 45600/94563 [07:30<08:01, 101.71it/s]

train:  48%|█████████████▌              | 45632/94563 [07:30<08:00, 101.80it/s]

train:  48%|█████████████▌              | 45664/94563 [07:31<08:00, 101.75it/s]

train:  48%|█████████████▌              | 45696/94563 [07:31<07:59, 101.87it/s]

train:  48%|█████████████▌              | 45728/94563 [07:31<07:59, 101.87it/s]

train:  48%|█████████████▌              | 45760/94563 [07:31<07:59, 101.71it/s]

train:  48%|█████████████▌              | 45792/94563 [07:32<08:00, 101.54it/s]

train:  48%|█████████████▌              | 45824/94563 [07:32<08:00, 101.48it/s]

train:  48%|█████████████▌              | 45856/94563 [07:32<08:00, 101.29it/s]

train:  49%|█████████████▌              | 45888/94563 [07:33<08:00, 101.38it/s]

train:  49%|█████████████▌              | 45920/94563 [07:33<07:59, 101.41it/s]

train:  49%|█████████████▌              | 45952/94563 [07:33<07:59, 101.41it/s]

train:  49%|█████████████▌              | 45984/94563 [07:34<07:59, 101.41it/s]

[train] Checkpoint saved at 46000/94563

train:  49%|██████████████               | 46016/94563 [07:34<08:11, 98.84it/s]

train:  49%|██████████████               | 46048/94563 [07:34<08:05, 99.87it/s]

train:  49%|█████████████▋              | 46080/94563 [07:35<08:02, 100.54it/s]

train:  49%|█████████████▋              | 46112/94563 [07:35<07:59, 101.10it/s]

train:  49%|█████████████▋              | 46144/94563 [07:35<07:57, 101.41it/s]

train:  49%|█████████████▋              | 46176/94563 [07:36<07:56, 101.56it/s]

train:  49%|█████████████▋              | 46208/94563 [07:36<07:55, 101.60it/s]

train:  49%|█████████████▋              | 46240/94563 [07:36<07:55, 101.57it/s]

train:  49%|█████████████▋              | 46272/94563 [07:37<07:55, 101.65it/s]

train:  49%|█████████████▋              | 46304/94563 [07:37<07:54, 101.67it/s]

train:  49%|█████████████▋              | 46336/94563 [07:37<07:54, 101.64it/s]

train:  49%|█████████████▋              | 46368/94563 [07:37<07:54, 101.57it/s]

train:  49%|█████████████▋              | 46400/94563 [07:38<07:53, 101.72it/s]

train:  49%|█████████████▋              | 46432/94563 [07:38<07:56, 101.12it/s]

train:  49%|█████████████▊              | 46464/94563 [07:38<07:53, 101.48it/s]

train:  49%|█████████████▊              | 46496/94563 [07:39<07:52, 101.72it/s]

train:  49%|█████████████▊              | 46528/94563 [07:39<07:51, 101.85it/s]

train:  49%|█████████████▊              | 46560/94563 [07:39<07:50, 102.02it/s]

train:  49%|█████████████▊              | 46592/94563 [07:40<07:50, 101.98it/s]

train:  49%|█████████████▊              | 46624/94563 [07:40<07:50, 101.94it/s]

train:  49%|█████████████▊              | 46656/94563 [07:40<07:49, 102.06it/s]

train:  49%|█████████████▊              | 46688/94563 [07:41<07:49, 101.97it/s]

train:  49%|█████████████▊              | 46720/94563 [07:41<07:49, 101.86it/s]

train:  49%|█████████████▊              | 46752/94563 [07:41<07:48, 101.95it/s]

train:  49%|█████████████▊              | 46784/94563 [07:42<07:48, 101.94it/s]

train:  50%|█████████████▊              | 46816/94563 [07:42<07:48, 101.97it/s]

train:  50%|█████████████▊              | 46848/94563 [07:42<07:47, 102.05it/s]

train:  50%|█████████████▉              | 46880/94563 [07:42<07:47, 102.01it/s]

train:  50%|█████████████▉              | 46912/94563 [07:43<07:47, 101.98it/s]

train:  50%|█████████████▉              | 46944/94563 [07:43<07:47, 101.85it/s]

train:  50%|█████████████▉              | 46976/94563 [07:43<07:47, 101.71it/s]

[train] Checkpoint saved at 47000/94563

train:  50%|██████████████▍              | 47008/94563 [07:44<07:58, 99.33it/s]

train:  50%|█████████████▉              | 47040/94563 [07:44<07:53, 100.29it/s]

train:  50%|█████████████▉              | 47072/94563 [07:44<07:51, 100.77it/s]

train:  50%|█████████████▉              | 47104/94563 [07:45<07:49, 101.07it/s]

train:  50%|█████████████▉              | 47136/94563 [07:45<07:47, 101.36it/s]

train:  50%|█████████████▉              | 47168/94563 [07:45<07:46, 101.56it/s]

train:  50%|█████████████▉              | 47200/94563 [07:46<07:45, 101.66it/s]

train:  50%|█████████████▉              | 47232/94563 [07:46<07:45, 101.62it/s]

train:  50%|█████████████▉              | 47264/94563 [07:46<07:45, 101.69it/s]

train:  50%|██████████████              | 47296/94563 [07:47<07:45, 101.52it/s]

train:  50%|██████████████              | 47328/94563 [07:47<07:45, 101.54it/s]

train:  50%|██████████████              | 47360/94563 [07:47<07:43, 101.76it/s]

train:  50%|██████████████              | 47392/94563 [07:48<07:42, 101.96it/s]

train:  50%|██████████████              | 47424/94563 [07:48<07:42, 102.03it/s]

train:  50%|██████████████              | 47456/94563 [07:48<07:42, 101.88it/s]

train:  50%|██████████████              | 47488/94563 [07:48<07:42, 101.72it/s]

train:  50%|██████████████              | 47520/94563 [07:49<07:43, 101.57it/s]

train:  50%|██████████████              | 47552/94563 [07:49<07:43, 101.44it/s]

train:  50%|██████████████              | 47584/94563 [07:49<07:43, 101.42it/s]

train:  50%|██████████████              | 47616/94563 [07:50<07:42, 101.46it/s]

train:  50%|██████████████              | 47648/94563 [07:50<07:41, 101.70it/s]

train:  50%|██████████████              | 47680/94563 [07:50<07:40, 101.84it/s]

train:  50%|██████████████▏             | 47712/94563 [07:51<07:39, 101.87it/s]

train:  50%|██████████████▏             | 47744/94563 [07:51<07:40, 101.71it/s]

train:  51%|██████████████▏             | 47776/94563 [07:51<07:40, 101.62it/s]

train:  51%|██████████████▏             | 47808/94563 [07:52<07:40, 101.55it/s]

train:  51%|██████████████▏             | 47840/94563 [07:52<07:40, 101.36it/s]

train:  51%|██████████████▏             | 47872/94563 [07:52<07:41, 101.20it/s]

train:  51%|██████████████▏             | 47904/94563 [07:53<07:41, 101.14it/s]

train:  51%|██████████████▏             | 47936/94563 [07:53<07:40, 101.29it/s]

train:  51%|██████████████▏             | 47968/94563 [07:53<07:40, 101.17it/s]

train:  51%|██████████████▋              | 48000/94563 [07:54<07:50, 99.03it/s]

[train] Checkpoint saved at 48000/94563

train:  51%|██████████████▋              | 48032/94563 [07:54<07:48, 99.36it/s]

train:  51%|██████████████▏             | 48064/94563 [07:54<07:43, 100.23it/s]

train:  51%|██████████████▏             | 48096/94563 [07:54<07:40, 100.87it/s]

train:  51%|██████████████▎             | 48128/94563 [07:55<07:38, 101.29it/s]

train:  51%|██████████████▎             | 48160/94563 [07:55<07:36, 101.60it/s]

train:  51%|██████████████▎             | 48192/94563 [07:55<07:36, 101.68it/s]

train:  51%|██████████████▎             | 48224/94563 [07:56<07:35, 101.74it/s]

train:  51%|██████████████▎             | 48256/94563 [07:56<07:35, 101.69it/s]

train:  51%|██████████████▎             | 48288/94563 [07:56<07:34, 101.90it/s]

train:  51%|██████████████▎             | 48320/94563 [07:57<07:33, 101.95it/s]

train:  51%|██████████████▎             | 48352/94563 [07:57<07:32, 102.04it/s]

train:  51%|██████████████▎             | 48384/94563 [07:57<07:33, 101.91it/s]

train:  51%|██████████████▎             | 48416/94563 [07:58<07:31, 102.16it/s]

train:  51%|██████████████▎             | 48448/94563 [07:58<07:31, 102.05it/s]

train:  51%|██████████████▎             | 48480/94563 [07:58<07:31, 102.11it/s]

train:  51%|██████████████▎             | 48512/94563 [07:59<07:30, 102.21it/s]

train:  51%|██████████████▎             | 48544/94563 [07:59<07:30, 102.08it/s]

train:  51%|██████████████▍             | 48576/94563 [07:59<07:31, 101.96it/s]

train:  51%|██████████████▍             | 48608/94563 [08:00<07:32, 101.51it/s]

train:  51%|██████████████▍             | 48640/94563 [08:00<07:32, 101.43it/s]

train:  51%|██████████████▍             | 48672/94563 [08:00<07:32, 101.38it/s]

train:  52%|██████████████▍             | 48704/94563 [08:00<07:31, 101.65it/s]

train:  52%|██████████████▍             | 48736/94563 [08:01<07:31, 101.60it/s]

train:  52%|██████████████▍             | 48768/94563 [08:01<07:31, 101.37it/s]

train:  52%|██████████████▍             | 48800/94563 [08:01<07:32, 101.11it/s]

train:  52%|██████████████▍             | 48832/94563 [08:02<07:33, 100.94it/s]

train:  52%|██████████████▍             | 48864/94563 [08:02<07:33, 100.81it/s]

train:  52%|██████████████▍             | 48896/94563 [08:02<07:33, 100.69it/s]

train:  52%|██████████████▍             | 48928/94563 [08:03<07:32, 100.75it/s]

train:  52%|██████████████▍             | 48960/94563 [08:03<07:32, 100.79it/s]

train:  52%|██████████████▌             | 48992/94563 [08:03<07:31, 100.93it/s]

[train] Checkpoint saved at 49000/94563

train:  52%|███████████████              | 49024/94563 [08:04<07:42, 98.43it/s]

train:  52%|███████████████              | 49056/94563 [08:04<07:37, 99.47it/s]

train:  52%|██████████████▌             | 49088/94563 [08:04<07:33, 100.24it/s]

train:  52%|██████████████▌             | 49120/94563 [08:05<07:30, 100.84it/s]

train:  52%|██████████████▌             | 49152/94563 [08:05<07:29, 101.10it/s]

train:  52%|██████████████▌             | 49184/94563 [08:05<07:28, 101.22it/s]

train:  52%|██████████████▌             | 49216/94563 [08:06<07:28, 101.19it/s]

train:  52%|██████████████▌             | 49248/94563 [08:06<07:28, 101.14it/s]

train:  52%|██████████████▌             | 49280/94563 [08:06<07:27, 101.28it/s]

train:  52%|██████████████▌             | 49312/94563 [08:06<07:26, 101.37it/s]

train:  52%|██████████████▌             | 49344/94563 [08:07<07:28, 100.87it/s]

train:  52%|██████████████▌             | 49376/94563 [08:07<07:27, 101.05it/s]

train:  52%|██████████████▋             | 49408/94563 [08:07<07:25, 101.35it/s]

train:  52%|██████████████▋             | 49440/94563 [08:08<07:25, 101.36it/s]

train:  52%|██████████████▋             | 49472/94563 [08:08<07:24, 101.48it/s]

train:  52%|██████████████▋             | 49504/94563 [08:08<07:22, 101.75it/s]

train:  52%|██████████████▋             | 49536/94563 [08:09<07:21, 101.90it/s]

train:  52%|██████████████▋             | 49568/94563 [08:09<07:20, 102.08it/s]

train:  52%|██████████████▋             | 49600/94563 [08:09<07:20, 102.07it/s]

train:  52%|██████████████▋             | 49632/94563 [08:10<07:20, 101.96it/s]

train:  53%|██████████████▋             | 49664/94563 [08:10<07:20, 101.96it/s]

train:  53%|██████████████▋             | 49696/94563 [08:10<07:19, 102.07it/s]

train:  53%|██████████████▋             | 49728/94563 [08:11<07:19, 102.00it/s]

train:  53%|██████████████▋             | 49760/94563 [08:11<07:19, 101.98it/s]

train:  53%|██████████████▋             | 49792/94563 [08:11<07:19, 101.80it/s]

train:  53%|██████████████▊             | 49824/94563 [08:12<07:19, 101.80it/s]

train:  53%|██████████████▊             | 49856/94563 [08:12<07:18, 101.89it/s]

train:  53%|██████████████▊             | 49888/94563 [08:12<07:18, 101.96it/s]

train:  53%|██████████████▊             | 49920/94563 [08:12<07:18, 101.91it/s]

train:  53%|██████████████▊             | 49952/94563 [08:13<07:18, 101.83it/s]

train:  53%|██████████████▊             | 49984/94563 [08:13<07:18, 101.73it/s]

[train] Checkpoint saved at 50000/94563

train:  53%|███████████████▎             | 50016/94563 [08:13<07:31, 98.62it/s]

train:  53%|███████████████▎             | 50048/94563 [08:14<07:26, 99.67it/s]

train:  53%|██████████████▊             | 50080/94563 [08:14<07:22, 100.47it/s]

train:  53%|██████████████▊             | 50112/94563 [08:14<07:20, 101.02it/s]

train:  53%|██████████████▊             | 50144/94563 [08:15<07:19, 101.18it/s]

train:  53%|██████████████▊             | 50176/94563 [08:15<07:18, 101.33it/s]

train:  53%|██████████████▊             | 50208/94563 [08:15<07:17, 101.34it/s]

train:  53%|██████████████▉             | 50240/94563 [08:16<07:17, 101.34it/s]

train:  53%|██████████████▉             | 50272/94563 [08:16<07:16, 101.37it/s]

train:  53%|██████████████▉             | 50304/94563 [08:16<07:16, 101.39it/s]

train:  53%|██████████████▉             | 50336/94563 [08:17<07:16, 101.37it/s]

train:  53%|██████████████▉             | 50368/94563 [08:17<07:15, 101.54it/s]

train:  53%|██████████████▉             | 50400/94563 [08:17<07:14, 101.58it/s]

train:  53%|██████████████▉             | 50432/94563 [08:18<07:17, 100.96it/s]

train:  53%|██████████████▉             | 50464/94563 [08:18<07:15, 101.30it/s]

train:  53%|██████████████▉             | 50496/94563 [08:18<07:14, 101.47it/s]

train:  53%|██████████████▉             | 50528/94563 [08:18<07:14, 101.44it/s]

train:  53%|██████████████▉             | 50560/94563 [08:19<07:14, 101.38it/s]

train:  54%|██████████████▉             | 50592/94563 [08:19<07:14, 101.30it/s]

train:  54%|██████████████▉             | 50624/94563 [08:19<07:13, 101.36it/s]

train:  54%|██████████████▉             | 50656/94563 [08:20<07:13, 101.26it/s]

train:  54%|███████████████             | 50688/94563 [08:20<07:12, 101.39it/s]

train:  54%|███████████████             | 50720/94563 [08:20<07:12, 101.28it/s]

train:  54%|███████████████             | 50752/94563 [08:21<07:13, 101.17it/s]

train:  54%|███████████████             | 50784/94563 [08:21<07:12, 101.22it/s]

train:  54%|███████████████             | 50816/94563 [08:21<07:12, 101.18it/s]

train:  54%|███████████████             | 50848/94563 [08:22<07:12, 101.08it/s]

train:  54%|███████████████             | 50880/94563 [08:22<07:11, 101.23it/s]

train:  54%|███████████████             | 50912/94563 [08:22<07:11, 101.16it/s]

train:  54%|███████████████             | 50944/94563 [08:23<07:10, 101.24it/s]

train:  54%|███████████████             | 50976/94563 [08:23<07:10, 101.33it/s]

[train] Checkpoint saved at 51000/94563

train:  54%|███████████████▋             | 51008/94563 [08:23<07:19, 99.01it/s]

train:  54%|███████████████▋             | 51040/94563 [08:24<07:15, 99.94it/s]

train:  54%|███████████████             | 51072/94563 [08:24<07:12, 100.64it/s]

train:  54%|███████████████▏            | 51104/94563 [08:24<07:09, 101.14it/s]

train:  54%|███████████████▏            | 51136/94563 [08:24<07:07, 101.57it/s]

train:  54%|███████████████▏            | 51168/94563 [08:25<07:06, 101.73it/s]

train:  54%|███████████████▏            | 51200/94563 [08:25<07:05, 101.90it/s]

train:  54%|███████████████▏            | 51232/94563 [08:25<07:05, 101.82it/s]

train:  54%|███████████████▏            | 51264/94563 [08:26<07:05, 101.79it/s]

train:  54%|███████████████▏            | 51296/94563 [08:26<07:04, 101.86it/s]

train:  54%|███████████████▏            | 51328/94563 [08:26<07:04, 101.81it/s]

train:  54%|███████████████▏            | 51360/94563 [08:27<07:03, 101.93it/s]

train:  54%|███████████████▏            | 51392/94563 [08:27<07:03, 101.88it/s]

train:  54%|███████████████▏            | 51424/94563 [08:27<07:03, 101.80it/s]

train:  54%|███████████████▏            | 51456/94563 [08:28<07:03, 101.69it/s]

train:  54%|███████████████▏            | 51488/94563 [08:28<07:02, 101.85it/s]

train:  54%|███████████████▎            | 51520/94563 [08:28<07:04, 101.37it/s]

train:  55%|███████████████▎            | 51552/94563 [08:29<07:03, 101.64it/s]

train:  55%|███████████████▎            | 51584/94563 [08:29<07:02, 101.73it/s]

train:  55%|███████████████▎            | 51616/94563 [08:29<07:02, 101.77it/s]

train:  55%|███████████████▎            | 51648/94563 [08:30<07:02, 101.51it/s]

train:  55%|███████████████▎            | 51680/94563 [08:30<07:02, 101.60it/s]

train:  55%|███████████████▎            | 51712/94563 [08:30<07:01, 101.60it/s]

train:  55%|███████████████▎            | 51744/94563 [08:30<07:01, 101.53it/s]

train:  55%|███████████████▎            | 51776/94563 [08:31<07:01, 101.40it/s]

train:  55%|███████████████▎            | 51808/94563 [08:31<07:01, 101.40it/s]

train:  55%|███████████████▎            | 51840/94563 [08:31<07:01, 101.45it/s]

train:  55%|███████████████▎            | 51872/94563 [08:32<07:00, 101.59it/s]

train:  55%|███████████████▎            | 51904/94563 [08:32<06:59, 101.62it/s]

train:  55%|███████████████▍            | 51936/94563 [08:32<06:59, 101.69it/s]

train:  55%|███████████████▍            | 51968/94563 [08:33<06:58, 101.69it/s]

train:  55%|███████████████▉             | 52000/94563 [08:33<07:07, 99.45it/s]

[train] Checkpoint saved at 52000/94563

train:  55%|███████████████▉             | 52032/94563 [08:33<07:05, 99.94it/s]

train:  55%|███████████████▍            | 52064/94563 [08:34<07:02, 100.62it/s]

train:  55%|███████████████▍            | 52096/94563 [08:34<06:59, 101.12it/s]

train:  55%|███████████████▍            | 52128/94563 [08:34<06:58, 101.40it/s]

train:  55%|███████████████▍            | 52160/94563 [08:35<06:57, 101.46it/s]

train:  55%|███████████████▍            | 52192/94563 [08:35<06:56, 101.76it/s]

train:  55%|███████████████▍            | 52224/94563 [08:35<06:56, 101.71it/s]

train:  55%|███████████████▍            | 52256/94563 [08:36<07:00, 100.65it/s]

train:  55%|███████████████▍            | 52288/94563 [08:36<06:58, 101.07it/s]

train:  55%|███████████████▍            | 52320/94563 [08:36<06:56, 101.35it/s]

train:  55%|███████████████▌            | 52352/94563 [08:36<06:55, 101.53it/s]

train:  55%|███████████████▌            | 52384/94563 [08:37<06:55, 101.50it/s]

train:  55%|███████████████▌            | 52416/94563 [08:37<06:54, 101.65it/s]

train:  55%|███████████████▌            | 52448/94563 [08:37<06:54, 101.63it/s]

train:  55%|███████████████▌            | 52480/94563 [08:38<06:53, 101.70it/s]

train:  56%|███████████████▌            | 52512/94563 [08:38<06:53, 101.61it/s]

train:  56%|███████████████▌            | 52544/94563 [08:38<06:54, 101.48it/s]

train:  56%|███████████████▌            | 52576/94563 [08:39<06:53, 101.60it/s]

train:  56%|███████████████▌            | 52608/94563 [08:39<06:52, 101.67it/s]

train:  56%|███████████████▌            | 52640/94563 [08:39<06:52, 101.63it/s]

train:  56%|███████████████▌            | 52672/94563 [08:40<06:51, 101.75it/s]

train:  56%|███████████████▌            | 52704/94563 [08:40<06:51, 101.84it/s]

train:  56%|███████████████▌            | 52736/94563 [08:40<06:50, 101.80it/s]

train:  56%|███████████████▌            | 52768/94563 [08:41<06:51, 101.66it/s]

train:  56%|███████████████▋            | 52800/94563 [08:41<06:51, 101.57it/s]

train:  56%|███████████████▋            | 52832/94563 [08:41<06:50, 101.71it/s]

train:  56%|███████████████▋            | 52864/94563 [08:42<06:50, 101.67it/s]

train:  56%|███████████████▋            | 52896/94563 [08:42<06:50, 101.60it/s]

train:  56%|███████████████▋            | 52928/94563 [08:42<06:49, 101.72it/s]

train:  56%|███████████████▋            | 52960/94563 [08:42<06:49, 101.53it/s]

train:  56%|███████████████▋            | 52992/94563 [08:43<06:49, 101.55it/s]

[train] Checkpoint saved at 53000/94563

train:  56%|████████████████▎            | 53024/94563 [08:43<06:59, 98.97it/s]

train:  56%|████████████████▎            | 53056/94563 [08:43<06:55, 99.98it/s]

train:  56%|███████████████▋            | 53088/94563 [08:44<06:52, 100.60it/s]

train:  56%|███████████████▋            | 53120/94563 [08:44<06:50, 101.02it/s]

train:  56%|███████████████▋            | 53152/94563 [08:44<06:49, 101.22it/s]

train:  56%|███████████████▋            | 53184/94563 [08:45<06:47, 101.44it/s]

train:  56%|███████████████▊            | 53216/94563 [08:45<06:47, 101.46it/s]

train:  56%|███████████████▊            | 53248/94563 [08:45<06:46, 101.69it/s]

train:  56%|███████████████▊            | 53280/94563 [08:46<06:45, 101.81it/s]

train:  56%|███████████████▊            | 53312/94563 [08:46<06:45, 101.83it/s]

train:  56%|███████████████▊            | 53344/94563 [08:46<06:45, 101.70it/s]

train:  56%|███████████████▊            | 53376/94563 [08:47<06:45, 101.64it/s]

train:  56%|███████████████▊            | 53408/94563 [08:47<06:45, 101.50it/s]

train:  57%|███████████████▊            | 53440/94563 [08:47<06:45, 101.37it/s]

train:  57%|████████████████▍            | 53472/94563 [08:48<06:51, 99.83it/s]

train:  57%|███████████████▊            | 53504/94563 [08:48<06:48, 100.40it/s]

train:  57%|███████████████▊            | 53536/94563 [08:48<06:47, 100.74it/s]

train:  57%|███████████████▊            | 53568/94563 [08:48<06:46, 100.93it/s]

train:  57%|███████████████▊            | 53600/94563 [08:49<06:45, 101.07it/s]

train:  57%|███████████████▉            | 53632/94563 [08:49<06:43, 101.32it/s]

train:  57%|███████████████▉            | 53664/94563 [08:49<06:44, 101.06it/s]

train:  57%|███████████████▉            | 53696/94563 [08:50<06:43, 101.18it/s]

train:  57%|███████████████▉            | 53728/94563 [08:50<06:44, 101.06it/s]

train:  57%|███████████████▉            | 53760/94563 [08:50<06:43, 101.09it/s]

train:  57%|███████████████▉            | 53792/94563 [08:51<06:43, 101.13it/s]

train:  57%|███████████████▉            | 53824/94563 [08:51<06:43, 100.99it/s]

train:  57%|███████████████▉            | 53856/94563 [08:51<06:42, 101.04it/s]

train:  57%|███████████████▉            | 53888/94563 [08:52<06:41, 101.21it/s]

train:  57%|███████████████▉            | 53920/94563 [08:52<06:41, 101.32it/s]

train:  57%|███████████████▉            | 53952/94563 [08:52<06:40, 101.39it/s]

train:  57%|███████████████▉            | 53984/94563 [08:53<06:39, 101.48it/s]

[train] Checkpoint saved at 54000/94563

train:  57%|████████████████▌            | 54016/94563 [08:53<06:50, 98.69it/s]

train:  57%|████████████████▌            | 54048/94563 [08:53<06:46, 99.74it/s]

train:  57%|████████████████            | 54080/94563 [08:54<06:42, 100.60it/s]

train:  57%|████████████████            | 54112/94563 [08:54<06:40, 100.88it/s]

train:  57%|████████████████            | 54144/94563 [08:54<06:39, 101.22it/s]

train:  57%|████████████████            | 54176/94563 [08:55<06:38, 101.35it/s]

train:  57%|████████████████            | 54208/94563 [08:55<06:38, 101.33it/s]

train:  57%|████████████████            | 54240/94563 [08:55<06:37, 101.49it/s]

train:  57%|████████████████            | 54272/94563 [08:55<06:36, 101.62it/s]

train:  57%|████████████████            | 54304/94563 [08:56<06:35, 101.78it/s]

train:  57%|████████████████            | 54336/94563 [08:56<06:34, 101.85it/s]

train:  57%|████████████████            | 54368/94563 [08:56<06:34, 101.95it/s]

train:  58%|████████████████            | 54400/94563 [08:57<06:34, 101.72it/s]

train:  58%|████████████████            | 54432/94563 [08:57<06:34, 101.65it/s]

train:  58%|████████████████▏           | 54464/94563 [08:57<06:34, 101.74it/s]

train:  58%|████████████████▏           | 54496/94563 [08:58<06:33, 101.91it/s]

train:  58%|████████████████▏           | 54528/94563 [08:58<06:32, 101.94it/s]

train:  58%|████████████████▏           | 54560/94563 [08:58<06:32, 101.95it/s]

train:  58%|████████████████▏           | 54592/94563 [08:59<06:32, 101.82it/s]

train:  58%|████████████████▏           | 54624/94563 [08:59<06:32, 101.69it/s]

train:  58%|████████████████▏           | 54656/94563 [08:59<06:32, 101.61it/s]

train:  58%|████████████████▏           | 54688/94563 [09:00<06:33, 101.42it/s]

train:  58%|████████████████▏           | 54720/94563 [09:00<06:33, 101.15it/s]

train:  58%|████████████████▏           | 54752/94563 [09:00<06:33, 101.26it/s]

train:  58%|████████████████▏           | 54784/94563 [09:00<06:32, 101.33it/s]

train:  58%|████████████████▏           | 54816/94563 [09:01<06:31, 101.49it/s]

train:  58%|████████████████▏           | 54848/94563 [09:01<06:30, 101.73it/s]

train:  58%|████████████████▏           | 54880/94563 [09:01<06:30, 101.69it/s]

train:  58%|████████████████▎           | 54912/94563 [09:02<06:30, 101.63it/s]

train:  58%|████████████████▎           | 54944/94563 [09:02<06:30, 101.54it/s]

train:  58%|████████████████▎           | 54976/94563 [09:02<06:29, 101.73it/s]

[train] Checkpoint saved at 55000/94563

train:  58%|████████████████▊            | 55008/94563 [09:03<06:42, 98.37it/s]

train:  58%|████████████████▉            | 55040/94563 [09:03<06:37, 99.48it/s]

train:  58%|████████████████▎           | 55072/94563 [09:03<06:33, 100.38it/s]

train:  58%|████████████████▎           | 55104/94563 [09:04<06:30, 100.92it/s]

train:  58%|████████████████▎           | 55136/94563 [09:04<06:29, 101.14it/s]

train:  58%|████████████████▎           | 55168/94563 [09:04<06:28, 101.39it/s]

train:  58%|████████████████▎           | 55200/94563 [09:05<06:28, 101.42it/s]

train:  58%|████████████████▎           | 55232/94563 [09:05<06:27, 101.37it/s]

train:  58%|████████████████▎           | 55264/94563 [09:05<06:27, 101.33it/s]

train:  58%|████████████████▎           | 55296/94563 [09:06<06:26, 101.48it/s]

train:  59%|████████████████▍           | 55328/94563 [09:06<06:26, 101.55it/s]

train:  59%|████████████████▍           | 55360/94563 [09:06<06:24, 101.88it/s]

train:  59%|████████████████▍           | 55392/94563 [09:06<06:25, 101.73it/s]

train:  59%|████████████████▍           | 55424/94563 [09:07<06:25, 101.64it/s]

train:  59%|████████████████▍           | 55456/94563 [09:07<06:25, 101.51it/s]

train:  59%|████████████████▍           | 55488/94563 [09:07<06:24, 101.56it/s]

train:  59%|████████████████▍           | 55520/94563 [09:08<06:24, 101.48it/s]

train:  59%|████████████████▍           | 55552/94563 [09:08<06:24, 101.34it/s]

train:  59%|████████████████▍           | 55584/94563 [09:08<06:24, 101.31it/s]

train:  59%|████████████████▍           | 55616/94563 [09:09<06:24, 101.20it/s]

train:  59%|████████████████▍           | 55648/94563 [09:09<06:24, 101.30it/s]

train:  59%|████████████████▍           | 55680/94563 [09:09<06:24, 101.13it/s]

train:  59%|████████████████▍           | 55712/94563 [09:10<06:23, 101.25it/s]

train:  59%|████████████████▌           | 55744/94563 [09:10<06:22, 101.48it/s]

train:  59%|████████████████▌           | 55776/94563 [09:10<06:21, 101.57it/s]

train:  59%|████████████████▌           | 55808/94563 [09:11<06:21, 101.54it/s]

train:  59%|████████████████▌           | 55840/94563 [09:11<06:20, 101.78it/s]

train:  59%|████████████████▌           | 55872/94563 [09:11<06:20, 101.79it/s]

train:  59%|████████████████▌           | 55904/94563 [09:12<06:20, 101.70it/s]

train:  59%|████████████████▌           | 55936/94563 [09:12<06:20, 101.60it/s]

train:  59%|████████████████▌           | 55968/94563 [09:12<06:20, 101.36it/s]

train:  59%|█████████████████▏           | 56000/94563 [09:13<06:32, 98.33it/s]

[train] Checkpoint saved at 56000/94563

train:  59%|█████████████████▏           | 56032/94563 [09:13<06:28, 99.09it/s]

train:  59%|████████████████▌           | 56064/94563 [09:13<06:24, 100.02it/s]

train:  59%|████████████████▌           | 56096/94563 [09:13<06:22, 100.65it/s]

train:  59%|████████████████▌           | 56128/94563 [09:14<06:20, 101.11it/s]

train:  59%|████████████████▋           | 56160/94563 [09:14<06:18, 101.37it/s]

train:  59%|████████████████▋           | 56192/94563 [09:14<06:18, 101.51it/s]

train:  59%|████████████████▋           | 56224/94563 [09:15<06:17, 101.49it/s]

train:  59%|████████████████▋           | 56256/94563 [09:15<06:17, 101.48it/s]

train:  60%|████████████████▋           | 56288/94563 [09:15<06:16, 101.60it/s]

train:  60%|████████████████▋           | 56320/94563 [09:16<06:15, 101.80it/s]

train:  60%|████████████████▋           | 56352/94563 [09:16<06:15, 101.72it/s]

train:  60%|████████████████▋           | 56384/94563 [09:16<06:16, 101.48it/s]

train:  60%|████████████████▋           | 56416/94563 [09:17<06:17, 101.00it/s]

train:  60%|████████████████▋           | 56448/94563 [09:17<06:17, 101.10it/s]

train:  60%|████████████████▋           | 56480/94563 [09:17<06:16, 101.19it/s]

train:  60%|████████████████▋           | 56512/94563 [09:18<06:19, 100.15it/s]

train:  60%|████████████████▋           | 56544/94563 [09:18<06:17, 100.64it/s]

train:  60%|████████████████▊           | 56576/94563 [09:18<06:16, 100.90it/s]

train:  60%|████████████████▊           | 56608/94563 [09:19<06:15, 101.02it/s]

train:  60%|████████████████▊           | 56640/94563 [09:19<06:14, 101.23it/s]

train:  60%|████████████████▊           | 56672/94563 [09:19<06:13, 101.39it/s]

train:  60%|████████████████▊           | 56704/94563 [09:19<06:13, 101.25it/s]

train:  60%|████████████████▊           | 56736/94563 [09:20<06:13, 101.17it/s]

train:  60%|████████████████▊           | 56768/94563 [09:20<06:14, 100.99it/s]

train:  60%|████████████████▊           | 56800/94563 [09:20<06:13, 101.09it/s]

train:  60%|████████████████▊           | 56832/94563 [09:21<06:13, 101.00it/s]

train:  60%|████████████████▊           | 56864/94563 [09:21<06:12, 101.18it/s]

train:  60%|████████████████▊           | 56896/94563 [09:21<06:12, 101.22it/s]

train:  60%|████████████████▊           | 56928/94563 [09:22<06:11, 101.29it/s]

train:  60%|████████████████▊           | 56960/94563 [09:22<06:11, 101.18it/s]

train:  60%|████████████████▉           | 56992/94563 [09:22<06:10, 101.31it/s]

[train] Checkpoint saved at 57000/94563

train:  60%|█████████████████▍           | 57024/94563 [09:23<06:22, 98.10it/s]

train:  60%|█████████████████▍           | 57056/94563 [09:23<06:17, 99.34it/s]

train:  60%|████████████████▉           | 57088/94563 [09:23<06:14, 100.01it/s]

train:  60%|████████████████▉           | 57120/94563 [09:24<06:12, 100.49it/s]

train:  60%|████████████████▉           | 57152/94563 [09:24<06:11, 100.59it/s]

train:  60%|████████████████▉           | 57184/94563 [09:24<06:11, 100.74it/s]

train:  61%|████████████████▉           | 57216/94563 [09:25<06:12, 100.23it/s]

train:  61%|████████████████▉           | 57248/94563 [09:25<06:10, 100.59it/s]

train:  61%|████████████████▉           | 57280/94563 [09:25<06:09, 100.98it/s]

train:  61%|████████████████▉           | 57312/94563 [09:26<06:09, 100.91it/s]

train:  61%|████████████████▉           | 57344/94563 [09:26<06:08, 101.11it/s]

train:  61%|████████████████▉           | 57376/94563 [09:26<06:07, 101.21it/s]

train:  61%|████████████████▉           | 57408/94563 [09:26<06:06, 101.24it/s]

train:  61%|█████████████████           | 57440/94563 [09:27<06:06, 101.21it/s]

train:  61%|█████████████████           | 57472/94563 [09:27<06:05, 101.34it/s]

train:  61%|█████████████████           | 57504/94563 [09:27<06:05, 101.48it/s]

train:  61%|█████████████████           | 57536/94563 [09:28<06:03, 101.75it/s]

train:  61%|█████████████████           | 57568/94563 [09:28<06:03, 101.74it/s]

train:  61%|█████████████████           | 57600/94563 [09:28<06:03, 101.80it/s]

train:  61%|█████████████████           | 57632/94563 [09:29<06:02, 101.74it/s]

train:  61%|█████████████████           | 57664/94563 [09:29<06:02, 101.71it/s]

train:  61%|█████████████████           | 57696/94563 [09:29<06:02, 101.72it/s]

train:  61%|█████████████████           | 57728/94563 [09:30<06:02, 101.58it/s]

train:  61%|█████████████████           | 57760/94563 [09:30<06:01, 101.67it/s]

train:  61%|█████████████████           | 57792/94563 [09:30<06:01, 101.72it/s]

train:  61%|█████████████████           | 57824/94563 [09:31<06:00, 101.77it/s]

train:  61%|█████████████████▏          | 57856/94563 [09:31<06:00, 101.76it/s]

train:  61%|█████████████████▏          | 57888/94563 [09:31<06:00, 101.60it/s]

train:  61%|█████████████████▏          | 57920/94563 [09:31<06:01, 101.42it/s]

train:  61%|█████████████████▏          | 57952/94563 [09:32<06:01, 101.27it/s]

train:  61%|█████████████████▏          | 57984/94563 [09:32<06:01, 101.15it/s]

[train] Checkpoint saved at 58000/94563

train:  61%|█████████████████▊           | 58016/94563 [09:32<06:12, 98.01it/s]

train:  61%|█████████████████▊           | 58048/94563 [09:33<06:07, 99.23it/s]

train:  61%|█████████████████▊           | 58080/94563 [09:33<06:05, 99.69it/s]

train:  61%|█████████████████▏          | 58112/94563 [09:33<06:03, 100.16it/s]

train:  61%|█████████████████▏          | 58144/94563 [09:34<06:02, 100.52it/s]

train:  62%|█████████████████▏          | 58176/94563 [09:34<06:01, 100.69it/s]

train:  62%|█████████████████▏          | 58208/94563 [09:34<06:00, 100.92it/s]

train:  62%|█████████████████▏          | 58240/94563 [09:35<05:59, 101.03it/s]

train:  62%|█████████████████▎          | 58272/94563 [09:35<05:58, 101.26it/s]

train:  62%|█████████████████▎          | 58304/94563 [09:35<05:57, 101.43it/s]

train:  62%|█████████████████▎          | 58336/94563 [09:36<05:57, 101.46it/s]

train:  62%|█████████████████▎          | 58368/94563 [09:36<05:56, 101.45it/s]

train:  62%|█████████████████▎          | 58400/94563 [09:36<05:56, 101.41it/s]

train:  62%|█████████████████▎          | 58432/94563 [09:37<05:56, 101.38it/s]

train:  62%|█████████████████▎          | 58464/94563 [09:37<05:56, 101.25it/s]

train:  62%|█████████████████▎          | 58496/94563 [09:37<05:56, 101.11it/s]

train:  62%|█████████████████▎          | 58528/94563 [09:38<05:55, 101.23it/s]

train:  62%|█████████████████▎          | 58560/94563 [09:38<05:55, 101.25it/s]

train:  62%|█████████████████▎          | 58592/94563 [09:38<05:55, 101.30it/s]

train:  62%|█████████████████▎          | 58624/94563 [09:38<05:54, 101.31it/s]

train:  62%|█████████████████▎          | 58656/94563 [09:39<05:54, 101.39it/s]

train:  62%|█████████████████▍          | 58688/94563 [09:39<05:53, 101.36it/s]

train:  62%|█████████████████▍          | 58720/94563 [09:39<05:53, 101.41it/s]

train:  62%|█████████████████▍          | 58752/94563 [09:40<05:53, 101.26it/s]

train:  62%|█████████████████▍          | 58784/94563 [09:40<05:53, 101.30it/s]

train:  62%|█████████████████▍          | 58816/94563 [09:40<05:52, 101.49it/s]

train:  62%|█████████████████▍          | 58848/94563 [09:41<05:51, 101.55it/s]

train:  62%|█████████████████▍          | 58880/94563 [09:41<05:51, 101.66it/s]

train:  62%|█████████████████▍          | 58912/94563 [09:41<05:50, 101.65it/s]

train:  62%|█████████████████▍          | 58944/94563 [09:42<05:50, 101.53it/s]

train:  62%|█████████████████▍          | 58976/94563 [09:42<05:51, 101.29it/s]

[train] Checkpoint saved at 59000/94563

train:  62%|██████████████████           | 59008/94563 [09:42<06:00, 98.57it/s]

train:  62%|██████████████████           | 59040/94563 [09:43<05:57, 99.45it/s]

train:  62%|██████████████████           | 59072/94563 [09:43<05:55, 99.95it/s]

train:  63%|█████████████████▌          | 59104/94563 [09:43<05:53, 100.29it/s]

train:  63%|█████████████████▌          | 59136/94563 [09:44<05:53, 100.31it/s]

train:  63%|█████████████████▌          | 59168/94563 [09:44<05:52, 100.43it/s]

train:  63%|█████████████████▌          | 59200/94563 [09:44<05:51, 100.47it/s]

train:  63%|█████████████████▌          | 59232/94563 [09:45<05:51, 100.60it/s]

train:  63%|█████████████████▌          | 59264/94563 [09:45<05:50, 100.71it/s]

train:  63%|█████████████████▌          | 59296/94563 [09:45<05:49, 100.83it/s]

train:  63%|█████████████████▌          | 59328/94563 [09:45<05:49, 100.86it/s]

train:  63%|█████████████████▌          | 59360/94563 [09:46<05:48, 101.03it/s]

train:  63%|█████████████████▌          | 59392/94563 [09:46<05:48, 101.03it/s]

train:  63%|█████████████████▌          | 59424/94563 [09:46<05:47, 101.08it/s]

train:  63%|█████████████████▌          | 59456/94563 [09:47<05:47, 101.13it/s]

train:  63%|█████████████████▌          | 59488/94563 [09:47<05:46, 101.33it/s]

train:  63%|█████████████████▌          | 59520/94563 [09:47<05:45, 101.44it/s]

train:  63%|█████████████████▋          | 59552/94563 [09:48<05:44, 101.71it/s]

train:  63%|█████████████████▋          | 59584/94563 [09:48<05:43, 101.73it/s]

train:  63%|█████████████████▋          | 59616/94563 [09:48<05:43, 101.60it/s]

train:  63%|█████████████████▋          | 59648/94563 [09:49<05:43, 101.54it/s]

train:  63%|█████████████████▋          | 59680/94563 [09:49<05:44, 101.31it/s]

train:  63%|█████████████████▋          | 59712/94563 [09:49<05:43, 101.56it/s]

train:  63%|█████████████████▋          | 59744/94563 [09:50<05:42, 101.52it/s]

train:  63%|█████████████████▋          | 59776/94563 [09:50<05:42, 101.45it/s]

train:  63%|█████████████████▋          | 59808/94563 [09:50<05:42, 101.38it/s]

train:  63%|█████████████████▋          | 59840/94563 [09:51<05:43, 101.12it/s]

train:  63%|█████████████████▋          | 59872/94563 [09:51<05:43, 101.12it/s]

train:  63%|█████████████████▋          | 59904/94563 [09:51<05:42, 101.17it/s]

train:  63%|█████████████████▋          | 59936/94563 [09:51<05:42, 101.17it/s]

train:  63%|█████████████████▊          | 59968/94563 [09:52<05:41, 101.22it/s]

train:  63%|██████████████████▍          | 60000/94563 [09:52<05:51, 98.35it/s]

[train] Checkpoint saved at 60000/94563

train:  63%|██████████████████▍          | 60032/94563 [09:52<05:49, 98.91it/s]

train:  64%|██████████████████▍          | 60064/94563 [09:53<05:45, 99.76it/s]

train:  64%|█████████████████▊          | 60096/94563 [09:53<05:43, 100.46it/s]

train:  64%|█████████████████▊          | 60128/94563 [09:53<05:41, 100.85it/s]

train:  64%|█████████████████▊          | 60160/94563 [09:54<05:40, 101.12it/s]

train:  64%|█████████████████▊          | 60192/94563 [09:54<05:39, 101.31it/s]

train:  64%|█████████████████▊          | 60224/94563 [09:54<05:38, 101.38it/s]

train:  64%|█████████████████▊          | 60256/94563 [09:55<05:37, 101.54it/s]

train:  64%|█████████████████▊          | 60288/94563 [09:55<05:37, 101.47it/s]

train:  64%|█████████████████▊          | 60320/94563 [09:55<05:37, 101.39it/s]

train:  64%|█████████████████▊          | 60352/94563 [09:56<05:37, 101.33it/s]

train:  64%|█████████████████▉          | 60384/94563 [09:56<05:37, 101.24it/s]

train:  64%|█████████████████▉          | 60416/94563 [09:56<05:37, 101.11it/s]

train:  64%|█████████████████▉          | 60448/94563 [09:57<05:37, 101.03it/s]

train:  64%|█████████████████▉          | 60480/94563 [09:57<05:36, 101.17it/s]

train:  64%|█████████████████▉          | 60512/94563 [09:57<05:36, 101.24it/s]

train:  64%|█████████████████▉          | 60544/94563 [09:57<05:35, 101.47it/s]

train:  64%|█████████████████▉          | 60576/94563 [09:58<05:34, 101.52it/s]

train:  64%|█████████████████▉          | 60608/94563 [09:58<05:33, 101.68it/s]

train:  64%|█████████████████▉          | 60640/94563 [09:58<05:33, 101.72it/s]

train:  64%|█████████████████▉          | 60672/94563 [09:59<05:33, 101.55it/s]

train:  64%|█████████████████▉          | 60704/94563 [09:59<05:33, 101.64it/s]

train:  64%|█████████████████▉          | 60736/94563 [09:59<05:32, 101.62it/s]

train:  64%|█████████████████▉          | 60768/94563 [10:00<05:33, 101.20it/s]

train:  64%|██████████████████          | 60800/94563 [10:00<05:33, 101.26it/s]

train:  64%|██████████████████          | 60832/94563 [10:00<05:32, 101.33it/s]

train:  64%|██████████████████          | 60864/94563 [10:01<05:32, 101.25it/s]

train:  64%|██████████████████          | 60896/94563 [10:01<05:32, 101.17it/s]

train:  64%|██████████████████          | 60928/94563 [10:01<05:32, 101.13it/s]

train:  64%|██████████████████          | 60960/94563 [10:02<05:32, 101.11it/s]

train:  64%|██████████████████          | 60992/94563 [10:02<05:31, 101.15it/s]

[train] Checkpoint saved at 61000/94563

train:  65%|██████████████████▋          | 61024/94563 [10:02<05:43, 97.66it/s]

train:  65%|██████████████████▋          | 61056/94563 [10:03<05:38, 98.93it/s]

train:  65%|██████████████████▋          | 61088/94563 [10:03<05:35, 99.72it/s]

train:  65%|██████████████████          | 61120/94563 [10:03<05:33, 100.20it/s]

train:  65%|██████████████████          | 61152/94563 [10:04<05:31, 100.73it/s]

train:  65%|██████████████████          | 61184/94563 [10:04<05:30, 101.09it/s]

train:  65%|██████████████████▏         | 61216/94563 [10:04<05:29, 101.29it/s]

train:  65%|██████████████████▏         | 61248/94563 [10:04<05:28, 101.48it/s]

train:  65%|██████████████████▏         | 61280/94563 [10:05<05:27, 101.55it/s]

train:  65%|██████████████████▏         | 61312/94563 [10:05<05:27, 101.53it/s]

train:  65%|██████████████████▏         | 61344/94563 [10:05<05:27, 101.37it/s]

train:  65%|██████████████████▏         | 61376/94563 [10:06<05:27, 101.32it/s]

train:  65%|██████████████████▏         | 61408/94563 [10:06<05:30, 100.46it/s]

train:  65%|██████████████████▏         | 61440/94563 [10:06<05:29, 100.66it/s]

train:  65%|██████████████████▏         | 61472/94563 [10:07<05:28, 100.67it/s]

train:  65%|██████████████████▏         | 61504/94563 [10:07<05:27, 100.92it/s]

train:  65%|██████████████████▏         | 61536/94563 [10:07<05:26, 101.08it/s]

train:  65%|██████████████████▏         | 61568/94563 [10:08<05:26, 101.16it/s]

train:  65%|██████████████████▏         | 61600/94563 [10:08<05:25, 101.27it/s]

train:  65%|██████████████████▏         | 61632/94563 [10:08<05:25, 101.29it/s]

train:  65%|██████████████████▎         | 61664/94563 [10:09<05:24, 101.33it/s]

train:  65%|██████████████████▎         | 61696/94563 [10:09<05:24, 101.30it/s]

train:  65%|██████████████████▎         | 61728/94563 [10:09<05:24, 101.28it/s]

train:  65%|██████████████████▎         | 61760/94563 [10:10<05:24, 101.13it/s]

train:  65%|██████████████████▎         | 61792/94563 [10:10<05:24, 101.10it/s]

train:  65%|██████████████████▎         | 61824/94563 [10:10<05:23, 101.11it/s]

train:  65%|██████████████████▎         | 61856/94563 [10:10<05:23, 101.12it/s]

train:  65%|██████████████████▎         | 61888/94563 [10:11<05:23, 101.04it/s]

train:  65%|██████████████████▎         | 61920/94563 [10:11<05:22, 101.11it/s]

train:  66%|██████████████████▎         | 61952/94563 [10:11<05:22, 101.07it/s]

train:  66%|██████████████████▎         | 61984/94563 [10:12<05:22, 101.15it/s]

[train] Checkpoint saved at 62000/94563

train:  66%|███████████████████          | 62016/94563 [10:12<05:32, 97.84it/s]

train:  66%|███████████████████          | 62048/94563 [10:12<05:27, 99.15it/s]

train:  66%|██████████████████▍         | 62080/94563 [10:13<05:24, 100.05it/s]

train:  66%|██████████████████▍         | 62112/94563 [10:13<05:22, 100.67it/s]

train:  66%|██████████████████▍         | 62144/94563 [10:13<05:20, 101.07it/s]

train:  66%|██████████████████▍         | 62176/94563 [10:14<05:19, 101.23it/s]

train:  66%|██████████████████▍         | 62208/94563 [10:14<05:19, 101.18it/s]

train:  66%|██████████████████▍         | 62240/94563 [10:14<05:19, 101.12it/s]

train:  66%|██████████████████▍         | 62272/94563 [10:15<05:19, 101.18it/s]

train:  66%|██████████████████▍         | 62304/94563 [10:15<05:19, 101.11it/s]

train:  66%|██████████████████▍         | 62336/94563 [10:15<05:18, 101.12it/s]

train:  66%|██████████████████▍         | 62368/94563 [10:16<05:18, 101.05it/s]

train:  66%|██████████████████▍         | 62400/94563 [10:16<05:17, 101.15it/s]

train:  66%|██████████████████▍         | 62432/94563 [10:16<05:18, 100.90it/s]

train:  66%|██████████████████▍         | 62464/94563 [10:17<05:17, 101.06it/s]

train:  66%|██████████████████▌         | 62496/94563 [10:17<05:17, 101.08it/s]

train:  66%|██████████████████▌         | 62528/94563 [10:17<05:17, 100.91it/s]

train:  66%|██████████████████▌         | 62560/94563 [10:17<05:16, 101.10it/s]

train:  66%|██████████████████▌         | 62592/94563 [10:18<05:15, 101.19it/s]

train:  66%|██████████████████▌         | 62624/94563 [10:18<05:15, 101.18it/s]

train:  66%|██████████████████▌         | 62656/94563 [10:18<05:15, 101.08it/s]

train:  66%|██████████████████▌         | 62688/94563 [10:19<05:15, 100.96it/s]

train:  66%|██████████████████▌         | 62720/94563 [10:19<05:15, 100.87it/s]

train:  66%|██████████████████▌         | 62752/94563 [10:19<05:15, 100.91it/s]

train:  66%|██████████████████▌         | 62784/94563 [10:20<05:14, 100.93it/s]

train:  66%|██████████████████▌         | 62816/94563 [10:20<05:14, 100.95it/s]

train:  66%|██████████████████▌         | 62848/94563 [10:20<05:14, 100.85it/s]

train:  66%|██████████████████▌         | 62880/94563 [10:21<05:14, 100.78it/s]

train:  67%|██████████████████▋         | 62912/94563 [10:21<05:13, 100.85it/s]

train:  67%|██████████████████▋         | 62944/94563 [10:21<05:13, 100.98it/s]

train:  67%|██████████████████▋         | 62976/94563 [10:22<05:12, 101.07it/s]

[train] Checkpoint saved at 63000/94563

train:  67%|███████████████████▎         | 63008/94563 [10:22<05:20, 98.36it/s]

train:  67%|███████████████████▎         | 63040/94563 [10:22<05:16, 99.46it/s]

train:  67%|██████████████████▋         | 63072/94563 [10:23<05:14, 100.16it/s]

train:  67%|██████████████████▋         | 63104/94563 [10:23<05:12, 100.69it/s]

train:  67%|██████████████████▋         | 63136/94563 [10:23<05:11, 101.00it/s]

train:  67%|██████████████████▋         | 63168/94563 [10:24<05:10, 101.19it/s]

train:  67%|██████████████████▋         | 63200/94563 [10:24<05:09, 101.28it/s]

train:  67%|██████████████████▋         | 63232/94563 [10:24<05:09, 101.14it/s]

train:  67%|██████████████████▋         | 63264/94563 [10:24<05:09, 101.15it/s]

train:  67%|██████████████████▋         | 63296/94563 [10:25<05:08, 101.26it/s]

train:  67%|██████████████████▊         | 63328/94563 [10:25<05:07, 101.43it/s]

train:  67%|██████████████████▊         | 63360/94563 [10:25<05:07, 101.47it/s]

train:  67%|██████████████████▊         | 63392/94563 [10:26<05:07, 101.51it/s]

train:  67%|██████████████████▊         | 63424/94563 [10:26<05:07, 101.26it/s]

train:  67%|██████████████████▊         | 63456/94563 [10:26<05:07, 101.12it/s]

train:  67%|██████████████████▊         | 63488/94563 [10:27<05:07, 101.07it/s]

train:  67%|██████████████████▊         | 63520/94563 [10:27<05:07, 101.00it/s]

train:  67%|██████████████████▊         | 63552/94563 [10:27<05:06, 101.02it/s]

train:  67%|██████████████████▊         | 63584/94563 [10:28<05:06, 100.95it/s]

train:  67%|██████████████████▊         | 63616/94563 [10:28<05:06, 100.93it/s]

train:  67%|██████████████████▊         | 63648/94563 [10:28<05:05, 101.06it/s]

train:  67%|██████████████████▊         | 63680/94563 [10:29<05:05, 101.24it/s]

train:  67%|██████████████████▊         | 63712/94563 [10:29<05:04, 101.29it/s]

train:  67%|██████████████████▊         | 63744/94563 [10:29<05:04, 101.27it/s]

train:  67%|██████████████████▉         | 63776/94563 [10:30<05:03, 101.34it/s]

train:  67%|██████████████████▉         | 63808/94563 [10:30<05:02, 101.64it/s]

train:  68%|██████████████████▉         | 63840/94563 [10:30<05:01, 101.74it/s]

train:  68%|██████████████████▉         | 63872/94563 [10:30<05:01, 101.66it/s]

train:  68%|██████████████████▉         | 63904/94563 [10:31<05:01, 101.65it/s]

train:  68%|██████████████████▉         | 63936/94563 [10:31<05:01, 101.62it/s]

train:  68%|██████████████████▉         | 63968/94563 [10:31<05:01, 101.37it/s]

train:  68%|███████████████████▋         | 64000/94563 [10:32<05:11, 98.03it/s]

[train] Checkpoint saved at 64000/94563

train:  68%|███████████████████▋         | 64032/94563 [10:32<05:09, 98.71it/s]

train:  68%|███████████████████▋         | 64064/94563 [10:32<05:06, 99.62it/s]

train:  68%|██████████████████▉         | 64096/94563 [10:33<05:04, 100.19it/s]

train:  68%|██████████████████▉         | 64128/94563 [10:33<05:03, 100.41it/s]

train:  68%|██████████████████▉         | 64160/94563 [10:33<05:02, 100.65it/s]

train:  68%|███████████████████         | 64192/94563 [10:34<05:01, 100.88it/s]

train:  68%|███████████████████         | 64224/94563 [10:34<05:00, 100.97it/s]

train:  68%|███████████████████         | 64256/94563 [10:34<05:00, 100.97it/s]

train:  68%|███████████████████         | 64288/94563 [10:35<04:59, 100.93it/s]

train:  68%|███████████████████         | 64320/94563 [10:35<04:59, 101.06it/s]

train:  68%|███████████████████         | 64352/94563 [10:35<04:59, 101.01it/s]

train:  68%|███████████████████         | 64384/94563 [10:36<04:58, 101.05it/s]

train:  68%|███████████████████         | 64416/94563 [10:36<04:58, 100.97it/s]

train:  68%|███████████████████         | 64448/94563 [10:36<04:58, 101.04it/s]

train:  68%|███████████████████         | 64480/94563 [10:36<04:57, 100.99it/s]

train:  68%|███████████████████         | 64512/94563 [10:37<04:57, 101.15it/s]

train:  68%|███████████████████         | 64544/94563 [10:37<04:56, 101.18it/s]

train:  68%|███████████████████         | 64576/94563 [10:37<04:56, 101.28it/s]

train:  68%|███████████████████▏        | 64608/94563 [10:38<04:55, 101.28it/s]

train:  68%|███████████████████▏        | 64640/94563 [10:38<04:54, 101.47it/s]

train:  68%|███████████████████▏        | 64672/94563 [10:38<04:54, 101.53it/s]

train:  68%|███████████████████▏        | 64704/94563 [10:39<04:53, 101.58it/s]

train:  68%|███████████████████▏        | 64736/94563 [10:39<04:53, 101.77it/s]

train:  68%|███████████████████▏        | 64768/94563 [10:39<04:52, 101.69it/s]

train:  69%|███████████████████▏        | 64800/94563 [10:40<04:52, 101.69it/s]

train:  69%|███████████████████▏        | 64832/94563 [10:40<04:52, 101.59it/s]

train:  69%|███████████████████▏        | 64864/94563 [10:40<04:52, 101.52it/s]

train:  69%|███████████████████▏        | 64896/94563 [10:41<04:52, 101.34it/s]

train:  69%|███████████████████▏        | 64928/94563 [10:41<04:52, 101.23it/s]

train:  69%|███████████████████▏        | 64960/94563 [10:41<04:52, 101.09it/s]

train:  69%|███████████████████▏        | 64992/94563 [10:42<04:52, 101.08it/s]

[train] Checkpoint saved at 65000/94563

train:  69%|███████████████████▉         | 65024/94563 [10:42<05:03, 97.48it/s]

train:  69%|███████████████████▉         | 65056/94563 [10:42<04:58, 98.83it/s]

train:  69%|███████████████████▉         | 65088/94563 [10:43<04:56, 99.57it/s]

train:  69%|███████████████████▉         | 65120/94563 [10:43<04:55, 99.73it/s]

train:  69%|███████████████████▎        | 65152/94563 [10:43<04:53, 100.20it/s]

train:  69%|███████████████████▉         | 65184/94563 [10:43<04:53, 99.93it/s]

train:  69%|███████████████████▎        | 65216/94563 [10:44<04:52, 100.33it/s]

train:  69%|███████████████████▎        | 65248/94563 [10:44<04:51, 100.64it/s]

train:  69%|███████████████████▎        | 65280/94563 [10:44<04:51, 100.56it/s]

train:  69%|███████████████████▎        | 65312/94563 [10:45<04:50, 100.66it/s]

train:  69%|███████████████████▎        | 65344/94563 [10:45<04:49, 100.95it/s]

train:  69%|███████████████████▎        | 65376/94563 [10:45<04:48, 101.02it/s]

train:  69%|███████████████████▎        | 65408/94563 [10:46<04:48, 100.89it/s]

train:  69%|███████████████████▍        | 65440/94563 [10:46<04:48, 100.91it/s]

train:  69%|███████████████████▍        | 65472/94563 [10:46<04:47, 101.04it/s]

train:  69%|███████████████████▍        | 65504/94563 [10:47<04:47, 101.10it/s]

train:  69%|███████████████████▍        | 65536/94563 [10:47<04:47, 101.02it/s]

train:  69%|███████████████████▍        | 65568/94563 [10:47<04:46, 101.23it/s]

train:  69%|████████████████████         | 65600/94563 [10:48<04:51, 99.52it/s]

train:  69%|███████████████████▍        | 65632/94563 [10:48<04:48, 100.26it/s]

train:  69%|███████████████████▍        | 65664/94563 [10:48<04:47, 100.39it/s]

train:  69%|███████████████████▍        | 65696/94563 [10:49<04:46, 100.66it/s]

train:  70%|███████████████████▍        | 65728/94563 [10:49<04:46, 100.80it/s]

train:  70%|███████████████████▍        | 65760/94563 [10:49<04:45, 100.76it/s]

train:  70%|███████████████████▍        | 65792/94563 [10:50<04:45, 100.64it/s]

train:  70%|███████████████████▍        | 65824/94563 [10:50<04:46, 100.46it/s]

train:  70%|███████████████████▍        | 65856/94563 [10:50<04:45, 100.55it/s]

train:  70%|███████████████████▌        | 65888/94563 [10:50<04:44, 100.70it/s]

train:  70%|███████████████████▌        | 65920/94563 [10:51<04:43, 100.88it/s]

train:  70%|███████████████████▌        | 65952/94563 [10:51<04:43, 100.99it/s]

train:  70%|███████████████████▌        | 65984/94563 [10:51<04:42, 101.13it/s]

[train] Checkpoint saved at 66000/94563

train:  70%|████████████████████▏        | 66016/94563 [10:52<04:58, 95.75it/s]

train:  70%|████████████████████▎        | 66048/94563 [10:52<04:51, 97.80it/s]

train:  70%|████████████████████▎        | 66080/94563 [10:52<04:47, 98.95it/s]

train:  70%|████████████████████▎        | 66112/94563 [10:53<04:44, 99.87it/s]

train:  70%|███████████████████▌        | 66144/94563 [10:53<04:42, 100.43it/s]

train:  70%|███████████████████▌        | 66176/94563 [10:53<04:42, 100.31it/s]

train:  70%|███████████████████▌        | 66208/94563 [10:54<04:42, 100.47it/s]

train:  70%|███████████████████▌        | 66240/94563 [10:54<04:41, 100.62it/s]

train:  70%|███████████████████▌        | 66272/94563 [10:54<04:40, 100.83it/s]

train:  70%|███████████████████▋        | 66304/94563 [10:55<04:39, 101.02it/s]

train:  70%|███████████████████▋        | 66336/94563 [10:55<04:39, 101.07it/s]

train:  70%|███████████████████▋        | 66368/94563 [10:55<04:39, 100.98it/s]

train:  70%|███████████████████▋        | 66400/94563 [10:56<04:38, 100.97it/s]

train:  70%|███████████████████▋        | 66432/94563 [10:56<04:38, 101.08it/s]

train:  70%|███████████████████▋        | 66464/94563 [10:56<04:37, 101.22it/s]

train:  70%|███████████████████▋        | 66496/94563 [10:57<04:37, 101.19it/s]

train:  70%|███████████████████▋        | 66528/94563 [10:57<04:37, 101.17it/s]

train:  70%|███████████████████▋        | 66560/94563 [10:57<04:37, 101.09it/s]

train:  70%|███████████████████▋        | 66592/94563 [10:57<04:36, 101.19it/s]

train:  70%|███████████████████▋        | 66624/94563 [10:58<04:35, 101.32it/s]

train:  70%|███████████████████▋        | 66656/94563 [10:58<04:35, 101.22it/s]

train:  71%|███████████████████▋        | 66688/94563 [10:58<04:35, 101.23it/s]

train:  71%|███████████████████▊        | 66720/94563 [10:59<04:34, 101.25it/s]

train:  71%|███████████████████▊        | 66752/94563 [10:59<04:34, 101.17it/s]

train:  71%|███████████████████▊        | 66784/94563 [10:59<04:34, 101.17it/s]

train:  71%|███████████████████▊        | 66816/94563 [11:00<04:34, 101.09it/s]

train:  71%|███████████████████▊        | 66848/94563 [11:00<04:34, 101.08it/s]

train:  71%|███████████████████▊        | 66880/94563 [11:00<04:33, 101.10it/s]

train:  71%|███████████████████▊        | 66912/94563 [11:01<04:33, 101.22it/s]

train:  71%|███████████████████▊        | 66944/94563 [11:01<04:32, 101.30it/s]

train:  71%|███████████████████▊        | 66976/94563 [11:01<04:32, 101.15it/s]

[train] Checkpoint saved at 67000/94563

train:  71%|████████████████████▌        | 67008/94563 [11:02<04:42, 97.62it/s]

train:  71%|████████████████████▌        | 67040/94563 [11:02<04:38, 98.91it/s]

train:  71%|████████████████████▌        | 67072/94563 [11:02<04:35, 99.66it/s]

train:  71%|███████████████████▊        | 67104/94563 [11:03<04:33, 100.25it/s]

train:  71%|███████████████████▉        | 67136/94563 [11:03<04:32, 100.75it/s]

train:  71%|███████████████████▉        | 67168/94563 [11:03<04:31, 101.07it/s]

train:  71%|███████████████████▉        | 67200/94563 [11:04<04:30, 101.23it/s]

train:  71%|███████████████████▉        | 67232/94563 [11:04<04:30, 101.21it/s]

train:  71%|███████████████████▉        | 67264/94563 [11:04<04:29, 101.39it/s]

train:  71%|███████████████████▉        | 67296/94563 [11:04<04:29, 101.33it/s]

train:  71%|███████████████████▉        | 67328/94563 [11:05<04:28, 101.44it/s]

train:  71%|███████████████████▉        | 67360/94563 [11:05<04:28, 101.47it/s]

train:  71%|███████████████████▉        | 67392/94563 [11:05<04:28, 101.35it/s]

train:  71%|███████████████████▉        | 67424/94563 [11:06<04:28, 101.23it/s]

train:  71%|███████████████████▉        | 67456/94563 [11:06<04:28, 101.14it/s]

train:  71%|███████████████████▉        | 67488/94563 [11:06<04:27, 101.16it/s]

train:  71%|███████████████████▉        | 67520/94563 [11:07<04:27, 101.12it/s]

train:  71%|████████████████████        | 67552/94563 [11:07<04:27, 100.90it/s]

train:  71%|████████████████████        | 67584/94563 [11:07<04:26, 101.07it/s]

train:  72%|████████████████████        | 67616/94563 [11:08<04:26, 101.03it/s]

train:  72%|████████████████████        | 67648/94563 [11:08<04:26, 101.14it/s]

train:  72%|████████████████████        | 67680/94563 [11:08<04:25, 101.13it/s]

train:  72%|████████████████████        | 67712/94563 [11:09<04:25, 101.19it/s]

train:  72%|████████████████████        | 67744/94563 [11:09<04:25, 101.19it/s]

train:  72%|████████████████████        | 67776/94563 [11:09<04:24, 101.12it/s]

train:  72%|████████████████████        | 67808/94563 [11:10<04:24, 101.15it/s]

train:  72%|████████████████████        | 67840/94563 [11:10<04:24, 101.09it/s]

train:  72%|████████████████████        | 67872/94563 [11:10<04:24, 101.07it/s]

train:  72%|████████████████████        | 67904/94563 [11:10<04:23, 101.06it/s]

train:  72%|████████████████████        | 67936/94563 [11:11<04:24, 100.69it/s]

train:  72%|████████████████████▏       | 67968/94563 [11:11<04:23, 100.80it/s]

train:  72%|████████████████████▊        | 68000/94563 [11:11<04:32, 97.46it/s]

[train] Checkpoint saved at 68000/94563

train:  72%|████████████████████▊        | 68032/94563 [11:12<04:29, 98.45it/s]

train:  72%|████████████████████▊        | 68064/94563 [11:12<04:26, 99.55it/s]

train:  72%|████████████████████▏       | 68096/94563 [11:12<04:23, 100.46it/s]

train:  72%|████████████████████▏       | 68128/94563 [11:13<04:22, 100.82it/s]

train:  72%|████████████████████▏       | 68160/94563 [11:13<04:20, 101.24it/s]

train:  72%|████████████████████▏       | 68192/94563 [11:13<04:19, 101.45it/s]

train:  72%|████████████████████▏       | 68224/94563 [11:14<04:19, 101.58it/s]

train:  72%|████████████████████▏       | 68256/94563 [11:14<04:19, 101.51it/s]

train:  72%|████████████████████▏       | 68288/94563 [11:14<04:18, 101.50it/s]

train:  72%|████████████████████▏       | 68320/94563 [11:15<04:18, 101.34it/s]

train:  72%|████████████████████▏       | 68352/94563 [11:15<04:18, 101.30it/s]

train:  72%|████████████████████▏       | 68384/94563 [11:15<04:19, 101.07it/s]

train:  72%|████████████████████▎       | 68416/94563 [11:16<04:19, 100.93it/s]

train:  72%|████████████████████▎       | 68448/94563 [11:16<04:18, 100.88it/s]

train:  72%|████████████████████▎       | 68480/94563 [11:16<04:18, 100.84it/s]

train:  72%|████████████████████▎       | 68512/94563 [11:17<04:18, 100.93it/s]

train:  72%|████████████████████▎       | 68544/94563 [11:17<04:17, 101.01it/s]

train:  73%|████████████████████▎       | 68576/94563 [11:17<04:17, 101.01it/s]

train:  73%|████████████████████▎       | 68608/94563 [11:17<04:16, 101.11it/s]

train:  73%|████████████████████▎       | 68640/94563 [11:18<04:16, 101.12it/s]

train:  73%|████████████████████▎       | 68672/94563 [11:18<04:16, 101.08it/s]

train:  73%|████████████████████▎       | 68704/94563 [11:18<04:15, 101.09it/s]

train:  73%|████████████████████▎       | 68736/94563 [11:19<04:15, 101.05it/s]

train:  73%|████████████████████▎       | 68768/94563 [11:19<04:15, 101.02it/s]

train:  73%|████████████████████▎       | 68800/94563 [11:19<04:15, 100.90it/s]

train:  73%|████████████████████▍       | 68832/94563 [11:20<04:15, 100.87it/s]

train:  73%|████████████████████▍       | 68864/94563 [11:20<04:15, 100.71it/s]

train:  73%|████████████████████▍       | 68896/94563 [11:20<04:14, 100.71it/s]

train:  73%|████████████████████▍       | 68928/94563 [11:21<04:14, 100.88it/s]

train:  73%|████████████████████▍       | 68960/94563 [11:21<04:13, 100.93it/s]

train:  73%|████████████████████▍       | 68992/94563 [11:21<04:13, 101.00it/s]

[train] Checkpoint saved at 69000/94563

train:  73%|█████████████████████▏       | 69024/94563 [11:22<04:26, 95.78it/s]

train:  73%|█████████████████████▏       | 69056/94563 [11:22<04:21, 97.68it/s]

train:  73%|█████████████████████▏       | 69088/94563 [11:22<04:17, 99.01it/s]

train:  73%|█████████████████████▏       | 69120/94563 [11:23<04:14, 99.86it/s]

train:  73%|████████████████████▍       | 69152/94563 [11:23<04:13, 100.40it/s]

train:  73%|████████████████████▍       | 69184/94563 [11:23<04:11, 100.77it/s]

train:  73%|████████████████████▍       | 69216/94563 [11:24<04:10, 101.01it/s]

train:  73%|████████████████████▌       | 69248/94563 [11:24<04:10, 101.10it/s]

train:  73%|████████████████████▌       | 69280/94563 [11:24<04:10, 100.88it/s]

train:  73%|████████████████████▌       | 69312/94563 [11:24<04:10, 100.87it/s]

train:  73%|████████████████████▌       | 69344/94563 [11:25<04:10, 100.86it/s]

train:  73%|████████████████████▌       | 69376/94563 [11:25<04:10, 100.74it/s]

train:  73%|████████████████████▌       | 69408/94563 [11:25<04:09, 100.85it/s]

train:  73%|████████████████████▌       | 69440/94563 [11:26<04:09, 100.89it/s]

train:  73%|████████████████████▌       | 69472/94563 [11:26<04:08, 100.99it/s]

train:  74%|████████████████████▌       | 69504/94563 [11:26<04:08, 101.00it/s]

train:  74%|████████████████████▌       | 69536/94563 [11:27<04:07, 101.07it/s]

train:  74%|████████████████████▌       | 69568/94563 [11:27<04:07, 101.01it/s]

train:  74%|████████████████████▌       | 69600/94563 [11:27<04:07, 100.99it/s]

train:  74%|████████████████████▌       | 69632/94563 [11:28<04:06, 101.00it/s]

train:  74%|████████████████████▋       | 69664/94563 [11:28<04:06, 101.07it/s]

train:  74%|████████████████████▋       | 69696/94563 [11:28<04:05, 101.20it/s]

train:  74%|████████████████████▋       | 69728/94563 [11:29<04:05, 101.26it/s]

train:  74%|████████████████████▋       | 69760/94563 [11:29<04:04, 101.30it/s]

train:  74%|████████████████████▋       | 69792/94563 [11:29<04:04, 101.26it/s]

train:  74%|████████████████████▋       | 69824/94563 [11:30<04:04, 101.20it/s]

train:  74%|████████████████████▋       | 69856/94563 [11:30<04:04, 100.88it/s]

train:  74%|████████████████████▋       | 69888/94563 [11:30<04:04, 100.93it/s]

train:  74%|████████████████████▋       | 69920/94563 [11:30<04:03, 101.10it/s]

train:  74%|████████████████████▋       | 69952/94563 [11:31<04:03, 101.09it/s]

train:  74%|████████████████████▋       | 69984/94563 [11:31<04:03, 101.12it/s]

[train] Checkpoint saved at 70000/94563

train:  74%|█████████████████████▍       | 70016/94563 [11:31<04:11, 97.57it/s]

train:  74%|█████████████████████▍       | 70048/94563 [11:32<04:08, 98.81it/s]

train:  74%|█████████████████████▍       | 70080/94563 [11:32<04:05, 99.71it/s]

train:  74%|████████████████████▊       | 70112/94563 [11:32<04:03, 100.25it/s]

train:  74%|████████████████████▊       | 70144/94563 [11:33<04:02, 100.70it/s]

train:  74%|████████████████████▊       | 70176/94563 [11:33<04:01, 100.78it/s]

train:  74%|████████████████████▊       | 70208/94563 [11:33<04:01, 100.85it/s]

train:  74%|████████████████████▊       | 70240/94563 [11:34<04:01, 100.87it/s]

train:  74%|████████████████████▊       | 70272/94563 [11:34<04:00, 100.90it/s]

train:  74%|████████████████████▊       | 70304/94563 [11:34<04:00, 101.01it/s]

train:  74%|████████████████████▊       | 70336/94563 [11:35<04:00, 100.92it/s]

train:  74%|████████████████████▊       | 70368/94563 [11:35<03:59, 101.01it/s]

train:  74%|████████████████████▊       | 70400/94563 [11:35<03:59, 100.94it/s]

train:  74%|████████████████████▊       | 70432/94563 [11:36<03:58, 101.07it/s]

train:  75%|████████████████████▊       | 70464/94563 [11:36<03:58, 101.12it/s]

train:  75%|████████████████████▊       | 70496/94563 [11:36<03:57, 101.21it/s]

train:  75%|████████████████████▉       | 70528/94563 [11:37<03:57, 101.05it/s]

train:  75%|████████████████████▉       | 70560/94563 [11:37<03:57, 101.02it/s]

train:  75%|████████████████████▉       | 70592/94563 [11:37<03:57, 101.03it/s]

train:  75%|████████████████████▉       | 70624/94563 [11:37<03:56, 101.08it/s]

train:  75%|████████████████████▉       | 70656/94563 [11:38<03:56, 101.08it/s]

train:  75%|████████████████████▉       | 70688/94563 [11:38<03:56, 101.08it/s]

train:  75%|████████████████████▉       | 70720/94563 [11:38<03:55, 101.09it/s]

train:  75%|████████████████████▉       | 70752/94563 [11:39<03:55, 101.12it/s]

train:  75%|████████████████████▉       | 70784/94563 [11:39<03:55, 100.98it/s]

train:  75%|████████████████████▉       | 70816/94563 [11:39<03:54, 101.05it/s]

train:  75%|████████████████████▉       | 70848/94563 [11:40<03:54, 101.10it/s]

train:  75%|████████████████████▉       | 70880/94563 [11:40<03:54, 101.12it/s]

train:  75%|████████████████████▉       | 70912/94563 [11:40<03:53, 101.10it/s]

train:  75%|█████████████████████       | 70944/94563 [11:41<03:54, 100.53it/s]

train:  75%|█████████████████████       | 70976/94563 [11:41<03:54, 100.78it/s]

[train] Checkpoint saved at 71000/94563

train:  75%|█████████████████████▊       | 71008/94563 [11:41<04:02, 97.30it/s]

train:  75%|█████████████████████▊       | 71040/94563 [11:42<03:58, 98.74it/s]

train:  75%|█████████████████████▊       | 71072/94563 [11:42<03:55, 99.74it/s]

train:  75%|█████████████████████       | 71104/94563 [11:42<03:53, 100.25it/s]

train:  75%|█████████████████████       | 71136/94563 [11:43<03:53, 100.52it/s]

train:  75%|█████████████████████       | 71168/94563 [11:43<03:52, 100.76it/s]

train:  75%|█████████████████████       | 71200/94563 [11:43<03:51, 100.92it/s]

train:  75%|█████████████████████       | 71232/94563 [11:44<03:51, 100.96it/s]

train:  75%|█████████████████████       | 71264/94563 [11:44<03:50, 101.02it/s]

train:  75%|█████████████████████       | 71296/94563 [11:44<03:50, 100.93it/s]

train:  75%|█████████████████████       | 71328/94563 [11:44<03:50, 100.90it/s]

train:  75%|█████████████████████▏      | 71360/94563 [11:45<03:49, 101.06it/s]

train:  75%|█████████████████████▏      | 71392/94563 [11:45<03:50, 100.70it/s]

train:  76%|█████████████████████▏      | 71424/94563 [11:45<03:49, 100.83it/s]

train:  76%|█████████████████████▏      | 71456/94563 [11:46<03:49, 100.87it/s]

train:  76%|█████████████████████▏      | 71488/94563 [11:46<03:48, 100.94it/s]

train:  76%|█████████████████████▏      | 71520/94563 [11:46<03:48, 100.97it/s]

train:  76%|█████████████████████▏      | 71552/94563 [11:47<03:47, 101.02it/s]

train:  76%|█████████████████████▏      | 71584/94563 [11:47<03:47, 100.99it/s]

train:  76%|█████████████████████▏      | 71616/94563 [11:47<03:47, 100.96it/s]

train:  76%|█████████████████████▏      | 71648/94563 [11:48<03:48, 100.18it/s]

train:  76%|█████████████████████▏      | 71680/94563 [11:48<03:47, 100.57it/s]

train:  76%|█████████████████████▏      | 71712/94563 [11:48<03:47, 100.66it/s]

train:  76%|█████████████████████▏      | 71744/94563 [11:49<03:46, 100.80it/s]

train:  76%|█████████████████████▎      | 71776/94563 [11:49<03:45, 100.85it/s]

train:  76%|█████████████████████▎      | 71808/94563 [11:49<03:45, 100.95it/s]

train:  76%|█████████████████████▎      | 71840/94563 [11:50<03:45, 100.76it/s]

train:  76%|█████████████████████▎      | 71872/94563 [11:50<03:45, 100.82it/s]

train:  76%|█████████████████████▎      | 71904/94563 [11:50<03:44, 100.96it/s]

train:  76%|█████████████████████▎      | 71936/94563 [11:51<03:43, 101.07it/s]

train:  76%|█████████████████████▎      | 71968/94563 [11:51<03:43, 101.01it/s]

train:  76%|██████████████████████       | 72000/94563 [11:51<03:51, 97.28it/s]

[train] Checkpoint saved at 72000/94563

train:  76%|██████████████████████       | 72032/94563 [11:52<03:52, 96.85it/s]

train:  76%|██████████████████████       | 72064/94563 [11:52<03:48, 98.50it/s]

train:  76%|██████████████████████       | 72096/94563 [11:52<03:46, 99.34it/s]

train:  76%|█████████████████████▎      | 72128/94563 [11:52<03:44, 100.11it/s]

train:  76%|█████████████████████▎      | 72160/94563 [11:53<03:43, 100.43it/s]

train:  76%|█████████████████████▍      | 72192/94563 [11:53<03:42, 100.76it/s]

train:  76%|█████████████████████▍      | 72224/94563 [11:53<03:41, 100.78it/s]

train:  76%|█████████████████████▍      | 72256/94563 [11:54<03:41, 100.78it/s]

train:  76%|█████████████████████▍      | 72288/94563 [11:54<03:40, 100.96it/s]

train:  76%|█████████████████████▍      | 72320/94563 [11:54<03:40, 101.01it/s]

train:  77%|█████████████████████▍      | 72352/94563 [11:55<03:39, 101.02it/s]

train:  77%|█████████████████████▍      | 72384/94563 [11:55<03:39, 100.92it/s]

train:  77%|█████████████████████▍      | 72416/94563 [11:55<03:39, 101.00it/s]

train:  77%|█████████████████████▍      | 72448/94563 [11:56<03:38, 101.02it/s]

train:  77%|█████████████████████▍      | 72480/94563 [11:56<03:38, 101.13it/s]

train:  77%|█████████████████████▍      | 72512/94563 [11:56<03:38, 101.08it/s]

train:  77%|█████████████████████▍      | 72544/94563 [11:57<03:37, 101.14it/s]

train:  77%|█████████████████████▍      | 72576/94563 [11:57<03:37, 101.13it/s]

train:  77%|█████████████████████▍      | 72608/94563 [11:57<03:36, 101.19it/s]

train:  77%|█████████████████████▌      | 72640/94563 [11:58<03:37, 101.03it/s]

train:  77%|█████████████████████▌      | 72672/94563 [11:58<03:36, 101.05it/s]

train:  77%|█████████████████████▌      | 72704/94563 [11:58<03:36, 101.17it/s]

train:  77%|█████████████████████▌      | 72736/94563 [11:58<03:35, 101.11it/s]

train:  77%|█████████████████████▌      | 72768/94563 [11:59<03:35, 101.01it/s]

train:  77%|█████████████████████▌      | 72800/94563 [11:59<03:35, 100.95it/s]

train:  77%|█████████████████████▌      | 72832/94563 [11:59<03:35, 100.94it/s]

train:  77%|█████████████████████▌      | 72864/94563 [12:00<03:34, 101.04it/s]

train:  77%|█████████████████████▌      | 72896/94563 [12:00<03:34, 101.22it/s]

train:  77%|█████████████████████▌      | 72928/94563 [12:00<03:33, 101.14it/s]

train:  77%|█████████████████████▌      | 72960/94563 [12:01<03:33, 101.15it/s]

train:  77%|█████████████████████▌      | 72992/94563 [12:01<03:33, 100.96it/s]

[train] Checkpoint saved at 73000/94563

train:  77%|██████████████████████▍      | 73024/94563 [12:01<03:45, 95.55it/s]

train:  77%|██████████████████████▍      | 73056/94563 [12:02<03:40, 97.63it/s]

train:  77%|██████████████████████▍      | 73088/94563 [12:02<03:36, 99.02it/s]

train:  77%|█████████████████████▋      | 73120/94563 [12:02<03:34, 100.00it/s]

train:  77%|█████████████████████▋      | 73152/94563 [12:03<03:33, 100.38it/s]

train:  77%|█████████████████████▋      | 73184/94563 [12:03<03:33, 100.22it/s]

train:  77%|█████████████████████▋      | 73216/94563 [12:03<03:32, 100.49it/s]

train:  77%|█████████████████████▋      | 73248/94563 [12:04<03:31, 100.72it/s]

train:  77%|█████████████████████▋      | 73280/94563 [12:04<03:30, 100.93it/s]

train:  78%|█████████████████████▋      | 73312/94563 [12:04<03:30, 100.99it/s]

train:  78%|█████████████████████▋      | 73344/94563 [12:05<03:29, 101.06it/s]

train:  78%|█████████████████████▋      | 73376/94563 [12:05<03:29, 101.01it/s]

train:  78%|█████████████████████▋      | 73408/94563 [12:05<03:29, 101.00it/s]

train:  78%|█████████████████████▋      | 73440/94563 [12:06<03:30, 100.13it/s]

train:  78%|█████████████████████▊      | 73472/94563 [12:06<03:29, 100.54it/s]

train:  78%|█████████████████████▊      | 73504/94563 [12:06<03:28, 100.84it/s]

train:  78%|█████████████████████▊      | 73536/94563 [12:06<03:28, 100.83it/s]

train:  78%|█████████████████████▊      | 73568/94563 [12:07<03:27, 101.06it/s]

train:  78%|█████████████████████▊      | 73600/94563 [12:07<03:27, 101.07it/s]

train:  78%|█████████████████████▊      | 73632/94563 [12:07<03:27, 101.05it/s]

train:  78%|█████████████████████▊      | 73664/94563 [12:08<03:27, 100.94it/s]

train:  78%|█████████████████████▊      | 73696/94563 [12:08<03:26, 100.83it/s]

train:  78%|█████████████████████▊      | 73728/94563 [12:08<03:26, 101.07it/s]

train:  78%|█████████████████████▊      | 73760/94563 [12:09<03:25, 101.04it/s]

train:  78%|█████████████████████▊      | 73792/94563 [12:09<03:25, 101.08it/s]

train:  78%|█████████████████████▊      | 73824/94563 [12:09<03:25, 100.84it/s]

train:  78%|█████████████████████▊      | 73856/94563 [12:10<03:25, 100.68it/s]

train:  78%|█████████████████████▉      | 73888/94563 [12:10<03:25, 100.42it/s]

train:  78%|█████████████████████▉      | 73920/94563 [12:10<03:25, 100.26it/s]

train:  78%|█████████████████████▉      | 73952/94563 [12:11<03:25, 100.30it/s]

train:  78%|█████████████████████▉      | 73984/94563 [12:11<03:25, 100.32it/s]

[train] Checkpoint saved at 74000/94563

train:  78%|██████████████████████▋      | 74016/94563 [12:11<03:36, 94.85it/s]

train:  78%|██████████████████████▋      | 74048/94563 [12:12<03:31, 97.09it/s]

train:  78%|██████████████████████▋      | 74080/94563 [12:12<03:27, 98.48it/s]

train:  78%|██████████████████████▋      | 74112/94563 [12:12<03:25, 99.43it/s]

train:  78%|█████████████████████▉      | 74144/94563 [12:13<03:24, 100.00it/s]

train:  78%|█████████████████████▉      | 74176/94563 [12:13<03:23, 100.18it/s]

train:  78%|█████████████████████▉      | 74208/94563 [12:13<03:23, 100.23it/s]

train:  79%|█████████████████████▉      | 74240/94563 [12:13<03:22, 100.45it/s]

train:  79%|█████████████████████▉      | 74272/94563 [12:14<03:22, 100.39it/s]

train:  79%|██████████████████████      | 74304/94563 [12:14<03:21, 100.46it/s]

train:  79%|██████████████████████      | 74336/94563 [12:14<03:20, 100.72it/s]

train:  79%|██████████████████████      | 74368/94563 [12:15<03:20, 100.80it/s]

train:  79%|██████████████████████      | 74400/94563 [12:15<03:19, 100.91it/s]

train:  79%|██████████████████████      | 74432/94563 [12:15<03:19, 100.96it/s]

train:  79%|██████████████████████      | 74464/94563 [12:16<03:19, 100.97it/s]

train:  79%|██████████████████████      | 74496/94563 [12:16<03:18, 100.97it/s]

train:  79%|██████████████████████      | 74528/94563 [12:16<03:19, 100.31it/s]

train:  79%|██████████████████████      | 74560/94563 [12:17<03:18, 100.65it/s]

train:  79%|██████████████████████      | 74592/94563 [12:17<03:17, 101.02it/s]

train:  79%|██████████████████████      | 74624/94563 [12:17<03:16, 101.26it/s]

train:  79%|██████████████████████      | 74656/94563 [12:18<03:17, 100.67it/s]

train:  79%|██████████████████████      | 74688/94563 [12:18<03:16, 101.01it/s]

train:  79%|██████████████████████      | 74720/94563 [12:18<03:16, 101.18it/s]

train:  79%|██████████████████████▏     | 74752/94563 [12:19<03:15, 101.24it/s]

train:  79%|██████████████████████▏     | 74784/94563 [12:19<03:15, 101.21it/s]

train:  79%|██████████████████████▏     | 74816/94563 [12:19<03:15, 100.96it/s]

train:  79%|██████████████████████▏     | 74848/94563 [12:20<03:15, 100.98it/s]

train:  79%|██████████████████████▏     | 74880/94563 [12:20<03:15, 100.91it/s]

train:  79%|██████████████████████▏     | 74912/94563 [12:20<03:14, 101.01it/s]

train:  79%|██████████████████████▏     | 74944/94563 [12:20<03:14, 100.92it/s]

train:  79%|██████████████████████▏     | 74976/94563 [12:21<03:14, 100.91it/s]

[train] Checkpoint saved at 75000/94563

train:  79%|███████████████████████      | 75008/94563 [12:21<03:24, 95.66it/s]

train:  79%|███████████████████████      | 75040/94563 [12:21<03:20, 97.55it/s]

train:  79%|███████████████████████      | 75072/94563 [12:22<03:17, 98.61it/s]

train:  79%|███████████████████████      | 75104/94563 [12:22<03:16, 99.27it/s]

train:  79%|███████████████████████      | 75136/94563 [12:22<03:14, 99.70it/s]

train:  79%|██████████████████████▎     | 75168/94563 [12:23<03:13, 100.04it/s]

train:  80%|██████████████████████▎     | 75200/94563 [12:23<03:13, 100.18it/s]

train:  80%|██████████████████████▎     | 75232/94563 [12:23<03:12, 100.50it/s]

train:  80%|██████████████████████▎     | 75264/94563 [12:24<03:11, 100.63it/s]

train:  80%|██████████████████████▎     | 75296/94563 [12:24<03:11, 100.81it/s]

train:  80%|██████████████████████▎     | 75328/94563 [12:24<03:10, 100.81it/s]

train:  80%|██████████████████████▎     | 75360/94563 [12:25<03:10, 100.97it/s]

train:  80%|██████████████████████▎     | 75392/94563 [12:25<03:09, 100.91it/s]

train:  80%|██████████████████████▎     | 75424/94563 [12:25<03:09, 100.92it/s]

train:  80%|██████████████████████▎     | 75456/94563 [12:26<03:09, 100.80it/s]

train:  80%|██████████████████████▎     | 75488/94563 [12:26<03:09, 100.91it/s]

train:  80%|██████████████████████▎     | 75520/94563 [12:26<03:08, 100.98it/s]

train:  80%|██████████████████████▎     | 75552/94563 [12:27<03:08, 100.99it/s]

train:  80%|██████████████████████▍     | 75584/94563 [12:27<03:07, 101.15it/s]

train:  80%|██████████████████████▍     | 75616/94563 [12:27<03:07, 101.14it/s]

train:  80%|██████████████████████▍     | 75648/94563 [12:27<03:07, 101.02it/s]

train:  80%|██████████████████████▍     | 75680/94563 [12:28<03:06, 101.18it/s]

train:  80%|██████████████████████▍     | 75712/94563 [12:28<03:06, 101.24it/s]

train:  80%|██████████████████████▍     | 75744/94563 [12:28<03:06, 100.71it/s]

train:  80%|██████████████████████▍     | 75776/94563 [12:29<03:06, 100.89it/s]

train:  80%|██████████████████████▍     | 75808/94563 [12:29<03:05, 100.96it/s]

train:  80%|██████████████████████▍     | 75840/94563 [12:29<03:05, 101.04it/s]

train:  80%|██████████████████████▍     | 75872/94563 [12:30<03:04, 101.11it/s]

train:  80%|██████████████████████▍     | 75904/94563 [12:30<03:04, 101.18it/s]

train:  80%|██████████████████████▍     | 75936/94563 [12:30<03:04, 101.07it/s]

train:  80%|██████████████████████▍     | 75968/94563 [12:31<03:03, 101.26it/s]

train:  80%|███████████████████████▎     | 76000/94563 [12:31<03:10, 97.52it/s]

[train] Checkpoint saved at 76000/94563

train:  80%|███████████████████████▎     | 76032/94563 [12:31<03:08, 98.39it/s]

train:  80%|███████████████████████▎     | 76064/94563 [12:32<03:05, 99.59it/s]

train:  80%|██████████████████████▌     | 76096/94563 [12:32<03:04, 100.24it/s]

train:  81%|██████████████████████▌     | 76128/94563 [12:32<03:03, 100.73it/s]

train:  81%|██████████████████████▌     | 76160/94563 [12:33<03:02, 100.75it/s]

train:  81%|██████████████████████▌     | 76192/94563 [12:33<03:01, 101.20it/s]

train:  81%|██████████████████████▌     | 76224/94563 [12:33<03:00, 101.58it/s]

train:  81%|██████████████████████▌     | 76256/94563 [12:34<03:00, 101.60it/s]

train:  81%|██████████████████████▌     | 76288/94563 [12:34<03:00, 101.52it/s]

train:  81%|██████████████████████▌     | 76320/94563 [12:34<03:00, 101.34it/s]

train:  81%|██████████████████████▌     | 76352/94563 [12:34<03:00, 101.13it/s]

train:  81%|██████████████████████▌     | 76384/94563 [12:35<03:00, 100.92it/s]

train:  81%|██████████████████████▋     | 76416/94563 [12:35<03:00, 100.80it/s]

train:  81%|██████████████████████▋     | 76448/94563 [12:35<03:00, 100.60it/s]

train:  81%|██████████████████████▋     | 76480/94563 [12:36<02:59, 100.65it/s]

train:  81%|██████████████████████▋     | 76512/94563 [12:36<02:59, 100.66it/s]

train:  81%|██████████████████████▋     | 76544/94563 [12:36<02:59, 100.52it/s]

train:  81%|██████████████████████▋     | 76576/94563 [12:37<02:59, 100.49it/s]

train:  81%|██████████████████████▋     | 76608/94563 [12:37<02:58, 100.43it/s]

train:  81%|██████████████████████▋     | 76640/94563 [12:37<02:58, 100.58it/s]

train:  81%|██████████████████████▋     | 76672/94563 [12:38<02:57, 100.63it/s]

train:  81%|██████████████████████▋     | 76704/94563 [12:38<02:57, 100.65it/s]

train:  81%|██████████████████████▋     | 76736/94563 [12:38<02:56, 100.87it/s]

train:  81%|██████████████████████▋     | 76768/94563 [12:39<02:56, 100.83it/s]

train:  81%|██████████████████████▋     | 76800/94563 [12:39<02:55, 100.98it/s]

train:  81%|██████████████████████▋     | 76832/94563 [12:39<02:55, 101.10it/s]

train:  81%|██████████████████████▊     | 76864/94563 [12:40<02:54, 101.16it/s]

train:  81%|██████████████████████▊     | 76896/94563 [12:40<02:54, 101.22it/s]

train:  81%|██████████████████████▊     | 76928/94563 [12:40<02:53, 101.51it/s]

train:  81%|██████████████████████▊     | 76960/94563 [12:41<02:53, 101.69it/s]

train:  81%|██████████████████████▊     | 76992/94563 [12:41<02:53, 101.46it/s]

[train] Checkpoint saved at 77000/94563

train:  81%|███████████████████████▌     | 77024/94563 [12:41<03:04, 95.14it/s]

train:  81%|███████████████████████▋     | 77056/94563 [12:42<02:59, 97.34it/s]

train:  82%|███████████████████████▋     | 77088/94563 [12:42<02:57, 98.70it/s]

train:  82%|███████████████████████▋     | 77120/94563 [12:42<02:55, 99.55it/s]

train:  82%|██████████████████████▊     | 77152/94563 [12:42<02:53, 100.23it/s]

train:  82%|██████████████████████▊     | 77184/94563 [12:43<02:53, 100.45it/s]

train:  82%|██████████████████████▊     | 77216/94563 [12:43<02:52, 100.66it/s]

train:  82%|██████████████████████▊     | 77248/94563 [12:43<02:51, 100.85it/s]

train:  82%|██████████████████████▉     | 77280/94563 [12:44<02:51, 100.88it/s]

train:  82%|██████████████████████▉     | 77312/94563 [12:44<02:50, 100.90it/s]

train:  82%|██████████████████████▉     | 77344/94563 [12:44<02:50, 101.00it/s]

train:  82%|██████████████████████▉     | 77376/94563 [12:45<02:50, 101.01it/s]

train:  82%|██████████████████████▉     | 77408/94563 [12:45<02:49, 101.29it/s]

train:  82%|██████████████████████▉     | 77440/94563 [12:45<02:48, 101.43it/s]

train:  82%|██████████████████████▉     | 77472/94563 [12:46<02:48, 101.31it/s]

train:  82%|██████████████████████▉     | 77504/94563 [12:46<02:48, 101.00it/s]

train:  82%|██████████████████████▉     | 77536/94563 [12:46<02:48, 100.83it/s]

train:  82%|██████████████████████▉     | 77568/94563 [12:47<02:48, 101.12it/s]

train:  82%|██████████████████████▉     | 77600/94563 [12:47<02:48, 100.81it/s]

train:  82%|██████████████████████▉     | 77632/94563 [12:47<02:48, 100.75it/s]

train:  82%|██████████████████████▉     | 77664/94563 [12:48<02:48, 100.46it/s]

train:  82%|███████████████████████     | 77696/94563 [12:48<02:47, 100.51it/s]

train:  82%|███████████████████████     | 77728/94563 [12:48<02:47, 100.45it/s]

train:  82%|███████████████████████     | 77760/94563 [12:48<02:46, 100.66it/s]

train:  82%|███████████████████████     | 77792/94563 [12:49<02:46, 100.82it/s]

train:  82%|███████████████████████     | 77824/94563 [12:49<02:46, 100.82it/s]

train:  82%|███████████████████████     | 77856/94563 [12:49<02:45, 100.67it/s]

train:  82%|███████████████████████     | 77888/94563 [12:50<02:45, 100.66it/s]

train:  82%|███████████████████████     | 77920/94563 [12:50<02:45, 100.62it/s]

train:  82%|███████████████████████     | 77952/94563 [12:50<02:45, 100.64it/s]

train:  82%|███████████████████████     | 77984/94563 [12:51<02:44, 100.78it/s]

[train] Checkpoint saved at 78000/94563

train:  83%|███████████████████████▉     | 78016/94563 [12:51<02:54, 95.01it/s]

train:  83%|███████████████████████▉     | 78048/94563 [12:51<02:50, 96.98it/s]

train:  83%|███████████████████████▉     | 78080/94563 [12:52<02:47, 98.36it/s]

train:  83%|███████████████████████▉     | 78112/94563 [12:52<02:45, 99.39it/s]

train:  83%|███████████████████████▉     | 78144/94563 [12:52<02:44, 99.91it/s]

train:  83%|███████████████████████▏    | 78176/94563 [12:53<02:43, 100.35it/s]

train:  83%|███████████████████████▏    | 78208/94563 [12:53<02:42, 100.70it/s]

train:  83%|███████████████████████▏    | 78240/94563 [12:53<02:42, 100.68it/s]

train:  83%|███████████████████████▏    | 78272/94563 [12:54<02:41, 100.83it/s]

train:  83%|███████████████████████▏    | 78304/94563 [12:54<02:41, 100.91it/s]

train:  83%|███████████████████████▏    | 78336/94563 [12:54<02:40, 100.87it/s]

train:  83%|███████████████████████▏    | 78368/94563 [12:55<02:40, 100.90it/s]

train:  83%|███████████████████████▏    | 78400/94563 [12:55<02:40, 100.94it/s]

train:  83%|███████████████████████▏    | 78432/94563 [12:55<02:39, 100.87it/s]

train:  83%|███████████████████████▏    | 78464/94563 [12:56<02:39, 100.99it/s]

train:  83%|███████████████████████▏    | 78496/94563 [12:56<02:39, 100.90it/s]

train:  83%|███████████████████████▎    | 78528/94563 [12:56<02:38, 101.01it/s]

train:  83%|███████████████████████▎    | 78560/94563 [12:56<02:38, 101.00it/s]

train:  83%|███████████████████████▎    | 78592/94563 [12:57<02:38, 100.98it/s]

train:  83%|███████████████████████▎    | 78624/94563 [12:57<02:37, 101.07it/s]

train:  83%|███████████████████████▎    | 78656/94563 [12:57<02:37, 101.21it/s]

train:  83%|███████████████████████▎    | 78688/94563 [12:58<02:36, 101.18it/s]

train:  83%|███████████████████████▎    | 78720/94563 [12:58<02:36, 101.20it/s]

train:  83%|███████████████████████▎    | 78752/94563 [12:58<02:36, 101.09it/s]

train:  83%|███████████████████████▎    | 78784/94563 [12:59<02:36, 100.98it/s]

train:  83%|███████████████████████▎    | 78816/94563 [12:59<02:35, 101.07it/s]

train:  83%|███████████████████████▎    | 78848/94563 [12:59<02:35, 101.16it/s]

train:  83%|███████████████████████▎    | 78880/94563 [13:00<02:35, 101.01it/s]

train:  83%|███████████████████████▎    | 78912/94563 [13:00<02:34, 101.03it/s]

train:  83%|███████████████████████▍    | 78944/94563 [13:00<02:34, 101.07it/s]

train:  84%|███████████████████████▍    | 78976/94563 [13:01<02:34, 101.15it/s]

train:  84%|███████████████████████▍    | 79007/94563 [13:01<02:03, 125.99it/s]

[train] Checkpoint saved at 79000/94563

train:  84%|███████████████████████▍    | 79024/94563 [13:01<02:31, 102.25it/s]

train:  84%|████████████████████████▏    | 79040/94563 [13:01<02:57, 87.53it/s]

train:  84%|████████████████████████▏    | 79072/94563 [13:02<02:47, 92.32it/s]

train:  84%|████████████████████████▎    | 79104/94563 [13:02<02:42, 95.32it/s]

train:  84%|████████████████████████▎    | 79136/94563 [13:02<02:38, 97.10it/s]

train:  84%|████████████████████████▎    | 79168/94563 [13:03<02:36, 98.40it/s]

train:  84%|████████████████████████▎    | 79200/94563 [13:03<02:34, 99.14it/s]

train:  84%|████████████████████████▎    | 79232/94563 [13:03<02:33, 99.69it/s]

train:  84%|████████████████████████▎    | 79264/94563 [13:04<02:34, 99.15it/s]

train:  84%|████████████████████████▎    | 79296/94563 [13:04<02:32, 99.87it/s]

train:  84%|███████████████████████▍    | 79328/94563 [13:04<02:31, 100.30it/s]

train:  84%|███████████████████████▍    | 79360/94563 [13:04<02:31, 100.49it/s]

train:  84%|███████████████████████▌    | 79392/94563 [13:05<02:30, 100.60it/s]

train:  84%|███████████████████████▌    | 79424/94563 [13:05<02:30, 100.67it/s]

train:  84%|███████████████████████▌    | 79456/94563 [13:05<02:29, 100.75it/s]

train:  84%|███████████████████████▌    | 79488/94563 [13:06<02:29, 100.61it/s]

train:  84%|███████████████████████▌    | 79520/94563 [13:06<02:29, 100.78it/s]

train:  84%|███████████████████████▌    | 79552/94563 [13:06<02:28, 101.04it/s]

train:  84%|███████████████████████▌    | 79584/94563 [13:07<02:28, 101.12it/s]

train:  84%|███████████████████████▌    | 79616/94563 [13:07<02:27, 101.03it/s]

train:  84%|███████████████████████▌    | 79648/94563 [13:07<02:27, 101.07it/s]

train:  84%|███████████████████████▌    | 79680/94563 [13:08<02:27, 100.99it/s]

train:  84%|███████████████████████▌    | 79712/94563 [13:08<02:27, 100.88it/s]

train:  84%|███████████████████████▌    | 79744/94563 [13:08<02:26, 100.85it/s]

train:  84%|███████████████████████▌    | 79776/94563 [13:09<02:26, 100.91it/s]

train:  84%|███████████████████████▋    | 79808/94563 [13:09<02:26, 100.92it/s]

train:  84%|███████████████████████▋    | 79840/94563 [13:09<02:26, 100.73it/s]

train:  84%|███████████████████████▋    | 79872/94563 [13:10<02:26, 100.61it/s]

train:  84%|███████████████████████▋    | 79904/94563 [13:10<02:25, 100.79it/s]

train:  85%|███████████████████████▋    | 79936/94563 [13:10<02:25, 100.66it/s]

train:  85%|███████████████████████▋    | 79968/94563 [13:10<02:24, 100.80it/s]

train:  85%|████████████████████████▌    | 80000/94563 [13:11<02:30, 96.90it/s]

[train] Checkpoint saved at 80000/94563

train:  85%|████████████████████████▌    | 80032/94563 [13:11<02:30, 96.86it/s]

train:  85%|████████████████████████▌    | 80064/94563 [13:11<02:27, 98.56it/s]

train:  85%|████████████████████████▌    | 80096/94563 [13:12<02:25, 99.42it/s]

train:  85%|███████████████████████▋    | 80128/94563 [13:12<02:24, 100.13it/s]

train:  85%|███████████████████████▋    | 80160/94563 [13:12<02:23, 100.60it/s]

train:  85%|███████████████████████▋    | 80192/94563 [13:13<02:22, 100.67it/s]

train:  85%|███████████████████████▊    | 80224/94563 [13:13<02:22, 100.79it/s]

train:  85%|███████████████████████▊    | 80256/94563 [13:13<02:21, 100.77it/s]

train:  85%|███████████████████████▊    | 80288/94563 [13:14<02:21, 100.77it/s]

train:  85%|███████████████████████▊    | 80320/94563 [13:14<02:21, 100.74it/s]

train:  85%|███████████████████████▊    | 80352/94563 [13:14<02:20, 100.87it/s]

train:  85%|███████████████████████▊    | 80384/94563 [13:15<02:19, 101.44it/s]

train:  85%|███████████████████████▊    | 80416/94563 [13:15<02:19, 101.68it/s]

train:  85%|███████████████████████▊    | 80448/94563 [13:15<02:19, 101.44it/s]

train:  85%|███████████████████████▊    | 80480/94563 [13:16<02:19, 101.25it/s]

train:  85%|███████████████████████▊    | 80512/94563 [13:16<02:19, 100.97it/s]

train:  85%|███████████████████████▊    | 80544/94563 [13:16<02:19, 100.77it/s]

train:  85%|███████████████████████▊    | 80576/94563 [13:17<02:19, 100.53it/s]

train:  85%|███████████████████████▊    | 80608/94563 [13:17<02:18, 100.50it/s]

train:  85%|███████████████████████▉    | 80640/94563 [13:17<02:18, 100.36it/s]

train:  85%|███████████████████████▉    | 80672/94563 [13:18<02:18, 100.25it/s]

train:  85%|███████████████████████▉    | 80704/94563 [13:18<02:17, 100.72it/s]

train:  85%|███████████████████████▉    | 80736/94563 [13:18<02:17, 100.53it/s]

train:  85%|███████████████████████▉    | 80768/94563 [13:18<02:17, 100.60it/s]

train:  85%|████████████████████████▊    | 80800/94563 [13:19<02:18, 99.52it/s]

train:  85%|████████████████████████▊    | 80832/94563 [13:19<02:17, 99.76it/s]

train:  86%|███████████████████████▉    | 80864/94563 [13:19<02:16, 100.20it/s]

train:  86%|███████████████████████▉    | 80896/94563 [13:20<02:16, 100.39it/s]

train:  86%|███████████████████████▉    | 80928/94563 [13:20<02:16, 100.03it/s]

train:  86%|████████████████████████▊    | 80960/94563 [13:20<02:16, 99.76it/s]

train:  86%|████████████████████████▊    | 80992/94563 [13:21<02:16, 99.33it/s]

train:  86%|███████████████████████▉    | 81009/94563 [13:21<02:06, 107.49it/s]

[train] Checkpoint saved at 81000/94563

train:  86%|████████████████████████▊    | 81024/94563 [13:21<02:32, 88.67it/s]

train:  86%|████████████████████████▊    | 81056/94563 [13:21<02:25, 92.72it/s]

train:  86%|████████████████████████▊    | 81088/94563 [13:22<02:21, 95.22it/s]

train:  86%|████████████████████████▉    | 81120/94563 [13:22<02:19, 96.35it/s]

train:  86%|████████████████████████▉    | 81152/94563 [13:22<02:18, 96.63it/s]

train:  86%|████████████████████████▉    | 81184/94563 [13:23<02:17, 97.39it/s]

train:  86%|████████████████████████▉    | 81216/94563 [13:23<02:15, 98.21it/s]

train:  86%|████████████████████████▉    | 81248/94563 [13:23<02:14, 98.91it/s]

train:  86%|████████████████████████▉    | 81280/94563 [13:24<02:13, 99.47it/s]

train:  86%|████████████████████████▉    | 81312/94563 [13:24<02:12, 99.93it/s]

train:  86%|████████████████████████    | 81344/94563 [13:24<02:11, 100.29it/s]

train:  86%|████████████████████████    | 81376/94563 [13:25<02:11, 100.16it/s]

train:  86%|████████████████████████▉    | 81408/94563 [13:25<02:11, 99.94it/s]

train:  86%|████████████████████████▉    | 81440/94563 [13:25<02:12, 98.85it/s]

train:  86%|████████████████████████▉    | 81472/94563 [13:26<02:12, 98.89it/s]

train:  86%|████████████████████████▉    | 81504/94563 [13:26<02:12, 98.61it/s]

train:  86%|█████████████████████████    | 81536/94563 [13:26<02:12, 98.47it/s]

train:  86%|█████████████████████████    | 81568/94563 [13:27<02:11, 98.52it/s]

train:  86%|█████████████████████████    | 81600/94563 [13:27<02:11, 98.91it/s]

train:  86%|█████████████████████████    | 81632/94563 [13:27<02:10, 98.86it/s]

train:  86%|█████████████████████████    | 81664/94563 [13:28<02:09, 99.54it/s]

train:  86%|████████████████████████▏   | 81696/94563 [13:28<02:08, 100.30it/s]

train:  86%|████████████████████████▏   | 81728/94563 [13:28<02:07, 100.93it/s]

train:  86%|████████████████████████▏   | 81760/94563 [13:28<02:06, 100.97it/s]

train:  86%|████████████████████████▏   | 81792/94563 [13:29<02:06, 100.94it/s]

train:  87%|████████████████████████▏   | 81824/94563 [13:29<02:06, 100.63it/s]

train:  87%|████████████████████████▏   | 81856/94563 [13:29<02:06, 100.24it/s]

train:  87%|████████████████████████▏   | 81888/94563 [13:30<02:06, 100.02it/s]

train:  87%|█████████████████████████    | 81920/94563 [13:30<02:06, 99.69it/s]

train:  87%|█████████████████████████▏   | 81952/94563 [13:30<02:06, 99.80it/s]

train:  87%|████████████████████████▎   | 81984/94563 [13:31<02:05, 100.22it/s]

train:  87%|████████████████████████▎   | 82006/94563 [13:31<01:49, 114.36it/s]

[train] Checkpoint saved at 82000/94563

train:  87%|█████████████████████████▏   | 82020/94563 [13:31<02:15, 92.82it/s]

train:  87%|█████████████████████████▏   | 82048/94563 [13:31<02:15, 92.50it/s]

train:  87%|█████████████████████████▏   | 82080/94563 [13:32<02:10, 95.54it/s]

train:  87%|█████████████████████████▏   | 82112/94563 [13:32<02:07, 97.63it/s]

train:  87%|█████████████████████████▏   | 82144/94563 [13:32<02:05, 98.85it/s]

train:  87%|█████████████████████████▏   | 82176/94563 [13:33<02:04, 99.70it/s]

train:  87%|████████████████████████▎   | 82208/94563 [13:33<02:03, 100.07it/s]

train:  87%|████████████████████████▎   | 82240/94563 [13:33<02:02, 100.47it/s]

train:  87%|████████████████████████▎   | 82272/94563 [13:34<02:01, 100.91it/s]

train:  87%|████████████████████████▎   | 82304/94563 [13:34<02:01, 101.02it/s]

train:  87%|████████████████████████▍   | 82336/94563 [13:34<02:01, 101.04it/s]

train:  87%|████████████████████████▍   | 82368/94563 [13:35<02:00, 100.98it/s]

train:  87%|████████████████████████▍   | 82400/94563 [13:35<02:00, 101.21it/s]

train:  87%|████████████████████████▍   | 82432/94563 [13:35<02:00, 100.81it/s]

train:  87%|████████████████████████▍   | 82464/94563 [13:36<01:59, 100.87it/s]

train:  87%|████████████████████████▍   | 82496/94563 [13:36<01:59, 100.93it/s]

train:  87%|████████████████████████▍   | 82528/94563 [13:36<01:59, 100.87it/s]

train:  87%|████████████████████████▍   | 82560/94563 [13:36<01:58, 101.04it/s]

train:  87%|████████████████████████▍   | 82592/94563 [13:37<01:58, 101.17it/s]

train:  87%|████████████████████████▍   | 82624/94563 [13:37<01:58, 101.07it/s]

train:  87%|████████████████████████▍   | 82656/94563 [13:37<01:58, 100.82it/s]

train:  87%|████████████████████████▍   | 82688/94563 [13:38<01:58, 100.61it/s]

train:  87%|████████████████████████▍   | 82720/94563 [13:38<01:58, 100.16it/s]

train:  88%|████████████████████████▌   | 82752/94563 [13:38<01:57, 100.11it/s]

train:  88%|████████████████████████▌   | 82784/94563 [13:39<01:57, 100.18it/s]

train:  88%|████████████████████████▌   | 82816/94563 [13:39<01:57, 100.10it/s]

train:  88%|████████████████████████▌   | 82848/94563 [13:39<01:56, 100.22it/s]

train:  88%|████████████████████████▌   | 82880/94563 [13:40<01:56, 100.46it/s]

train:  88%|████████████████████████▌   | 82912/94563 [13:40<01:55, 100.53it/s]

train:  88%|████████████████████████▌   | 82944/94563 [13:40<01:55, 100.43it/s]

train:  88%|█████████████████████████▍   | 82976/94563 [13:41<01:55, 99.94it/s]

train:  88%|████████████████████████▌   | 83007/94563 [13:41<01:32, 124.71it/s]

[train] Checkpoint saved at 83000/94563

train:  88%|████████████████████████▌   | 83024/94563 [13:41<01:54, 100.49it/s]

train:  88%|█████████████████████████▍   | 83040/94563 [13:41<02:14, 85.57it/s]

train:  88%|█████████████████████████▍   | 83072/94563 [13:42<02:07, 89.80it/s]

train:  88%|█████████████████████████▍   | 83104/94563 [13:42<02:03, 92.48it/s]

train:  88%|█████████████████████████▍   | 83136/94563 [13:42<02:01, 94.12it/s]

train:  88%|█████████████████████████▌   | 83168/94563 [13:43<01:59, 95.62it/s]

train:  88%|█████████████████████████▌   | 83200/94563 [13:43<01:57, 96.64it/s]

train:  88%|█████████████████████████▌   | 83232/94563 [13:43<01:56, 97.22it/s]

train:  88%|█████████████████████████▌   | 83264/94563 [13:44<01:55, 97.62it/s]

train:  88%|█████████████████████████▌   | 83296/94563 [13:44<01:55, 97.60it/s]

train:  88%|█████████████████████████▌   | 83328/94563 [13:44<01:56, 96.70it/s]

train:  88%|█████████████████████████▌   | 83360/94563 [13:45<01:55, 97.23it/s]

train:  88%|█████████████████████████▌   | 83392/94563 [13:45<01:54, 97.32it/s]

train:  88%|█████████████████████████▌   | 83424/94563 [13:45<01:54, 97.37it/s]

train:  88%|█████████████████████████▌   | 83456/94563 [13:46<01:53, 97.46it/s]

train:  88%|█████████████████████████▌   | 83488/94563 [13:46<01:53, 97.42it/s]

train:  88%|█████████████████████████▌   | 83520/94563 [13:46<01:53, 97.66it/s]

train:  88%|█████████████████████████▌   | 83552/94563 [13:47<01:52, 97.93it/s]

train:  88%|█████████████████████████▋   | 83584/94563 [13:47<01:51, 98.19it/s]

train:  88%|█████████████████████████▋   | 83616/94563 [13:47<01:51, 98.59it/s]

train:  88%|█████████████████████████▋   | 83648/94563 [13:48<01:50, 99.07it/s]

train:  88%|█████████████████████████▋   | 83680/94563 [13:48<01:49, 99.72it/s]

train:  89%|████████████████████████▊   | 83712/94563 [13:48<01:48, 100.21it/s]

train:  89%|████████████████████████▊   | 83744/94563 [13:48<01:47, 100.70it/s]

train:  89%|████████████████████████▊   | 83776/94563 [13:49<01:46, 101.33it/s]

train:  89%|████████████████████████▊   | 83808/94563 [13:49<01:45, 101.56it/s]

train:  89%|████████████████████████▊   | 83840/94563 [13:49<01:45, 101.79it/s]

train:  89%|████████████████████████▊   | 83872/94563 [13:50<01:44, 101.98it/s]

train:  89%|████████████████████████▊   | 83904/94563 [13:50<01:44, 102.07it/s]

train:  89%|████████████████████████▊   | 83936/94563 [13:50<01:44, 102.17it/s]

train:  89%|████████████████████████▊   | 83968/94563 [13:51<01:43, 102.20it/s]

train:  89%|█████████████████████████▊   | 84000/94563 [13:51<01:48, 97.77it/s]

[train] Checkpoint saved at 84000/94563

train:  89%|█████████████████████████▊   | 84032/94563 [13:51<01:49, 96.36it/s]

train:  89%|█████████████████████████▊   | 84064/94563 [13:52<01:46, 98.19it/s]

train:  89%|█████████████████████████▊   | 84096/94563 [13:52<01:45, 99.38it/s]

train:  89%|████████████████████████▉   | 84128/94563 [13:52<01:43, 100.42it/s]

train:  89%|████████████████████████▉   | 84160/94563 [13:53<01:42, 101.06it/s]

train:  89%|████████████████████████▉   | 84192/94563 [13:53<01:42, 101.47it/s]

train:  89%|████████████████████████▉   | 84224/94563 [13:53<01:41, 101.76it/s]

train:  89%|████████████████████████▉   | 84256/94563 [13:54<01:41, 101.97it/s]

train:  89%|████████████████████████▉   | 84288/94563 [13:54<01:40, 102.04it/s]

train:  89%|████████████████████████▉   | 84320/94563 [13:54<01:40, 102.13it/s]

train:  89%|████████████████████████▉   | 84352/94563 [13:54<01:39, 102.15it/s]

train:  89%|████████████████████████▉   | 84384/94563 [13:55<01:39, 102.00it/s]

train:  89%|████████████████████████▉   | 84416/94563 [13:55<01:39, 101.70it/s]

train:  89%|█████████████████████████   | 84448/94563 [13:55<01:39, 101.37it/s]

train:  89%|█████████████████████████   | 84480/94563 [13:56<01:39, 101.05it/s]

train:  89%|█████████████████████████   | 84512/94563 [13:56<01:39, 100.99it/s]

train:  89%|█████████████████████████   | 84544/94563 [13:56<01:39, 100.90it/s]

train:  89%|█████████████████████████   | 84576/94563 [13:57<01:39, 100.87it/s]

train:  89%|█████████████████████████   | 84608/94563 [13:57<01:38, 100.68it/s]

train:  90%|█████████████████████████   | 84640/94563 [13:57<01:38, 100.63it/s]

train:  90%|█████████████████████████   | 84672/94563 [13:58<01:38, 100.40it/s]

train:  90%|█████████████████████████   | 84704/94563 [13:58<01:38, 100.46it/s]

train:  90%|█████████████████████████   | 84736/94563 [13:58<01:38, 100.21it/s]

train:  90%|█████████████████████████   | 84768/94563 [13:59<01:37, 100.31it/s]

train:  90%|█████████████████████████   | 84800/94563 [13:59<01:37, 100.39it/s]

train:  90%|█████████████████████████   | 84832/94563 [13:59<01:36, 100.40it/s]

train:  90%|█████████████████████████▏  | 84864/94563 [14:00<01:36, 100.44it/s]

train:  90%|█████████████████████████▏  | 84896/94563 [14:00<01:36, 100.50it/s]

train:  90%|█████████████████████████▏  | 84928/94563 [14:00<01:35, 100.54it/s]

train:  90%|█████████████████████████▏  | 84960/94563 [14:01<01:35, 100.51it/s]

train:  90%|█████████████████████████▏  | 84992/94563 [14:01<01:35, 100.52it/s]

[train] Checkpoint saved at 85000/94563

train:  90%|██████████████████████████   | 85024/94563 [14:01<01:39, 95.80it/s]

train:  90%|██████████████████████████   | 85056/94563 [14:02<01:37, 97.61it/s]

train:  90%|██████████████████████████   | 85088/94563 [14:02<01:36, 98.57it/s]

train:  90%|██████████████████████████   | 85120/94563 [14:02<01:34, 99.54it/s]

train:  90%|█████████████████████████▏  | 85152/94563 [14:02<01:33, 100.15it/s]

train:  90%|██████████████████████████   | 85184/94563 [14:03<01:33, 99.97it/s]

train:  90%|█████████████████████████▏  | 85216/94563 [14:03<01:33, 100.32it/s]

train:  90%|█████████████████████████▏  | 85248/94563 [14:03<01:32, 100.45it/s]

train:  90%|█████████████████████████▎  | 85280/94563 [14:04<01:32, 100.43it/s]

train:  90%|█████████████████████████▎  | 85312/94563 [14:04<01:32, 100.54it/s]

train:  90%|█████████████████████████▎  | 85344/94563 [14:04<01:31, 100.84it/s]

train:  90%|█████████████████████████▎  | 85376/94563 [14:05<01:30, 101.05it/s]

train:  90%|█████████████████████████▎  | 85408/94563 [14:05<01:31, 100.46it/s]

train:  90%|█████████████████████████▎  | 85440/94563 [14:05<01:30, 100.68it/s]

train:  90%|█████████████████████████▎  | 85472/94563 [14:06<01:30, 101.00it/s]

train:  90%|█████████████████████████▎  | 85504/94563 [14:06<01:29, 101.24it/s]

train:  90%|█████████████████████████▎  | 85536/94563 [14:06<01:29, 101.27it/s]

train:  90%|█████████████████████████▎  | 85568/94563 [14:07<01:28, 101.30it/s]

train:  91%|█████████████████████████▎  | 85600/94563 [14:07<01:28, 101.21it/s]

train:  91%|█████████████████████████▎  | 85632/94563 [14:07<01:28, 101.25it/s]

train:  91%|█████████████████████████▎  | 85664/94563 [14:08<01:27, 101.13it/s]

train:  91%|█████████████████████████▎  | 85696/94563 [14:08<01:27, 100.99it/s]

train:  91%|█████████████████████████▍  | 85728/94563 [14:08<01:27, 101.04it/s]

train:  91%|█████████████████████████▍  | 85760/94563 [14:09<01:27, 100.91it/s]

train:  91%|█████████████████████████▍  | 85792/94563 [14:09<01:26, 100.92it/s]

train:  91%|█████████████████████████▍  | 85824/94563 [14:09<01:26, 101.01it/s]

train:  91%|█████████████████████████▍  | 85856/94563 [14:09<01:26, 101.04it/s]

train:  91%|█████████████████████████▍  | 85888/94563 [14:10<01:25, 100.95it/s]

train:  91%|█████████████████████████▍  | 85920/94563 [14:10<01:25, 101.00it/s]

train:  91%|█████████████████████████▍  | 85952/94563 [14:10<01:25, 100.99it/s]

train:  91%|█████████████████████████▍  | 85984/94563 [14:11<01:24, 101.10it/s]

[train] Checkpoint saved at 86000/94563

train:  91%|██████████████████████████▍  | 86016/94563 [14:11<01:29, 95.09it/s]

train:  91%|██████████████████████████▍  | 86048/94563 [14:11<01:27, 97.18it/s]

train:  91%|██████████████████████████▍  | 86080/94563 [14:12<01:25, 98.65it/s]

train:  91%|██████████████████████████▍  | 86112/94563 [14:12<01:24, 99.48it/s]

train:  91%|██████████████████████████▍  | 86144/94563 [14:12<01:24, 99.99it/s]

train:  91%|█████████████████████████▌  | 86176/94563 [14:13<01:23, 100.25it/s]

train:  91%|█████████████████████████▌  | 86208/94563 [14:13<01:23, 100.30it/s]

train:  91%|█████████████████████████▌  | 86240/94563 [14:13<01:22, 100.50it/s]

train:  91%|█████████████████████████▌  | 86272/94563 [14:14<01:22, 100.57it/s]

train:  91%|█████████████████████████▌  | 86304/94563 [14:14<01:22, 100.52it/s]

train:  91%|█████████████████████████▌  | 86336/94563 [14:14<01:21, 100.90it/s]

train:  91%|█████████████████████████▌  | 86368/94563 [14:15<01:21, 100.99it/s]

train:  91%|█████████████████████████▌  | 86400/94563 [14:15<01:20, 100.79it/s]

train:  91%|█████████████████████████▌  | 86432/94563 [14:15<01:20, 100.81it/s]

train:  91%|█████████████████████████▌  | 86464/94563 [14:16<01:20, 101.16it/s]

train:  91%|█████████████████████████▌  | 86496/94563 [14:16<01:19, 101.27it/s]

train:  92%|█████████████████████████▌  | 86528/94563 [14:16<01:19, 101.13it/s]

train:  92%|█████████████████████████▋  | 86560/94563 [14:16<01:18, 101.34it/s]

train:  92%|█████████████████████████▋  | 86592/94563 [14:17<01:18, 101.35it/s]

train:  92%|█████████████████████████▋  | 86624/94563 [14:17<01:18, 101.56it/s]

train:  92%|█████████████████████████▋  | 86656/94563 [14:17<01:17, 101.50it/s]

train:  92%|█████████████████████████▋  | 86688/94563 [14:18<01:17, 101.34it/s]

train:  92%|█████████████████████████▋  | 86720/94563 [14:18<01:17, 101.20it/s]

train:  92%|█████████████████████████▋  | 86752/94563 [14:18<01:17, 100.83it/s]

train:  92%|█████████████████████████▋  | 86784/94563 [14:19<01:17, 100.81it/s]

train:  92%|█████████████████████████▋  | 86816/94563 [14:19<01:17, 100.58it/s]

train:  92%|█████████████████████████▋  | 86848/94563 [14:19<01:16, 100.58it/s]

train:  92%|█████████████████████████▋  | 86880/94563 [14:20<01:16, 100.09it/s]

train:  92%|█████████████████████████▋  | 86912/94563 [14:20<01:16, 100.22it/s]

train:  92%|█████████████████████████▋  | 86944/94563 [14:20<01:16, 100.21it/s]

train:  92%|█████████████████████████▊  | 86976/94563 [14:21<01:15, 100.22it/s]

[train] Checkpoint saved at 87000/94563

train:  92%|██████████████████████████▋  | 87008/94563 [14:21<01:18, 96.14it/s]

train:  92%|██████████████████████████▋  | 87040/94563 [14:21<01:17, 97.68it/s]

train:  92%|██████████████████████████▋  | 87072/94563 [14:22<01:15, 98.68it/s]

train:  92%|██████████████████████████▋  | 87104/94563 [14:22<01:15, 99.25it/s]

train:  92%|██████████████████████████▋  | 87136/94563 [14:22<01:14, 99.66it/s]

train:  92%|██████████████████████████▋  | 87168/94563 [14:23<01:14, 99.75it/s]

train:  92%|██████████████████████████▋  | 87200/94563 [14:23<01:13, 99.96it/s]

train:  92%|██████████████████████████▊  | 87232/94563 [14:23<01:13, 99.95it/s]

train:  92%|█████████████████████████▊  | 87264/94563 [14:24<01:12, 100.17it/s]

train:  92%|█████████████████████████▊  | 87296/94563 [14:24<01:12, 100.13it/s]

train:  92%|█████████████████████████▊  | 87328/94563 [14:24<01:12, 100.16it/s]

train:  92%|█████████████████████████▊  | 87360/94563 [14:24<01:11, 100.19it/s]

train:  92%|█████████████████████████▉  | 87392/94563 [14:25<01:11, 100.31it/s]

train:  92%|█████████████████████████▉  | 87424/94563 [14:25<01:11, 100.23it/s]

train:  92%|██████████████████████████▊  | 87456/94563 [14:25<01:11, 99.85it/s]

train:  93%|█████████████████████████▉  | 87488/94563 [14:26<01:10, 100.13it/s]

train:  93%|█████████████████████████▉  | 87520/94563 [14:26<01:10, 100.43it/s]

train:  93%|█████████████████████████▉  | 87552/94563 [14:26<01:09, 100.74it/s]

train:  93%|█████████████████████████▉  | 87584/94563 [14:27<01:09, 100.85it/s]

train:  93%|█████████████████████████▉  | 87616/94563 [14:27<01:08, 101.02it/s]

train:  93%|█████████████████████████▉  | 87648/94563 [14:27<01:08, 101.15it/s]

train:  93%|█████████████████████████▉  | 87680/94563 [14:28<01:08, 101.15it/s]

train:  93%|█████████████████████████▉  | 87712/94563 [14:28<01:07, 101.20it/s]

train:  93%|█████████████████████████▉  | 87744/94563 [14:28<01:07, 101.21it/s]

train:  93%|█████████████████████████▉  | 87776/94563 [14:29<01:07, 101.22it/s]

train:  93%|█████████████████████████▉  | 87808/94563 [14:29<01:06, 101.31it/s]

train:  93%|██████████████████████████  | 87840/94563 [14:29<01:06, 101.38it/s]

train:  93%|██████████████████████████  | 87872/94563 [14:30<01:06, 101.33it/s]

train:  93%|██████████████████████████  | 87904/94563 [14:30<01:05, 101.10it/s]

train:  93%|██████████████████████████  | 87936/94563 [14:30<01:05, 101.22it/s]

train:  93%|██████████████████████████  | 87968/94563 [14:30<01:05, 101.21it/s]

train:  93%|██████████████████████████▉  | 88000/94563 [14:31<01:07, 97.23it/s]

[train] Checkpoint saved at 88000/94563

train:  93%|██████████████████████████▉  | 88032/94563 [14:31<01:06, 98.00it/s]

train:  93%|███████████████████████████  | 88064/94563 [14:31<01:05, 99.20it/s]

train:  93%|██████████████████████████  | 88096/94563 [14:32<01:04, 100.19it/s]

train:  93%|██████████████████████████  | 88128/94563 [14:32<01:03, 100.78it/s]

train:  93%|██████████████████████████  | 88160/94563 [14:32<01:03, 100.83it/s]

train:  93%|██████████████████████████  | 88192/94563 [14:33<01:03, 100.89it/s]

train:  93%|██████████████████████████  | 88224/94563 [14:33<01:02, 100.83it/s]

train:  93%|██████████████████████████▏ | 88256/94563 [14:33<01:02, 100.86it/s]

train:  93%|██████████████████████████▏ | 88288/94563 [14:34<01:02, 100.79it/s]

train:  93%|██████████████████████████▏ | 88320/94563 [14:34<01:01, 100.78it/s]

train:  93%|██████████████████████████▏ | 88352/94563 [14:34<01:01, 100.70it/s]

train:  93%|██████████████████████████▏ | 88384/94563 [14:35<01:01, 100.71it/s]

train:  93%|██████████████████████████▏ | 88416/94563 [14:35<01:00, 100.77it/s]

train:  94%|██████████████████████████▏ | 88448/94563 [14:35<01:00, 100.79it/s]

train:  94%|██████████████████████████▏ | 88480/94563 [14:36<01:00, 100.87it/s]

train:  94%|██████████████████████████▏ | 88512/94563 [14:36<00:59, 100.94it/s]

train:  94%|██████████████████████████▏ | 88544/94563 [14:36<00:59, 101.06it/s]

train:  94%|██████████████████████████▏ | 88576/94563 [14:37<00:59, 100.86it/s]

train:  94%|██████████████████████████▏ | 88608/94563 [14:37<00:58, 100.97it/s]

train:  94%|██████████████████████████▏ | 88640/94563 [14:37<00:58, 100.98it/s]

train:  94%|██████████████████████████▎ | 88672/94563 [14:38<00:58, 100.94it/s]

train:  94%|██████████████████████████▎ | 88704/94563 [14:38<00:58, 101.01it/s]

train:  94%|██████████████████████████▎ | 88736/94563 [14:38<00:57, 101.16it/s]

train:  94%|██████████████████████████▎ | 88768/94563 [14:38<00:57, 101.09it/s]

train:  94%|██████████████████████████▎ | 88800/94563 [14:39<00:57, 100.85it/s]

train:  94%|██████████████████████████▎ | 88832/94563 [14:39<00:56, 100.86it/s]

train:  94%|██████████████████████████▎ | 88864/94563 [14:39<00:56, 101.10it/s]

train:  94%|██████████████████████████▎ | 88896/94563 [14:40<00:55, 101.24it/s]

train:  94%|██████████████████████████▎ | 88928/94563 [14:40<00:55, 101.51it/s]

train:  94%|██████████████████████████▎ | 88960/94563 [14:40<00:55, 101.42it/s]

train:  94%|██████████████████████████▎ | 88992/94563 [14:41<00:55, 101.01it/s]

train:  94%|██████████████████████████▎ | 89022/94563 [14:41<00:44, 124.73it/s]

[train] Checkpoint saved at 89000/94563

train:  94%|██████████████████████████▎ | 89039/94563 [14:41<00:54, 101.26it/s]

train:  94%|███████████████████████████▎ | 89056/94563 [14:41<01:03, 87.34it/s]

train:  94%|███████████████████████████▎ | 89088/94563 [14:42<00:59, 91.79it/s]

train:  94%|███████████████████████████▎ | 89120/94563 [14:42<00:57, 94.54it/s]

train:  94%|███████████████████████████▎ | 89152/94563 [14:42<00:56, 96.33it/s]

train:  94%|███████████████████████████▎ | 89184/94563 [14:43<00:55, 97.60it/s]

train:  94%|███████████████████████████▎ | 89216/94563 [14:43<00:54, 98.31it/s]

train:  94%|███████████████████████████▎ | 89248/94563 [14:43<00:53, 98.76it/s]

train:  94%|███████████████████████████▍ | 89280/94563 [14:44<00:53, 99.26it/s]

train:  94%|███████████████████████████▍ | 89312/94563 [14:44<00:52, 99.26it/s]

train:  94%|███████████████████████████▍ | 89344/94563 [14:44<00:52, 99.62it/s]

train:  95%|███████████████████████████▍ | 89376/94563 [14:45<00:51, 99.79it/s]

train:  95%|███████████████████████████▍ | 89408/94563 [14:45<00:51, 99.90it/s]

train:  95%|██████████████████████████▍ | 89440/94563 [14:45<00:51, 100.07it/s]

train:  95%|██████████████████████████▍ | 89472/94563 [14:46<00:50, 100.16it/s]

train:  95%|██████████████████████████▌ | 89504/94563 [14:46<00:50, 100.34it/s]

train:  95%|██████████████████████████▌ | 89536/94563 [14:46<00:50, 100.45it/s]

train:  95%|██████████████████████████▌ | 89568/94563 [14:46<00:49, 100.59it/s]

train:  95%|██████████████████████████▌ | 89600/94563 [14:47<00:49, 100.87it/s]

train:  95%|██████████████████████████▌ | 89632/94563 [14:47<00:48, 101.04it/s]

train:  95%|██████████████████████████▌ | 89664/94563 [14:47<00:48, 101.07it/s]

train:  95%|██████████████████████████▌ | 89696/94563 [14:48<00:48, 101.09it/s]

train:  95%|██████████████████████████▌ | 89728/94563 [14:48<00:47, 101.07it/s]

train:  95%|██████████████████████████▌ | 89760/94563 [14:48<00:47, 101.06it/s]

train:  95%|██████████████████████████▌ | 89792/94563 [14:49<00:47, 101.16it/s]

train:  95%|██████████████████████████▌ | 89824/94563 [14:49<00:47, 100.32it/s]

train:  95%|██████████████████████████▌ | 89856/94563 [14:49<00:46, 100.70it/s]

train:  95%|██████████████████████████▌ | 89888/94563 [14:50<00:46, 100.69it/s]

train:  95%|██████████████████████████▋ | 89920/94563 [14:50<00:46, 100.59it/s]

train:  95%|██████████████████████████▋ | 89952/94563 [14:50<00:45, 100.55it/s]

train:  95%|██████████████████████████▋ | 89984/94563 [14:51<00:45, 100.62it/s]

train:  95%|██████████████████████████▋ | 90015/94563 [14:51<00:36, 125.46it/s]

[train] Checkpoint saved at 90000/94563

train:  95%|██████████████████████████▋ | 90032/94563 [14:51<00:44, 101.37it/s]

train:  95%|███████████████████████████▌ | 90048/94563 [14:51<00:51, 86.95it/s]

train:  95%|███████████████████████████▋ | 90080/94563 [14:52<00:48, 91.77it/s]

train:  95%|███████████████████████████▋ | 90112/94563 [14:52<00:47, 94.68it/s]

train:  95%|███████████████████████████▋ | 90144/94563 [14:52<00:45, 96.50it/s]

train:  95%|███████████████████████████▋ | 90176/94563 [14:53<00:44, 97.81it/s]

train:  95%|███████████████████████████▋ | 90208/94563 [14:53<00:44, 98.72it/s]

train:  95%|███████████████████████████▋ | 90240/94563 [14:53<00:43, 99.17it/s]

train:  95%|███████████████████████████▋ | 90272/94563 [14:54<00:43, 99.58it/s]

train:  95%|██████████████████████████▋ | 90304/94563 [14:54<00:42, 100.35it/s]

train:  96%|██████████████████████████▋ | 90336/94563 [14:54<00:42, 100.15it/s]

train:  96%|██████████████████████████▊ | 90368/94563 [14:54<00:41, 100.65it/s]

train:  96%|██████████████████████████▊ | 90400/94563 [14:55<00:41, 100.84it/s]

train:  96%|██████████████████████████▊ | 90432/94563 [14:55<00:40, 101.08it/s]

train:  96%|██████████████████████████▊ | 90464/94563 [14:55<00:40, 101.21it/s]

train:  96%|██████████████████████████▊ | 90496/94563 [14:56<00:40, 101.41it/s]

train:  96%|██████████████████████████▊ | 90528/94563 [14:56<00:39, 101.12it/s]

train:  96%|██████████████████████████▊ | 90560/94563 [14:56<00:39, 101.27it/s]

train:  96%|██████████████████████████▊ | 90592/94563 [14:57<00:39, 101.04it/s]

train:  96%|██████████████████████████▊ | 90624/94563 [14:57<00:38, 101.26it/s]

train:  96%|██████████████████████████▊ | 90656/94563 [14:57<00:38, 101.01it/s]

train:  96%|██████████████████████████▊ | 90688/94563 [14:58<00:38, 100.73it/s]

train:  96%|██████████████████████████▊ | 90720/94563 [14:58<00:38, 100.51it/s]

train:  96%|██████████████████████████▊ | 90752/94563 [14:58<00:37, 100.33it/s]

train:  96%|██████████████████████████▉ | 90784/94563 [14:59<00:37, 100.79it/s]

train:  96%|██████████████████████████▉ | 90816/94563 [14:59<00:37, 100.78it/s]

train:  96%|██████████████████████████▉ | 90848/94563 [14:59<00:36, 100.69it/s]

train:  96%|██████████████████████████▉ | 90880/94563 [15:00<00:36, 100.21it/s]

train:  96%|██████████████████████████▉ | 90912/94563 [15:00<00:36, 100.03it/s]

train:  96%|███████████████████████████▉ | 90944/94563 [15:00<00:36, 99.86it/s]

train:  96%|███████████████████████████▉ | 90976/94563 [15:01<00:36, 99.49it/s]

train:  96%|██████████████████████████▉ | 91007/94563 [15:01<00:28, 124.05it/s]

[train] Checkpoint saved at 91000/94563

train:  96%|██████████████████████████▉ | 91024/94563 [15:01<00:35, 100.05it/s]

train:  96%|███████████████████████████▉ | 91040/94563 [15:01<00:41, 85.66it/s]

train:  96%|███████████████████████████▉ | 91072/94563 [15:02<00:38, 90.40it/s]

train:  96%|███████████████████████████▉ | 91104/94563 [15:02<00:36, 93.60it/s]

train:  96%|███████████████████████████▉ | 91136/94563 [15:02<00:35, 95.55it/s]

train:  96%|███████████████████████████▉ | 91168/94563 [15:03<00:35, 96.75it/s]

train:  96%|███████████████████████████▉ | 91200/94563 [15:03<00:34, 97.77it/s]

train:  96%|███████████████████████████▉ | 91232/94563 [15:03<00:33, 98.53it/s]

train:  97%|███████████████████████████▉ | 91264/94563 [15:03<00:33, 99.25it/s]

train:  97%|███████████████████████████▉ | 91296/94563 [15:04<00:32, 99.85it/s]

train:  97%|███████████████████████████ | 91328/94563 [15:04<00:32, 100.38it/s]

train:  97%|███████████████████████████ | 91360/94563 [15:04<00:31, 100.78it/s]

train:  97%|███████████████████████████ | 91392/94563 [15:05<00:31, 101.07it/s]

train:  97%|███████████████████████████ | 91424/94563 [15:05<00:31, 100.92it/s]

train:  97%|███████████████████████████ | 91456/94563 [15:05<00:30, 100.93it/s]

train:  97%|███████████████████████████ | 91488/94563 [15:06<00:30, 101.01it/s]

train:  97%|███████████████████████████ | 91520/94563 [15:06<00:30, 101.05it/s]

train:  97%|███████████████████████████ | 91552/94563 [15:06<00:29, 101.34it/s]

train:  97%|███████████████████████████ | 91584/94563 [15:07<00:29, 101.32it/s]

train:  97%|███████████████████████████▏| 91616/94563 [15:07<00:29, 101.23it/s]

train:  97%|███████████████████████████▏| 91648/94563 [15:07<00:28, 101.02it/s]

train:  97%|███████████████████████████▏| 91680/94563 [15:08<00:28, 101.14it/s]

train:  97%|███████████████████████████▏| 91712/94563 [15:08<00:28, 101.23it/s]

train:  97%|███████████████████████████▏| 91744/94563 [15:08<00:27, 101.31it/s]

train:  97%|███████████████████████████▏| 91776/94563 [15:09<00:27, 101.46it/s]

train:  97%|███████████████████████████▏| 91808/94563 [15:09<00:27, 101.40it/s]

train:  97%|███████████████████████████▏| 91840/94563 [15:09<00:26, 101.47it/s]

train:  97%|███████████████████████████▏| 91872/94563 [15:09<00:26, 101.58it/s]

train:  97%|███████████████████████████▏| 91904/94563 [15:10<00:26, 101.65it/s]

train:  97%|███████████████████████████▏| 91936/94563 [15:10<00:25, 101.76it/s]

train:  97%|███████████████████████████▏| 91968/94563 [15:10<00:25, 101.47it/s]

train:  97%|████████████████████████████▏| 92000/94563 [15:11<00:26, 96.22it/s]

[train] Checkpoint saved at 92000/94563

train:  97%|████████████████████████████▏| 92032/94563 [15:11<00:26, 94.93it/s]

train:  97%|████████████████████████████▏| 92064/94563 [15:11<00:25, 97.10it/s]

train:  97%|████████████████████████████▏| 92096/94563 [15:12<00:25, 98.04it/s]

train:  97%|████████████████████████████▎| 92128/94563 [15:12<00:24, 98.97it/s]

train:  97%|████████████████████████████▎| 92160/94563 [15:12<00:24, 99.41it/s]

train:  97%|████████████████████████████▎| 92192/94563 [15:13<00:23, 99.42it/s]

train:  98%|████████████████████████████▎| 92224/94563 [15:13<00:23, 99.42it/s]

train:  98%|████████████████████████████▎| 92256/94563 [15:13<00:23, 99.47it/s]

train:  98%|████████████████████████████▎| 92288/94563 [15:14<00:22, 99.38it/s]

train:  98%|████████████████████████████▎| 92320/94563 [15:14<00:22, 99.46it/s]

train:  98%|████████████████████████████▎| 92352/94563 [15:14<00:22, 99.29it/s]

train:  98%|████████████████████████████▎| 92384/94563 [15:15<00:22, 98.94it/s]

train:  98%|████████████████████████████▎| 92416/94563 [15:15<00:21, 99.33it/s]

train:  98%|████████████████████████████▎| 92448/94563 [15:15<00:21, 99.58it/s]

train:  98%|████████████████████████████▎| 92480/94563 [15:16<00:20, 99.63it/s]

train:  98%|████████████████████████████▎| 92512/94563 [15:16<00:20, 99.72it/s]

train:  98%|████████████████████████████▍| 92544/94563 [15:16<00:20, 99.97it/s]

train:  98%|███████████████████████████▍| 92576/94563 [15:17<00:19, 100.06it/s]

train:  98%|███████████████████████████▍| 92608/94563 [15:17<00:19, 100.18it/s]

train:  98%|███████████████████████████▍| 92640/94563 [15:17<00:19, 100.24it/s]

train:  98%|███████████████████████████▍| 92672/94563 [15:18<00:18, 100.15it/s]

train:  98%|███████████████████████████▍| 92704/94563 [15:18<00:18, 100.25it/s]

train:  98%|███████████████████████████▍| 92736/94563 [15:18<00:18, 100.55it/s]

train:  98%|███████████████████████████▍| 92768/94563 [15:18<00:17, 100.73it/s]

train:  98%|███████████████████████████▍| 92800/94563 [15:19<00:17, 101.03it/s]

train:  98%|███████████████████████████▍| 92832/94563 [15:19<00:17, 101.17it/s]

train:  98%|███████████████████████████▍| 92864/94563 [15:19<00:16, 101.17it/s]

train:  98%|███████████████████████████▌| 92896/94563 [15:20<00:16, 101.24it/s]

train:  98%|███████████████████████████▌| 92928/94563 [15:20<00:16, 101.23it/s]

train:  98%|███████████████████████████▌| 92960/94563 [15:20<00:15, 101.30it/s]

train:  98%|███████████████████████████▌| 92992/94563 [15:21<00:15, 101.07it/s]

train:  98%|███████████████████████████▌| 93019/94563 [15:21<00:12, 121.18it/s]

[train] Checkpoint saved at 93000/94563

train:  98%|████████████████████████████▌| 93035/94563 [15:21<00:15, 96.78it/s]

train:  98%|████████████████████████████▌| 93056/94563 [15:21<00:17, 88.54it/s]

train:  98%|████████████████████████████▌| 93088/94563 [15:22<00:15, 93.01it/s]

train:  98%|████████████████████████████▌| 93120/94563 [15:22<00:15, 95.98it/s]

train:  99%|████████████████████████████▌| 93152/94563 [15:22<00:14, 97.81it/s]

train:  99%|████████████████████████████▌| 93184/94563 [15:23<00:13, 99.01it/s]

train:  99%|████████████████████████████▌| 93216/94563 [15:23<00:13, 99.67it/s]

train:  99%|████████████████████████████▌| 93248/94563 [15:23<00:13, 99.94it/s]

train:  99%|███████████████████████████▌| 93280/94563 [15:24<00:12, 100.24it/s]

train:  99%|████████████████████████████▌| 93312/94563 [15:24<00:12, 99.88it/s]

train:  99%|████████████████████████████▋| 93344/94563 [15:24<00:12, 99.97it/s]

train:  99%|███████████████████████████▋| 93376/94563 [15:25<00:11, 100.33it/s]

train:  99%|███████████████████████████▋| 93408/94563 [15:25<00:11, 100.60it/s]

train:  99%|███████████████████████████▋| 93440/94563 [15:25<00:11, 100.49it/s]

train:  99%|███████████████████████████▋| 93472/94563 [15:26<00:10, 100.82it/s]

train:  99%|███████████████████████████▋| 93504/94563 [15:26<00:10, 100.88it/s]

train:  99%|███████████████████████████▋| 93536/94563 [15:26<00:10, 100.95it/s]

train:  99%|███████████████████████████▋| 93568/94563 [15:26<00:09, 100.86it/s]

train:  99%|███████████████████████████▋| 93600/94563 [15:27<00:09, 100.82it/s]

train:  99%|███████████████████████████▋| 93632/94563 [15:27<00:09, 100.69it/s]

train:  99%|███████████████████████████▋| 93664/94563 [15:27<00:08, 100.56it/s]

train:  99%|███████████████████████████▋| 93696/94563 [15:28<00:08, 100.59it/s]

train:  99%|███████████████████████████▊| 93728/94563 [15:28<00:08, 100.49it/s]

train:  99%|███████████████████████████▊| 93760/94563 [15:28<00:07, 100.47it/s]

train:  99%|███████████████████████████▊| 93792/94563 [15:29<00:07, 100.46it/s]

train:  99%|███████████████████████████▊| 93824/94563 [15:29<00:07, 100.28it/s]

train:  99%|███████████████████████████▊| 93856/94563 [15:29<00:07, 100.44it/s]

train:  99%|███████████████████████████▊| 93888/94563 [15:30<00:06, 100.49it/s]

train:  99%|███████████████████████████▊| 93920/94563 [15:30<00:06, 100.45it/s]

train:  99%|███████████████████████████▊| 93952/94563 [15:30<00:06, 100.43it/s]

train:  99%|███████████████████████████▊| 93984/94563 [15:31<00:05, 100.43it/s]

train:  99%|███████████████████████████▊| 94014/94563 [15:31<00:04, 123.96it/s]

[train] Checkpoint saved at 94000/94563

train:  99%|████████████████████████████▊| 94030/94563 [15:31<00:05, 99.24it/s]

train:  99%|████████████████████████████▊| 94048/94563 [15:31<00:05, 87.46it/s]

train:  99%|████████████████████████████▊| 94080/94563 [15:32<00:05, 92.26it/s]

train: 100%|████████████████████████████▊| 94112/94563 [15:32<00:04, 95.23it/s]

train: 100%|████████████████████████████▊| 94144/94563 [15:32<00:04, 97.10it/s]

train: 100%|████████████████████████████▉| 94176/94563 [15:33<00:03, 98.31it/s]

train: 100%|████████████████████████████▉| 94208/94563 [15:33<00:03, 99.08it/s]

train: 100%|████████████████████████████▉| 94240/94563 [15:33<00:03, 99.60it/s]

train: 100%|████████████████████████████▉| 94272/94563 [15:34<00:02, 99.95it/s]

train: 100%|███████████████████████████▉| 94304/94563 [15:34<00:02, 100.23it/s]

train: 100%|███████████████████████████▉| 94336/94563 [15:34<00:02, 100.41it/s]

train: 100%|███████████████████████████▉| 94368/94563 [15:34<00:01, 100.58it/s]

train: 100%|███████████████████████████▉| 94400/94563 [15:35<00:01, 100.64it/s]

train: 100%|███████████████████████████▉| 94432/94563 [15:35<00:01, 100.76it/s]

train: 100%|███████████████████████████▉| 94464/94563 [15:35<00:00, 100.84it/s]

train: 100%|███████████████████████████▉| 94496/94563 [15:36<00:00, 100.82it/s]

train: 100%|███████████████████████████▉| 94528/94563 [15:36<00:00, 100.78it/s]

train: 100%|████████████████████████████| 94563/94563 [15:36<00:00, 100.93it/s]

[train] Done — saved img_emb_train.npy, shape (94563, 512)
[val] Starting fresh — 11925 images to encode

val:   0%|                                           | 0/11925 [00:00<?, ?it/s]

val:   0%|                                  | 32/11925 [00:00<02:07, 93.58it/s]

val:   1%|▏                                 | 64/11925 [00:00<02:00, 98.78it/s]

val:   1%|▎                                | 96/11925 [00:00<01:57, 100.37it/s]

val:   1%|▎                               | 128/11925 [00:01<01:56, 101.18it/s]

val:   1%|▍                               | 160/11925 [00:01<01:55, 101.60it/s]

val:   2%|▌                               | 192/11925 [00:01<01:55, 101.86it/s]

val:   2%|▌                               | 224/11925 [00:02<01:54, 102.02it/s]

val:   2%|▋                               | 256/11925 [00:02<01:54, 102.03it/s]

val:   2%|▊                               | 288/11925 [00:02<01:53, 102.08it/s]

val:   3%|▊                               | 320/11925 [00:03<01:53, 101.98it/s]

val:   3%|▉                               | 352/11925 [00:03<01:53, 102.05it/s]

val:   3%|█                               | 384/11925 [00:03<01:53, 102.10it/s]

val:   3%|█                               | 416/11925 [00:04<01:52, 102.15it/s]

val:   4%|█▏                              | 448/11925 [00:04<01:52, 102.08it/s]

val:   4%|█▎                              | 480/11925 [00:04<01:52, 101.97it/s]

val:   4%|█▎                              | 512/11925 [00:05<01:52, 101.88it/s]

val:   5%|█▍                              | 544/11925 [00:05<01:51, 101.74it/s]

val:   5%|█▌                              | 576/11925 [00:05<01:51, 101.47it/s]

val:   5%|█▋                              | 608/11925 [00:05<01:51, 101.36it/s]

val:   5%|█▋                              | 640/11925 [00:06<01:51, 101.04it/s]

val:   6%|█▊                              | 672/11925 [00:06<01:51, 100.79it/s]

val:   6%|█▉                              | 704/11925 [00:06<01:51, 100.36it/s]

val:   6%|██                               | 736/11925 [00:07<01:52, 99.29it/s]

val:   6%|██▏                              | 768/11925 [00:07<01:51, 99.64it/s]

val:   7%|██▏                              | 800/11925 [00:07<01:51, 99.73it/s]

val:   7%|██▎                              | 832/11925 [00:08<01:51, 99.66it/s]

val:   7%|██▍                              | 864/11925 [00:08<01:51, 99.49it/s]

val:   8%|██▍                              | 896/11925 [00:08<01:50, 99.45it/s]

val:   8%|██▌                              | 928/11925 [00:09<01:50, 99.51it/s]

val:   8%|██▋                              | 960/11925 [00:09<01:50, 99.42it/s]

val:   8%|██▋                              | 992/11925 [00:09<01:49, 99.55it/s]

[val] Checkpoint saved at 1000/11925

val:   9%|██▋                             | 1024/11925 [00:10<01:49, 99.99it/s]

val:   9%|██▋                            | 1056/11925 [00:10<01:48, 100.10it/s]

val:   9%|██▊                            | 1088/11925 [00:10<01:48, 100.06it/s]

val:   9%|██▉                            | 1120/11925 [00:11<01:47, 100.17it/s]

val:  10%|███                             | 1152/11925 [00:11<01:47, 99.95it/s]

val:  10%|███▏                            | 1184/11925 [00:11<01:47, 99.86it/s]

val:  10%|███▎                            | 1216/11925 [00:12<01:47, 99.73it/s]

val:  10%|███▎                            | 1248/11925 [00:12<01:47, 99.57it/s]

val:  11%|███▍                            | 1280/11925 [00:12<01:46, 99.55it/s]

val:  11%|███▌                            | 1312/11925 [00:13<01:46, 99.49it/s]

val:  11%|███▌                            | 1344/11925 [00:13<01:46, 99.40it/s]

val:  12%|███▋                            | 1376/11925 [00:13<01:46, 99.36it/s]

val:  12%|███▊                            | 1408/11925 [00:14<01:45, 99.29it/s]

val:  12%|███▊                            | 1440/11925 [00:14<01:45, 99.47it/s]

val:  12%|███▉                            | 1472/11925 [00:14<01:44, 99.75it/s]

val:  13%|███▉                           | 1504/11925 [00:14<01:44, 100.02it/s]

val:  13%|████                            | 1536/11925 [00:15<01:44, 99.80it/s]

val:  13%|████                           | 1568/11925 [00:15<01:43, 100.18it/s]

val:  13%|████▏                          | 1600/11925 [00:15<01:42, 100.42it/s]

val:  14%|████▏                          | 1632/11925 [00:16<01:42, 100.38it/s]

val:  14%|████▎                          | 1664/11925 [00:16<01:41, 100.73it/s]

val:  14%|████▍                          | 1696/11925 [00:16<01:41, 100.84it/s]

val:  14%|████▍                          | 1728/11925 [00:17<01:40, 101.00it/s]

val:  15%|████▌                          | 1760/11925 [00:17<01:40, 101.37it/s]

val:  15%|████▋                          | 1792/11925 [00:17<01:39, 101.36it/s]

val:  15%|████▋                          | 1824/11925 [00:18<01:39, 101.26it/s]

val:  16%|████▊                          | 1856/11925 [00:18<01:39, 101.24it/s]

val:  16%|████▉                          | 1888/11925 [00:18<01:39, 101.37it/s]

val:  16%|████▉                          | 1920/11925 [00:19<01:38, 101.39it/s]

val:  16%|█████                          | 1952/11925 [00:19<01:38, 101.23it/s]

val:  17%|█████▏                         | 1984/11925 [00:19<01:38, 101.06it/s]

[val] Checkpoint saved at 2000/11925

val:  17%|█████▏                         | 2016/11925 [00:20<01:38, 101.01it/s]

val:  17%|█████▎                         | 2048/11925 [00:20<01:37, 100.85it/s]

val:  17%|█████▍                         | 2080/11925 [00:20<01:37, 100.86it/s]

val:  18%|█████▍                         | 2112/11925 [00:20<01:37, 100.90it/s]

val:  18%|█████▌                         | 2144/11925 [00:21<01:37, 100.75it/s]

val:  18%|█████▋                         | 2176/11925 [00:21<01:37, 100.30it/s]

val:  19%|█████▉                          | 2208/11925 [00:21<01:37, 99.43it/s]

val:  19%|██████                          | 2240/11925 [00:22<01:37, 99.38it/s]

val:  19%|██████                          | 2272/11925 [00:22<01:36, 99.53it/s]

val:  19%|██████▏                         | 2304/11925 [00:22<01:36, 99.66it/s]

val:  20%|██████▎                         | 2336/11925 [00:23<01:36, 99.37it/s]

val:  20%|██████▎                         | 2368/11925 [00:23<01:36, 99.10it/s]

val:  20%|██████▍                         | 2400/11925 [00:23<01:36, 98.90it/s]

val:  20%|██████▌                         | 2432/11925 [00:24<01:35, 99.06it/s]

val:  21%|██████▌                         | 2464/11925 [00:24<01:35, 99.18it/s]

val:  21%|██████▋                         | 2496/11925 [00:24<01:35, 99.21it/s]

val:  21%|██████▊                         | 2528/11925 [00:25<01:34, 99.11it/s]

val:  21%|██████▊                         | 2560/11925 [00:25<01:34, 98.97it/s]

val:  22%|██████▉                         | 2592/11925 [00:25<01:34, 98.86it/s]

val:  22%|███████                         | 2624/11925 [00:26<01:34, 98.89it/s]

val:  22%|███████▏                        | 2656/11925 [00:26<01:33, 98.89it/s]

val:  23%|███████▏                        | 2688/11925 [00:26<01:35, 97.12it/s]

val:  23%|███████▎                        | 2720/11925 [00:27<01:34, 97.59it/s]

val:  23%|███████▍                        | 2752/11925 [00:27<01:33, 98.15it/s]

val:  23%|███████▍                        | 2784/11925 [00:27<01:32, 98.35it/s]

val:  24%|███████▌                        | 2816/11925 [00:28<01:32, 98.23it/s]

val:  24%|███████▋                        | 2848/11925 [00:28<01:32, 98.27it/s]

val:  24%|███████▋                        | 2880/11925 [00:28<01:32, 98.00it/s]

val:  24%|███████▊                        | 2912/11925 [00:29<01:33, 96.21it/s]

val:  25%|███████▉                        | 2944/11925 [00:29<01:34, 95.02it/s]

val:  25%|███████▉                        | 2976/11925 [00:29<01:33, 95.75it/s]

[val] Checkpoint saved at 3000/11925

val:  25%|████████                        | 3008/11925 [00:30<01:33, 95.76it/s]

val:  25%|████████▏                       | 3040/11925 [00:30<01:32, 95.96it/s]

val:  26%|████████▏                       | 3072/11925 [00:30<01:32, 95.88it/s]

val:  26%|████████▎                       | 3104/11925 [00:31<01:31, 96.04it/s]

val:  26%|████████▍                       | 3136/11925 [00:31<01:31, 96.44it/s]

val:  27%|████████▌                       | 3168/11925 [00:31<01:30, 96.87it/s]

val:  27%|████████▌                       | 3200/11925 [00:32<01:29, 97.98it/s]

val:  27%|████████▋                       | 3232/11925 [00:32<01:27, 98.81it/s]

val:  27%|████████▊                       | 3264/11925 [00:32<01:27, 99.28it/s]

val:  28%|████████▊                       | 3296/11925 [00:33<01:26, 99.79it/s]

val:  28%|████████▉                       | 3328/11925 [00:33<01:26, 99.84it/s]

val:  28%|█████████                       | 3360/11925 [00:33<01:25, 99.80it/s]

val:  28%|█████████                       | 3392/11925 [00:34<01:25, 99.70it/s]

val:  29%|█████████▏                      | 3424/11925 [00:34<01:25, 99.28it/s]

val:  29%|█████████▎                      | 3456/11925 [00:34<01:25, 99.27it/s]

val:  29%|█████████▎                      | 3488/11925 [00:34<01:25, 99.05it/s]

val:  30%|█████████▍                      | 3520/11925 [00:35<01:24, 99.24it/s]

val:  30%|█████████▌                      | 3552/11925 [00:35<01:24, 99.27it/s]

val:  30%|█████████▌                      | 3584/11925 [00:35<01:24, 99.24it/s]

val:  30%|█████████▋                      | 3616/11925 [00:36<01:23, 99.42it/s]

val:  31%|█████████▊                      | 3648/11925 [00:36<01:23, 99.28it/s]

val:  31%|█████████▉                      | 3680/11925 [00:36<01:23, 98.96it/s]

val:  31%|█████████▉                      | 3712/11925 [00:37<01:23, 98.09it/s]

val:  31%|██████████                      | 3744/11925 [00:37<01:23, 98.49it/s]

val:  32%|██████████▏                     | 3776/11925 [00:37<01:22, 98.73it/s]

val:  32%|██████████▏                     | 3808/11925 [00:38<01:22, 98.91it/s]

val:  32%|██████████▎                     | 3840/11925 [00:38<01:21, 99.23it/s]

val:  32%|██████████▍                     | 3872/11925 [00:38<01:20, 99.67it/s]

val:  33%|██████████▍                     | 3904/11925 [00:39<01:21, 98.85it/s]

val:  33%|██████████▌                     | 3936/11925 [00:39<01:20, 98.98it/s]

val:  33%|██████████▋                     | 3968/11925 [00:39<01:20, 98.38it/s]

val:  34%|██████████▋                     | 4000/11925 [00:40<01:20, 98.13it/s]

[val] Checkpoint saved at 4000/11925

val:  34%|██████████▊                     | 4032/11925 [00:40<01:20, 97.85it/s]

val:  34%|██████████▉                     | 4064/11925 [00:40<01:20, 97.55it/s]

val:  34%|██████████▉                     | 4096/11925 [00:41<01:20, 97.42it/s]

val:  35%|███████████                     | 4128/11925 [00:41<01:20, 97.18it/s]

val:  35%|███████████▏                    | 4160/11925 [00:41<01:19, 97.91it/s]

val:  35%|███████████▏                    | 4192/11925 [00:42<01:18, 98.10it/s]

val:  35%|███████████▎                    | 4224/11925 [00:42<01:18, 98.00it/s]

val:  36%|███████████▍                    | 4256/11925 [00:42<01:18, 98.01it/s]

val:  36%|███████████▌                    | 4288/11925 [00:43<01:17, 98.04it/s]

val:  36%|███████████▌                    | 4320/11925 [00:43<01:17, 98.68it/s]

val:  36%|███████████▋                    | 4352/11925 [00:43<01:16, 98.94it/s]

val:  37%|███████████▊                    | 4384/11925 [00:44<01:15, 99.48it/s]

val:  37%|███████████▊                    | 4416/11925 [00:44<01:15, 99.69it/s]

val:  37%|███████████▉                    | 4448/11925 [00:44<01:14, 99.78it/s]

val:  38%|████████████                    | 4480/11925 [00:45<01:14, 99.89it/s]

val:  38%|████████████                    | 4512/11925 [00:45<01:14, 99.63it/s]

val:  38%|████████████▏                   | 4544/11925 [00:45<01:13, 99.84it/s]

val:  38%|███████████▉                   | 4576/11925 [00:46<01:13, 100.18it/s]

val:  39%|███████████▉                   | 4608/11925 [00:46<01:12, 100.67it/s]

val:  39%|████████████                   | 4640/11925 [00:46<01:12, 101.00it/s]

val:  39%|████████████▌                   | 4672/11925 [00:46<01:13, 99.04it/s]

val:  39%|████████████▌                   | 4704/11925 [00:47<01:12, 99.78it/s]

val:  40%|████████████▋                   | 4736/11925 [00:47<01:11, 99.97it/s]

val:  40%|████████████▍                  | 4768/11925 [00:47<01:11, 100.56it/s]

val:  40%|████████████▍                  | 4800/11925 [00:48<01:10, 100.84it/s]

val:  41%|████████████▌                  | 4832/11925 [00:48<01:10, 100.83it/s]

val:  41%|████████████▋                  | 4864/11925 [00:48<01:10, 100.75it/s]

val:  41%|████████████▋                  | 4896/11925 [00:49<01:09, 100.90it/s]

val:  41%|████████████▊                  | 4928/11925 [00:49<01:09, 100.99it/s]

val:  42%|████████████▉                  | 4960/11925 [00:49<01:09, 100.89it/s]

val:  42%|████████████▉                  | 4992/11925 [00:50<01:08, 100.80it/s]

[val] Checkpoint saved at 5000/11925

val:  42%|█████████████                  | 5024/11925 [00:50<01:08, 100.64it/s]

val:  42%|█████████████▏                 | 5056/11925 [00:50<01:08, 100.73it/s]

val:  43%|█████████████▏                 | 5088/11925 [00:51<01:08, 100.51it/s]

val:  43%|█████████████▎                 | 5120/11925 [00:51<01:07, 100.35it/s]

val:  43%|█████████████▍                 | 5152/11925 [00:51<01:07, 100.24it/s]

val:  43%|█████████████▍                 | 5184/11925 [00:52<01:07, 100.28it/s]

val:  44%|█████████████▉                  | 5216/11925 [00:52<01:08, 98.57it/s]

val:  44%|██████████████                  | 5248/11925 [00:52<01:07, 99.04it/s]

val:  44%|██████████████▏                 | 5280/11925 [00:53<01:06, 99.30it/s]

val:  45%|██████████████▎                 | 5312/11925 [00:53<01:06, 99.39it/s]

val:  45%|██████████████▎                 | 5344/11925 [00:53<01:06, 99.56it/s]

val:  45%|██████████████▍                 | 5376/11925 [00:53<01:05, 99.96it/s]

val:  45%|██████████████                 | 5408/11925 [00:54<01:05, 100.03it/s]

val:  46%|██████████████▌                 | 5440/11925 [00:54<01:04, 99.94it/s]

val:  46%|██████████████▋                 | 5472/11925 [00:54<01:04, 99.46it/s]

val:  46%|██████████████▊                 | 5504/11925 [00:55<01:04, 99.19it/s]

val:  46%|██████████████▊                 | 5536/11925 [00:55<01:04, 99.26it/s]

val:  47%|██████████████▉                 | 5568/11925 [00:55<01:04, 98.75it/s]

val:  47%|███████████████                 | 5600/11925 [00:56<01:03, 98.98it/s]

val:  47%|███████████████                 | 5632/11925 [00:56<01:03, 99.14it/s]

val:  47%|███████████████▏                | 5664/11925 [00:56<01:03, 99.18it/s]

val:  48%|███████████████▎                | 5696/11925 [00:57<01:02, 98.91it/s]

val:  48%|███████████████▎                | 5728/11925 [00:57<01:02, 98.96it/s]

val:  48%|███████████████▍                | 5760/11925 [00:57<01:02, 99.00it/s]

val:  49%|███████████████▌                | 5792/11925 [00:58<01:01, 99.34it/s]

val:  49%|███████████████▋                | 5824/11925 [00:58<01:01, 99.57it/s]

val:  49%|███████████████▋                | 5856/11925 [00:58<01:00, 99.79it/s]

val:  49%|███████████████▊                | 5888/11925 [00:59<01:00, 99.71it/s]

val:  50%|███████████████▉                | 5920/11925 [00:59<01:00, 99.48it/s]

val:  50%|███████████████▉                | 5952/11925 [00:59<01:00, 99.36it/s]

val:  50%|████████████████                | 5984/11925 [01:00<00:59, 99.29it/s]

[val] Checkpoint saved at 6000/11925

val:  50%|████████████████▏               | 6016/11925 [01:00<00:59, 99.03it/s]

val:  51%|████████████████▏               | 6048/11925 [01:00<00:59, 98.95it/s]

val:  51%|████████████████▎               | 6080/11925 [01:01<00:59, 99.01it/s]

val:  51%|████████████████▍               | 6112/11925 [01:01<00:58, 99.21it/s]

val:  52%|████████████████▍               | 6144/11925 [01:01<00:58, 99.02it/s]

val:  52%|████████████████▌               | 6176/11925 [01:02<00:57, 99.18it/s]

val:  52%|████████████████▋               | 6208/11925 [01:02<00:57, 99.22it/s]

val:  52%|████████████████▋               | 6240/11925 [01:02<00:57, 99.36it/s]

val:  53%|████████████████▊               | 6272/11925 [01:03<00:56, 99.22it/s]

val:  53%|████████████████▉               | 6304/11925 [01:03<00:56, 99.43it/s]

val:  53%|█████████████████               | 6336/11925 [01:03<00:56, 99.30it/s]

val:  53%|█████████████████               | 6368/11925 [01:03<00:55, 99.37it/s]

val:  54%|█████████████████▏              | 6400/11925 [01:04<00:55, 99.59it/s]

val:  54%|█████████████████▎              | 6432/11925 [01:04<00:55, 99.44it/s]

val:  54%|█████████████████▎              | 6464/11925 [01:04<00:54, 99.48it/s]

val:  54%|█████████████████▍              | 6496/11925 [01:05<00:55, 98.67it/s]

val:  55%|█████████████████▌              | 6528/11925 [01:05<00:54, 98.54it/s]

val:  55%|█████████████████▌              | 6560/11925 [01:05<00:54, 98.35it/s]

val:  55%|█████████████████▋              | 6592/11925 [01:06<00:54, 97.98it/s]

val:  56%|█████████████████▊              | 6624/11925 [01:06<00:54, 97.53it/s]

val:  56%|█████████████████▊              | 6656/11925 [01:06<00:54, 97.26it/s]

val:  56%|█████████████████▉              | 6688/11925 [01:07<00:53, 97.31it/s]

val:  56%|██████████████████              | 6720/11925 [01:07<00:53, 97.55it/s]

val:  57%|██████████████████              | 6752/11925 [01:07<00:52, 97.75it/s]

val:  57%|██████████████████▏             | 6784/11925 [01:08<00:52, 98.26it/s]

val:  57%|██████████████████▎             | 6816/11925 [01:08<00:51, 98.57it/s]

val:  57%|██████████████████▍             | 6848/11925 [01:08<00:51, 98.99it/s]

val:  58%|██████████████████▍             | 6880/11925 [01:09<00:50, 99.33it/s]

val:  58%|█████████████████▉             | 6912/11925 [01:09<00:50, 100.09it/s]

val:  58%|██████████████████             | 6944/11925 [01:09<00:49, 100.49it/s]

val:  58%|██████████████████▏            | 6976/11925 [01:10<00:49, 100.83it/s]

[val] Checkpoint saved at 7000/11925

val:  59%|██████████████████▏            | 7008/11925 [01:10<00:48, 100.88it/s]

val:  59%|██████████████████▎            | 7040/11925 [01:10<00:48, 101.25it/s]

val:  59%|██████████████████▍            | 7072/11925 [01:11<00:47, 101.43it/s]

val:  60%|██████████████████▍            | 7104/11925 [01:11<00:47, 101.37it/s]

val:  60%|██████████████████▌            | 7136/11925 [01:11<00:47, 101.49it/s]

val:  60%|██████████████████▋            | 7168/11925 [01:12<00:46, 101.74it/s]

val:  60%|██████████████████▋            | 7200/11925 [01:12<00:46, 101.67it/s]

val:  61%|██████████████████▊            | 7232/11925 [01:12<00:46, 101.52it/s]

val:  61%|██████████████████▉            | 7264/11925 [01:12<00:45, 101.55it/s]

val:  61%|██████████████████▉            | 7296/11925 [01:13<00:45, 101.53it/s]

val:  61%|███████████████████            | 7328/11925 [01:13<00:45, 101.25it/s]

val:  62%|███████████████████▏           | 7360/11925 [01:13<00:45, 101.00it/s]

val:  62%|███████████████████▏           | 7392/11925 [01:14<00:44, 100.84it/s]

val:  62%|███████████████████▎           | 7424/11925 [01:14<00:44, 100.84it/s]

val:  63%|███████████████████▍           | 7456/11925 [01:14<00:44, 100.96it/s]

val:  63%|███████████████████▍           | 7488/11925 [01:15<00:43, 101.03it/s]

val:  63%|███████████████████▌           | 7520/11925 [01:15<00:43, 101.01it/s]

val:  63%|███████████████████▋           | 7552/11925 [01:15<00:43, 100.85it/s]

val:  64%|███████████████████▋           | 7584/11925 [01:16<00:43, 100.48it/s]

val:  64%|███████████████████▊           | 7616/11925 [01:16<00:43, 100.04it/s]

val:  64%|████████████████████▌           | 7648/11925 [01:16<00:42, 99.95it/s]

val:  64%|████████████████████▌           | 7680/11925 [01:17<00:42, 99.78it/s]

val:  65%|████████████████████▋           | 7712/11925 [01:17<00:42, 99.55it/s]

val:  65%|████████████████████▊           | 7744/11925 [01:17<00:42, 99.49it/s]

val:  65%|████████████████████▊           | 7776/11925 [01:18<00:41, 99.40it/s]

val:  65%|████████████████████▉           | 7808/11925 [01:18<00:41, 99.35it/s]

val:  66%|█████████████████████           | 7840/11925 [01:18<00:41, 99.35it/s]

val:  66%|█████████████████████           | 7872/11925 [01:19<00:40, 99.60it/s]

val:  66%|█████████████████████▏          | 7904/11925 [01:19<00:40, 99.80it/s]

val:  67%|████████████████████▋          | 7936/11925 [01:19<00:39, 100.07it/s]

val:  67%|████████████████████▋          | 7968/11925 [01:19<00:39, 100.40it/s]

val:  67%|█████████████████████▍          | 8000/11925 [01:20<00:39, 99.90it/s]

[val] Checkpoint saved at 8000/11925

val:  67%|████████████████████▉          | 8032/11925 [01:20<00:38, 100.08it/s]

val:  68%|████████████████████▉          | 8064/11925 [01:20<00:38, 100.36it/s]

val:  68%|█████████████████████          | 8096/11925 [01:21<00:38, 100.31it/s]

val:  68%|█████████████████████▏         | 8128/11925 [01:21<00:37, 100.38it/s]

val:  68%|█████████████████████▏         | 8160/11925 [01:21<00:37, 100.20it/s]

val:  69%|█████████████████████▉          | 8192/11925 [01:22<00:37, 99.90it/s]

val:  69%|██████████████████████          | 8224/11925 [01:22<00:37, 99.82it/s]

val:  69%|██████████████████████▏         | 8256/11925 [01:22<00:36, 99.61it/s]

val:  70%|██████████████████████▏         | 8288/11925 [01:23<00:36, 99.39it/s]

val:  70%|██████████████████████▎         | 8320/11925 [01:23<00:36, 99.66it/s]

val:  70%|█████████████████████▋         | 8352/11925 [01:23<00:35, 100.08it/s]

val:  70%|█████████████████████▊         | 8384/11925 [01:24<00:35, 100.32it/s]

val:  71%|█████████████████████▉         | 8416/11925 [01:24<00:35, 100.19it/s]

val:  71%|█████████████████████▉         | 8448/11925 [01:24<00:34, 100.17it/s]

val:  71%|██████████████████████         | 8480/11925 [01:25<00:34, 100.24it/s]

val:  71%|██████████████████████▏        | 8512/11925 [01:25<00:34, 100.06it/s]

val:  72%|██████████████████████▏        | 8544/11925 [01:25<00:33, 100.04it/s]

val:  72%|██████████████████████▎        | 8576/11925 [01:26<00:33, 100.14it/s]

val:  72%|██████████████████████▍        | 8608/11925 [01:26<00:33, 100.09it/s]

val:  72%|██████████████████████▍        | 8640/11925 [01:26<00:32, 100.07it/s]

val:  73%|██████████████████████▌        | 8672/11925 [01:27<00:32, 100.11it/s]

val:  73%|██████████████████████▋        | 8704/11925 [01:27<00:32, 100.25it/s]

val:  73%|██████████████████████▋        | 8736/11925 [01:27<00:31, 100.33it/s]

val:  74%|██████████████████████▊        | 8768/11925 [01:27<00:31, 100.52it/s]

val:  74%|██████████████████████▉        | 8800/11925 [01:28<00:31, 100.74it/s]

val:  74%|██████████████████████▉        | 8832/11925 [01:28<00:30, 100.92it/s]

val:  74%|███████████████████████        | 8864/11925 [01:28<00:30, 100.90it/s]

val:  75%|███████████████████████▏       | 8896/11925 [01:29<00:30, 100.81it/s]

val:  75%|███████████████████████▏       | 8928/11925 [01:29<00:29, 100.95it/s]

val:  75%|███████████████████████▎       | 8960/11925 [01:29<00:29, 100.94it/s]

val:  75%|███████████████████████▍       | 8992/11925 [01:30<00:29, 100.91it/s]

[val] Checkpoint saved at 9000/11925

val:  76%|███████████████████████▍       | 9024/11925 [01:30<00:28, 100.55it/s]

val:  76%|███████████████████████▌       | 9056/11925 [01:30<00:28, 100.59it/s]

val:  76%|███████████████████████▌       | 9088/11925 [01:31<00:28, 100.52it/s]

val:  76%|███████████████████████▋       | 9120/11925 [01:31<00:27, 100.47it/s]

val:  77%|███████████████████████▊       | 9152/11925 [01:31<00:27, 100.32it/s]

val:  77%|███████████████████████▊       | 9184/11925 [01:32<00:27, 100.42it/s]

val:  77%|███████████████████████▉       | 9216/11925 [01:32<00:26, 100.56it/s]

val:  78%|████████████████████████       | 9248/11925 [01:32<00:26, 100.54it/s]

val:  78%|████████████████████████       | 9280/11925 [01:33<00:26, 100.60it/s]

val:  78%|████████████████████████▏      | 9312/11925 [01:33<00:26, 100.45it/s]

val:  78%|████████████████████████▎      | 9344/11925 [01:33<00:25, 100.38it/s]

val:  79%|████████████████████████▎      | 9376/11925 [01:34<00:25, 100.30it/s]

val:  79%|████████████████████████▍      | 9408/11925 [01:34<00:25, 100.24it/s]

val:  79%|████████████████████████▌      | 9440/11925 [01:34<00:24, 100.13it/s]

val:  79%|████████████████████████▌      | 9472/11925 [01:34<00:24, 100.16it/s]

val:  80%|████████████████████████▋      | 9504/11925 [01:35<00:24, 100.03it/s]

val:  80%|████████████████████████▊      | 9536/11925 [01:35<00:23, 100.04it/s]

val:  80%|████████████████████████▊      | 9568/11925 [01:35<00:23, 100.05it/s]

val:  81%|████████████████████████▉      | 9600/11925 [01:36<00:23, 100.05it/s]

val:  81%|█████████████████████████      | 9632/11925 [01:36<00:22, 100.22it/s]

val:  81%|█████████████████████████      | 9664/11925 [01:36<00:22, 100.40it/s]

val:  81%|█████████████████████████▏     | 9696/11925 [01:37<00:22, 100.52it/s]

val:  82%|█████████████████████████▎     | 9728/11925 [01:37<00:21, 100.54it/s]

val:  82%|█████████████████████████▎     | 9760/11925 [01:37<00:21, 100.28it/s]

val:  82%|█████████████████████████▍     | 9792/11925 [01:38<00:21, 100.07it/s]

val:  82%|█████████████████████████▌     | 9824/11925 [01:38<00:21, 100.02it/s]

val:  83%|█████████████████████████▌     | 9856/11925 [01:38<00:20, 100.01it/s]

val:  83%|█████████████████████████▋     | 9888/11925 [01:39<00:20, 100.00it/s]

val:  83%|██████████████████████████▌     | 9920/11925 [01:39<00:20, 99.95it/s]

val:  83%|█████████████████████████▊     | 9952/11925 [01:39<00:19, 100.04it/s]

val:  84%|█████████████████████████▉     | 9984/11925 [01:40<00:19, 100.00it/s]

[val] Checkpoint saved at 10000/11925

val:  84%|██████████████████████████     | 10016/11925 [01:40<00:19, 99.75it/s]

val:  84%|█████████████████████████▎    | 10048/11925 [01:40<00:18, 100.00it/s]

val:  85%|██████████████████████████▏    | 10080/11925 [01:41<00:18, 99.86it/s]

val:  85%|█████████████████████████▍    | 10112/11925 [01:41<00:18, 100.04it/s]

val:  85%|█████████████████████████▌    | 10144/11925 [01:41<00:17, 100.13it/s]

val:  85%|█████████████████████████▌    | 10176/11925 [01:42<00:17, 100.23it/s]

val:  86%|█████████████████████████▋    | 10208/11925 [01:42<00:17, 100.10it/s]

val:  86%|█████████████████████████▊    | 10240/11925 [01:42<00:16, 100.29it/s]

val:  86%|█████████████████████████▊    | 10272/11925 [01:42<00:16, 100.29it/s]

val:  86%|█████████████████████████▉    | 10304/11925 [01:43<00:16, 100.28it/s]

val:  87%|██████████████████████████    | 10336/11925 [01:43<00:15, 100.25it/s]

val:  87%|██████████████████████████    | 10368/11925 [01:43<00:15, 100.24it/s]

val:  87%|██████████████████████████▏   | 10400/11925 [01:44<00:15, 100.34it/s]

val:  87%|██████████████████████████▏   | 10432/11925 [01:44<00:14, 100.51it/s]

val:  88%|██████████████████████████▎   | 10464/11925 [01:44<00:14, 100.38it/s]

val:  88%|██████████████████████████▍   | 10496/11925 [01:45<00:14, 100.31it/s]

val:  88%|██████████████████████████▍   | 10528/11925 [01:45<00:13, 100.33it/s]

val:  89%|██████████████████████████▌   | 10560/11925 [01:45<00:13, 100.26it/s]

val:  89%|██████████████████████████▋   | 10592/11925 [01:46<00:13, 100.34it/s]

val:  89%|██████████████████████████▋   | 10624/11925 [01:46<00:12, 100.47it/s]

val:  89%|██████████████████████████▊   | 10656/11925 [01:46<00:12, 100.72it/s]

val:  90%|██████████████████████████▉   | 10688/11925 [01:47<00:12, 100.85it/s]

val:  90%|██████████████████████████▉   | 10720/11925 [01:47<00:11, 100.79it/s]

val:  90%|███████████████████████████   | 10752/11925 [01:47<00:11, 100.94it/s]

val:  90%|███████████████████████████▏  | 10784/11925 [01:48<00:11, 100.97it/s]

val:  91%|███████████████████████████▏  | 10816/11925 [01:48<00:10, 100.94it/s]

val:  91%|███████████████████████████▎  | 10848/11925 [01:48<00:10, 100.93it/s]

val:  91%|███████████████████████████▎  | 10880/11925 [01:49<00:10, 100.84it/s]

val:  92%|███████████████████████████▍  | 10912/11925 [01:49<00:10, 101.03it/s]

val:  92%|███████████████████████████▌  | 10944/11925 [01:49<00:09, 101.02it/s]

val:  92%|███████████████████████████▌  | 10976/11925 [01:49<00:09, 101.02it/s]

[val] Checkpoint saved at 11000/11925

val:  92%|███████████████████████████▋  | 11008/11925 [01:50<00:09, 100.38it/s]

val:  93%|███████████████████████████▊  | 11040/11925 [01:50<00:08, 100.47it/s]

val:  93%|███████████████████████████▊  | 11072/11925 [01:50<00:08, 100.26it/s]

val:  93%|███████████████████████████▉  | 11104/11925 [01:51<00:08, 100.04it/s]

val:  93%|████████████████████████████▉  | 11136/11925 [01:51<00:07, 99.96it/s]

val:  94%|████████████████████████████  | 11168/11925 [01:51<00:07, 100.03it/s]

val:  94%|█████████████████████████████  | 11200/11925 [01:52<00:07, 99.91it/s]

val:  94%|█████████████████████████████▏ | 11232/11925 [01:52<00:06, 99.92it/s]

val:  94%|████████████████████████████▎ | 11264/11925 [01:52<00:06, 100.05it/s]

val:  95%|████████████████████████████▍ | 11296/11925 [01:53<00:06, 100.02it/s]

val:  95%|█████████████████████████████▍ | 11328/11925 [01:53<00:05, 99.93it/s]

val:  95%|████████████████████████████▌ | 11360/11925 [01:53<00:05, 100.14it/s]

val:  96%|████████████████████████████▋ | 11392/11925 [01:54<00:05, 100.28it/s]

val:  96%|████████████████████████████▋ | 11424/11925 [01:54<00:05, 100.19it/s]

val:  96%|████████████████████████████▊ | 11456/11925 [01:54<00:04, 100.16it/s]

val:  96%|████████████████████████████▉ | 11488/11925 [01:55<00:04, 100.50it/s]

val:  97%|████████████████████████████▉ | 11520/11925 [01:55<00:04, 100.82it/s]

val:  97%|█████████████████████████████ | 11552/11925 [01:55<00:03, 100.93it/s]

val:  97%|█████████████████████████████▏| 11584/11925 [01:56<00:03, 100.93it/s]

val:  97%|█████████████████████████████▏| 11616/11925 [01:56<00:03, 100.82it/s]

val:  98%|█████████████████████████████▎| 11648/11925 [01:56<00:02, 100.54it/s]

val:  98%|█████████████████████████████▍| 11680/11925 [01:56<00:02, 100.67it/s]

val:  98%|█████████████████████████████▍| 11712/11925 [01:57<00:02, 100.43it/s]

val:  98%|█████████████████████████████▌| 11744/11925 [01:57<00:01, 100.35it/s]

val:  99%|█████████████████████████████▋| 11776/11925 [01:57<00:01, 100.18it/s]

val:  99%|██████████████████████████████▋| 11808/11925 [01:58<00:01, 99.89it/s]

val:  99%|██████████████████████████████▊| 11840/11925 [01:58<00:00, 99.79it/s]

val: 100%|██████████████████████████████▊| 11872/11925 [01:58<00:00, 99.42it/s]

val: 100%|███████████████████████████████| 11925/11925 [01:59<00:00, 99.98it/s]

[val] Done — saved img_emb_val.npy, shape (11925, 512)
[test] Starting fresh — 11798 images to encode

test:   0%|                                          | 0/11798 [00:00<?, ?it/s]

test:   0%|                                | 32/11798 [00:00<01:57, 100.51it/s]

test:   1%|▏                               | 64/11798 [00:00<01:56, 100.33it/s]

test:   1%|▎                               | 96/11798 [00:00<01:56, 100.07it/s]

test:   1%|▎                               | 128/11798 [00:01<01:57, 99.52it/s]

test:   1%|▍                               | 160/11798 [00:01<01:57, 99.14it/s]

test:   2%|▌                               | 192/11798 [00:01<01:57, 98.83it/s]

test:   2%|▌                               | 224/11798 [00:02<01:57, 98.68it/s]

test:   2%|▋                               | 256/11798 [00:02<01:57, 98.64it/s]

test:   2%|▊                               | 288/11798 [00:02<01:56, 98.59it/s]

test:   3%|▊                               | 320/11798 [00:03<01:56, 98.46it/s]

test:   3%|▉                               | 352/11798 [00:03<01:55, 98.90it/s]

test:   3%|█                               | 384/11798 [00:03<01:55, 99.04it/s]

test:   4%|█▏                              | 416/11798 [00:04<01:54, 99.50it/s]

test:   4%|█▏                              | 448/11798 [00:04<01:54, 99.50it/s]

test:   4%|█▎                              | 480/11798 [00:04<01:53, 99.81it/s]

test:   4%|█▍                              | 512/11798 [00:05<01:52, 99.93it/s]

test:   5%|█▍                              | 544/11798 [00:05<01:52, 99.74it/s]

test:   5%|█▌                              | 576/11798 [00:05<01:52, 99.64it/s]

test:   5%|█▋                              | 608/11798 [00:06<01:52, 99.74it/s]

test:   5%|█▋                              | 640/11798 [00:06<01:52, 99.48it/s]

test:   6%|█▊                              | 672/11798 [00:06<01:52, 99.33it/s]

test:   6%|█▉                              | 704/11798 [00:07<01:51, 99.29it/s]

test:   6%|█▉                              | 736/11798 [00:07<01:51, 99.29it/s]

test:   7%|██                              | 768/11798 [00:07<01:52, 97.68it/s]

test:   7%|██▏                             | 800/11798 [00:08<01:51, 98.37it/s]

test:   7%|██▎                             | 832/11798 [00:08<01:51, 98.52it/s]

test:   7%|██▎                             | 864/11798 [00:08<01:50, 98.76it/s]

test:   8%|██▍                             | 896/11798 [00:09<01:50, 98.78it/s]

test:   8%|██▌                             | 928/11798 [00:09<01:49, 99.12it/s]

test:   8%|██▌                             | 960/11798 [00:09<01:48, 99.57it/s]

test:   8%|██▋                             | 992/11798 [00:10<01:48, 99.53it/s]

[test] Checkpoint saved at 1000/11798

test:   9%|██▋                            | 1024/11798 [00:10<01:48, 99.24it/s]

test:   9%|██▊                            | 1056/11798 [00:10<01:48, 99.41it/s]

test:   9%|██▊                            | 1088/11798 [00:10<01:47, 99.35it/s]

test:   9%|██▉                            | 1120/11798 [00:11<01:47, 99.34it/s]

test:  10%|███                            | 1152/11798 [00:11<01:47, 99.42it/s]

test:  10%|███                            | 1184/11798 [00:11<01:47, 99.02it/s]

test:  10%|███▏                           | 1216/11798 [00:12<01:47, 98.80it/s]

test:  11%|███▎                           | 1248/11798 [00:12<01:46, 98.90it/s]

test:  11%|███▎                           | 1280/11798 [00:12<01:48, 96.86it/s]

test:  11%|███▍                           | 1312/11798 [00:13<01:49, 95.71it/s]

test:  11%|███▌                           | 1344/11798 [00:13<01:50, 94.66it/s]

test:  12%|███▌                           | 1376/11798 [00:13<01:51, 93.77it/s]

test:  12%|███▋                           | 1408/11798 [00:14<01:51, 92.84it/s]

test:  12%|███▊                           | 1440/11798 [00:14<01:52, 92.40it/s]

test:  12%|███▊                           | 1472/11798 [00:15<01:52, 91.87it/s]

test:  13%|███▉                           | 1504/11798 [00:15<01:51, 92.62it/s]

test:  13%|████                           | 1536/11798 [00:15<01:49, 93.56it/s]

test:  13%|████                           | 1568/11798 [00:16<01:48, 94.50it/s]

test:  14%|████▏                          | 1600/11798 [00:16<01:48, 94.40it/s]

test:  14%|████▎                          | 1632/11798 [00:16<01:46, 95.30it/s]

test:  14%|████▎                          | 1664/11798 [00:17<01:45, 96.36it/s]

test:  14%|████▍                          | 1696/11798 [00:17<01:43, 97.26it/s]

test:  15%|████▌                          | 1728/11798 [00:17<01:42, 98.01it/s]

test:  15%|████▌                          | 1760/11798 [00:17<01:41, 98.52it/s]

test:  15%|████▋                          | 1792/11798 [00:18<01:41, 99.05it/s]

test:  15%|████▊                          | 1824/11798 [00:18<01:40, 99.43it/s]

test:  16%|████▉                          | 1856/11798 [00:18<01:39, 99.98it/s]

test:  16%|████▊                         | 1888/11798 [00:19<01:38, 100.45it/s]

test:  16%|████▉                         | 1920/11798 [00:19<01:38, 100.48it/s]

test:  17%|████▉                         | 1952/11798 [00:19<01:38, 100.47it/s]

test:  17%|█████                         | 1984/11798 [00:20<01:37, 100.27it/s]

[test] Checkpoint saved at 2000/11798

test:  17%|█████▎                         | 2016/11798 [00:20<01:37, 99.96it/s]

test:  17%|█████▏                        | 2048/11798 [00:20<01:37, 100.37it/s]

test:  18%|█████▎                        | 2080/11798 [00:21<01:36, 100.68it/s]

test:  18%|█████▎                        | 2112/11798 [00:21<01:36, 100.84it/s]

test:  18%|█████▍                        | 2144/11798 [00:21<01:35, 100.67it/s]

test:  18%|█████▌                        | 2176/11798 [00:22<01:35, 100.75it/s]

test:  19%|█████▌                        | 2208/11798 [00:22<01:35, 100.42it/s]

test:  19%|█████▋                        | 2240/11798 [00:22<01:35, 100.55it/s]

test:  19%|█████▊                        | 2272/11798 [00:23<01:35, 100.10it/s]

test:  20%|██████                         | 2304/11798 [00:23<01:35, 99.86it/s]

test:  20%|██████▏                        | 2336/11798 [00:23<01:34, 99.66it/s]

test:  20%|██████▏                        | 2368/11798 [00:24<01:34, 99.33it/s]

test:  20%|██████▎                        | 2400/11798 [00:24<01:34, 99.33it/s]

test:  21%|██████▍                        | 2432/11798 [00:24<01:34, 99.33it/s]

test:  21%|██████▍                        | 2464/11798 [00:25<01:33, 99.31it/s]

test:  21%|██████▌                        | 2496/11798 [00:25<01:33, 99.58it/s]

test:  21%|██████▋                        | 2528/11798 [00:25<01:33, 99.57it/s]

test:  22%|██████▋                        | 2560/11798 [00:25<01:32, 99.85it/s]

test:  22%|██████▊                        | 2592/11798 [00:26<01:32, 99.98it/s]

test:  22%|██████▋                       | 2624/11798 [00:26<01:31, 100.11it/s]

test:  23%|██████▊                       | 2656/11798 [00:26<01:31, 100.23it/s]

test:  23%|██████▊                       | 2688/11798 [00:27<01:30, 100.27it/s]

test:  23%|██████▉                       | 2720/11798 [00:27<01:30, 100.40it/s]

test:  23%|██████▉                       | 2752/11798 [00:27<01:30, 100.44it/s]

test:  24%|███████                       | 2784/11798 [00:28<01:29, 100.68it/s]

test:  24%|███████▏                      | 2816/11798 [00:28<01:28, 101.01it/s]

test:  24%|███████▏                      | 2848/11798 [00:28<01:28, 101.20it/s]

test:  24%|███████▎                      | 2880/11798 [00:29<01:28, 101.33it/s]

test:  25%|███████▍                      | 2912/11798 [00:29<01:27, 101.25it/s]

test:  25%|███████▍                      | 2944/11798 [00:29<01:27, 101.11it/s]

test:  25%|███████▌                      | 2976/11798 [00:30<01:27, 101.17it/s]

[test] Checkpoint saved at 3000/11798

test:  25%|███████▋                      | 3008/11798 [00:30<01:27, 101.00it/s]

test:  26%|███████▋                      | 3040/11798 [00:30<01:26, 101.21it/s]

test:  26%|███████▊                      | 3072/11798 [00:31<01:26, 101.14it/s]

test:  26%|███████▉                      | 3104/11798 [00:31<01:26, 100.96it/s]

test:  27%|███████▉                      | 3136/11798 [00:31<01:25, 100.79it/s]

test:  27%|████████                      | 3168/11798 [00:32<01:25, 100.53it/s]

test:  27%|████████▏                     | 3200/11798 [00:32<01:25, 100.12it/s]

test:  27%|████████▍                      | 3232/11798 [00:32<01:25, 99.91it/s]

test:  28%|████████▌                      | 3264/11798 [00:32<01:25, 99.67it/s]

test:  28%|████████▋                      | 3296/11798 [00:33<01:25, 99.68it/s]

test:  28%|████████▋                      | 3328/11798 [00:33<01:25, 99.60it/s]

test:  28%|████████▊                      | 3360/11798 [00:33<01:24, 99.55it/s]

test:  29%|████████▉                      | 3392/11798 [00:34<01:24, 99.30it/s]

test:  29%|████████▉                      | 3424/11798 [00:34<01:24, 99.37it/s]

test:  29%|█████████                      | 3456/11798 [00:34<01:23, 99.43it/s]

test:  30%|█████████▏                     | 3488/11798 [00:35<01:23, 99.59it/s]

test:  30%|█████████▏                     | 3520/11798 [00:35<01:22, 99.74it/s]

test:  30%|█████████▎                     | 3552/11798 [00:35<01:22, 99.76it/s]

test:  30%|█████████▍                     | 3584/11798 [00:36<01:22, 99.80it/s]

test:  31%|█████████▌                     | 3616/11798 [00:36<01:21, 99.97it/s]

test:  31%|█████████▎                    | 3648/11798 [00:36<01:21, 100.11it/s]

test:  31%|█████████▎                    | 3680/11798 [00:37<01:21, 100.12it/s]

test:  31%|█████████▍                    | 3712/11798 [00:37<01:20, 100.37it/s]

test:  32%|█████████▌                    | 3744/11798 [00:37<01:20, 100.54it/s]

test:  32%|█████████▌                    | 3776/11798 [00:38<01:19, 100.62it/s]

test:  32%|█████████▋                    | 3808/11798 [00:38<01:19, 100.67it/s]

test:  33%|█████████▊                    | 3840/11798 [00:38<01:18, 100.80it/s]

test:  33%|█████████▊                    | 3872/11798 [00:39<01:18, 100.60it/s]

test:  33%|█████████▉                    | 3904/11798 [00:39<01:18, 100.68it/s]

test:  33%|██████████                    | 3936/11798 [00:39<01:18, 100.65it/s]

test:  34%|██████████                    | 3968/11798 [00:39<01:17, 100.44it/s]

test:  34%|██████████▏                   | 4000/11798 [00:40<01:17, 100.23it/s]

[test] Checkpoint saved at 4000/11798

test:  34%|██████████▎                   | 4032/11798 [00:40<01:17, 100.25it/s]

test:  34%|██████████▎                   | 4064/11798 [00:40<01:16, 100.69it/s]

test:  35%|██████████▍                   | 4096/11798 [00:41<01:16, 101.04it/s]

test:  35%|██████████▍                   | 4128/11798 [00:41<01:15, 101.15it/s]

test:  35%|██████████▌                   | 4160/11798 [00:41<01:15, 101.18it/s]

test:  36%|██████████▋                   | 4192/11798 [00:42<01:15, 101.14it/s]

test:  36%|██████████▋                   | 4224/11798 [00:42<01:15, 100.80it/s]

test:  36%|██████████▊                   | 4256/11798 [00:42<01:14, 100.91it/s]

test:  36%|██████████▉                   | 4288/11798 [00:43<01:14, 100.60it/s]

test:  37%|██████████▉                   | 4320/11798 [00:43<01:14, 100.41it/s]

test:  37%|███████████                   | 4352/11798 [00:43<01:14, 100.17it/s]

test:  37%|███████████▌                   | 4384/11798 [00:44<01:14, 99.87it/s]

test:  37%|███████████▌                   | 4416/11798 [00:44<01:14, 99.68it/s]

test:  38%|███████████▋                   | 4448/11798 [00:44<01:13, 99.68it/s]

test:  38%|███████████▊                   | 4480/11798 [00:45<01:13, 99.90it/s]

test:  38%|███████████▊                   | 4512/11798 [00:45<01:12, 99.85it/s]

test:  39%|███████████▉                   | 4544/11798 [00:45<01:12, 99.68it/s]

test:  39%|████████████                   | 4576/11798 [00:46<01:12, 99.57it/s]

test:  39%|████████████                   | 4608/11798 [00:46<01:12, 99.51it/s]

test:  39%|████████████▏                  | 4640/11798 [00:46<01:11, 99.69it/s]

test:  40%|████████████▎                  | 4672/11798 [00:47<01:11, 99.77it/s]

test:  40%|███████████▉                  | 4704/11798 [00:47<01:10, 100.03it/s]

test:  40%|████████████▍                  | 4736/11798 [00:47<01:10, 99.97it/s]

test:  40%|████████████▌                  | 4768/11798 [00:47<01:10, 99.88it/s]

test:  41%|████████████▌                  | 4800/11798 [00:48<01:09, 99.99it/s]

test:  41%|████████████▎                 | 4832/11798 [00:48<01:09, 100.14it/s]

test:  41%|████████████▎                 | 4864/11798 [00:48<01:09, 100.38it/s]

test:  41%|████████████▍                 | 4896/11798 [00:49<01:08, 100.82it/s]

test:  42%|████████████▌                 | 4928/11798 [00:49<01:08, 100.86it/s]

test:  42%|████████████▌                 | 4960/11798 [00:49<01:07, 100.77it/s]

test:  42%|████████████▋                 | 4992/11798 [00:50<01:07, 100.75it/s]

[test] Checkpoint saved at 5000/11798

test:  43%|████████████▊                 | 5024/11798 [00:50<01:07, 100.88it/s]

test:  43%|████████████▊                 | 5056/11798 [00:50<01:06, 101.16it/s]

test:  43%|████████████▉                 | 5088/11798 [00:51<01:06, 101.25it/s]

test:  43%|█████████████                 | 5120/11798 [00:51<01:06, 100.96it/s]

test:  44%|█████████████                 | 5152/11798 [00:51<01:05, 100.86it/s]

test:  44%|█████████████▏                | 5184/11798 [00:52<01:05, 101.01it/s]

test:  44%|█████████████▎                | 5216/11798 [00:52<01:05, 100.81it/s]

test:  44%|█████████████▎                | 5248/11798 [00:52<01:05, 100.68it/s]

test:  45%|█████████████▍                | 5280/11798 [00:53<01:04, 100.35it/s]

test:  45%|█████████████▉                 | 5312/11798 [00:53<01:04, 99.97it/s]

test:  45%|██████████████                 | 5344/11798 [00:53<01:04, 99.79it/s]

test:  46%|██████████████▏                | 5376/11798 [00:54<01:04, 99.49it/s]

test:  46%|██████████████▏                | 5408/11798 [00:54<01:04, 99.58it/s]

test:  46%|██████████████▎                | 5440/11798 [00:54<01:03, 99.61it/s]

test:  46%|██████████████▍                | 5472/11798 [00:54<01:03, 99.57it/s]

test:  47%|██████████████▍                | 5504/11798 [00:55<01:03, 99.51it/s]

test:  47%|██████████████▌                | 5536/11798 [00:55<01:02, 99.60it/s]

test:  47%|██████████████▋                | 5568/11798 [00:55<01:02, 99.86it/s]

test:  47%|██████████████▋                | 5600/11798 [00:56<01:02, 99.93it/s]

test:  48%|██████████████▎               | 5632/11798 [00:56<01:01, 100.00it/s]

test:  48%|██████████████▍               | 5664/11798 [00:56<01:01, 100.05it/s]

test:  48%|██████████████▉                | 5696/11798 [00:57<01:01, 99.83it/s]

test:  49%|██████████████▌               | 5728/11798 [00:57<01:00, 100.03it/s]

test:  49%|██████████████▋               | 5760/11798 [00:57<01:00, 100.15it/s]

test:  49%|██████████████▋               | 5792/11798 [00:58<00:59, 100.21it/s]

test:  49%|██████████████▊               | 5824/11798 [00:58<00:59, 100.21it/s]

test:  50%|██████████████▉               | 5856/11798 [00:58<00:59, 100.26it/s]

test:  50%|██████████████▉               | 5888/11798 [00:59<00:59, 100.13it/s]

test:  50%|███████████████               | 5920/11798 [00:59<00:58, 100.35it/s]

test:  50%|███████████████▏              | 5952/11798 [00:59<00:58, 100.60it/s]

test:  51%|███████████████▏              | 5984/11798 [01:00<00:57, 100.63it/s]

[test] Checkpoint saved at 6000/11798

test:  51%|███████████████▎              | 6016/11798 [01:00<00:57, 100.52it/s]

test:  51%|███████████████▍              | 6048/11798 [01:00<00:57, 100.70it/s]

test:  52%|███████████████▍              | 6080/11798 [01:01<00:56, 100.76it/s]

test:  52%|███████████████▌              | 6112/11798 [01:01<00:56, 100.68it/s]

test:  52%|███████████████▌              | 6144/11798 [01:01<00:56, 100.59it/s]

test:  52%|███████████████▋              | 6176/11798 [01:02<00:55, 100.57it/s]

test:  53%|███████████████▊              | 6208/11798 [01:02<00:55, 100.56it/s]

test:  53%|███████████████▊              | 6240/11798 [01:02<00:55, 100.42it/s]

test:  53%|███████████████▉              | 6272/11798 [01:02<00:54, 100.51it/s]

test:  53%|████████████████              | 6304/11798 [01:03<00:54, 100.46it/s]

test:  54%|████████████████              | 6336/11798 [01:03<00:54, 100.45it/s]

test:  54%|████████████████▏             | 6368/11798 [01:03<00:53, 100.73it/s]

test:  54%|████████████████▎             | 6400/11798 [01:04<00:53, 100.69it/s]

test:  55%|████████████████▎             | 6432/11798 [01:04<00:53, 100.68it/s]

test:  55%|████████████████▍             | 6464/11798 [01:04<00:52, 100.80it/s]

test:  55%|████████████████▌             | 6496/11798 [01:05<00:52, 100.59it/s]

test:  55%|████████████████▌             | 6528/11798 [01:05<00:52, 100.37it/s]

test:  56%|████████████████▋             | 6560/11798 [01:05<00:52, 100.29it/s]

test:  56%|████████████████▊             | 6592/11798 [01:06<00:51, 100.25it/s]

test:  56%|████████████████▊             | 6624/11798 [01:06<00:51, 100.27it/s]

test:  56%|████████████████▉             | 6656/11798 [01:06<00:51, 100.40it/s]

test:  57%|█████████████████             | 6688/11798 [01:07<00:50, 100.55it/s]

test:  57%|█████████████████             | 6720/11798 [01:07<00:50, 100.39it/s]

test:  57%|█████████████████▏            | 6752/11798 [01:07<00:50, 100.08it/s]

test:  58%|█████████████████▎            | 6784/11798 [01:08<00:50, 100.02it/s]

test:  58%|█████████████████▎            | 6816/11798 [01:08<00:49, 100.04it/s]

test:  58%|█████████████████▍            | 6848/11798 [01:08<00:49, 100.22it/s]

test:  58%|█████████████████▍            | 6880/11798 [01:09<00:49, 100.20it/s]

test:  59%|█████████████████▌            | 6912/11798 [01:09<00:48, 100.34it/s]

test:  59%|█████████████████▋            | 6944/11798 [01:09<00:48, 100.24it/s]

test:  59%|█████████████████▋            | 6976/11798 [01:09<00:48, 100.22it/s]

[test] Checkpoint saved at 7000/11798

test:  59%|█████████████████▊            | 7008/11798 [01:10<00:47, 100.37it/s]

test:  60%|█████████████████▉            | 7040/11798 [01:10<00:47, 100.49it/s]

test:  60%|█████████████████▉            | 7072/11798 [01:10<00:47, 100.52it/s]

test:  60%|██████████████████            | 7104/11798 [01:11<00:46, 100.55it/s]

test:  60%|██████████████████▏           | 7136/11798 [01:11<00:46, 100.54it/s]

test:  61%|██████████████████▏           | 7168/11798 [01:11<00:46, 100.37it/s]

test:  61%|██████████████████▎           | 7200/11798 [01:12<00:45, 100.15it/s]

test:  61%|██████████████████▍           | 7232/11798 [01:12<00:45, 100.13it/s]

test:  62%|███████████████████            | 7264/11798 [01:12<00:45, 99.68it/s]

test:  62%|██████████████████▌           | 7296/11798 [01:13<00:44, 100.13it/s]

test:  62%|██████████████████▋           | 7328/11798 [01:13<00:44, 100.30it/s]

test:  62%|██████████████████▋           | 7360/11798 [01:13<00:44, 100.16it/s]

test:  63%|██████████████████▊           | 7392/11798 [01:14<00:43, 100.15it/s]

test:  63%|██████████████████▉           | 7424/11798 [01:14<00:43, 100.08it/s]

test:  63%|███████████████████▌           | 7456/11798 [01:14<00:43, 99.88it/s]

test:  63%|███████████████████▋           | 7488/11798 [01:15<00:43, 99.88it/s]

test:  64%|███████████████████▊           | 7520/11798 [01:15<00:42, 99.73it/s]

test:  64%|███████████████████▊           | 7552/11798 [01:15<00:42, 99.61it/s]

test:  64%|███████████████████▎          | 7584/11798 [01:16<00:42, 100.11it/s]

test:  65%|███████████████████▎          | 7616/11798 [01:16<00:41, 100.54it/s]

test:  65%|███████████████████▍          | 7648/11798 [01:16<00:41, 100.80it/s]

test:  65%|███████████████████▌          | 7680/11798 [01:17<00:40, 101.03it/s]

test:  65%|███████████████████▌          | 7712/11798 [01:17<00:40, 100.98it/s]

test:  66%|███████████████████▋          | 7744/11798 [01:17<00:40, 100.86it/s]

test:  66%|███████████████████▊          | 7776/11798 [01:17<00:39, 100.81it/s]

test:  66%|███████████████████▊          | 7808/11798 [01:18<00:39, 100.62it/s]

test:  66%|███████████████████▉          | 7840/11798 [01:18<00:39, 100.34it/s]

test:  67%|████████████████████▋          | 7872/11798 [01:18<00:39, 99.94it/s]

test:  67%|████████████████████▊          | 7904/11798 [01:19<00:39, 99.53it/s]

test:  67%|████████████████████▊          | 7936/11798 [01:19<00:38, 99.21it/s]

test:  68%|████████████████████▉          | 7968/11798 [01:19<00:38, 98.94it/s]

test:  68%|█████████████████████          | 8000/11798 [01:20<00:38, 98.51it/s]

[test] Checkpoint saved at 8000/11798

test:  68%|█████████████████████          | 8032/11798 [01:20<00:38, 98.77it/s]

test:  68%|█████████████████████▏         | 8064/11798 [01:20<00:37, 99.45it/s]

test:  69%|█████████████████████▎         | 8096/11798 [01:21<00:37, 99.77it/s]

test:  69%|█████████████████████▎         | 8128/11798 [01:21<00:36, 99.78it/s]

test:  69%|█████████████████████▍         | 8160/11798 [01:21<00:36, 99.67it/s]

test:  69%|█████████████████████▌         | 8192/11798 [01:22<00:36, 99.67it/s]

test:  70%|█████████████████████▌         | 8224/11798 [01:22<00:35, 99.91it/s]

test:  70%|████████████████████▉         | 8256/11798 [01:22<00:35, 100.18it/s]

test:  70%|█████████████████████         | 8288/11798 [01:23<00:34, 100.29it/s]

test:  71%|█████████████████████▏        | 8320/11798 [01:23<00:34, 100.72it/s]

test:  71%|█████████████████████▏        | 8352/11798 [01:23<00:34, 100.73it/s]

test:  71%|█████████████████████▎        | 8384/11798 [01:24<00:33, 101.01it/s]

test:  71%|█████████████████████▍        | 8416/11798 [01:24<00:33, 100.98it/s]

test:  72%|█████████████████████▍        | 8448/11798 [01:24<00:33, 100.92it/s]

test:  72%|█████████████████████▌        | 8480/11798 [01:24<00:32, 100.89it/s]

test:  72%|█████████████████████▋        | 8512/11798 [01:25<00:32, 100.67it/s]

test:  72%|█████████████████████▋        | 8544/11798 [01:25<00:32, 100.43it/s]

test:  73%|█████████████████████▊        | 8576/11798 [01:25<00:32, 100.19it/s]

test:  73%|█████████████████████▉        | 8608/11798 [01:26<00:31, 100.03it/s]

test:  73%|██████████████████████▋        | 8640/11798 [01:26<00:31, 99.82it/s]

test:  74%|██████████████████████▊        | 8672/11798 [01:26<00:31, 99.28it/s]

test:  74%|██████████████████████▊        | 8704/11798 [01:27<00:31, 99.47it/s]

test:  74%|██████████████████████▉        | 8736/11798 [01:27<00:30, 99.03it/s]

test:  74%|██████████████████████▉        | 8746/11798 [01:27<00:31, 97.07it/s]

test:  74%|███████████████████████        | 8768/11798 [01:28<00:34, 87.70it/s]

test:  75%|███████████████████████        | 8800/11798 [01:28<00:32, 92.01it/s]

test:  75%|███████████████████████▏       | 8832/11798 [01:28<00:31, 93.88it/s]

test:  75%|███████████████████████▎       | 8864/11798 [01:28<00:30, 94.89it/s]

test:  75%|███████████████████████▎       | 8896/11798 [01:29<00:30, 95.43it/s]

test:  76%|███████████████████████▍       | 8928/11798 [01:29<00:29, 95.82it/s]

test:  76%|███████████████████████▌       | 8960/11798 [01:29<00:29, 96.45it/s]

test:  76%|███████████████████████▋       | 8992/11798 [01:30<00:28, 97.13it/s]

[test] Checkpoint saved at 9000/11798

test:  76%|███████████████████████▋       | 9024/11798 [01:30<00:28, 97.13it/s]

test:  77%|███████████████████████▊       | 9056/11798 [01:30<00:28, 97.71it/s]

test:  77%|███████████████████████▉       | 9088/11798 [01:31<00:27, 98.31it/s]

test:  77%|███████████████████████▉       | 9120/11798 [01:31<00:27, 98.90it/s]

test:  78%|████████████████████████       | 9152/11798 [01:31<00:26, 99.25it/s]

test:  78%|████████████████████████▏      | 9184/11798 [01:32<00:26, 99.31it/s]

test:  78%|████████████████████████▏      | 9216/11798 [01:32<00:26, 99.15it/s]

test:  78%|████████████████████████▎      | 9248/11798 [01:32<00:25, 99.22it/s]

test:  79%|████████████████████████▍      | 9280/11798 [01:33<00:25, 99.08it/s]

test:  79%|████████████████████████▍      | 9312/11798 [01:33<00:25, 98.99it/s]

test:  79%|████████████████████████▌      | 9344/11798 [01:33<00:24, 99.15it/s]

test:  79%|████████████████████████▋      | 9376/11798 [01:34<00:24, 99.17it/s]

test:  80%|████████████████████████▋      | 9408/11798 [01:34<00:24, 99.09it/s]

test:  80%|████████████████████████▊      | 9440/11798 [01:34<00:23, 99.16it/s]

test:  80%|████████████████████████▉      | 9472/11798 [01:35<00:23, 99.21it/s]

test:  81%|████████████████████████▉      | 9504/11798 [01:35<00:23, 99.52it/s]

test:  81%|█████████████████████████      | 9536/11798 [01:35<00:22, 99.70it/s]

test:  81%|████████████████████████▎     | 9568/11798 [01:36<00:22, 100.23it/s]

test:  81%|████████████████████████▍     | 9600/11798 [01:36<00:21, 100.51it/s]

test:  82%|████████████████████████▍     | 9632/11798 [01:36<00:21, 100.72it/s]

test:  82%|████████████████████████▌     | 9664/11798 [01:37<00:21, 100.79it/s]

test:  82%|████████████████████████▋     | 9696/11798 [01:37<00:20, 100.81it/s]

test:  82%|████████████████████████▋     | 9728/11798 [01:37<00:20, 100.87it/s]

test:  83%|████████████████████████▊     | 9760/11798 [01:37<00:20, 100.74it/s]

test:  83%|████████████████████████▉     | 9792/11798 [01:38<00:19, 100.48it/s]

test:  83%|████████████████████████▉     | 9824/11798 [01:38<00:19, 100.52it/s]

test:  84%|█████████████████████████     | 9856/11798 [01:38<00:19, 100.13it/s]

test:  84%|█████████████████████████▏    | 9888/11798 [01:39<00:19, 100.19it/s]

test:  84%|█████████████████████████▏    | 9920/11798 [01:39<00:18, 100.30it/s]

test:  84%|█████████████████████████▎    | 9952/11798 [01:39<00:18, 100.34it/s]

test:  85%|█████████████████████████▍    | 9984/11798 [01:40<00:18, 100.51it/s]

[test] Checkpoint saved at 10000/11798

test:  85%|█████████████████████████▍    | 10016/11798 [01:40<00:17, 99.50it/s]

test:  85%|█████████████████████████▌    | 10048/11798 [01:40<00:17, 99.55it/s]

test:  85%|█████████████████████████▋    | 10080/11798 [01:41<00:17, 99.63it/s]

test:  86%|█████████████████████████▋    | 10112/11798 [01:41<00:16, 99.39it/s]

test:  86%|█████████████████████████▊    | 10144/11798 [01:41<00:16, 99.53it/s]

test:  86%|█████████████████████████▉    | 10176/11798 [01:42<00:16, 99.48it/s]

test:  87%|█████████████████████████▉    | 10208/11798 [01:42<00:16, 99.06it/s]

test:  87%|██████████████████████████    | 10240/11798 [01:42<00:15, 98.96it/s]

test:  87%|██████████████████████████    | 10272/11798 [01:43<00:15, 98.98it/s]

test:  87%|██████████████████████████▏   | 10304/11798 [01:43<00:14, 99.60it/s]

test:  88%|██████████████████████████▎   | 10336/11798 [01:43<00:14, 99.86it/s]

test:  88%|█████████████████████████▍   | 10368/11798 [01:44<00:14, 100.31it/s]

test:  88%|█████████████████████████▌   | 10400/11798 [01:44<00:13, 100.29it/s]

test:  88%|█████████████████████████▋   | 10432/11798 [01:44<00:13, 100.24it/s]

test:  89%|██████████████████████████▌   | 10464/11798 [01:45<00:13, 99.96it/s]

test:  89%|██████████████████████████▋   | 10496/11798 [01:45<00:13, 99.75it/s]

test:  89%|██████████████████████████▊   | 10528/11798 [01:45<00:12, 99.40it/s]

test:  90%|██████████████████████████▊   | 10560/11798 [01:46<00:12, 99.06it/s]

test:  90%|██████████████████████████▉   | 10592/11798 [01:46<00:12, 98.72it/s]

test:  90%|███████████████████████████   | 10624/11798 [01:46<00:11, 98.29it/s]

test:  90%|███████████████████████████   | 10656/11798 [01:47<00:11, 98.06it/s]

test:  91%|███████████████████████████▏  | 10688/11798 [01:47<00:11, 98.21it/s]

test:  91%|███████████████████████████▎  | 10720/11798 [01:47<00:10, 98.45it/s]

test:  91%|███████████████████████████▎  | 10752/11798 [01:47<00:10, 98.44it/s]

test:  91%|███████████████████████████▍  | 10784/11798 [01:48<00:10, 98.51it/s]

test:  92%|███████████████████████████▌  | 10816/11798 [01:48<00:09, 98.63it/s]

test:  92%|███████████████████████████▌  | 10848/11798 [01:48<00:09, 98.50it/s]

test:  92%|███████████████████████████▋  | 10880/11798 [01:49<00:09, 98.48it/s]

test:  92%|███████████████████████████▋  | 10912/11798 [01:49<00:08, 98.55it/s]

test:  93%|███████████████████████████▊  | 10944/11798 [01:49<00:08, 98.59it/s]

test:  93%|███████████████████████████▉  | 10976/11798 [01:50<00:08, 98.64it/s]

[test] Checkpoint saved at 11000/11798

test:  93%|███████████████████████████▉  | 11008/11798 [01:50<00:08, 97.89it/s]

test:  94%|████████████████████████████  | 11040/11798 [01:50<00:07, 97.99it/s]

test:  94%|████████████████████████████▏ | 11072/11798 [01:51<00:07, 98.42it/s]

test:  94%|████████████████████████████▏ | 11104/11798 [01:51<00:07, 98.60it/s]

test:  94%|████████████████████████████▎ | 11136/11798 [01:51<00:06, 98.77it/s]

test:  95%|████████████████████████████▍ | 11168/11798 [01:52<00:06, 99.02it/s]

test:  95%|████████████████████████████▍ | 11200/11798 [01:52<00:06, 99.16it/s]

test:  95%|████████████████████████████▌ | 11232/11798 [01:52<00:05, 99.19it/s]

test:  95%|████████████████████████████▋ | 11264/11798 [01:53<00:05, 99.17it/s]

test:  96%|████████████████████████████▋ | 11296/11798 [01:53<00:05, 99.13it/s]

test:  96%|████████████████████████████▊ | 11328/11798 [01:53<00:04, 98.98it/s]

test:  96%|████████████████████████████▉ | 11360/11798 [01:54<00:04, 98.87it/s]

test:  97%|████████████████████████████▉ | 11392/11798 [01:54<00:04, 98.81it/s]

test:  97%|█████████████████████████████ | 11424/11798 [01:54<00:03, 98.69it/s]

test:  97%|█████████████████████████████▏| 11456/11798 [01:55<00:03, 98.53it/s]

test:  97%|█████████████████████████████▏| 11488/11798 [01:55<00:03, 98.38it/s]

test:  98%|█████████████████████████████▎| 11520/11798 [01:55<00:02, 98.40it/s]

test:  98%|█████████████████████████████▎| 11552/11798 [01:56<00:02, 98.46it/s]

test:  98%|█████████████████████████████▍| 11584/11798 [01:56<00:02, 98.73it/s]

test:  98%|█████████████████████████████▌| 11616/11798 [01:56<00:01, 98.71it/s]

test:  99%|█████████████████████████████▌| 11648/11798 [01:57<00:01, 98.60it/s]

test:  99%|█████████████████████████████▋| 11680/11798 [01:57<00:01, 98.63it/s]

test:  99%|█████████████████████████████▊| 11712/11798 [01:57<00:00, 98.69it/s]

test: 100%|█████████████████████████████▊| 11744/11798 [01:58<00:00, 98.71it/s]

test: 100%|██████████████████████████████| 11798/11798 [01:58<00:00, 99.66it/s]

[test] Done — saved img_emb_test.npy, shape (11798, 512)

## Step - 5 Use the image emeddings to cclacluate the concept simliarity scores

In [222]:

# ============================================================
# Cell 1 — imports + config
# ============================================================
import json
import numpy as np
import torch
from sklearn.cluster import KMeans
from pathlib import Path
 
DEVICE = "mps"
MIN_MAX_SIM = 0.2          # filter 3 threshold
N_CONCEPTS_BEFORE = None   # filled in after loading
 
concepts = json.load(open("concepts_stage1.json"))
text_emb = torch.load("text_emb.pt").to(DEVICE)   # [95, 512]
 
print(f"Concepts loaded: {len(concepts)}")
print(f"text_emb shape: {text_emb.shape}")

Concepts loaded: 95
text_emb shape: torch.Size([95, 512])

In [223]:
# ============================================================
# Cell 2 — helper: compute raw score matrix on MPS
# ============================================================
def compute_scores(img_emb_path):
    """
    Loads image embeddings from disk, moves to MPS,
    computes cosine similarity against all concepts.
    Returns raw scores as numpy array [N, n_concepts].
    """
    img_emb = np.load(img_emb_path).astype(np.float32)
    img_tensor = torch.from_numpy(img_emb).to(DEVICE)   # [N, 512]
    with torch.no_grad():
        scores = img_tensor @ text_emb.T                 # [N, 95] — MPS parallel
    return scores.cpu().numpy()                          # back to CPU for sklearn

In [224]:
# ============================================================
# Cell 3 — compute scores for all three splits
# ============================================================
scores_train = compute_scores("img_emb_train.npy")
scores_val   = compute_scores("img_emb_val.npy")
scores_test  = compute_scores("img_emb_test.npy")
 
print(f"scores_train: {scores_train.shape}")   # [7723, 95]
print(f"scores_val:   {scores_val.shape}")     # [1117, 95]
print(f"scores_test:  {scores_test.shape}")    # [977,  95]

scores_train: (94563, 95)
scores_val:   (11925, 95)
scores_test:  (11798, 95)

In [225]:
# ============================================================
# Cell 4 — filter 3: drop concepts with max sim < 0.2
#           computed on train only (val/test must not influence filtering)
# ============================================================
max_sim_per_concept = scores_train.max(axis=0)   # [95] — max across all train images
keep_mask = max_sim_per_concept >= MIN_MAX_SIM
 
concepts_final = [c for c, keep in zip(concepts, keep_mask) if keep]
n_dropped = len(concepts) - len(concepts_final)
 
print(f"\nFilter 3 results:")
print(f"  Concepts before: {len(concepts)}")
print(f"  Dropped (max sim < {MIN_MAX_SIM}): {n_dropped}")
print(f"  Surviving: {len(concepts_final)}")
 
if n_dropped > 0:
    dropped = [c for c, keep in zip(concepts, keep_mask) if not keep]
    print(f"  Dropped concepts: {dropped}")
 
# apply mask to all three splits
scores_train = scores_train[:, keep_mask]
scores_val   = scores_val[:,   keep_mask]
scores_test  = scores_test[:,  keep_mask]
 
# save surviving concept list — canonical from here on
json.dump(concepts_final, open("../data/concepts_final.json", "w"), indent=2)
print(f"\nSaved concepts_final.json ({len(concepts_final)} concepts)")

Filter 3 results:
  Concepts before: 95
  Dropped (max sim < 0.2): 0
  Surviving: 95

Saved concepts_final.json (95 concepts)

In [226]:
# ============================================================
# Cell 5 — save raw scores (needed for diagnostics + inference)
# ============================================================
np.save("concept_scores_train.npy", scores_train)
np.save("concept_scores_val.npy",   scores_val)
np.save("concept_scores_test.npy",  scores_test)
print("Saved raw concept scores for all splits")

Saved raw concept scores for all splits

In [227]:
# ============================================================
# Cell 6 — binarize with KMeans per concept column
#           fit on train, apply same centroids to val + test
# ============================================================
n_concepts = len(concepts_final)
 
def binarize(scores, kmeans_models=None, fit=False):
    """
    Binarizes score matrix column by column using 2-means.
    If fit=True, fits KMeans on this data and returns (binary_matrix, models).
    If fit=False, applies pre-fitted models from training split.
    Higher centroid cluster → 1, lower → 0.
    """
    binary = np.zeros_like(scores, dtype=np.int8)
    models = [] if fit else kmeans_models
 
    for j in range(scores.shape[1]):
        col = scores[:, j].reshape(-1, 1)
        if fit:
            km = KMeans(n_clusters=2, random_state=42, n_init=10)
            km.fit(col)
            models.append(km)
        else:
            km = kmeans_models[j]
 
        labels = km.predict(col)
        # figure out which cluster label corresponds to the higher centroid
        c0, c1 = km.cluster_centers_[0][0], km.cluster_centers_[1][0]
        high_label = 0 if c0 > c1 else 1
        binary[:, j] = (labels == high_label).astype(np.int8)
 
    if fit:
        return binary, models
    return binary
 
# fit on train, transform val + test with the same models
concept_matrix_train, kmeans_models = binarize(scores_train, fit=True)
concept_matrix_val  = binarize(scores_val,  kmeans_models=kmeans_models)
concept_matrix_test = binarize(scores_test, kmeans_models=kmeans_models)
 
print(f"\nconcept_matrix_train: {concept_matrix_train.shape}")
print(f"concept_matrix_val:   {concept_matrix_val.shape}")
print(f"concept_matrix_test:  {concept_matrix_test.shape}")

concept_matrix_train: (94563, 95)
concept_matrix_val:   (11925, 95)
concept_matrix_test:  (11798, 95)

In [228]:
# ============================================================
# Cell 7 — save binarized matrices
# ============================================================
np.save("concept_matrix_train.npy", concept_matrix_train)
np.save("concept_matrix_val.npy",   concept_matrix_val)
np.save("concept_matrix_test.npy",  concept_matrix_test)
print("Saved binarized concept matrices for all splits")

Saved binarized concept matrices for all splits

In [229]:
# ============================================================
# Cell 8 — sanity checks
# ============================================================
# centroid separation per concept — flag anything suspiciously close
print("\nCentroid separation per concept (flag if < 0.05):")
warnings = []
for j, (km, concept) in enumerate(zip(kmeans_models, concepts_final)):
    sep = abs(km.cluster_centers_[0][0] - km.cluster_centers_[1][0])
    if sep < 0.05:
        warnings.append((concept, sep))
 
if warnings:
    print(f"  {len(warnings)} concepts with low separation:")
    for c, s in warnings:
        print(f"    '{c}': {s:.4f}")
else:
    print("  All concepts have healthy centroid separation ✓")
 
# activation rate per concept in train (should not be all 0s or all 1s)
activation_rate = concept_matrix_train.mean(axis=0)
print(f"\nActivation rate stats across concepts (train):")
print(f"  min: {activation_rate.min():.3f}")
print(f"  max: {activation_rate.max():.3f}")
print(f"  mean: {activation_rate.mean():.3f}")
degenerate = [(concepts_final[j], activation_rate[j])
              for j in range(n_concepts)
              if activation_rate[j] < 0.01 or activation_rate[j] > 0.99]
if degenerate:
    print(f"  Degenerate concepts (nearly all 0 or all 1): {degenerate}")
else:
    print("  No degenerate concepts ✓")

Centroid separation per concept (flag if < 0.05):
  32 concepts with low separation:
    'clear lung fields': 0.0429
    'symmetric lung inflation': 0.0435
    'widened vascular pedicle': 0.0489
    'loss of mediastinal margins': 0.0464
    'hazy lung opacity': 0.0448
    'increased lung density': 0.0408
    'airspace opacification': 0.0435
    'patchy parenchymal opacity': 0.0483
    'diffuse ground glass opacity': 0.0481
    'focal consolidative opacity': 0.0470
    'irregular lung mass': 0.0480
    'interstitial lung markings': 0.0436
    'kerley b lines': 0.0493
    'peribronchial cuffing': 0.0443
    'vascular redistribution': 0.0411
    'fluid in fissures': 0.0453
    'segmental consolidation': 0.0475
    'unilateral lung infiltrate': 0.0481
    'volume loss in lung': 0.0440
    'shifted fissure': 0.0421
    'platelike atelectasis': 0.0492
    'collapsed lung segment': 0.0345
    'visceral pleural line': 0.0443
    'deep sulcus sign': 0.0494
    'small apical lucency': 0.0440
    'fluid tracking into fissure': 0.0482
    'pleural thickening': 0.0453
    'calcified pleura': 0.0419
    'pleural scarring': 0.0451
    'vertebral compression deformity': 0.0403
    'acute rib fracture': 0.0471
    'picc line': 0.0479

Activation rate stats across concepts (train):
  min: 0.396
  max: 0.614
  mean: 0.516
  No degenerate concepts ✓

## Step 7

In [230]:
# ============================================================
# Cell 1 — imports + config
# ============================================================
import torch
import torch.nn as nn
import numpy as np
from sklearn.metrics import roc_auc_score

DEVICE = "mps"
L1_LAMBDA = 1e-4     # encourages sparse weights
N_EPOCHS = 100
LR = 1e-3

In [232]:
# ============================================================
# Cell 2 — load labels from the same CSVs used for encoding
# These are the exact row-order source encode_split() read from,
# so row i here == row i of img_emb_{split}.npy
# ============================================================
train_df = pd.read_csv("train_full.csv")
val_df   = pd.read_csv("val_full.csv")

y_train = train_df[LABEL_COLS].values
y_val   = val_df[LABEL_COLS].values

print(f"y_train: {y_train.shape}, y_val: {y_val.shape}")

y_train: (94563, 14), y_val: (11925, 14)

In [247]:
train_df.head(-3)

,Path,Sex,Age,Frontal/Lateral,AP/PA,No Finding,Enlarged Cardiomediastinum,Cardiomegaly,Lung Opacity,Lung Lesion,Edema,Consolidation,Pneumonia,Atelectasis,Pneumothorax,Pleural Effusion,Pleural Other,Fracture,Support Devices,patient_id
0,CheXpert-v1.0-small/train/patient00001/study1/...,Female,68,Frontal,AP,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,patient00001
1,CheXpert-v1.0-small/train/patient00003/study1/...,Male,41,Frontal,AP,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,patient00003
2,CheXpert-v1.0-small/train/patient00005/study1/...,Male,33,Frontal,PA,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,patient00005
3,CheXpert-v1.0-small/train/patient00005/study2/...,Male,33,Frontal,AP,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,patient00005
4,CheXpert-v1.0-small/train/patient00005/study2/...,Male,33,Frontal,AP,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,patient00005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94555,CheXpert-v1.0-small/train/patient64522/study1/...,Female,21,Frontal,AP,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,patient64522
94556,CheXpert-v1.0-small/train/patient64524/study1/...,Female,61,Frontal,AP,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,patient64524
94557,CheXpert-v1.0-small/train/patient64527/study2/...,Male,85,Frontal,AP,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,patient64527
94558,CheXpert-v1.0-small/train/patient64529/study1/...,Male,81,Frontal,AP,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,patient64529
94559,CheXpert-v1.0-small/train/patient64530/study1/...,Male,65,Frontal,AP,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,patient64530

In [248]:
df1.head(-3)

,Path,Sex,Age,Frontal/Lateral,AP/PA,No Finding,Enlarged Cardiomediastinum,Cardiomegaly,Lung Opacity,Lung Lesion,Edema,Consolidation,Pneumonia,Atelectasis,Pneumothorax,Pleural Effusion,Pleural Other,Fracture,Support Devices
0,CheXpert-v1.0-small/train/patient00001/study1/...,Female,68,Frontal,AP,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,CheXpert-v1.0-small/train/patient00003/study1/...,Male,41,Frontal,AP,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,CheXpert-v1.0-small/train/patient00004/study1/...,Female,20,Frontal,PA,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,CheXpert-v1.0-small/train/patient00005/study1/...,Male,33,Frontal,PA,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
9,CheXpert-v1.0-small/train/patient00005/study2/...,Male,33,Frontal,AP,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223396,CheXpert-v1.0-small/train/patient64527/study2/...,Male,85,Frontal,AP,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
223399,CheXpert-v1.0-small/train/patient64529/study1/...,Male,81,Frontal,AP,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
223400,CheXpert-v1.0-small/train/patient64530/study1/...,Male,65,Frontal,AP,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
223402,CheXpert-v1.0-small/train/patient64532/study1/...,Female,52,Frontal,AP,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
223403,CheXpert-v1.0-small/train/patient64533/study1/...,Male,75,Frontal,AP,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0

In [233]:
# ============================================================
# Cell 3 — load onto MPS
# y_train, y_val must already exist as [N, 14] numpy arrays,
# same row order as concept_matrix_train / concept_matrix_val
# ============================================================
X_train = torch.tensor(concept_matrix_train, dtype=torch.float32).to(DEVICE)
X_val   = torch.tensor(concept_matrix_val,   dtype=torch.float32).to(DEVICE)
y_train_t = torch.tensor(y_train, dtype=torch.float32).to(DEVICE)
y_val_t   = torch.tensor(y_val,   dtype=torch.float32).to(DEVICE)

n_concepts = X_train.shape[1]
n_labels = y_train_t.shape[1]
print(f"X_train: {X_train.shape}, y_train: {y_train_t.shape}")

X_train: torch.Size([94563, 95]), y_train: torch.Size([94563, 14])

In [234]:
# ============================================================
# Cell 4 — model, loss, optimizer
# ============================================================
model = nn.Linear(n_concepts, n_labels).to(DEVICE)
criterion = nn.BCEWithLogitsLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=LR)

In [235]:
# ============================================================
# Cell 5 — training loop
# ============================================================
best_val_auroc = 0

for epoch in range(N_EPOCHS):
    model.train()
    optimizer.zero_grad()
    logits = model(X_train)
    loss = criterion(logits, y_train_t)
    l1_penalty = sum(p.abs().sum() for p in model.parameters())
    loss = loss + L1_LAMBDA * l1_penalty
    loss.backward()
    optimizer.step()

    model.eval()
    with torch.no_grad():
        val_probs = torch.sigmoid(model(X_val)).cpu().numpy()

    y_val_np = y_val_t.cpu().numpy()
    aurocs = [
        roc_auc_score(y_val_np[:, i], val_probs[:, i])
        for i in range(n_labels)
        if len(np.unique(y_val_np[:, i])) > 1
    ]
    macro_auroc = np.mean(aurocs)

    if macro_auroc > best_val_auroc:
        best_val_auroc = macro_auroc
        torch.save(model.state_dict(), "linear_head_best.pt")

    if epoch % 10 == 0:
        print(f"epoch {epoch:3d}  loss {loss.item():.4f}  val macro AUROC {macro_auroc:.4f}")

epoch   0  loss 0.6942  val macro AUROC 0.4914
epoch  10  loss 0.5632  val macro AUROC 0.5199
epoch  20  loss 0.4839  val macro AUROC 0.5442
epoch  30  loss 0.4394  val macro AUROC 0.5602
epoch  40  loss 0.4147  val macro AUROC 0.5707
epoch  50  loss 0.4004  val macro AUROC 0.5784
epoch  60  loss 0.3913  val macro AUROC 0.5846
epoch  70  loss 0.3850  val macro AUROC 0.5898
epoch  80  loss 0.3805  val macro AUROC 0.5944
epoch  90  loss 0.3770  val macro AUROC 0.5983

In [236]:
# ============================================================
# Cell 6 — report
# ============================================================
print(f"best val macro AUROC: {best_val_auroc:.4f}")

best val macro AUROC: 0.6014

In [238]:
# ============================================================
# Cell 1 — load test data + best checkpoint
# ============================================================
test_df = pd.read_csv("test_full.csv")
y_test = test_df[LABEL_COLS].values

X_test = torch.tensor(concept_matrix_test, dtype=torch.float32).to(DEVICE)
y_test_t = torch.tensor(y_test, dtype=torch.float32).to(DEVICE)

model.load_state_dict(torch.load("linear_head_best.pt"))
model.eval()

print(f"X_test: {X_test.shape}, y_test: {y_test_t.shape}")

X_test: torch.Size([11798, 95]), y_test: torch.Size([11798, 14])

In [239]:
# ============================================================
# Cell 2 — per-label AUROC on test set
# ============================================================
with torch.no_grad():
    test_probs = torch.sigmoid(model(X_test)).cpu().numpy()

y_test_np = y_test_t.cpu().numpy()

print(f"{'Label':<28} {'AUROC':>8} {'n_pos':>7}")
per_label_auroc = {}
for i, name in enumerate(LABEL_COLS):
    if len(np.unique(y_test_np[:, i])) > 1:
        auc = roc_auc_score(y_test_np[:, i], test_probs[:, i])
        per_label_auroc[name] = auc
        print(f"{name:<28} {auc:8.4f} {int(y_test_np[:, i].sum()):7d}")
    else:
        print(f"{name:<28} {'skip':>8} {int(y_test_np[:, i].sum()):7d}  (no positives in test)")

macro_test_auroc = np.mean(list(per_label_auroc.values()))
print(f"\nmacro AUROC (test): {macro_test_auroc:.4f}")

Label                           AUROC   n_pos
No Finding                     0.7104    1662
Enlarged Cardiomediastinum     0.5065     639
Cardiomegaly                   0.5792    1542
Lung Opacity                   0.6906    4921
Lung Lesion                    0.5464     469
Edema                          0.7231    3400
Consolidation                  0.5710     752
Pneumonia                      0.6157     274
Atelectasis                    0.4853    2199
Pneumothorax                   0.5334    1265
Pleural Effusion               0.7882    5084
Pleural Other                  0.5296     147
Fracture                       0.4809     518
Support Devices                0.7619    6857

macro AUROC (test): 0.6087

In [240]:
# ============================================================
# Cell 3 — baseline: plain linear probe on raw CLIP embeddings
# No concept bottleneck at all. This is the accuracy ceiling —
# what you're giving up for interpretability.
# ============================================================
img_emb_train_raw = np.load("img_emb_train.npy")
img_emb_val_raw   = np.load("img_emb_val.npy")
img_emb_test_raw  = np.load("img_emb_test.npy")

Xb_train = torch.tensor(img_emb_train_raw, dtype=torch.float32).to(DEVICE)
Xb_val   = torch.tensor(img_emb_val_raw,   dtype=torch.float32).to(DEVICE)
Xb_test  = torch.tensor(img_emb_test_raw,  dtype=torch.float32).to(DEVICE)

baseline = nn.Linear(Xb_train.shape[1], n_labels).to(DEVICE)
opt_b = torch.optim.Adam(baseline.parameters(), lr=LR)
crit_b = nn.BCEWithLogitsLoss()

best_val_b = 0
for epoch in range(N_EPOCHS):
    baseline.train()
    opt_b.zero_grad()
    loss = crit_b(baseline(Xb_train), y_train_t)
    loss.backward()
    opt_b.step()

    baseline.eval()
    with torch.no_grad():
        val_probs_b = torch.sigmoid(baseline(Xb_val)).cpu().numpy()
    aurocs_b = [roc_auc_score(y_val_t.cpu().numpy()[:, i], val_probs_b[:, i])
                for i in range(n_labels) if len(np.unique(y_val_t.cpu().numpy()[:, i])) > 1]
    macro_b = np.mean(aurocs_b)
    if macro_b > best_val_b:
        best_val_b = macro_b
        torch.save(baseline.state_dict(), "baseline_best.pt")

baseline.load_state_dict(torch.load("baseline_best.pt"))
baseline.eval()
with torch.no_grad():
    test_probs_b = torch.sigmoid(baseline(Xb_test)).cpu().numpy()

aurocs_b_test = [roc_auc_score(y_test_np[:, i], test_probs_b[:, i])
                  for i in range(n_labels) if len(np.unique(y_test_np[:, i])) > 1]
macro_baseline_test = np.mean(aurocs_b_test)

print(f"CBM  macro AUROC (test): {macro_test_auroc:.4f}")
print(f"Baseline (no bottleneck) macro AUROC (test): {macro_baseline_test:.4f}")
print(f"Accuracy cost of the bottleneck: {macro_baseline_test - macro_test_auroc:.4f}")

CBM  macro AUROC (test): 0.6087
Baseline (no bottleneck) macro AUROC (test): 0.6318
Accuracy cost of the bottleneck: 0.0230

In [241]:
# ============================================================
# Cell 4 — faithfulness check
# For each label, find the concept the model itself leans on
# most (largest weight magnitude), then check whether that
# concept is actually MORE active in positive cases than
# negative cases. If it's not, the model's stated reason
# for a prediction doesn't match the data.
# ============================================================
weights = model.weight.detach().cpu().numpy()  # [14, n_concepts]

print(f"{'Label':<28} {'Top concept':<30} {'weight':>7} {'pos rate':>9} {'neg rate':>9}")
for i, label_name in enumerate(LABEL_COLS):
    top_j = np.argmax(np.abs(weights[i]))
    concept_name = concepts_final[top_j]
    w = weights[i, top_j]

    pos_mask = y_train[:, i] == 1
    neg_mask = y_train[:, i] == 0
    pos_rate = concept_matrix_train[pos_mask, top_j].mean() if pos_mask.sum() > 0 else float("nan")
    neg_rate = concept_matrix_train[neg_mask, top_j].mean() if neg_mask.sum() > 0 else float("nan")

    print(f"{label_name:<28} {concept_name:<30} {w:7.3f} {pos_rate:9.3f} {neg_rate:9.3f}")

Label                        Top concept                     weight  pos rate  neg rate
No Finding                   callus formation                -0.158     0.166     0.466
Enlarged Cardiomediastinum   increased cardiothoracic ratio  -0.154     0.500     0.469
Cardiomegaly                 kerley b lines                  -0.136     0.429     0.529
Lung Opacity                 rib cortical discontinuity      -0.150     0.413     0.561
Lung Lesion                  widened mediastinal silhouette  -0.159     0.378     0.621
Edema                        cavitary lung lesion            -0.149     0.349     0.508
Consolidation                pacemaker leads                 -0.145     0.373     0.478
Pneumonia                    boot shaped heart               -0.162     0.348     0.465
Atelectasis                  abnormal aortic contour         -0.140     0.580     0.544
Pneumothorax                 biventricular enlargement       -0.148     0.292     0.409
Pleural Effusion             bat wing opacity pattern        -0.161     0.274     0.603
Pleural Other                peribronchial cuffing           -0.157     0.537     0.528
Fracture                     pacemaker leads                 -0.149     0.460     0.472
Support Devices              mediastinal shift from large effusion   0.155     0.611     0.394

In [242]:
# ============================================================
# Step 7 — print all results in one place
# ============================================================

# ── per-label AUROC (CBM) ─────────────────────────────────
print("=" * 58)
print("Per-label AUROC — CBM (test set)")
print("=" * 58)
print(f"{'Label':<28} {'AUROC':>8} {'n_pos':>7}")
per_label_auroc = {}
for i, name in enumerate(LABEL_COLS):
    if len(np.unique(y_test_np[:, i])) > 1:
        auc = roc_auc_score(y_test_np[:, i], test_probs[:, i])
        per_label_auroc[name] = auc
        print(f"{name:<28} {auc:8.4f} {int(y_test_np[:, i].sum()):7d}")
    else:
        print(f"{name:<28} {'skip':>8} {int(y_test_np[:, i].sum()):7d}")
macro_cbm = np.mean(list(per_label_auroc.values()))
print(f"\nCBM macro AUROC (test): {macro_cbm:.4f}")

# ── faithfulness ─────────────────────────────────────────
print("\n" + "=" * 58)
print("Faithfulness — top concept per label")
print("=" * 58)
weights = model.weight.detach().cpu().numpy()
print(f"{'Label':<28} {'Top concept':<32} {'w':>6} {'pos%':>7} {'neg%':>7}")
for i, name in enumerate(LABEL_COLS):
    top_j = np.argmax(np.abs(weights[i]))
    w = weights[i, top_j]
    pos_mask = y_train[:, i] == 1
    neg_mask = y_train[:, i] == 0
    pos_r = concept_matrix_train[pos_mask, top_j].mean() if pos_mask.sum() > 0 else float("nan")
    neg_r = concept_matrix_train[neg_mask, top_j].mean() if neg_mask.sum() > 0 else float("nan")
    print(f"{name:<28} {concepts_final[top_j]:<32} {w:6.3f} {pos_r:7.3f} {neg_r:7.3f}")

==========================================================
Per-label AUROC — CBM (test set)
==========================================================
Label                           AUROC   n_pos
No Finding                     0.7104    1662
Enlarged Cardiomediastinum     0.5065     639
Cardiomegaly                   0.5792    1542
Lung Opacity                   0.6906    4921
Lung Lesion                    0.5464     469
Edema                          0.7231    3400
Consolidation                  0.5710     752
Pneumonia                      0.6157     274
Atelectasis                    0.4853    2199
Pneumothorax                   0.5334    1265
Pleural Effusion               0.7882    5084
Pleural Other                  0.5296     147
Fracture                       0.4809     518
Support Devices                0.7619    6857

CBM macro AUROC (test): 0.6087

==========================================================
Faithfulness — top concept per label
==========================================================
Label                        Top concept                           w    pos%    neg%
No Finding                   callus formation                 -0.158   0.166   0.466
Enlarged Cardiomediastinum   increased cardiothoracic ratio   -0.154   0.500   0.469
Cardiomegaly                 kerley b lines                   -0.136   0.429   0.529
Lung Opacity                 rib cortical discontinuity       -0.150   0.413   0.561
Lung Lesion                  widened mediastinal silhouette   -0.159   0.378   0.621
Edema                        cavitary lung lesion             -0.149   0.349   0.508
Consolidation                pacemaker leads                  -0.145   0.373   0.478
Pneumonia                    boot shaped heart                -0.162   0.348   0.465
Atelectasis                  abnormal aortic contour          -0.140   0.580   0.544
Pneumothorax                 biventricular enlargement        -0.148   0.292   0.409
Pleural Effusion             bat wing opacity pattern         -0.161   0.274   0.603
Pleural Other                peribronchial cuffing            -0.157   0.537   0.528
Fracture                     pacemaker leads                  -0.149   0.460   0.472
Support Devices              mediastinal shift from large effusion  0.155   0.611   0.394

In [243]:
# ============================================================
# Step 8 — interpretability output
# show top driving concepts + one intervention per example
# focusing on Pleural Effusion as the strongest case
# ============================================================

TARGET_LABEL = "Pleural Effusion"
label_idx = LABEL_COLS.index(TARGET_LABEL)
TOP_K = 5

weights = model.weight.detach().cpu().numpy()   # [14, n_concepts]
label_weights = weights[label_idx]              # [n_concepts]

# find test cases the model called correctly with high confidence
pred_scores = test_probs[:, label_idx]
true_labels = y_test_np[:, label_idx]

high_conf_pos = np.where((pred_scores > 0.6) & (true_labels == 1))[0]
high_conf_neg = np.where((pred_scores < 0.4) & (true_labels == 0))[0]

print(f"High-confidence correct positives: {len(high_conf_pos)}")
print(f"High-confidence correct negatives: {len(high_conf_neg)}")

def explain(row_idx, split="test"):
    cm = concept_matrix_test if split == "test" else concept_matrix_train
    concept_scores_raw = cm[row_idx]
    contributions = label_weights * concept_scores_raw
    top_indices = np.argsort(np.abs(contributions))[::-1][:TOP_K]

    pred = pred_scores[row_idx]
    true = int(true_labels[row_idx])
    path = test_df.iloc[row_idx]["Path"]

    print(f"\nImage: {path}")
    print(f"True label: {true}  |  Model score: {pred:.3f}")
    print(f"{'Concept':<32} {'active':>7} {'weight':>8} {'contribution':>14}")
    for j in top_indices:
        print(f"{concepts_final[j]:<32} {int(concept_scores_raw[j]):>7} "
              f"{label_weights[j]:>8.3f} {contributions[j]:>14.4f}")

    # intervention: flip the top concept and reobserve
    top_j = top_indices[0]
    intervened = concept_scores_raw.copy()
    intervened[top_j] = 1 - intervened[top_j]   # flip 0→1 or 1→0
    intervened_t = torch.tensor(intervened, dtype=torch.float32).to(DEVICE)
    with torch.no_grad():
        new_score = torch.sigmoid(model(intervened_t))[label_idx].item()
    print(f"\nIntervention: flip '{concepts_final[top_j]}' "
          f"{int(concept_scores_raw[top_j])} → {1 - int(concept_scores_raw[top_j])}")
    print(f"Score before: {pred:.3f}  →  after: {new_score:.3f}")

# show 3 positive and 2 negative examples
print("\n" + "=" * 65)
print(f"Explanations for {TARGET_LABEL}")
print("=" * 65)
for idx in high_conf_pos[:3]:
    explain(idx)
for idx in high_conf_neg[:2]:
    explain(idx)

High-confidence correct positives: 1999
High-confidence correct negatives: 4294

=================================================================
Explanations for Pleural Effusion
=================================================================

Image: CheXpert-v1.0-small/train/patient00011/study11/view1_frontal.jpg
True label: 1  |  Model score: 0.664
Concept                           active   weight   contribution
chest tube                             1    0.139         0.1391
patchy parenchymal opacity             1   -0.123        -0.1227
subpulmonic effusion                   1    0.122         0.1224
boot shaped heart                      1    0.121         0.1210
normal cardiac silhouette              1   -0.105        -0.1053

Intervention: flip 'chest tube' 1 → 0
Score before: 0.664  →  after: 0.633

Image: CheXpert-v1.0-small/train/patient00100/study2/view1_frontal.jpg
True label: 1  |  Model score: 0.601
Concept                           active   weight   contribution
chest tube                             1    0.139         0.1391
patchy parenchymal opacity             1   -0.123        -0.1227
boot shaped heart                      1    0.121         0.1210
callus formation                       1    0.118         0.1180
pacemaker leads                        1   -0.115        -0.1154

Intervention: flip 'chest tube' 1 → 0
Score before: 0.601  →  after: 0.567

Image: CheXpert-v1.0-small/train/patient00118/study3/view1_frontal.jpg
True label: 1  |  Model score: 0.603
Concept                           active   weight   contribution
patchy parenchymal opacity             1   -0.123        -0.1227
subpulmonic effusion                   1    0.122         0.1224
boot shaped heart                      1    0.121         0.1210
callus formation                       1    0.118         0.1180
normal cardiac silhouette              1   -0.105        -0.1053

Intervention: flip 'patchy parenchymal opacity' 1 → 0
Score before: 0.603  →  after: 0.632

Image: CheXpert-v1.0-small/train/patient00011/study13/view1_frontal.jpg
True label: 0  |  Model score: 0.186
Concept                           active   weight   contribution
bat wing opacity pattern               1   -0.161        -0.1614
calcified granuloma                    1   -0.153        -0.1526
elevated hemidiaphragm                 1    0.138         0.1375
obscured vascular markings             1   -0.134        -0.1342
calcified pleura                       1    0.131         0.1310

Intervention: flip 'bat wing opacity pattern' 1 → 0
Score before: 0.186  →  after: 0.212

Image: CheXpert-v1.0-small/train/patient00068/study1/view1_frontal.jpg
True label: 0  |  Model score: 0.214
Concept                           active   weight   contribution
bat wing opacity pattern               1   -0.161        -0.1614
calcified granuloma                    1   -0.153        -0.1526
chest tube                             1    0.139         0.1391
elevated hemidiaphragm                 1    0.138         0.1375
obscured vascular markings             1   -0.134        -0.1342

Intervention: flip 'bat wing opacity pattern' 1 → 0
Score before: 0.214  →  after: 0.243

In [251]:
print(f"High-confidence correct positives: {len(high_conf_pos)}/ {len(pred_scores)}")

High-confidence correct positives: 1999/ 11798